import {arr,base64ToBytes,bytesToBase64,clean,score} from './source.mjs';
import {POLICY,finalValidationAccepted,sourceInspectionAccepted} from './policy.mjs';

export const MODEL='gpt-image-2.5-sunburst',VALIDATOR_MODEL='gpt-5.6-luna';
export const GRID={width:2400,height:1200,rows:3,cols:6,cellWidth:400,cellHeight:400};
export const VALIDATION_POLICY={...POLICY,maxAttempts:3};
const IMAGE_URL='https://api.openai.com/v1/images/edits',RESPONSES_URL='https://api.openai.com/v1/responses';
let magickPromise=null;
async function magick(){if(!magickPromise)magickPromise=(async()=>{const m=await import('npm:@imagemagick/magick-wasm@0.0.30');const wasm=await Deno.readFile(new URL('magick.wasm',import.meta.resolve('npm:@imagemagick/magick-wasm@0.0.30')));await m.initializeImageMagick(wasm);return m;})();return magickPromise;}
const copy=d=>new Uint8Array(d);

export async function prepareCell(source){const m=await magick(),bg=new m.MagickColor('#ECECEC');return m.ImageMagick.read(source.bytes,img=>{img.resize(new m.MagickGeometry(360,360));img.extent(400,400,m.Gravity.Center,bg);return img.write(m.MagickFormat.Png,d=>copy(d));});}
export async function composeSheet(cells){if(!Array.isArray(cells)||cells.length!==18)throw new Error('grid18_requires_18_cells');const [{PNG},{Buffer}]=await Promise.all([import('npm:pngjs@7.0.0'),import('node:buffer')]);const canvas=new PNG({width:GRID.width,height:GRID.height});for(let i=0;i<18;i++){const src=PNG.sync.read(Buffer.from(cells[i]));if(src.width!==400||src.height!==400)throw new Error(`grid18_cell_dimensions_${i+1}_${src.width}x${src.height}`);const row=Math.floor(i/6),col=i%6;for(let y=0;y<400;y++){const srcStart=y*400*4,srcEnd=srcStart+400*4,dstStart=((row*400+y)*GRID.width+col*400)*4;canvas.data.set(src.data.subarray(srcStart,srcEnd),dstStart);}}return new Uint8Array(PNG.sync.write(canvas,{colorType:6,inputColorType:6}));}
export async function cropCell(gridBytes,position){const m=await magick(),p=Number(position)-1,x=(p%6)*400,y=Math.floor(p/6)*400;let q=90;let out=m.ImageMagick.read(gridBytes,img=>{img.crop(new m.MagickGeometry(x,y,400,400));img.quality=q;return img.write(m.MagickFormat.WebP,d=>copy(d));});if(out.length>650000){q=82;out=m.ImageMagick.read(gridBytes,img=>{img.crop(new m.MagickGeometry(x,y,400,400));img.quality=q;return img.write(m.MagickFormat.WebP,d=>copy(d));});}return out;}

const GRID_PROMPT=`Edite a ÚNICA folha de referência enviada. Ela contém EXATAMENTE 18 células fixas em 3 linhas por 6 colunas. Cada célula deve continuar contendo exatamente o MESMO produto da referência daquela célula, sem trocar, misturar ou duplicar produtos. A referência visual é a verdade SOMENTE para identidade do produto: variante, embalagem, marca, logotipo, tampa, formato, proporções, cores e arte do rótulo. NÃO use a referência como verdade para ambiente, fundo, piso, parede, mesa, iluminação ambiente ou cenário.

Objetivo visual: fotografia comercial de produto ULTRARREALISTA, limpa e profissional, como fotografada em estúdio de alto nível. Preserve textura real de plástico, papel, vidro, metal ou embalagem flexível; bordas nítidas; impressão e logotipo visualmente fiéis; iluminação de estúdio suave e controlada; contraste natural; nitidez alta sem aparência artificial de render 3D.

REGRA ABSOLUTA EM CADA CÉLULA: mostre SOMENTE UM produto, inteiro da base ao topo e de uma lateral à outra, centralizado e com margem de segurança em todos os lados. Não corte tampa, alça, bico, cantos, base, laterais ou qualquer parte da embalagem. Não deixe o produto encostar nas bordas da célula. Não crie nem preserve mãos, dedos, frutas decorativas, alimentos soltos, copos, pratos, talheres, tecidos, mesas, caixas de cenário, etiquetas de preço, textos promocionais, selos soltos, logos flutuantes, reflexos de outros objetos, segundo produto ou qualquer acessório que não faça parte física do próprio produto.

FUNDO É REGRA DE HARD FAIL: não preserve o fundo da imagem original. Remova completamente o fundo original e qualquer vestígio dele, inclusive parede, mesa, prateleira, piso, textura, gradiente, sombra de ambiente, recorte, halo ou cenário. Substitua tudo ao redor do produto por fundo sólido, chapado e uniforme #ECECEC, que deve ocupar toda a imagem de cada célula, de ponta a ponta e até todos os quatro cantos. Não usar fundo branco, quase branco diferente de #ECECEC, degradê, vinheta, transparência, painel branco, moldura branca, faixa branca ou borda branca. O único elemento adicional permitido é uma sombra de contato muito discreta, fisicamente plausível e macia diretamente na base do produto. Sem horizonte, pedestal ou reflexo espelhado.

Se uma referência tiver fundo ruim ou elementos extras, use-a apenas para reconhecer o produto e reconstrua uma foto limpa de estúdio. Se tiver várias vistas do MESMO produto, use-as apenas para compreender a embalagem e entregue uma única vista frontal/3-4 frontal limpa. Não invente detalhes ausentes nem mude variante. A saída será recortada matematicamente nas mesmas 18 células; portanto preserve rigorosamente a posição de cada célula.`;

async function imageCall(key,form,prefix,max=14_000_000){const r=await fetch(IMAGE_URL,{method:'POST',headers:{Authorization:`Bearer ${key}`},body:form,signal:AbortSignal.timeout(115000)}),d=await r.json().catch(()=>({})),requestId=r.headers.get('x-request-id')||null;if(!r.ok)throw new Error(`${prefix}_http_${r.status}_${clean(d?.error?.code||d?.error?.message||'error',180)}`);const b64=clean(d?.data?.[0]?.b64_json,80_000_000);if(!b64)throw new Error(`${prefix}_empty_image`);const bytes=base64ToBytes(b64);if(!bytes.length||bytes.length>max)throw new Error(`${prefix}_output_size_${bytes.length}`);return{bytes,usage:d?.usage||{},requestId};}
export async function generateGrid(key,sheet){const f=new FormData();f.append('model',MODEL);f.append('prompt',GRID_PROMPT);f.append('size','2400x1200');f.append('quality','medium');f.append('output_format','webp');f.append('output_compression','86');f.append('background','opaque');f.append('image[]',new Blob([sheet],{type:'image/png'}),'referencias-18.png');return imageCall(key,f,'openai_grid18');}

const sourceSchema={type:'object',additionalProperties:false,properties:{same_product_confidence:{type:'number',minimum:0,maximum:1},product_complete:{type:'boolean'},bad_crop:{type:'boolean'},bad_cutout:{type:'boolean'},extra_elements:{type:'boolean'},front_or_usable_view:{type:'boolean'},source_quality_score:{type:'number',minimum:0,maximum:1},critical_issue:{type:'string',maxLength:260}},required:['same_product_confidence','product_complete','bad_crop','bad_cutout','extra_elements','front_or_usable_view','source_quality_score','critical_issue']};
const finalSchema={type:'object',additionalProperties:false,properties:{pass:{type:'boolean'},same_product:{type:'boolean'},packaging_color_match:{type:'boolean'},shape_match:{type:'boolean'},label_match:{type:'boolean'},product_complete:{type:'boolean'},bad_crop:{type:'boolean'},bad_cutout:{type:'boolean'},extra_elements:{type:'boolean'},professional_photo:{type:'boolean'},natural_contact_shadow:{type:'boolean'},background_uniform:{type:'boolean'},background_is_ececec:{type:'boolean'},white_background:{type:'boolean'},original_background_visible:{type:'boolean'},white_border:{type:'boolean'},fidelity_score:{type:'number',minimum:0,maximum:1},composition_score:{type:'number',minimum:0,maximum:1},cutout_score:{type:'number',minimum:0,maximum:1},background_score:{type:'number',minimum:0,maximum:1},critical_issue:{type:'string',maxLength:260}},required:['pass','same_product','packaging_color_match','shape_match','label_match','product_complete','bad_crop','bad_cutout','extra_elements','professional_photo','natural_contact_shadow','background_uniform','background_is_ececec','white_background','original_background_visible','white_border','fidelity_score','composition_score','cutout_score','background_score','critical_issue']};
function finalText(d){return arr(d?.output).filter(x=>x?.type==='message').flatMap(x=>arr(x?.content)).filter(x=>x?.type==='output_text').map(x=>String(x?.text||'')).join('').trim();}
async function structuredVision(key,content,schema,name,maxOutputTokens=360){const body={model:VALIDATOR_MODEL,store:false,max_output_tokens:maxOutputTokens,reasoning:{effort:'low'},input:[{role:'user',content}],text:{format:{type:'json_schema',name,strict:true,schema}}};const r=await fetch(RESPONSES_URL,{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(60000)}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`vision_http_${r.status}_${clean(d?.error?.code||d?.error?.message||'error',180)}`);const t=finalText(d);if(!t)throw new Error('vision_empty_output');let p;try{p=JSON.parse(t);}catch{throw new Error('vision_invalid_json');}return{parsed:p,usage:d?.usage||{}};}

export async function inspectSource(key,product,source){
  const identity=`Produto esperado: ${clean(product?.name,220)}. Marca: ${clean(product?.brand,100)||'não informada'}. Embalagem/apresentação: ${clean(product?.packaging,100)||'não informada'}. GTIN/EAN: ${clean(product?.gtin,40)||'não informado'}.`;
  const content=[{type:'input_text',text:`Analise a FOTO como fonte para fotografia de catálogo. ${identity} O objetivo é decidir se ela é segura para reconstruir exatamente este produto. Reprove se o produto estiver cortado em qualquer lado, se faltar tampa/base/alça/cantos, se o recorte tiver comido partes do produto, se houver mãos, pessoas, frutas, alimentos decorativos, copos, pratos, textos promocionais, outro produto, cenário ou qualquer elemento extra que não pertença fisicamente ao produto. Uma sombra/fundo existente não conta como elemento extra. Exija vista frontal ou suficientemente frontal para identificar embalagem e variante. same_product_confidence mede a confiança de que a foto representa exatamente o produto esperado; se não houver evidência suficiente, pontue baixo.`},{type:'input_image',image_url:`data:${source.type};base64,${bytesToBase64(source.bytes)}`,detail:'high'}];
  try{
    const {parsed:p,usage}=await structuredVision(key,content,sourceSchema,'product_source_inspection_v2');
    const v={same_product_confidence:score(p?.same_product_confidence),product_complete:p?.product_complete===true,bad_crop:p?.bad_crop===true,bad_cutout:p?.bad_cutout===true,extra_elements:p?.extra_elements===true,front_or_usable_view:p?.front_or_usable_view===true,source_quality_score:score(p?.source_quality_score),critical_issue:clean(p?.critical_issue,260)};
    return{accepted:sourceInspectionAccepted(v),inspection:v,usage};
  }catch(e){
    const issue=clean(e instanceof Error?e.message:e,180)||'inspection_failed';
    const v={same_product_confidence:0.70,product_complete:false,bad_crop:true,bad_cutout:false,extra_elements:false,front_or_usable_view:false,source_quality_score:0,critical_issue:`source_inspection_unavailable:${issue}`};
    return{accepted:false,inspection:v,usage:{},inspection_error:issue};
  }
}

export async function validateGenerated(key,source,candidate){const content=[{type:'input_text',text:'Compare as duas imagens. A primeira é a referência verdadeira SOMENTE para identidade do produto e a segunda é a imagem candidata de catálogo. A candidata só pode ser aprovada se mostrar exatamente o mesmo produto/variante e se estiver visualmente limpa e profissional. HARD FAIL: produto cortado ou encostando nas bordas; tampa, base, alça, bico, cantos ou laterais faltando; recorte que removeu parte da embalagem; qualquer mão, pessoa, fruta, alimento decorativo, copo, prato, tecido, mesa, cenário, preço, texto promocional, outro produto, logo solto ou objeto extra. HARD FAIL DE FUNDO: fundo branco; fundo original ainda visível total ou parcialmente; parede, mesa, prateleira, piso, textura ou cenário herdado da referência; moldura branca, faixa branca ou borda branca; gradiente, vinheta ou transparência. A única coisa permitida além do produto é uma sombra de contato discreta e natural na base. O fundo deve ser sólido, uniforme e visualmente #ECECEC em toda a imagem até os quatro cantos. Marque background_uniform=true e background_is_ececec=true somente se isso estiver claramente atendido; white_background, original_background_visible e white_border devem ser false. Exija produto inteiro centralizado com margem, aparência fotográfica realista de estúdio (não render 3D artificial), textura e embalagem fiéis. Fidelidade mínima 90%.'},{type:'input_image',image_url:`data:${source.type};base64,${bytesToBase64(source.bytes)}`,detail:'high'},{type:'input_image',image_url:`data:image/webp;base64,${bytesToBase64(candidate)}`,detail:'high'}];const {parsed:p,usage}=await structuredVision(key,content,finalSchema,'grid18_cell_validation_v4',480);const v={pass:p?.pass===true,same_product:p?.same_product===true,packaging_color_match:p?.packaging_color_match===true,shape_match:p?.shape_match===true,label_match:p?.label_match===true,product_complete:p?.product_complete===true,bad_crop:p?.bad_crop===true,bad_cutout:p?.bad_cutout===true,extra_elements:p?.extra_elements===true,professional_photo:p?.professional_photo===true,natural_contact_shadow:p?.natural_contact_shadow===true,background_uniform:p?.background_uniform===true,background_is_ececec:p?.background_is_ececec===true,white_background:p?.white_background===true,original_background_visible:p?.original_background_visible===true,white_border:p?.white_border===true,fidelity_score:score(p?.fidelity_score),composition_score:score(p?.composition_score),cutout_score:score(p?.cutout_score),background_score:score(p?.background_score),critical_issue:clean(p?.critical_issue,260),approval_threshold:POLICY.fidelityMin};return{accepted:finalValidationAccepted(v),validation:v,usage};}

export function generationCost(u){const ii=Number(u?.input_tokens_details?.image_tokens||0),ti=Number(u?.input_tokens_details?.text_tokens||0),io=Number(u?.output_tokens_details?.image_tokens||0);return Math.round((((ii*8)+(ti*5)+(io*30))/1e6)*1e6)/1e6;}
export function proratedGenerationUsage(u,d=18){return{input_tokens_details:{image_tokens:Number(u?.input_tokens_details?.image_tokens||0)/d,text_tokens:Number(u?.input_tokens_details?.text_tokens||0)/d},output_tokens_details:{image_tokens:Number(u?.output_tokens_details?.image_tokens||0)/d}};}
