import {arr,base64ToBytes,bytesToBase64,clean,score} from './source.mjs';
export const MODEL='gpt-image-2.5-sunburst',VALIDATOR_MODEL='gpt-5.6-luna';
export const GRID={width:2400,height:1200,rows:3,cols:6,cellWidth:400,cellHeight:400};
const IMAGE_URL='https://api.openai.com/v1/images/edits',RESPONSES_URL='https://api.openai.com/v1/responses';
let magickPromise=null;
async function magick(){if(!magickPromise)magickPromise=(async()=>{const m=await import('npm:@imagemagick/magick-wasm@0.0.30');const wasm=await Deno.readFile(new URL('magick.wasm',import.meta.resolve('npm:@imagemagick/magick-wasm@0.0.30')));await m.initializeImageMagick(wasm);return m;})();return magickPromise;}
const copy=d=>new Uint8Array(d);
export async function prepareCell(source){const m=await magick(),bg=new m.MagickColor('#ECECEC');return m.ImageMagick.read(source.bytes,img=>{img.resize(new m.MagickGeometry(360,360));img.extent(400,400,m.Gravity.Center,bg);img.quality=80;return img.write(m.MagickFormat.WebP,d=>copy(d));});}
function appendH(m,bytes){const c=m.MagickImageCollection.create();try{for(const b of bytes)c.push(m.MagickImage.create(b));return c.appendHorizontally(img=>img.write(m.MagickFormat.WebP,d=>copy(d)));}finally{c.dispose();}}
function appendV(m,bytes){const c=m.MagickImageCollection.create();try{for(const b of bytes)c.push(m.MagickImage.create(b));return c.appendVertically(img=>img.write(m.MagickFormat.WebP,d=>copy(d)));}finally{c.dispose();}}
export async function composeSheet(cells){if(!Array.isArray(cells)||cells.length!==18)throw new Error('grid18_requires_18_cells');const m=await magick(),rows=[];for(let r=0;r<3;r++)rows.push(appendH(m,cells.slice(r*6,r*6+6)));return appendV(m,rows);}
export async function cropCell(gridBytes,position){const m=await magick(),p=Number(position)-1,x=(p%6)*400,y=Math.floor(p/6)*400;let q=82;let out=m.ImageMagick.read(gridBytes,img=>{img.crop(new m.MagickGeometry(x,y,400,400));img.quality=q;return img.write(m.MagickFormat.WebP,d=>copy(d));});if(out.length>480000){q=68;out=m.ImageMagick.read(gridBytes,img=>{img.crop(new m.MagickGeometry(x,y,400,400));img.quality=q;return img.write(m.MagickFormat.WebP,d=>copy(d));});}return out;}
const GRID_PROMPT=`Edite a ÚNICA folha de referência enviada. Ela contém EXATAMENTE 18 células fixas em 3 linhas por 6 colunas. A FOTO é a única verdade visual. Não use nomes de catálogo, pesos ou descrições externas. Mantenha cada produto na MESMA célula e nas MESMAS coordenadas aproximadas; nunca mova, troque, misture ou duplique produtos entre células. Em cada célula, gere uma única foto limpa do MESMO produto. Se a referência tiver duas vistas do mesmo produto, use-as só para entender a embalagem e produza uma vista frontal única. Preserve exatamente cor, tampa, formato, proporções, marca, logotipo, arte do rótulo, variante e todo texto visível; não corrija, reescreva, traduza ou invente texto. Produto inteiro e centralizado, com margem. Fundo uniforme #ECECEC. Sem linhas, bordas, números, preços, cenário ou objetos extras. A saída será cortada matematicamente nas mesmas 18 células.`;
const SINGLE_PROMPT=`Edite somente a FOTO DE REFERÊNCIA. Ela é a única verdade visual. Gere uma foto quadrada profissional do MESMO produto, preservando exatamente embalagem, cor, tampa, formato, proporções, marca, logotipo, arte do rótulo, variante e todo texto visível. Não use conhecimento externo e não corrija, reescreva, traduza ou invente texto. Fundo uniforme #ECECEC, produto inteiro e centralizado com margem, sem cenário, preço ou objetos extras.`;
async function imageCall(key,form,prefix,max=10_000_000){const r=await fetch(IMAGE_URL,{method:'POST',headers:{Authorization:`Bearer ${key}`},body:form,signal:AbortSignal.timeout(115000)}),d=await r.json().catch(()=>({})),requestId=r.headers.get('x-request-id')||null;if(!r.ok)throw new Error(`${prefix}_http_${r.status}_${clean(d?.error?.code||d?.error?.message||'error',180)}`);const b64=clean(d?.data?.[0]?.b64_json,60_000_000);if(!b64)throw new Error(`${prefix}_empty_image`);const bytes=base64ToBytes(b64);if(!bytes.length||bytes.length>max)throw new Error(`${prefix}_output_size_${bytes.length}`);return{bytes,usage:d?.usage||{},requestId};}
export async function generateGrid(key,sheet){const f=new FormData();f.append('model',MODEL);f.append('prompt',GRID_PROMPT);f.append('size','2400x1200');f.append('quality','medium');f.append('output_format','webp');f.append('output_compression','68');f.append('background','opaque');f.append('image[]',new Blob([sheet],{type:'image/webp'}),'referencias-18.webp');return imageCall(key,f,'openai_grid18');}
export async function generateSingle(key,source){const f=new FormData();f.append('model',MODEL);f.append('prompt',SINGLE_PROMPT);f.append('size','816x816');f.append('quality','medium');f.append('output_format','webp');f.append('output_compression','70');f.append('background','opaque');f.append('image[]',new Blob([source.bytes],{type:source.type}),'referencia.webp');return imageCall(key,f,'openai_single18',2_000_000);}
const schema={type:'object',additionalProperties:false,properties:{pass:{type:'boolean'},same_product:{type:'boolean'},packaging_color_match:{type:'boolean'},shape_match:{type:'boolean'},label_match:{type:'boolean'},fidelity_score:{type:'number',minimum:0,maximum:1},composition_score:{type:'number',minimum:0,maximum:1},background_score:{type:'number',minimum:0,maximum:1},critical_issue:{type:'string',maxLength:260}},required:['pass','same_product','packaging_color_match','shape_match','label_match','fidelity_score','composition_score','background_score','critical_issue']};
function finalText(d){return arr(d?.output).filter(x=>x?.type==='message').flatMap(x=>arr(x?.content)).filter(x=>x?.type==='output_text').map(x=>String(x?.text||'')).join('').trim();}
export async function validateGenerated(key,source,candidate){const content=[{type:'input_text',text:'Compare apenas as duas imagens. A primeira é a referência verdadeira; a segunda deve ser o mesmo produto. Ignore nomes externos. Reprove se houver troca de produto, cor, formato, marca, logotipo, arte do rótulo, variante ou texto visível. Exija produto inteiro, centralizado e fundo #ECECEC.'},{type:'input_image',image_url:`data:${source.type};base64,${bytesToBase64(source.bytes)}`,detail:'high'},{type:'input_image',image_url:`data:image/webp;base64,${bytesToBase64(candidate)}`,detail:'high'}],body={model:VALIDATOR_MODEL,store:false,max_output_tokens:300,reasoning:{effort:'low'},input:[{role:'user',content}],text:{format:{type:'json_schema',name:'grid18_cell_validation_v1',strict:true,schema}}};const r=await fetch(RESPONSES_URL,{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(60000)}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`vision_http_${r.status}_${clean(d?.error?.code||d?.error?.message||'error',180)}`);const t=finalText(d);if(!t)throw new Error('vision_empty_output');let p;try{p=JSON.parse(t);}catch{throw new Error('vision_invalid_json');}const v={pass:p?.pass===true,same_product:p?.same_product===true,packaging_color_match:p?.packaging_color_match===true,shape_match:p?.shape_match===true,label_match:p?.label_match===true,fidelity_score:score(p?.fidelity_score),composition_score:score(p?.composition_score),background_score:score(p?.background_score),critical_issue:clean(p?.critical_issue,260)},accepted=v.pass&&v.same_product&&v.packaging_color_match&&v.shape_match&&v.label_match&&v.fidelity_score>=.95&&v.composition_score>=.95&&v.background_score>=.95&&!v.critical_issue;return{accepted,validation:v,usage:d?.usage||{}};}
export function generationCost(u){const ii=Number(u?.input_tokens_details?.image_tokens||0),ti=Number(u?.input_tokens_details?.text_tokens||0),io=Number(u?.output_tokens_details?.image_tokens||0);return Math.round((((ii*8)+(ti*5)+(io*30))/1e6)*1e6)/1e6;}
export function proratedGenerationUsage(u,d=18){return{input_tokens_details:{image_tokens:Number(u?.input_tokens_details?.image_tokens||0)/d,text_tokens:Number(u?.input_tokens_details?.text_tokens||0)/d},output_tokens_details:{image_tokens:Number(u?.output_tokens_details?.image_tokens||0)/d}};}