import {arr,clean,fetchExternalImage,fetchExternalPage,score} from './source.mjs';
import {inspectSource} from './image.mjs';

const RESPONSES_URL='https://api.openai.com/v1/responses';
const RESEARCH_MODEL='gpt-5.6-luna';
const schema={type:'object',additionalProperties:false,properties:{found:{type:'boolean'},confidence:{type:'number',minimum:0,maximum:1},image_url:{type:'string',maxLength:1800},source_page_url:{type:'string',maxLength:1800},evidence:{type:'string',maxLength:500}},required:['found','confidence','image_url','source_page_url','evidence']};
const safeUrl=v=>{try{const u=new URL(clean(v,1800));return ['https:','http:'].includes(u.protocol)?u.toString():'';}catch{return'';}};
function finalText(d){return arr(d?.output).filter(x=>x?.type==='message').flatMap(x=>arr(x?.content)).filter(x=>x?.type==='output_text').map(x=>String(x?.text||'')).join('').trim();}
export function parseResearchJson(value){const raw=String(value??'').trim();const tries=[raw,raw.replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'').trim()];const s=raw.indexOf('{'),e=raw.lastIndexOf('}');if(s>=0&&e>s)tries.push(raw.slice(s,e+1));for(const t of tries){if(!t)continue;try{const p=JSON.parse(t);if(p&&typeof p==='object'&&!Array.isArray(p))return p;}catch{}}throw new Error('research_invalid_json');}

async function webResearch(key,product){const identity=`EAN/GTIN: ${clean(product?.gtin,40)||'não informado'}; nome: ${clean(product?.name,240)}; marca: ${clean(product?.brand,120)||'não informada'}; embalagem/apresentação: ${clean(product?.packaging,120)||'não informada'}.`;const body={model:RESEARCH_MODEL,store:false,max_output_tokens:1000,reasoning:{effort:'low'},instructions:'Pesquise na web uma fotografia real e limpa do produto exato. Priorize fabricante, distribuidor oficial ou varejista confiável. Confirme EAN/GTIN, marca, variante, sabor/fragrância e peso/volume. Não aceite outra variante ou gramatura. A foto ideal deve mostrar somente uma unidade do produto, inteira, não cortada, sem mãos, pessoas, alimentos decorativos, copos, pratos, cenários, preços ou outros objetos. Retorne URL direta da imagem quando houver e também a página de origem. Se não houver confiança suficiente, found=false.',tools:[{type:'web_search'}],tool_choice:'auto',input:[{role:'user',content:[{type:'input_text',text:`Encontre a melhor fonte visual para: ${identity}`}]}],text:{format:{type:'json_schema',name:'product_image_source_research_v2',strict:true,schema}}};const r=await fetch(RESPONSES_URL,{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(65000)}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`research_http_${r.status}_${clean(d?.error?.message||d?.error?.code||'error',160)}`);const t=finalText(d);if(!t)throw new Error('research_empty_output');return{result:parseResearchJson(t),usage:d?.usage||{},responseId:clean(d?.id,160)};}

function metaCandidates(html,pageUrl){const patterns=[/<meta[^>]+(?:property|name)=["'](?:og:image(?::secure_url)?|twitter:image(?::src)?)["'][^>]+content=["']([^"']+)/gi,/<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["'](?:og:image(?::secure_url)?|twitter:image(?::src)?)["']/gi,/<link[^>]+rel=["']image_src["'][^>]+href=["']([^"']+)/gi,/"image"\s*:\s*"(https?:\\?\/\\?\/[^"\\]+)/gi];const out=[];for(const re of patterns){for(const m of html.matchAll(re)){let v=String(m[1]||'').replaceAll('\\/','/').replaceAll('&amp;','&').trim();try{v=new URL(v,pageUrl).toString();}catch{continue;}if(v&&!out.includes(v))out.push(v);if(out.length>=8)return out;}}return out;}
async function candidateUrls(result){const out=[];const direct=safeUrl(result?.image_url),page=safeUrl(result?.source_page_url);if(direct)out.push({url:direct,page:page||null,kind:'direct'});if(page){try{const p=await fetchExternalPage(page);for(const url of metaCandidates(p.text,p.url)){if(!out.some(x=>x.url===url))out.push({url,page:p.url,kind:'page_meta'});if(out.length>=7)break;}}catch{}}return out;}
async function inspectCandidate(key,product,c){try{const source=await fetchExternalImage(c.url),checked=await inspectSource(key,product,source);return{candidate:c,source,checked,error:null};}catch(e){return{candidate:c,source:null,checked:null,error:clean(e instanceof Error?e.message:e,180)};}}

export async function findReplacementSource(key,product,rejectedSourceUrl=''){const researched=await webResearch(key,product),r=researched.result;if(r?.found!==true||score(r?.confidence)<0.80)return{found:false,reason:'no_confident_web_source',research:researched};const candidates=(await candidateUrls(r)).filter(c=>!rejectedSourceUrl||c.url!==rejectedSourceUrl).slice(0,3);const checked=await Promise.all(candidates.map(c=>inspectCandidate(key,product,c))),attempts=checked.map(x=>({url:x.candidate.url,accepted:x.checked?.accepted===true,inspection:x.checked?.inspection||null,error:x.error}));const winner=checked.find(x=>x.checked?.accepted===true&&x.source);if(winner)return{found:true,source:{...winner.source,field:'web_research',origin:'web_research_verified_v2',source_page_url:winner.candidate.page||safeUrl(r?.source_page_url)||null,inspection:winner.checked.inspection},research:researched,attempts};return{found:false,reason:'researched_candidates_failed_visual_inspection',research:researched,attempts};}
