const FIREBASE_HOST='cedar-chemist-310801-default-rtdb.firebaseio.com';
const GH_OWNER='osvaldosereia',GH_REPO='SUCEDOAN12',SOURCE_BUCKET='product-images';
export class TerminalError extends Error{}
export const clean=(v,max=1000)=>String(v??'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,max);
export const arr=v=>Array.isArray(v)?v:[];
export const score=v=>Math.max(0,Math.min(1,Number(v||0)));
export function base64ToBytes(b64){const raw=atob(b64),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out;}
export function bytesToBase64(bytes){let binary='',chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)binary+=String.fromCharCode(...bytes.subarray(i,Math.min(i+chunk,bytes.length)));return btoa(binary);}
export function safeName(v){return clean(v,120).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,70)||'produto';}
export async function sha256Hex(bytes){const d=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,'0')).join('');}
export async function sha256Text(v){return sha256Hex(new TextEncoder().encode(v));}
function allowedSource(raw,host){try{const u=new URL(raw);return u.protocol==='https:'&&['raw.githubusercontent.com',host,'donaantonia.com.br','www.donaantonia.com.br'].includes(u.hostname);}catch{return false;}}
function normalizeLegacyPath(raw){let v=clean(raw,1800);if(!v)return'';if(v.startsWith('../'))v=v.replace(/^\.\.\//,'');if(v.startsWith('./'))v=v.replace(/^\.\//,'');v=v.replace(/^\//,'');if(v.startsWith('site/'))return `https://raw.githubusercontent.com/${GH_OWNER}/${GH_REPO}/main/${v}`;return clean(raw,1800);}
function contentTypeFor(url,h){h=(h||'').split(';',1)[0].trim().toLowerCase();if(['image/png','image/jpeg','image/webp'].includes(h))return h;const p=url.toLowerCase();if(p.includes('.png'))return'image/png';if(p.includes('.jpg')||p.includes('.jpeg'))return'image/jpeg';return'image/webp';}
export function imageDimensions(bytes,type){if(type==='image/png'&&bytes.length>=24&&bytes[0]===0x89&&bytes[1]===0x50){const d=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);return{width:d.getUint32(16,false),height:d.getUint32(20,false)};}if(type==='image/webp'&&bytes.length>=30&&String.fromCharCode(...bytes.subarray(0,4))==='RIFF'&&String.fromCharCode(...bytes.subarray(8,12))==='WEBP'){const k=String.fromCharCode(...bytes.subarray(12,16));if(k==='VP8X')return{width:1+bytes[24]+(bytes[25]<<8)+(bytes[26]<<16),height:1+bytes[27]+(bytes[28]<<8)+(bytes[29]<<16)};if(k==='VP8 '&&bytes[23]===0x9d&&bytes[24]===1&&bytes[25]===0x2a)return{width:(bytes[26]|(bytes[27]<<8))&0x3fff,height:(bytes[28]|(bytes[29]<<8))&0x3fff};if(k==='VP8L'&&bytes[20]===0x2f){const b1=bytes[21],b2=bytes[22],b3=bytes[23],b4=bytes[24];return{width:1+(((b2&0x3f)<<8)|b1),height:1+(((b4&0x0f)<<10)|(b3<<2)|((b2&0xc0)>>6))};}}if(type==='image/jpeg'&&bytes.length>4&&bytes[0]===0xff&&bytes[1]===0xd8){let i=2;while(i+8<bytes.length){if(bytes[i]!==0xff){i++;continue;}const m=bytes[i+1];if([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(m))return{height:(bytes[i+5]<<8)|bytes[i+6],width:(bytes[i+7]<<8)|bytes[i+8]};const len=(bytes[i+2]<<8)|bytes[i+3];if(len<2)break;i+=2+len;}}return{width:0,height:0};}
export async function fetchImage(url,host){if(!allowedSource(url,host))throw new TerminalError('source_host_not_allowed');const r=await fetch(url,{headers:{'User-Agent':'DonaAntonia-Grid18/1.1'},signal:AbortSignal.timeout(30000)});if(!r.ok)throw new Error(`source_http_${r.status}`);const declared=Number(r.headers.get('content-length')||0);if(declared>8_000_000)throw new TerminalError('source_too_large');const bytes=new Uint8Array(await r.arrayBuffer());if(!bytes.length||bytes.length>8_000_000)throw new TerminalError('source_size_invalid');const type=contentTypeFor(url,r.headers.get('content-type')),dim=imageDimensions(bytes,type);return{bytes,type,width:dim.width,height:dim.height,sha256:await sha256Hex(bytes)};}
function parseRawGithub(raw){try{const u=new URL(raw);if(u.hostname!=='raw.githubusercontent.com')return null;const p=u.pathname.split('/').filter(Boolean);if(p.length<4||p[0]!==GH_OWNER||p[1]!==GH_REPO)return null;return{ref:p[2],path:p.slice(3).join('/')};}catch{return null;}}
async function immutableGithubImage(raw,host){const p=parseRawGithub(raw);if(!p)return null;if(/^[0-9a-f]{40}$/i.test(p.ref)){try{return{...await fetchImage(raw,host),url:raw,recovered:false};}catch{return null;}}try{const api=`https://api.github.com/repos/${GH_OWNER}/${GH_REPO}/commits?path=${encodeURIComponent(p.path)}&per_page=12`,r=await fetch(api,{headers:{Accept:'application/vnd.github+json','User-Agent':'DonaAntonia-Grid18/1.1'},signal:AbortSignal.timeout(15000)});if(r.ok)for(const c of arr(await r.json()))for(const ref of[clean(c?.sha,80),clean(c?.parents?.[0]?.sha,80)].filter(Boolean)){const candidate=`https://raw.githubusercontent.com/${GH_OWNER}/${GH_REPO}/${ref}/${p.path}`;try{return{...await fetchImage(candidate,host),url:candidate,recovered:candidate!==raw};}catch(e){if(!(e instanceof Error)||!String(e.message).startsWith('source_http_404'))throw e;}}}catch(e){if(e instanceof TerminalError)throw e;}try{return{...await fetchImage(raw,host),url:raw,recovered:false};}catch{return null;}}
async function fetchTrustedCandidate(raw,host){const url=normalizeLegacyPath(raw);if(!url)return null;if(parseRawGithub(url))return immutableGithubImage(url,host);try{return{...await fetchImage(url,host),url,recovered:false};}catch(e){const m=e instanceof Error?String(e.message):'';if(m.startsWith('source_http_400')||m.startsWith('source_http_404'))return null;throw e;}}
async function firebase(key){if(!key)return null;const r=await fetch(`https://${FIREBASE_HOST}/produtos/${encodeURIComponent(key)}.json`,{headers:{Accept:'application/json','User-Agent':'DonaAntonia-Grid18/1.1'},signal:AbortSignal.timeout(15000)});if(r.status===404)return null;if(!r.ok)throw new Error(`firebase_http_${r.status}`);const d=await r.json().catch(()=>null);return d&&typeof d==='object'&&!Array.isArray(d)?d:null;}
function identity(p,f){const pg=clean(p?.gtin,40),fg=clean(f?.gtin||f?.ean,40);if(pg&&fg)return pg===fg;const ps=clean(p?.sku,80),fs=clean(f?.codigo||f?.sku,80);if(ps&&fs)return ps===fs;return clean(p?.name,240).toLowerCase()===clean(f?.nome||f?.name,240).toLowerCase();}
export async function resolveTrustedSource(base,host,p){const saved=clean(p?.image_source_url,1800);if(saved){const f=await fetchTrustedCandidate(saved,host);if(f)return{...f,field:'products.image_source_url',origin:f.recovered?'verified_saved_source_git_history':(clean(p?.image_source_origin,120)||'verified_saved_source')};}const key=clean(p?.firebase_key,180);if(key){const fbp=await firebase(key);if(fbp){if(!identity(p,fbp))throw new TerminalError('firebase_identity_mismatch');const prev=normalizeLegacyPath(fbp?.imagem_anterior),cur=normalizeLegacyPath(fbp?.imagem||fbp?.imagem_url||fbp?.url_imagem);if(prev&&prev!==cur&&!/foto-atual-otimizada/i.test(prev)){const f=await fetchTrustedCandidate(prev,host);if(f)return{...f,field:'firebase.imagem_anterior',origin:f.recovered?'legacy_firebase_imagem_anterior_git_history':'legacy_firebase_imagem_anterior'};}}}const cat=`${base}/storage/v1/object/public/${SOURCE_BUCKET}/catalog-products/${p.id}.webp`,f=await fetchTrustedCandidate(cat,host);if(f)return{...f,field:'storage.catalog-products',origin:'supabase_catalog_products_original'};throw new TerminalError('trusted_source_missing');}