import {hydrateExperienceImages,loadFlowCompatibleImageBase64,loadFlowSelectorImageBase64} from "./image.ts";

const COMPACT_LIST_MAX_BASE64_CHARS=18_000;
const COMPACT_LIST_TOTAL_BASE64_CHARS=180_000;
const FALLBACK_IMAGE_BASE64="iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVR4nGP4//8/AAX+Av4N70a4AAAAAElFTkSuQmCC";

function isUuid(value:string):boolean{return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);}
async function mapLimited<T,R>(values:T[],limit:number,fn:(value:T,index:number)=>Promise<R>):Promise<R[]>{const output=new Array<R>(values.length);let cursor=0;const workers=Array.from({length:Math.min(limit,values.length)},async()=>{while(true){const index=cursor++;if(index>=values.length)return;output[index]=await fn(values[index],index);}});await Promise.all(workers);return output;}
function hydrateFastBasketOptions(items:unknown[]):unknown[]{return items.slice(0,9).map((item)=>{if(!item||typeof item!=="object"||Array.isArray(item))return item;const option={...(item as Record<string,unknown>)};delete option.image_url;option.image=FALLBACK_IMAGE_BASE64;return option;});}
async function hydrateNavigationProductItems(items:unknown[],supabaseUrl:string):Promise<unknown[]>{let budget=COMPACT_LIST_TOTAL_BASE64_CHARS;return await mapLimited(items.slice(0,20),2,async(item)=>{if(!item||typeof item!=="object"||Array.isArray(item))return item;const row={...(item as Record<string,unknown>)};const productId=String(row.id||"").trim();const startRaw=row.start;if(!startRaw||typeof startRaw!=="object"||Array.isArray(startRaw))return row;const start={...(startRaw as Record<string,unknown>)};const imageUrl=String(start.image_url||"").trim().slice(0,2000);const existing=String(start.image||"").trim();delete start.image_url;delete start.src;if(existing&&(existing.length>COMPACT_LIST_MAX_BASE64_CHARS||existing.length>budget))delete start.image;if(!start.image&&imageUrl&&budget>0){const assetKey=isUuid(productId)?`products/${productId}.jpg`:null;const image=await loadFlowSelectorImageBase64(imageUrl,supabaseUrl,assetKey);if(image&&image.length<=COMPACT_LIST_MAX_BASE64_CHARS&&image.length<=budget){start.image=image;budget-=image.length;}}else if(start.image){budget-=start.image.length;}row.start=start;return row;});}
export async function hydrateExperienceImagesWithCards(response:unknown,supabaseUrl:string,definitionSlug:string|null=null):Promise<unknown>{if(!response||typeof response!=="object"||Array.isArray(response))return response;const raw=response as Record<string,unknown>;const rawData=raw.data;const screen=String(raw.screen||"");const isFastCandidate=definitionSlug==="flow-cestas-comercial-v5";let hydrated=response;if(isFastCandidate&&screen==="CESTAS"&&rawData&&typeof rawData==="object"&&!Array.isArray(rawData)){const data=rawData as Record<string,unknown>;if(Array.isArray(data.baskets))data.baskets=hydrateFastBasketOptions(data.baskets as unknown[]);}else hydrated=await hydrateExperienceImages(response,supabaseUrl);if(!hydrated||typeof hydrated!=="object"||Array.isArray(hydrated))return hydrated;const obj=hydrated as Record<string,unknown>;if(!obj.data||typeof obj.data!=="object"||Array.isArray(obj.data))return hydrated;const data=obj.data as Record<string,unknown>;const current=String(obj.screen||"");if(isFastCandidate&&/^PRODUTOS_[A-L]$/.test(current)&&Array.isArray(data.product_items)){data.product_items=await hydrateNavigationProductItems(data.product_items as unknown[],supabaseUrl);return hydrated;}if(isFastCandidate&&/^PRODUTO_[A-L]$/.test(current)){const productId=String(data.product_id||data.id||"").trim();const existing=String(data.product_image_base64||"").trim();if(existing){data.has_product_image=true;delete data.product_image_url;delete data.product_id;return hydrated;}const imageUrl=String(data.product_image_url||"").trim().slice(0,2000);const assetKey=isUuid(productId)?`products/${productId}.jpg`:null;const image=imageUrl?await loadFlowCompatibleImageBase64(imageUrl,supabaseUrl,assetKey):null;data.product_image_base64=image||FALLBACK_IMAGE_BASE64;data.has_product_image=Boolean(image);delete data.product_image_url;delete data.product_id;return hydrated;}return hydrated;}
