const FLOW_SELECTOR_IMAGE_MAX_BYTES=45_000;
const FLOW_IMAGE_MAX_BYTES=80_000;
const FLOW_ASSET_BUCKET='whatsapp-flow-assets';
const FALLBACK_IMAGE_BASE64='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVR4nGP4//8/AAX+Av4N70a4AAAAAElFTkSuQmCC';
function bytesToBase64(bytes:Uint8Array):string{let s='';for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,Math.min(i+0x8000,bytes.length)));return btoa(s);}
function imageStem(imageUrl:string):string|null{try{const base=decodeURIComponent(new URL(imageUrl).pathname.split('/').filter(Boolean).pop()||'');return base?base.replace(/\.(avif|webp|png|jpe?g)$/i,'').replace(/[^A-Za-z0-9._-]/g,'-').slice(0,160):null;}catch{return null;}}
function isUuid(v:string){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);}
async function fetchBase64(url:string,maxBytes:number):Promise<string|null>{try{const r=await fetch(url,{signal:AbortSignal.timeout(3000)});if(!r.ok)return null;const declared=Number(r.headers.get('content-length')||0);if(declared&&declared>maxBytes)return null;const b=new Uint8Array(await r.arrayBuffer());if(!b.length||b.length>maxBytes)return null;return bytesToBase64(b);}catch{return null;}}
function assetUrl(supabaseUrl:string,key:string){return `${supabaseUrl.replace(/\/$/,'')}/storage/v1/object/public/${FLOW_ASSET_BUCKET}/${key.split('/').map(encodeURIComponent).join('/')}`;}
export async function loadFlowSelectorImageBase64(_imageUrl:string,supabaseUrl:string,assetKey?:string|null):Promise<string|null>{if(assetKey){const cached=await fetchBase64(assetUrl(supabaseUrl,assetKey),FLOW_SELECTOR_IMAGE_MAX_BYTES);if(cached)return cached;}return null;}
export async function loadFlowCompatibleImageBase64(_imageUrl:string,supabaseUrl:string,assetKey?:string|null):Promise<string|null>{if(assetKey){const cached=await fetchBase64(assetUrl(supabaseUrl,assetKey),FLOW_IMAGE_MAX_BYTES);if(cached)return cached;}return null;}
async function hydrateItems(items:unknown[],supabaseUrl:string,scope:'basket'|'product'):Promise<unknown[]>{return await Promise.all(items.map(async(item)=>{if(!item||typeof item!=='object'||Array.isArray(item))return item;const o={...(item as Record<string,unknown>)};const imageUrl=String(o.image_url||'');const id=String(o.id||'');delete o.image_url;let key:string|null=null;if(scope==='basket'){const stem=imageStem(imageUrl);if(stem)key=`baskets/${stem}.jpg`;}else if(isUuid(id))key=`products/${id}.jpg`;if(key){const image=await loadFlowSelectorImageBase64(imageUrl,supabaseUrl,key);if(image)o.image=image;}return o;}));}
async function hydrateBasketNavigation(items:unknown[],supabaseUrl:string):Promise<unknown[]>{return await Promise.all(items.slice(0,9).map(async(item)=>{if(!item||typeof item!=='object'||Array.isArray(item))return item;const row={...(item as Record<string,unknown>)};const imageUrl=String(row.image_url||'');delete row.image_url;const stem=imageStem(imageUrl);if(!stem)return row;const image=await loadFlowSelectorImageBase64(imageUrl,supabaseUrl,`baskets/${stem}.jpg`);if(!image)return row;const main=row['main-content']&&typeof row['main-content']==='object'&&!Array.isArray(row['main-content'])?row['main-content'] as Record<string,unknown>:{};row.start={image,'alt-text':String(main.title||'Cesta básica').slice(0,80)};return row;}));}
export async function hydrateExperienceImages(response:unknown,supabaseUrl:string):Promise<unknown>{if(!response||typeof response!=='object'||Array.isArray(response))return response;const obj=response as Record<string,unknown>;if(!obj.data||typeof obj.data!=='object'||Array.isArray(obj.data))return response;const data=obj.data as Record<string,unknown>;const screen=String(obj.screen||'');if(screen==='CESTAS'&&Array.isArray(data.baskets)){const first=(data.baskets as unknown[])[0];const nav=Boolean(first&&typeof first==='object'&&!Array.isArray(first)&&('main-content' in (first as Record<string,unknown>)||'on-click-action' in (first as Record<string,unknown>)));data.baskets=nav?await hydrateBasketNavigation(data.baskets as unknown[],supabaseUrl):await hydrateItems((data.baskets as unknown[]).slice(0,9),supabaseUrl,'basket');return response;}if(/^PERSONALIZAR_[A-L]$/.test(screen)){const imageUrl=String(data.basket_image_url||'');const stem=imageStem(imageUrl);const image=stem?await loadFlowCompatibleImageBase64(imageUrl,supabaseUrl,`baskets/${stem}.jpg`):null;data.basket_image_base64=image||FALLBACK_IMAGE_BASE64;data.has_basket_image=Boolean(image);delete data.basket_image_url;return response;}return response;}
