-- R02-R09 integrated stage - genuine synthetic checkout -> frozen R06
-- -> verified OR uncertain R07. All IDs are generated by the checkout tests.
-- No payment/stock/Bl ing/SEFAZ data from production.
\set ON_ERROR_STOP on

CREATE TABLE public.bling_hub_entity_links_v2 (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source_system text NOT NULL,
  entity_type text NOT NULL,
  source_id text NOT NULL,
  bling_id bigint NOT NULL,
  identity_value text NOT NULL,
  status text NOT NULL,
  UNIQUE (source_system,entity_type,source_id)
);

INSERT INTO public.bling_hub_entity_links_v2
  (source_system,entity_type,source_id,bling_id,identity_value,status)
SELECT 'vitrine_qx','order',i.order_id::text,i.bling_order_id,
  'VITRINE-'||i.order_id::text,'matched'
FROM public.order_bling_r7_sync_intents_v1 i
WHERE i.status='verified';

INSERT INTO public.bling_hub_entity_links_v2
  (source_system,entity_type,source_id,bling_id,identity_value,status)
SELECT 'vitrine_qx','product',line->>'product_id',555,
  'SYNTHETIC-PRODUCT-'||(line->>'product_id'),'matched'
FROM public.order_bling_r7_sync_intents_v1 i
CROSS JOIN LATERAL jsonb_array_elements(i.manifest->'lines') AS line
WHERE i.status='verified' AND line->>'deliverable'='true'
  AND line->>'state'='separated';

-- Snapshot key, original weekly number and true R06 receipt must remain
-- bound to the SAME checkout-generated order (not hand-coded UUIDs).
DO $r9_preflight$
DECLARE verified uuid; uncertain uuid; r jsonb;
BEGIN
  SELECT i.order_id INTO verified
  FROM public.order_bling_r7_sync_intents_v1 i WHERE status='verified';
  SELECT i.order_id INTO uncertain
  FROM public.order_bling_r7_sync_intents_v1 i WHERE status='uncertain';
  IF verified IS NULL OR uncertain IS NULL THEN
    RAISE EXCEPTION 'R07 expected verified and uncertain outcomes missing';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.orders o
    JOIN public.order_separation_completions_v1 c ON c.order_id=o.id
    JOIN public.order_bling_r7_sync_intents_v1 i ON i.order_id=o.id
    WHERE o.id=verified AND o.status='ready'
      AND c.phase='completed' AND c.metadata->>'stock_applied'='true'
      AND c.metadata->'r6_reconciliation'=i.manifest
      AND i.status='verified' AND i.bling_order_id=o.bling_order_id
  ) THEN RAISE EXCEPTION 'R07 receipt not bound to live checkout and R06'; END IF;
  IF EXISTS(SELECT 1 FROM public.bling_hub_entity_links_v2 l WHERE
    l.source_id=uncertain::text AND l.entity_type='order') THEN
    RAISE EXCEPTION 'uncertain Bling sale was falsely linked'; END IF;
END $r9_preflight$;
SELECT 'PASS R09 preconditions use checkout-created order and original R06/R07 receipt' result;
