-- Disposable PostgreSQL 17 fixture. NEVER execute this file on production.
\set ON_ERROR_STOP on
create extension if not exists pgcrypto;
create role anon;
create role authenticated;
create role service_role bypassrls;
create table public.orders (
  id uuid primary key default gen_random_uuid(),
  payment_method text
);
create table public.order_public_snapshots_v1 (
  order_id uuid primary key references public.orders(id) on delete cascade,
  snapshot jsonb not null default '{}'::jsonb,
  public_code text not null default 'AA999',
  created_at timestamptz not null default now()
);
alter table public.order_public_snapshots_v1
  add constraint order_public_snapshots_v1_public_code_format_chk
  check (public_code ~ '^[A-Z]{2}[0-9]{3}$');
create unique index order_public_snapshots_v1_public_code_uidx
  on public.order_public_snapshots_v1(public_code);
create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id),
  quantity integer not null default 1 check (quantity > 0)
);
create or replace function public.ops2_refresh_order_public_snapshot_v1(p_order_id uuid)
returns jsonb language plpgsql security definer
set search_path=public,pg_temp as $$
declare v_snapshot jsonb;
begin
  select jsonb_build_object('version',3,'item_count',count(*))
    into v_snapshot from public.order_items where order_id=p_order_id;
  insert into public.order_public_snapshots_v1(order_id,snapshot)
    values(p_order_id,v_snapshot)
    on conflict(order_id) do update set snapshot=excluded.snapshot;
  return v_snapshot;
end $$;
-- This is the deployed BEFORE-migration behavior, which skipped all
-- snapshots once an early public code row had been created.
create or replace function public.ops2_order_item_public_snapshot_trigger_v1()
returns trigger language plpgsql security definer
set search_path=public,pg_temp as $$
begin
  if exists(select 1 from public.order_public_snapshots_v1 where order_id=new.order_id)
    then return new; end if;
  perform public.ops2_refresh_order_public_snapshot_v1(new.order_id);
  return new;
end $$;
create constraint trigger trg_order_item_public_snapshot_v1
  after insert on public.order_items deferrable initially deferred
  for each row execute function public.ops2_order_item_public_snapshot_trigger_v1();
-- Historical identities must never change.
insert into public.orders(id) values ('00000000-0000-4000-8000-000000000001');
insert into public.order_public_snapshots_v1(order_id,public_code,snapshot)
values('00000000-0000-4000-8000-000000000001','AA001','{"version":1}'::jsonb);
grant usage on schema public to service_role;
grant select,insert,update on public.orders to service_role;
grant select,insert,update on public.order_public_snapshots_v1 to service_role;
grant select,insert on public.order_items to service_role;
-- A deliberately small, transactional inventory ledger provides a reproducible
-- rollback/idempotency contract. It DOES NOT substitute for the complete
-- production reservation engine (basket lots, allocations or fiscal triggers).
create table public._test_stock_reservation_v1 (
  sku text primary key,
  available integer not null check (available >= 0)
);
insert into public._test_stock_reservation_v1(sku,available) values('X',10);
grant select,update on public._test_stock_reservation_v1 to service_role;
-- Use the exact production create_vitrine_cart_order_v3 wrapper via a separate
-- SQL fixture. These three business dependencies are narrow test doubles; the
-- wrapper itself, its stock failure handling, and transaction sequence are real.
create or replace function public.create_vitrine_cart_order_v3_base(
 p_phone text,p_payment_method text,p_items jsonb,
 p_customer_snapshot jsonb,p_delivery jsonb
) returns jsonb language plpgsql security invoker as $base$
declare
 v_id uuid;
 v_qty integer := coalesce(nullif(p_items->0->>'qty','')::integer,1);
begin
 if v_qty < 1 then raise exception 'invalid_qty'; end if;
 perform pg_sleep(0.2);
 insert into public.orders(payment_method) values (p_payment_method) returning id into v_id;
 insert into public.order_items(order_id,quantity) values(v_id,v_qty);
 return jsonb_build_object('order_id',v_id,'total',75);
end;
$base$;

create or replace function public.reserve_vitrine_order_stock_v1(p_order_id uuid)
returns jsonb language plpgsql security invoker as $reserve$
declare v_qty integer;
 v_payment_method text;
 v_remaining integer;
begin
 select payment_method into v_payment_method
   from public.orders where id=p_order_id;
 select coalesce(max(quantity),1) into v_qty
   from public.order_items where order_id=p_order_id;
 update public._test_stock_reservation_v1 set available=available-v_qty
   where sku='X' and available >= v_qty
   returning available into v_remaining;
 if not found then return jsonb_build_object('ok',false,'error','insufficient_stock'); end if;
 if v_payment_method='TEST_ERROR' then
   raise exception 'simulated_reservation_or_order_failure';
 end if;
 return jsonb_build_object('ok',true,'status','reserved','available_after',v_remaining);
end;
$reserve$;

create or replace function public.ops2_enrich_storefront_order_result_v1(p_result jsonb)
returns jsonb language plpgsql stable security invoker as $enrich$
begin
 return p_result || jsonb_build_object(
   'registration_complete',true,
   'registration_state','complete',
   'whatsapp_return_origin','0975'
 );
end;
$enrich$;

-- The actual v3 wrapper follows from orders-production-v3-wrapper-v1.sql.

-- Synthetic WhatsApp outbox schema for the ACTUAL checkout_auto claim RPC.
-- Never connect this test to real provider credentials or live customer data.
create table public.ops2_whatsapp_order_runtime_v1 (
  id integer primary key,
  mode text not null,
  canary_order_id uuid
);
insert into public.ops2_whatsapp_order_runtime_v1(id,mode) values(1,'live');
create table public.ops2_whatsapp_outbox_v1 (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  recipient_kind text not null default 'customer',
  status text not null default 'pending',
  delivery_mode text not null default 'utility_template',
  available_at timestamptz not null default now(),
  attempt_count integer not null default 0,
  locked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_error text
);

