-- Disposable PostgreSQL 17 fixture. NEVER execute this file on production.
\set ON_ERROR_STOP on
create extension if not exists pgcrypto;
create role anon;
create role authenticated;
create role service_role bypassrls;
create table public.orders (
  id uuid primary key default gen_random_uuid(),
  payment_method text,
  order_number text,
  created_at timestamptz not null default now(),
  source text not null default 'vitrine',
  bling_synced_at timestamptz,
  sync_status text not null default 'pending'
);
create unique index orders_order_number_uq on public.orders(order_number) where order_number is not null;
-- Legacy snapshot fallback is used only for imports without customer number.
create sequence public.order_public_code_seq_v1;
create function public.ops2_format_order_public_code_v1(p_seq bigint)
 returns text language sql immutable as $format$
  select 'AA' || lpad((p_seq % 1000)::text,3,'0')
$format$;
create table public.order_public_snapshots_v1 (
  order_id uuid primary key references public.orders(id) on delete cascade,
  snapshot jsonb not null default '{}'::jsonb,
  public_code text not null default 'AA999',
  created_at timestamptz not null default now()
);
alter table public.order_public_snapshots_v1
  add constraint order_public_snapshots_v1_public_code_format_chk
  check (public_code ~ '^[A-Z]{2}[0-9]{3}$');
create unique index order_public_snapshots_v1_public_code_uidx
  on public.order_public_snapshots_v1(public_code);
create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id),
  product_id uuid,
  quantity numeric not null default 1 check (quantity > 0),
  metadata jsonb not null default '{}'::jsonb
);
create or replace function public.ops2_refresh_order_public_snapshot_v1(p_order_id uuid)
returns jsonb language plpgsql security definer
set search_path=public,pg_temp as $$
declare v_snapshot jsonb;
begin
  select jsonb_build_object('version',3,'item_count',count(*))
    into v_snapshot from public.order_items where order_id=p_order_id;
  insert into public.order_public_snapshots_v1(order_id,snapshot)
    values(p_order_id,v_snapshot)
    on conflict(order_id) do update set snapshot=excluded.snapshot;
  return v_snapshot;
end $$;
-- This is the deployed BEFORE-migration behavior, which skipped all
-- snapshots once an early public code row had been created.
create or replace function public.ops2_order_item_public_snapshot_trigger_v1()
returns trigger language plpgsql security definer
set search_path=public,pg_temp as $$
begin
  if exists(select 1 from public.order_public_snapshots_v1 where order_id=new.order_id)
    then return new; end if;
  perform public.ops2_refresh_order_public_snapshot_v1(new.order_id);
  return new;
end $$;
create constraint trigger trg_order_item_public_snapshot_v1
  after insert on public.order_items deferrable initially deferred
  for each row execute function public.ops2_order_item_public_snapshot_trigger_v1();
-- Historical identities must never change.
insert into public.orders(id) values ('00000000-0000-4000-8000-000000000001');
insert into public.order_public_snapshots_v1(order_id,public_code,snapshot)
values('00000000-0000-4000-8000-000000000001','AA001','{"version":1}'::jsonb);
grant usage on schema public to service_role;
grant select,insert,update on public.orders to service_role;
grant select,insert,update on public.order_public_snapshots_v1 to service_role;
grant select,insert on public.order_items to service_role;
-- Synthetic data schema for the REAL production reservation function.
-- Production currently uses Bling as stock authority; exercise that branch.
-- No production customer or stock rows are copied into this disposable fixture.
create table public.products (
  id uuid primary key,
  is_active boolean not null default true,
  stock numeric not null default 10
);
insert into public.products(id,is_active,stock)
values('00000000-0000-4000-8000-0000000000aa',true,10);
create table public.bling_hub_runtime_v2 (
  id integer primary key,
  metadata jsonb not null default '{}'::jsonb
);
insert into public.bling_hub_runtime_v2(id,metadata)
values(1,'{"ops2_stock_authority":"bling"}'::jsonb);
create view public.basket_locked_component_stock_v1 as
select id as product_id,0::numeric as basket_locked_quantity
from public.products where false;
create view public.ops2_loose_sellable_stock_v1 as
select id as product_id,stock as loose_sellable_stock,
       is_active,true as bling_stock_ready
from public.products;
create table public.vitrine_stock_reservations (
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid not null references public.products(id),
  quantity numeric not null check (quantity > 0),
  status text not null,
  expires_at timestamptz not null,
  updated_at timestamptz not null default now(),
  consumed_at timestamptz,
  released_at timestamptz,
  primary key(order_id,product_id)
);
grant select,insert,update on public.products to service_role;
grant select on public.bling_hub_runtime_v2 to service_role;
grant select on public.basket_locked_component_stock_v1 to service_role;
grant select on public.ops2_loose_sellable_stock_v1 to service_role;
grant select,insert,update on public.vitrine_stock_reservations to service_role;
-- Use the exact production create_vitrine_cart_order_v3 wrapper via a separate
-- SQL fixture. These three business dependencies are narrow test doubles; the
-- wrapper itself, its stock failure handling, and transaction sequence are real.
create or replace function public.create_vitrine_cart_order_v3_base(
 p_phone text,p_payment_method text,p_items jsonb,
 p_customer_snapshot jsonb,p_delivery jsonb
) returns jsonb language plpgsql security invoker as $base$
declare
 v_id uuid;
 v_qty integer := coalesce(nullif(p_items->0->>'qty','')::integer,1);
begin
 if v_qty < 1 then raise exception 'invalid_qty'; end if;
 perform pg_sleep(0.2);
 insert into public.orders(payment_method,source)
 values (p_payment_method,'vitrine') returning id into v_id;
 insert into public.order_items(order_id,product_id,quantity,metadata)
 values(v_id,'00000000-0000-4000-8000-0000000000aa',v_qty,'{}'::jsonb);
 return jsonb_build_object(
    'order_id',v_id,'total',75,'checkout_payment_method',p_payment_method);
end;
$base$;

create or replace function public.ops2_enrich_storefront_order_result_v1(p_result jsonb)
returns jsonb language plpgsql stable security invoker as $enrich$
begin
 -- Fail AFTER the real stock reservation is inserted. The entire checkout
 -- transaction must roll back orders, public identity and reservation rows.
 if p_result->>'checkout_payment_method'='TEST_ERROR' then
   raise exception 'simulated_reservation_or_order_failure';
 end if;
 return p_result || jsonb_build_object(
   'registration_complete',true,
   'registration_state','complete',
   'whatsapp_return_origin','0975'
 );
end;
$enrich$;

-- The actual v3 wrapper follows from orders-production-v3-wrapper-v1.sql.

-- Synthetic WhatsApp outbox schema for the ACTUAL checkout_auto claim RPC.
-- Never connect this test to real provider credentials or live customer data.
create table public.ops2_whatsapp_order_runtime_v1 (
  id integer primary key,
  mode text not null,
  canary_order_id uuid
);
insert into public.ops2_whatsapp_order_runtime_v1(id,mode) values(1,'live');
create table public.ops2_whatsapp_outbox_v1 (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  recipient_kind text not null default 'customer',
  status text not null default 'pending',
  delivery_mode text not null default 'utility_template',
  available_at timestamptz not null default now(),
  attempt_count integer not null default 0,
  locked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_error text
);
