-- R02+ privilege simulation ONLY in a newly created PostgreSQL CI database.
-- Never run in the canonical Supabase project.
\set ON_ERROR_STOP on
-- Roles are cluster-scoped; R02 checkout synthetic DB may have created them.
DO $test_roles$
DECLARE role_name text;
BEGIN
 FOREACH role_name IN ARRAY ARRAY['anon','authenticated','service_role','supabase_admin']
 LOOP
   IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname=role_name) THEN
     EXECUTE format('CREATE ROLE %I',role_name);
   END IF;
 END LOOP;
END $test_roles$;
GRANT USAGE ON SCHEMA public TO anon,authenticated,service_role;
GRANT CREATE,USAGE ON SCHEMA public TO supabase_admin;
CREATE TABLE public.dispatch_fiscal_jobs(order_id uuid PRIMARY KEY, state text);
CREATE TABLE public.ops_events(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, body jsonb);
CREATE TABLE public.order_payment_settlements(order_id uuid PRIMARY KEY, amount numeric);
GRANT SELECT ON public.dispatch_fiscal_jobs TO authenticated;
GRANT INSERT,SELECT ON public.ops_events TO authenticated;
GRANT SELECT ON public.ops_events TO anon;
GRANT SELECT ON public.dispatch_fiscal_jobs, public.ops_events TO service_role;
GRANT TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON ALL TABLES IN SCHEMA public TO anon,authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLES TO anon,authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public
  GRANT TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLES TO anon,authenticated;
SET ROLE supabase_admin;
CREATE TABLE public.future_admin_before_hardening(id bigint PRIMARY KEY);
RESET ROLE;

DO $baseline$
BEGIN
 IF NOT has_table_privilege('anon','public.dispatch_fiscal_jobs','TRUNCATE')
   OR NOT has_table_privilege('authenticated','public.ops_events','TRIGGER')
   OR NOT has_table_privilege('anon','public.future_admin_before_hardening','TRUNCATE')
   OR NOT has_table_privilege('anon','public.ops_events','MAINTAIN')
   OR NOT has_table_privilege('authenticated','public.future_admin_before_hardening','MAINTAIN')
 THEN RAISE EXCEPTION 'test did not model dangerous live table grants'; END IF;
END $baseline$;
