import fs from 'node:fs';
import assert from 'node:assert/strict';
const js=fs.readFileSync('admin/admin-customer-r10-v2.js','utf8');
const css=fs.readFileSync('admin/admin-customer-r10-v2.css','utf8');
const html=fs.readFileSync('admin/index.html','utf8');
const app=fs.readFileSync('admin/app.js','utf8');
const api=fs.readFileSync('admin/customer-os-api.js','utf8');
assert.doesNotMatch(js,/\bfetch\s*\(/,'R10 layer must not fetch');
assert.doesNotMatch(js,/localStorage|sessionStorage/,'R10 layer must not persist');
assert.match(js,/revisão humana/,'Identity conflicts must remain human-reviewed');
assert.match(js,/data-identity-approve/,'Mutable identity review must be guarded');
assert.match(js,/data-identity-reject/,'Identity rejection must be guarded');
assert.match(js,/aria-busy/,'Sensitive review actions must expose busy state');
assert.match(js,/stopImmediatePropagation/,'Repeated sensitive clicks must be intercepted before functional handler');
assert.match(js,/role','status/,'Empty/loading states must receive status semantics');
assert.match(css,/min-height:44px/,'Touch targets must be first-class');
assert.match(css,/safe-area-inset-bottom/,'Mobile safe area must be preserved');
assert.match(css,/100dvh/,'Customer 360 must support full-height mobile layout');
assert.match(app,/secureCustomersEnabled/,'Existing Customer OS gate must remain authority');
assert.match(app,/authenticateCustomerOsWithPin/,'Existing protected authentication contract must remain');
assert.match(app,/customerOsApi\('identity_review'/,'Identity review must stay on existing Customer OS API');
assert.match(app,/Isso não fará merge/,'Identity review must keep explicit no-merge confirmation');
assert.match(api,/missing_token/,'Customer OS API must remain fail-closed without session token');
assert.match(api,/clearCustomerOsSession/,'Unauthorized session must still be cleared');
assert.match(html,/admin-customer-r10-v2\.js/,'R10 layer must be wired');
assert.match(html,/admin-customer-r10-v2\.css/,'R10 styles must be wired');
console.log('admin R10 customer contract ok');
