import assert from 'node:assert/strict';
import fs from 'node:fs';
const html=fs.readFileSync('admin/index.html','utf8');
const cfg=fs.readFileSync('admin/config.js','utf8');
const js=fs.readFileSync('admin/admin-r14-operations-v2.js','utf8');
const css=fs.readFileSync('admin/admin-r14-operations-v2.css','utf8');
const logistics=fs.readFileSync('admin/logistics.js','utf8');
const financial=fs.readFileSync('admin/financial-admin.js','utf8');
assert.match(cfg,/logisticsUiEnabled:\s*false/,'logistics UI gate must remain OFF');
assert.match(cfg,/financialAdminUiEnabled:\s*false/,'financial UI gate must remain OFF');
assert.match(html,/financialAdminUiEnabled[^\n]*import\('\.\/financial-admin\.js'/,'financial module must stay behind its UI gate');
assert.match(html,/admin-r14-operations-v2\.js/);
assert.match(html,/admin-r14-operations-v2\.css/);
assert.doesNotMatch(js,/\bfetch\s*\(/,'R14 additive layer must not create transport');
assert.doesNotMatch(js,/localStorage|sessionStorage|indexedDB/,'R14 additive layer must not persist state');
assert.match(js,/aria-busy/);
assert.match(css,/min-height:\s*44px/);
assert.match(css,/safe-area-inset-bottom/);
assert.match(logistics,/runtime permaneceu OFF|runtime.*OFF/i);
assert.match(financial,/somente leitura|Nenhum provider real/i);
console.log('admin R14 operations contract: ok');
