import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');

test('Admin publica Estúdio Criativo',()=>{const h=read('admin/index.html');assert.match(h,/creative-studio\.html/);assert.match(h,/Estúdio Criativo/)});
test('briefing oferece somente completo rápido e institucional',()=>{const h=read('admin/creative-studio.html');for(const s of ['productionMode','referenceUpload','institutionalGoal'])assert.match(h,new RegExp(`id="${s}"`));for(const v of ['full','product_only','institutional'])assert.match(h,new RegExp(`value="${v}"`));assert.doesNotMatch(h,/mosaic_6x6|creative-studio-mosaic\.js/)});
test('todos os segmentos Gemini são de 10 segundos',()=>{const d=read('supabase/functions/creative-storyboard-director/index.ts');assert.match(d,/length:d\/10/);assert.match(d,/end_second:i\*10\+10/)});
test('modo rápido não exige geração visual',()=>{const j=read('admin/creative-studio.js');assert.match(j,/production_mode/);assert.match(j,/product_only/);assert.match(j,/skip_visual_generation/)});
test('modo institucional permite criar sem produto',()=>{const j=read('admin/creative-studio.js'),d=read('supabase/functions/creative-storyboard-director/index.ts'),p=read('supabase/functions/creative-storyboard-projects/index.ts');assert.match(j,/institutional/);assert.match(j,/reference_image/);assert.match(d,/mode!==\'institutional\'&&!products\.length/);assert.match(p,/mode!==\'institutional\'&&!products\.length/)});
test('produto e imagens geradas oferecem download e prompt',()=>{const j=read('admin/creative-studio.js'),u=read('admin/creative-studio-ui-helpers.js');assert.match(j,/downloadAsset/);assert.match(j,/Baixar foto original/);assert.match(j,/Baixar imagem/);assert.match(j,/Copiar prompt/);assert.match(u,/Baixar foto original/);assert.match(u,/Baixar imagem/)});
test('pacotes Gemini mobile exibem produto e copiar prompt com fallback',()=>{const u=read('admin/creative-studio-ui-helpers.js'),c=read('admin/creative-studio.css'),h=read('admin/creative-studio.html');assert.match(u,/package-product-ref/);assert.match(u,/Copiar prompt Gemini/);assert.match(u,/execCommand\('copy'\)/);assert.match(c,/@media\(max-width:480px\)/);assert.match(c,/overflow-x:hidden/);assert.match(c,/gemini-package>button/);assert.match(h,/creative-studio\.css\?v=20260917-6/)});
test('pacote Veo trava produto e referências',()=>{const d=read('supabase/functions/creative-storyboard-director/index.ts');for(const s of ['REFERENCE PRIORITY','PRODUCT LOCK','STYLE LOCK','SHOT TIMELINE','CAMERA DIRECTION','AUDIO BLUEPRINT','NEGATIVE CONSTRAINTS','FINAL FRAME REQUIREMENT'])assert.match(d,new RegExp(s));assert.match(d,/foto original/i);assert.match(d,/embalagem/i);assert.match(d,/logotipo/i)});
test('plano persiste briefing completo para retomada',()=>{const j=read('admin/creative-studio.js');assert.match(j,/Object\.assign\(plan,b\)/);assert.match(j,/production_mode/);assert.match(j,/institutional_goal/)});
test('busca de produtos usa backend protegido do Estúdio',()=>{const j=read('admin/creative-studio.js'),p=read('supabase/functions/creative-storyboard-projects/index.ts');assert.match(j,/action:'search_products'/);assert.doesNotMatch(j,/adminApi\(/);assert.match(p,/action==='search_products'/)});
test('produção completa gera uma imagem por vez',()=>{const j=read('admin/creative-studio.js');assert.match(j,/if\(i>0&&!prev\?\.approved_image_url\)/);assert.match(j,/candidate_image_url/);assert.match(j,/approved_image_url/)});
test('primeira imagem trava identidade visual',()=>{const h=read('admin/creative-studio.html'),j=read('admin/creative-studio.js');assert.match(h,/Aprovar identidade visual/);assert.match(j,/visualBible\?\.locked/)});
test('pacotes completos exigem as duas imagens de limite aprovadas',()=>{const j=read('admin/creative-studio.js');assert.match(j,/\[p\.start_second,p\.end_second\]/);assert.match(j,/f\?\.status==='approved'&&f\?\.approved_image_url/);assert.match(j,/navigator\.clipboard\.writeText/)});
test('Estúdio renova JWT expirado',()=>{const j=read('admin/creative-studio.js');assert.match(j,/grant_type=refresh_token/);assert.match(j,/r\.status===401&&retry/)});
test('quantidade de imagens segue 2 a 7 por duração',()=>{const d=read('supabase/functions/creative-storyboard-director/index.ts'),j=read('admin/creative-studio.js'),h=read('admin/creative-studio.html');assert.match(d,/imageCount=\(d:number\)=>d\/10\+1/);assert.match(d,/i\*10/);assert.match(j,/imageCountForDuration/);for(const t of ['10 segundos · 2 imagens','20 segundos · 3 imagens','30 segundos · 4 imagens','40 segundos · 5 imagens','50 segundos · 6 imagens','60 segundos · 7 imagens'])assert.match(h,new RegExp(t))});
test('gerador local de vídeo e mosaico foram removidos',()=>{const h=read('admin/creative-studio.html'),d=read('supabase/functions/creative-storyboard-director/index.ts'),i=read('supabase/functions/creative-storyboard-image/index.ts'),p=read('admin/creative-studio-persistence.js');for(const x of[h,d,i,p])assert.doesNotMatch(x,/mosaic_6x6|CreativeStudioMosaic|captureStream|MediaRecorder/)});
test('projetos ficam salvos, podem ser reabertos e excluídos com confirmação',()=>{const h=read('admin/creative-studio.html'),p=read('supabase/functions/creative-storyboard-projects/index.ts'),x=read('admin/creative-studio-persistence.js');assert.match(h,/Projetos salvos/);assert.match(p,/action==='delete'/);assert.match(p,/creative_storyboard_generation_events/);assert.match(p,/creative_storyboard_gemini_packages/);assert.match(p,/creative_storyboard_keyframes/);assert.match(p,/creative_video_project_products/);assert.match(p,/creative_video_projects/);assert.match(p,/creative-storyboards/);assert.match(p,/storage\.from/);assert.match(x,/Excluir projeto/);assert.match(x,/confirm\(/);assert.match(x,/action:'delete'/);assert.match(x,/openSavedProject/)});
