import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8');
const must=(v,m)=>{if(!v)throw new Error(m)};
const media=read('supabase/functions/admin-marketing-media-v1/index.ts');
const insights=read('supabase/functions/admin-marketing-insights-v1/index.ts');
const api=read('admin/marketing-api.js');
const ui=read('admin/marketing.js');
const worker=read('scripts/marketing-light-video-render-worker.mjs');
const workflow=read('.github/workflows/marketing-light-video-preview.yml');
const queue=read('supabase/migrations/20260918160126_marketing_light_video_preview_queue_v1.sql');

must(media.includes('@imagemagick/magick-wasm@0.0.30'),'magick-wasm renderer missing');
must(media.includes('action==="render_preview"'),'render_preview action missing');
must(media.includes('action==="queue_light_video"'),'queue_light_video action missing');
must(media.includes('generation_mode!=="no_ai"'),'preview must be no_ai only');
must(media.includes('external_publish:false'),'preview must never publish');
must(media.includes('source_host_not_allowed'),'source allowlist missing');
must(insights.includes('render_jobs:renderJobs||[]'),'render job status missing from overview');
must(insights.includes('output_spec'),'asset output spec missing');
must(api.includes('renderMarketingPreview'),'render API missing');
must(api.includes('queueMarketingLightVideo'),'video queue API missing');
must(ui.includes('Colocar MP4 10s na fila'),'video queue button missing');
must(ui.includes('<video src='),'video player missing');
must(worker.includes("'-t','10'"),'worker must render exactly 10s');
must(worker.includes("'libx264'"),'worker must use H264');
must(worker.includes("'-an'"),'V1 must have no audio');
must(worker.includes('zoompan'),'micro motion missing');
must(workflow.includes('workflow_dispatch'),'manual workflow missing');
must(!workflow.includes('schedule:'),'workflow must not recur during homologation');
must(queue.includes("render_kind='economical_video'"),'queue must be economical video only');
must(queue.includes('estimated_cost_cents'), 'cost accounting missing');
must(queue.includes('ai_used=false'),'AI must be disabled');
must(queue.includes('10000'),'10s contract missing');
must(queue.includes('grant execute on function public.claim_marketing_light_video_preview_job_v1'), 'service role worker grant missing');
console.log('marketing deterministic preview + light video v1 contract: ok');