import {CONFIG} from '../admin-v3/config.js';
const $=id=>document.getElementById(id), AI_FN='ame-mais-analyze-v2', LI_FN='ame-mais-loja-integrada', MAX_PHOTOS=3, HISTORY_KEY='ameMais2RecentRuns';
const KINDS=[['hero','Principal'],['lifestyle','Em uso'],['detail','Detalhe'],['alternate','Outro ângulo']];
const state={files:[],sessionId:null,analysis:null,images:{},busy:false,edit:null,count:null,countMode:'total'};
const cleanEan=v=>String(v||'').replace(/\D/g,'').slice(0,14), parsePrice=v=>{let s=String(v||'').trim().replace(/[^\d,.-]/g,'');if(!s)return 0;if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');const n=Number(s);return Number.isFinite(n)&&n>0?Math.round(n*100)/100:0}, money=v=>`R$ ${Number(v||0).toFixed(2).replace('.',',')}`;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
function toast(m,t=''){const e=document.createElement('div');e.className=`toast ${t}`;e.textContent=m;$('toastRegion').append(e);setTimeout(()=>e.remove(),3200)}
async function post(fn,body){const c=new AbortController(),t=setTimeout(()=>c.abort(),150000);try{const r=await fetch(`${CONFIG.supabaseUrl}/functions/v1/${fn}`,{method:'POST',headers:{apikey:CONFIG.supabasePublishableKey,'content-type':'application/json'},body:JSON.stringify(body),signal:c.signal});const d=await r.json();if(!r.ok||d.ok===false)throw new Error(d.error||d.detail||'Falha.');return d}finally{clearTimeout(t)}}
async function li(action,payload={}){return (await post(LI_FN,{action,...payload})).data}
async function apiForm(form){const r=await fetch(`${CONFIG.supabaseUrl}/functions/v1/${AI_FN}`,{method:'POST',headers:{apikey:CONFIG.supabasePublishableKey},body:form});const d=await r.json();if(!r.ok||d.ok===false)throw new Error(d.error||d.detail||'Falha no processamento.');return d}
function mode(name){for(const n of ['Create','Products','Count']){$(`mode${n}`).classList.toggle('active',n.toLowerCase()===name);$(`${n.toLowerCase()}View`).classList.toggle('hidden',n.toLowerCase()!==name)}if(name==='products')loadProducts();if(name==='count')setTimeout(()=>$('countEan').focus(),50)}
$('modeCreate').onclick=()=>mode('create');$('modeProducts').onclick=()=>mode('products');$('modeCount').onclick=()=>mode('count');
async function health(){try{await li('health');$('liStatus').textContent='Loja conectada';$('liStatus').classList.add('ok')}catch{$('liStatus').textContent='Loja não conectada'}}health();
async function compress(file){const b=await createImageBitmap(file),s=Math.min(1,1800/Math.max(b.width,b.height)),c=document.createElement('canvas');c.width=Math.round(b.width*s);c.height=Math.round(b.height*s);c.getContext('2d').drawImage(b,0,0,c.width,c.height);b.close();const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.86));return new File([blob],file.name||'produto.jpg',{type:'image/jpeg'})}
async function addFiles(list){for(const f of Array.from(list||[]).slice(0,MAX_PHOTOS-state.files.length))state.files.push(await compress(f));renderPhotos()}
function renderPhotos(){$('photoCount').textContent=`${state.files.length}/3`;$('photoPreviews').innerHTML=state.files.map((f,i)=>`<span class="photo-preview"><img src="${URL.createObjectURL(f)}"><button data-remove="${i}">×</button></span>`).join('');$('analyzeButton').disabled=!state.files.length||state.busy}
$('cameraInput').onchange=e=>addFiles(e.target.files);$('photoInput').onchange=e=>addFiles(e.target.files);$('photoPreviews').onclick=e=>{const b=e.target.closest('[data-remove]');if(b){state.files.splice(+b.dataset.remove,1);renderPhotos()}};
async function scan(file,target){if(!file)return;try{if(!('BarcodeDetector'in window))throw new Error('Digite o EAN neste aparelho.');const d=new BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e']}),b=await createImageBitmap(file),codes=await d.detect(b);b.close();const ean=cleanEan(codes?.[0]?.rawValue);if(!ean)throw new Error('Código não encontrado.');$(target).value=ean;if(target==='eanInput')$('eanMessage').textContent=`EAN lido: ${ean}`;if(target==='countEan')await lookupCount()}catch(e){toast(e.message,'error')}}
$('scanEanInput').onchange=e=>scan(e.target.files?.[0],'eanInput');$('countScan').onchange=e=>scan(e.target.files?.[0],'countEan');
function progress(a,b,p){$('progressCard').classList.remove('hidden');$('progressTitle').textContent=a;$('progressText').textContent=b;$('progressPercent').textContent=`${p}%`;$('progressBar').style.width=`${p}%`}
async function analyze(){if(!state.files.length)return;state.busy=true;state.sessionId=crypto.randomUUID();try{progress('Analisando','Preparando cadastro de e-commerce.',15);const f=new FormData();f.append('action','analyze');f.append('session_id',state.sessionId);f.append('ean',cleanEan($('eanInput').value));f.append('price',String(parsePrice($('priceInput').value)));state.files.forEach((x,i)=>f.append(`image${i+1}`,x));const d=await apiForm(f);state.analysis=d.analysis;$('productName').value=state.analysis.nome_cadastro||'';$('ecommerceDescription').value=state.analysis.descricao_ecommerce||'';$('resultMeta').textContent=state.analysis.tipo_produto||'';$('resultArea').classList.remove('hidden');for(let i=0;i<KINDS.length;i++){const [kind]=KINDS[i],g=new FormData();g.append('action','generate_image');g.append('session_id',state.sessionId);g.append('kind',kind);g.append('analysis_json',JSON.stringify({...state.analysis,nome_cadastro:$('productName').value,descricao_ecommerce:$('ecommerceDescription').value,ean:cleanEan($('eanInput').value),preco:parsePrice($('priceInput').value)}));progress('Gerando imagens',`${i+1} de 4`,30+i*16);state.images[kind]=await apiForm(g)}renderImages();progress('Pronto','Revise e publique na loja.',100);remember(state.sessionId);renderHistory()}catch(e){toast(e.message,'error')}finally{state.busy=false;renderPhotos()}}
$('analyzeButton').onclick=analyze;
function renderImages(){$('imageGrid').innerHTML=KINDS.map(([k,n])=>state.images[k]?.url?`<article class="output-card"><img src="${esc(state.images[k].url)}"><b>${n}</b></article>`:'').join('')}
$('publishLi').onclick=async()=>{try{const ean=cleanEan($('eanInput').value),found=ean?await li('find_by_ean',{ean}):null;if(found?.product){toast('EAN já cadastrado. Abrindo para editar.');mode('products');return openEditor(found)}const product={nome:$('productName').value.trim(),descricao_completa:$('ecommerceDescription').value.trim(),gtin:ean,sku:ean||`AME-${Date.now()}`,ativo:true};const created=await li('create_product',{product}),id=created.id;if(!id)throw new Error('Produto criado sem ID retornado.');await li('set_price',{id,price:parsePrice($('priceInput').value)});for(const [kind] of KINDS)if(state.images[kind]?.url)await li('add_image',{id,image_url:state.images[kind].url,primary:kind==='hero'});toast('Produto publicado na Loja Integrada.','ok')}catch(e){toast(e.message,'error')}};
async function loadProducts(){try{const q=$('liSearch').value.trim();if(/^\d{8,14}$/.test(cleanEan(q))&&q){const hit=await li('find_by_ean',{ean:q});return renderList(hit?[hit]:[])}const d=await li('list_products',{limit:50});let rows=d?.objects||d?.results||[];if(q)rows=rows.filter(x=>`${x.nome} ${x.sku}`.toLowerCase().includes(q.toLowerCase()));renderList(rows.map(product=>({product})))}catch(e){$('liProductList').innerHTML=`<p>${esc(e.message)}</p>`}}
function renderList(rows){$('liProductList').innerHTML=rows.length?rows.map(x=>{const p=x.product||x,c=x.card;return `<button class="product-row" data-id="${p.id}"><span><strong>${esc(p.nome)}</strong><small>${esc(p.sku||'')} ${esc(p.gtin||'')}</small></span><span>${c?`${money(c.price)}<small>Estoque ${c.stock}</small>`:''}<small>${p.ativo?'Ativo':'Inativo'}</small></span></button>`}).join(''):'<p>Nenhum produto encontrado.</p>'}
$('liSearchButton').onclick=loadProducts;$('liSearch').onkeydown=e=>{if(e.key==='Enter')loadProducts()};$('liProductList').onclick=async e=>{const b=e.target.closest('[data-id]');if(b)openEditor(await li('get_product',{id:b.dataset.id}))};
function openEditor(d){const p=d.product||d,price=d.price?.cheio??d.card?.price??0,stock=d.stock?.quantidade??d.card?.stock??0;state.edit={id:p.id,active:Boolean(p.ativo)};$('editTitle').textContent=p.nome;$('editName').value=p.nome||'';$('editEan').value=p.gtin||'';$('editDescription').value=p.descricao_completa||'';$('editPrice').value=money(price);$('editStock').value=stock;$('toggleActive').textContent=state.edit.active?'Desativar':'Ativar';$('productEditor').classList.remove('hidden');$('productEditor').scrollIntoView({behavior:'smooth'})}
$('saveProduct').onclick=async()=>{if(!state.edit)return;try{await li('update_product',{id:state.edit.id,changes:{nome:$('editName').value.trim(),gtin:cleanEan($('editEan').value),descricao_completa:$('editDescription').value}});await Promise.all([li('set_price',{id:state.edit.id,price:parsePrice($('editPrice').value)}),li('set_stock',{id:state.edit.id,quantity:$('editStock').value})]);toast('Produto atualizado.','ok');loadProducts()}catch(e){toast(e.message,'error')}};
$('toggleActive').onclick=async()=>{if(!state.edit)return;try{state.edit.active=!state.edit.active;await li('set_active',{id:state.edit.id,active:state.edit.active});$('toggleActive').textContent=state.edit.active?'Desativar':'Ativar';toast(state.edit.active?'Produto ativado.':'Produto desativado.','ok')}catch(e){state.edit.active=!state.edit.active;toast(e.message,'error')}};
async function lookupCount(){const ean=cleanEan($('countEan').value);if(ean.length<8)return;try{const d=await li('find_by_ean',{ean});state.count=d;if(!d){$('countProduct').textContent='Produto não encontrado';return}$('countProduct').innerHTML=`<strong>${esc(d.card?.name||d.product.nome)}</strong><br>Estoque atual: <b>${d.card?.stock??d.stock?.quantidade??0}</b>`;$('countQuantity').value=state.countMode==='add'?1:'';$('countQuantity').focus()}catch(e){toast(e.message,'error')}}
$('countEan').onkeydown=e=>{if(e.key==='Enter')lookupCount()};$('countTotal').onclick=()=>{state.countMode='total';$('countTotal').classList.add('active');$('countAdd').classList.remove('active')};$('countAdd').onclick=()=>{state.countMode='add';$('countAdd').classList.add('active');$('countTotal').classList.remove('active')};
$('saveCount').onclick=async()=>{if(!state.count?.product)return toast('Leia um produto primeiro.','error');try{const current=state.count.card?.stock??state.count.stock?.quantidade??0,q=Math.max(0,parseInt($('countQuantity').value||'0',10)),next=state.countMode==='add'?current+q:q;await li('set_stock',{id:state.count.product.id,quantity:next});toast(`Estoque atualizado: ${next}`,'ok');state.count=null;$('countEan').value='';$('countQuantity').value='';$('countProduct').textContent='Aguardando produto';$('countEan').focus()}catch(e){toast(e.message,'error')}};
function getHistory(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]')}catch{return[]}}function remember(id){localStorage.setItem(HISTORY_KEY,JSON.stringify([id,...getHistory().filter(x=>x!==id)].slice(0,3)))}async function renderHistory(){const cards=[];for(const id of getHistory()){try{const f=new FormData();f.append('action','get_run');f.append('session_id',id);const d=await apiForm(f),a=d.run?.analysis||{},hero=(d.image_rows||[]).find(x=>x.kind==='hero')?.image_url||'';cards.push(`<article class="recent-card">${hero?`<img src="${esc(hero)}">`:''}<div class="recent-card-copy"><strong>${esc(a.nome_cadastro||'Produto')}</strong><span>${money(a.preco)}</span></div></article>`)}catch{}}$('recentCreations').innerHTML=cards.join('')||'<p>Nenhuma criação neste aparelho.</p>'}
$('newProduct').onclick=()=>location.href=location.pathname;renderPhotos();renderHistory();