(function(){
'use strict';
const C=window.DA_COUNT_CONFIG||{};
const EDGE='inventory-fast-balance-v3';
const K={device:'da_count_v2_device',queue:'da_fast_capture_queue_v3',rows:'da_fast_balance_rows_v3',unknown:'da_fast_balance_unknown_v3',stats:'da_fast_capture_stats_v3'};
const $=id=>document.getElementById(id),txt=v=>String(v??'').replace(/\s+/g,' ').trim(),dig=v=>String(v??'').replace(/\D/g,''),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let autoTimer=null,flushTimer=null,inFlight=false,retryMs=700,bootstrapped=false,bootstrapping=false;
function read(k,f){try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
function uuid(){if(globalThis.crypto?.randomUUID)return crypto.randomUUID();let d=Date.now();return'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=(d+Math.random()*16)%16|0;d=Math.floor(d/16);return(c==='x'?r:(r&3)|8).toString(16)})}
function device(){let v=localStorage.getItem(K.device);if(!v){const f=/Android/i.test(navigator.userAgent)?'Android':/iPhone|iPad/i.test(navigator.userAgent)?'iOS':'Browser';v=`${f}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;localStorage.setItem(K.device,v)}return v}
function queue(){return read(K.queue,[])}function rows(){return read(K.rows,[])}function unknown(){return read(K.unknown,[])}function stats(){return read(K.stats,{captured:0,confirmed:0,unknown:0})}
function status(m,k=''){const e=$('fastStatus');if(e){e.textContent=m;e.className=`note ${k}`.trim()}}
function toast(m,k=''){const h=$('toastRegion');if(!h)return;const e=document.createElement('div');e.className=`toast ${k}`.trim();e.textContent=m;h.appendChild(e);setTimeout(()=>e.remove(),k==='error'?5200:2600)}
function focus(){setTimeout(()=>{const i=$('fastScanInput');if(!i)return;i.disabled=false;i.readOnly=false;try{i.focus({preventScroll:true})}catch{try{i.focus()}catch{}}},0)}
function feedback(kind='ok'){const c=$('fastLastRead');if(c){c.classList.remove('ok','warn','error','pulse');c.classList.add(kind==='ok'?'ok':kind==='warn'?'warn':'error','pulse');setTimeout(()=>c.classList.remove('pulse'),120)}if(navigator.vibrate)navigator.vibrate(kind==='ok'?12:[35,25,35])}
function showLast(name,qty='',kind='ok',label='CAPTURADO'){if($('fastLastState'))$('fastLastState').textContent=label;if($('fastLastName'))$('fastLastName').textContent=name;if($('fastLastQty'))$('fastLastQty').textContent=qty?`× ${qty}`:'';feedback(kind)}
async function api(action,payload={}){const r=await fetch(`${C.supabaseUrl}/functions/v1/${EDGE}`,{method:'POST',headers:{apikey:C.supabasePublishableKey,'Content-Type':'application/json'},body:JSON.stringify({action,device_label:device(),...payload}),cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw new Error(d.detail||d.error||`Erro ${r.status}`);return d}
function render(){const q=queue(),r=rows(),u=unknown(),s=stats();if($('fastTotalUnits'))$('fastTotalUnits').textContent=String(s.captured||0);if($('fastDistinctCount'))$('fastDistinctCount').textContent=String(r.length);if($('fastUnknownCount'))$('fastUnknownCount').textContent=String(u.length);if($('fastUnknownUnits'))$('fastUnknownUnits').textContent=String(s.unknown||0);if($('fastCatalogBadge'))$('fastCatalogBadge').textContent=q.length?`${q.length} na fila`:'AUTO';const h=$('fastCountedList');if(h)h.innerHTML=r.length?r.map(x=>`<article class="fast-count-row"><div class="fast-count-name"><strong>${esc(x.name)}</strong><small>EAN ${esc(x.code)} · ${esc(x.source==='firebase_imported'?'migrado do Firebase · ':'')}${esc(x.last_scanned_at?new Date(x.last_scanned_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}):'')}</small></div><div class="fast-balance-qty"><span>ESTOQUE</span><b>${esc(x.quantity)}</b></div></article>`).join(''):'<div class="fast-empty">Pode começar a ler. A tela não precisa esperar a busca de cada EAN.</div>';const uh=$('fastUnknownList');if(uh)uh.innerHTML=u.length?u.map(x=>`<article class="fast-unknown-row"><div style="grid-column:1/4"><strong>EAN ${esc(x.code)}</strong><small>${esc(x.last_scanned_at?new Date(x.last_scanned_at).toLocaleTimeString('pt-BR'):'')}</small><span>enviado para cadastro pela IA</span></div><b>× ${esc(x.quantity)}</b></article>`).join(''):'<div class="fast-empty">Nenhum EAN aguardando cadastro.</div>';if($('fastUnknownSection'))$('fastUnknownSection').classList.toggle('has-pending',u.length>0)}
function upsertConfirmed(product,result,source){const list=rows();let x=list.find(r=>r.key===product.id);if(!x){x={key:product.id,product_id:product.id,code:dig(product.gtin||result.ean),name:txt(product.name)||`EAN ${result.ean}`,quantity:0};list.unshift(x)}x.code=dig(product.gtin||result.ean);x.name=txt(product.name)||x.name;x.quantity=Number(result.quantity||product.stock||0);x.last_scanned_at=result.scanned_at||new Date().toISOString();x.source=source||product.source_system||'supabase';list.sort((a,b)=>String(b.last_scanned_at||'').localeCompare(String(a.last_scanned_at||'')));write(K.rows,list.slice(0,120))}
function upsertUnknown(ean,at){const list=unknown();let x=list.find(r=>r.code===ean);if(!x){x={code:ean,quantity:0};list.unshift(x)}x.quantity++;x.last_scanned_at=at||new Date().toISOString();write(K.unknown,list.slice(0,80))}
function applyResponse(data,batch){const products=new Map((data.products||[]).map(p=>[p.id,p])),sources=data.source_by_product||{};let confirmed=0,unk=0;for(const r of data.results||[]){if(r.kind==='counted'){const p=products.get(r.product_id);if(p){upsertConfirmed(p,r,sources[r.product_id]?.source);confirmed++}}else if(r.kind==='unknown'){upsertUnknown(r.ean,r.scanned_at);unk++}}const s=stats();s.confirmed=(s.confirmed||0)+confirmed;s.unknown=(s.unknown||0)+unk;write(K.stats,s);const ids=new Set(batch.map(e=>e.event_id));write(K.queue,queue().filter(e=>!ids.has(e.event_id)));render();if(unk)status(`${confirmed} leitura(s) aplicadas · ${unk} EAN(s) enviados para cadastro IA.`,'warning');else status(`${confirmed||batch.length} leitura(s) processadas · balanço salvo automaticamente.`,'success')}
async function flush(){clearTimeout(flushTimer);if(inFlight||!navigator.onLine)return;const q=queue();if(!q.length){render();return}const batch=q.slice(0,50);inFlight=true;try{const d=await api('scan_batch',{events:batch});applyResponse(d,batch);retryMs=700}catch(e){status(`Fila preservada (${q.length}). Tentando novamente sem perder leituras…`,'warning');retryMs=Math.min(8000,Math.round(retryMs*1.7))}finally{inFlight=false;if(queue().length)scheduleFlush(retryMs);else render()}}
function scheduleFlush(delay=260){clearTimeout(flushTimer);flushTimer=setTimeout(flush,delay)}
function capture(raw){const ean=dig(raw),input=$('fastScanInput');if(input)input.value='';clearTimeout(autoTimer);if(!ean){focus();return}const q=queue();q.push({event_id:uuid(),ean,scanned_at:new Date().toISOString()});write(K.queue,q);const s=stats();s.captured=(s.captured||0)+1;write(K.stats,s);showLast(`EAN ${ean}`,'','ok','CAPTURADO');status(q.length===1?'Leitura guardada · processamento automático em segundo plano.':`${q.length} leituras na fila local · continue lendo.`,'busy');render();scheduleFlush(q.length>=40?20:220);focus()}
function normalizeRecent(state){const p=Array.isArray(state.product)?state.product[0]:state.product;if(!p?.id)return null;return{key:p.id,product_id:p.id,code:dig(state.ean||p.gtin),name:txt(p.name)||`EAN ${state.ean}`,quantity:Number(state.quantity||p.stock||0),last_scanned_at:state.last_scanned_at,source:p.source_system||'supabase'}}
async function bootstrap(force=false){if(bootstrapping||(!force&&bootstrapped))return;bootstrapping=true;try{const d=await api('bootstrap');bootstrapped=true;const recent=(d.recent||[]).map(normalizeRecent).filter(Boolean);if(recent.length)write(K.rows,recent);render();status('Conectado ao Supabase. Pode começar a ler.','success');scheduleFlush(50)}catch(e){bootstrapped=false;status('Leitor pronto. A sincronização será repetida automaticamente.','warning')}finally{bootstrapping=false}}
function clearScreen(){write(K.rows,[]);write(K.unknown,[]);write(K.stats,{captured:0,confirmed:0,unknown:0});render();status(queue().length?`Histórico da tela limpo. ${queue().length} leitura(s) continuam seguras na fila.`:'Tela limpa. O estoque já salvo não foi alterado.');focus()}
function bind(){const input=$('fastScanInput');if(!input)return;input.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key==='Tab'){e.preventDefault();capture(input.value)}});input.addEventListener('input',()=>{clearTimeout(autoTimer);const v=dig(input.value);if(v.length>=8)autoTimer=setTimeout(()=>capture(input.value),70)});input.addEventListener('blur',focus);document.addEventListener('keydown',e=>{const t=e.target;if(t instanceof HTMLButtonElement||t instanceof HTMLAnchorElement)return;if(document.activeElement!==input&&(/^\d$/.test(e.key)||e.key==='Enter')){focus();if(/^\d$/.test(e.key)){e.preventDefault();input.value+=e.key;input.dispatchEvent(new Event('input',{bubbles:true}))}}},true);$('fastFinishButton')?.addEventListener('click',()=>{scheduleFlush(0);focus()});$('fastClearButton')?.addEventListener('click',clearScreen);$('fastRefreshCatalogButton')?.addEventListener('click',async()=>{try{const d=await api('recent');const recent=(d.recent||[]).map(normalizeRecent).filter(Boolean);write(K.rows,recent);render();status('Situação atualizada do Supabase.','success')}catch(e){status(e.message||'Falha ao atualizar.','error')}focus()});window.addEventListener('online',()=>{bootstrap(true);scheduleFlush(0)});window.addEventListener('pageshow',()=>{bootstrap(true);focus();scheduleFlush(50)});document.addEventListener('visibilitychange',()=>{if(!document.hidden){bootstrap(true);focus();scheduleFlush(50)}});setInterval(()=>{focus();if(queue().length)scheduleFlush(0);if(!bootstrapped)bootstrap()},1500);render();bootstrap();focus();scheduleFlush(80)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
