import {attendanceAuthorizedFetch} from '../atendimento/attendance-auth.js?v=auth-refresh-v2';

const REPORT_API='https://ssbesxgaijknwsjbsbcz.supabase.co/functions/v1/admin-marketing-campaign-report-v1';
const ADMIN_PUBLIC_KEY=['sb','publishable','tFXHtH0HCXZepVtwgKElIg','DxS76Gu8'].join('_');
const CSS_URL='/vitrine/admin/marketing/campaign-report.css?v=marketing-campaign-report-v1';
const STATUS_LABELS={accepted:'Aceita',sent:'Enviada',delivered:'Entregue',read:'Lida',failed:'Falhou',skipped:'Não enviada',pending:'Pendente'};
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const fmtDate=value=>{if(!value)return '—';const date=new Date(value);return Number.isNaN(date.getTime())?'—':date.toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})};
function ensureCss(){if(document.querySelector('link[data-da-marketing-campaign-report]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href=CSS_URL;link.dataset.daMarketingCampaignReport='1';document.head.appendChild(link)}
function close(dialog){try{dialog.close()}catch{}dialog.remove()}
async function loadCampaignReport(campaignId){const url=new URL(REPORT_API);url.searchParams.set('campaign_id',campaignId);const response=await attendanceAuthorizedFetch(url,{method:'GET',headers:{apikey:ADMIN_PUBLIC_KEY},cache:'no-store'});const data=await response.json().catch(()=>({}));if(!response.ok||data?.ok===false)throw new Error(data?.error||`report_${response.status}`);return data}
function renderCampaignReport(data){const s=data?.summary||{},items=Array.isArray(data?.items)?data.items:[],campaign=data?.campaign||{};return `<div class="marketing-report"><header class="marketing-report-head"><h3>${esc(campaign.name||'Campanha')}</h3><p>${esc(campaign.template_name||'Template')} · ${esc(campaign.status||'—')}</p></header><div class="marketing-report-kpis"><article><small>Enviados</small><strong>${Number(s.sent||0)}</strong></article><article><small>Entregues</small><strong>${Number(s.delivered||0)}</strong></article><article><small>Lidos</small><strong>${Number(s.read||0)}</strong></article><article><small>Falhas</small><strong>${Number(s.failed||0)}</strong></article></div><div class="marketing-report-rates"><article><small>Taxa de entrega</small><strong>${Number(s.delivery_rate||0).toLocaleString('pt-BR')}%</strong></article><article><small>Taxa de leitura</small><strong>${Number(s.read_rate||0).toLocaleString('pt-BR')}%</strong></article></div><div class="marketing-report-table-wrap"><table class="marketing-report-table"><thead><tr><th>Cliente</th><th>Telefone</th><th>Status</th><th>Atualização</th></tr></thead><tbody>${items.length?items.map(item=>`<tr><td><strong>${esc(item.name||'Cliente')}</strong></td><td>${esc(item.masked_phone||'—')}</td><td><span class="marketing-report-pill ${esc(item.status||'pending')}">${esc(STATUS_LABELS[item.status]||item.status||'Pendente')}</span></td><td>${esc(fmtDate(item.updated_at))}</td></tr>`).join(''):'<tr><td colspan="4" class="marketing-report-empty">Nenhum destinatário registrado nesta campanha.</td></tr>'}</tbody></table></div><p class="marketing-campaign-note">Público total da campanha: ${Number(s.total||0)} destinatário(s).</p></div>`}
async function openCampaignReport(campaignId){ensureCss();const dialog=document.createElement('dialog');dialog.className='marketing-template-dialog marketing-report-dialog';dialog.innerHTML='<div class="marketing-template-dialog-head"><strong>Relatório da campanha</strong><button type="button" aria-label="Fechar" data-report-close>×</button></div><div class="marketing-template-dialog-body" data-report-body><div class="loading">Carregando relatório…</div></div>';dialog.querySelector('[data-report-close]').addEventListener('click',()=>close(dialog));dialog.addEventListener('cancel',event=>{event.preventDefault();close(dialog)});document.body.appendChild(dialog);dialog.showModal();try{const data=await loadCampaignReport(campaignId);if(dialog.isConnected)dialog.querySelector('[data-report-body]').innerHTML=renderCampaignReport(data)}catch(error){if(dialog.isConnected)dialog.querySelector('[data-report-body]').innerHTML=`<div class="marketing-audience-error">Não foi possível carregar o relatório: ${esc(error?.message||error)}</div>`}return dialog}
window.addEventListener('marketing:open-campaign-report',event=>{const id=String(event?.detail?.campaign_id||'');if(id)openCampaignReport(id).catch(error=>console.warn('marketing-campaign-report',String(error?.message||error).slice(0,160)))})
window.DAMarketingCampaignReport={openCampaignReport,loadCampaignReport,renderCampaignReport};
export {openCampaignReport,loadCampaignReport,renderCampaignReport};
