import {attendanceAuthorizedFetch,attendanceJsonApi} from '../atendimento/attendance-auth.js?v=auth-refresh-v2';

const STRATEGY_API='https://ssbesxgaijknwsjbsbcz.supabase.co/functions/v1/admin-marketing-strategy-v1';
const CAMPAIGN_BRIDGE_API='https://ssbesxgaijknwsjbsbcz.supabase.co/functions/v1/admin-marketing-strategy-campaign-v1';
const LEARNINGS_API='https://ssbesxgaijknwsjbsbcz.supabase.co/functions/v1/admin-marketing-strategy-learnings-v1';
const ADMIN_PUBLIC_KEY=['sb','publishable','tFXHtH0HCXZepVtwgKElIg','DxS76Gu8'].join('_');
const CSS_URL='/vitrine/admin/marketing/strategy-center.css?v=marketing-strategy-v1';
const STATUS_LABELS={
  draft:'Rascunho',awaiting_internal_approval:'Aguardando sua aprovação',approved_internal:'Aprovada internamente',
  awaiting_meta:'Em análise na Meta',meta_approved:'Aprovado pela Meta',meta_rejected:'Rejeitado pela Meta',
  ready_to_send:'Pronta para envio',send_approved:'Envio aprovado',scheduled:'Agendada',running:'Em execução',
  completed:'Concluída',discarded:'Descartada',blocked:'Bloqueada',
};
const WEIGHT_LABELS={availability_stock:'Estoque e disponibilidade',seasonality:'Sazonalidade',audience_fit:'Adequação ao público',historical_performance:'Desempenho anterior',exploration:'Novidade e teste',operational_quality:'Qualidade operacional'};
let currentRoot=null,accounts=[],currentStrategy=null,settingsCache=null,busy=false;

const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const objectLike=value=>Boolean(value)&&typeof value==='object'&&!Array.isArray(value);
const fmtMoney=value=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value||0));
const fmtDate=value=>{if(!value)return '—';const date=new Date(value);return Number.isNaN(date.getTime())?'—':date.toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})};
const channelByPhone=value=>{const digits=String(value||'').replace(/\D/g,'');return digits.endsWith('0975')?'0975':digits.endsWith('1018')?'1018':null};
const localInputValue=value=>{if(!value)return '';const d=new Date(value);if(Number.isNaN(d.getTime()))return '';const pad=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`};

function ensureCss(){if(document.querySelector('link[data-da-marketing-strategy]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href=CSS_URL;link.dataset.daMarketingStrategy='1';document.head.appendChild(link)}
async function apiCall(base,action,{method='GET',body=null,params={}}={}){
  const url=new URL(base);url.searchParams.set('action',action);for(const [key,value] of Object.entries(params))if(value!==null&&value!==undefined&&value!=='')url.searchParams.set(key,String(value));
  const options={method,headers:{apikey:ADMIN_PUBLIC_KEY},cache:'no-store'};if(body!==null){options.headers['Content-Type']='application/json';options.body=JSON.stringify(body)}
  const response=await attendanceAuthorizedFetch(url,options);const data=await response.json().catch(()=>({}));
  if(!response.ok||data?.ok===false){const error=new Error(data?.error||`strategy_${response.status}`);error.payload=data;throw error}return data;
}
const apiGet=(action,params={})=>apiCall(action==='learnings'?LEARNINGS_API:STRATEGY_API,action,{params});
const apiPost=(action,body={})=>apiCall(STRATEGY_API,action,{method:'POST',body});
const bridgePost=(action,body={})=>apiCall(CAMPAIGN_BRIDGE_API,action,{method:'POST',body});
function notice(text,tone='neutral'){const node=currentRoot?.querySelector?.('[data-strategy-status]');if(node){node.textContent=text;node.dataset.tone=tone}}
function setBusy(on,text='Processando…'){busy=on;currentRoot?.querySelectorAll?.('[data-strategy-action]').forEach(button=>{button.disabled=on;button.setAttribute('aria-busy',on?'true':'false')});if(on)notice(text)}
async function loadAccounts(){if(accounts.length)return accounts;const data=await attendanceJsonApi('accounts',{},'GET');accounts=(data.items||[]).filter(item=>item?.id&&channelByPhone(item.phone_e164));return accounts}
function navMarkup(){const item=(key,label)=>`<button type="button" class="${key==='strategy'?'active':''}" data-marketing-view="${key}">${label}</button>`;return `<div class="marketing-template-subnav marketing-strategy-nav" data-marketing-subnav>${item('overview','Visão geral')}${item('strategy','Estratégia')}${item('templates','Templates')}${item('campaigns','Campanhas')}${item('audiences','Públicos')}<span class="marketing-campaign-gate">Envios desativados</span></div>`}
async function openMarketingView(view,root){
  if(view==='overview')return document.querySelector('[data-tab="marketing"]')?.click();if(view==='strategy')return;
  if(view==='templates'){const module=window.DAMarketingTemplateCenter||await import('/vitrine/admin/marketing/template-center.js?v=marketing-template-v1');return module?.mountTemplateView?.(root)}
  if(view==='campaigns'){const module=window.DAMarketingCampaignEntry||await import('/vitrine/admin/marketing/campaign-entry.js?v=marketing-campaign-v1');return module?.openCampaigns?.()}
  if(view==='audiences'){const module=window.DAMarketingAudienceCenter||await import('/vitrine/admin/marketing/audience-center.js?v=marketing-audience-v1');return module?.mountAudienceView?.(root)}
}
function bindNav(root){root.querySelectorAll('[data-marketing-view]').forEach(button=>button.addEventListener('click',()=>openMarketingView(button.dataset.marketingView,root).catch(error=>console.warn('marketing-strategy-nav',String(error?.message||error).slice(0,160)))))}
function shellHtml(){return `<div class="marketing-strategy-center"><div class="page-head"><div><h1>Marketing</h1><p>Estratégias assistidas para vender Cestas e Kits pelo WhatsApp.</p></div><span class="marketing-campaign-gate">Envios desativados</span></div>${navMarkup()}<div class="strategy-head"><div><h2>Estratégia de Marketing</h2><p>A Dona Antônia analisa Cestas, Kits, clientes e resultados para sugerir a melhor campanha da semana.</p></div><label class="strategy-account"><span>Canal</span><select data-strategy-account><option value="">Carregando…</option></select></label></div><div class="strategy-toolbar"><button type="button" class="primary" data-strategy-action="generate" aria-busy="false">Gerar estratégia agora</button><button type="button" data-strategy-action="calendar">Calendário</button><button type="button" data-strategy-action="settings">Configurações</button></div><div class="strategy-status" data-strategy-status role="status" aria-live="polite"></div><section class="strategy-recommendation" data-strategy-recommendation></section><section class="strategy-section"><div class="strategy-section-head"><div><span>Radar comercial</span><h3>Oportunidades detectadas</h3></div></div><div class="strategy-opportunities" data-strategy-opportunities></div></section><section class="strategy-section"><div class="strategy-section-head"><div><span>Evidências</span><h3>Aprendizados</h3></div></div><div class="strategy-learnings" data-strategy-learnings></div></section><section class="strategy-panel" data-strategy-calendar hidden></section><section class="strategy-panel" data-strategy-settings hidden></section></div>`}
function scoreLabel(value){const n=Number(value||0);return n>=80?'Excelente oportunidade':n>=60?'Boa oportunidade':n>=40?'Vale testar':'Baixa prioridade'}
function offerCards(offers=[]){return offers.map(item=>`<article class="strategy-offer-card"><img src="${esc(item.image_url||'/img/sem-foto.svg')}" alt=""><div><strong>${esc(item.public_name||'Cesta ou Kit')}</strong><small>${esc(item.category_name||'')}</small><b>${esc(fmtMoney(item.sale_price_snapshot??item.sale_price))}</b><em>${Number(item.public_available_snapshot??item.public_available||0)} disponíveis</em></div></article>`).join('')}
function scheduleControls(strategy,approveLabel=true){const value=localInputValue(strategy?.schedule_suggestion);return `<label class="strategy-send-when"><span>Data e hora</span><input type="datetime-local" data-strategy-schedule value="${esc(value)}"></label><button type="button" class="primary" data-strategy-action="${approveLabel?'approve_start':'start_send'}">${approveLabel?'Aprovar e enviar agora':'Enviar agora'}</button><button type="button" data-strategy-action="${approveLabel?'approve_schedule':'schedule_send'}">${approveLabel?'Aprovar e agendar':'Agendar envio'}</button>`}
function allowedActions(strategy){
  const status=String(strategy?.status||'');
  if(status==='draft')return `<button type="button" data-strategy-action="request_internal_approval">Enviar para minha aprovação</button><button type="button" data-strategy-action="regenerate">Gerar alternativa</button><button type="button" class="danger" data-strategy-action="discard">Descartar</button>`;
  if(status==='awaiting_internal_approval')return `<button type="button" class="primary" data-strategy-action="approve_internal">Aprovar estratégia</button><button type="button" data-strategy-action="regenerate">Gerar alternativa</button><button type="button" class="danger" data-strategy-action="discard">Descartar</button>`;
  if(status==='approved_internal')return `<button type="button" class="primary" data-strategy-action="submit_template">Reutilizar ou enviar template para Meta</button><button type="button" data-strategy-action="regenerate">Gerar alternativa</button>`;
  if(status==='awaiting_meta')return `<button type="button" data-strategy-action="refresh_template_status">Atualizar análise da Meta</button>`;
  if(status==='meta_rejected')return `<button type="button" data-strategy-action="regenerate">Gerar alternativa</button>`;
  if(status==='meta_approved')return `<button type="button" class="primary" data-strategy-action="materialize_campaign">Preparar campanha</button>`;
  if(status==='ready_to_send')return scheduleControls(strategy,true);
  if(status==='send_approved')return scheduleControls(strategy,false);
  if(['scheduled','running','completed','blocked','discarded'].includes(status))return `<button type="button" data-strategy-action="regenerate">Gerar alternativa</button>`;
  return '';
}
function renderRecommendation(detail){
  const host=currentRoot?.querySelector?.('[data-strategy-recommendation]');if(!host)return;const strategy=detail?.strategy||null,offers=Array.isArray(detail?.offers)?detail.offers:[];currentStrategy=strategy?{...strategy,offers}:null;
  if(!strategy){host.innerHTML=`<div class="strategy-empty"><span>Recomendação da semana</span><h3>Ainda não há uma estratégia gerada</h3><p>Escolha um canal e clique em <b>Gerar estratégia agora</b>. Nada será enviado automaticamente.</p></div>`;return}
  const evidence=objectLike(strategy.evidence)?strategy.evidence:{},reasons=Array.isArray(evidence.reasons)?evidence.reasons:[],audience=objectLike(strategy.audience_snapshot)?strategy.audience_snapshot:{};
  host.innerHTML=`<div class="strategy-rec-head"><div><span>Recomendação da semana</span><h3>${esc(offers.map(item=>item.public_name).join(' · ')||strategy.objective||'Estratégia semanal')}</h3><p>${esc(STATUS_LABELS[strategy.status]||strategy.status)}</p></div><div class="strategy-score"><b>${Number(strategy.score||0).toFixed(0)}</b><span>${esc(scoreLabel(strategy.score))}</span></div></div><div class="strategy-rec-facts"><div><span>Público elegível</span><strong>${Number(audience.eligible_count||0)}</strong></div><div><span>Formato</span><strong>${strategy.offer_format==='carousel'?'Carrossel':'Oferta única'}</strong></div><div><span>Janela sugerida</span><strong>${esc(fmtDate(strategy.schedule_suggestion))}</strong></div></div><div class="strategy-offers">${offerCards(offers)}</div><div class="strategy-why"><h4>Por que esta estratégia?</h4>${reasons.length?`<ul>${reasons.map(reason=>`<li>${esc(reason)}</li>`).join('')}</ul>`:'<p>A recomendação foi formada com dados comerciais disponíveis neste momento.</p>'}</div><div class="strategy-rec-actions">${allowedActions(currentStrategy)}</div>`;bindStrategyActions(host);
}
function renderOpportunities(items=[]){const host=currentRoot?.querySelector?.('[data-strategy-opportunities]');if(!host)return;if(!items.length){host.innerHTML='<p class="strategy-empty-line">Nenhuma oportunidade elegível encontrada agora.</p>';return}host.innerHTML=items.slice(0,6).map(item=>`<article><div><span>${esc(scoreLabel(item.score))}</span><h4>${esc(item.public_name||'Cesta ou Kit')}</h4><p>${esc(item.category_name||'')}</p></div><strong>${esc(fmtMoney(item.sale_price))}</strong><small>${Number(item.public_available||0)} disponíveis · score ${Number(item.score||0).toFixed(0)}</small></article>`).join('')}
function evidenceLanguage(data){const level=String(data?.evidence_level||'insufficient');if(level==='confirmed')return 'Aprendizado confirmado';if(level==='trend')return 'Tendência';return 'Sinal inicial'}
function renderLearnings(data={}){const host=currentRoot?.querySelector?.('[data-strategy-learnings]');if(!host)return;const items=Array.isArray(data.items)?data.items:[],label=evidenceLanguage(data);if(!items.length){host.innerHTML=`<article><span>${esc(label)}</span><h4>Ainda estamos formando histórico próprio</h4><p>Conforme as campanhas gerarem entregas e pedidos, esta área mostrará Tendência e aprendizados com evidência.</p><small>${Number(data?.sample?.completed_strategies||0)} estratégias concluídas na amostra atual.</small></article>`;return}host.innerHTML=items.map(item=>`<article><span>${esc(item.evidence_label||label)}</span><h4>${esc(item.title||'Aprendizado')}</h4><p>${esc(item.summary||'')}</p><small>${esc(item.sample_label||'')}</small></article>`).join('')}
async function loadLatestStrategy(){const overview=await apiGet('overview'),first=Array.isArray(overview.items)?overview.items[0]:null;if(!first?.id){renderRecommendation(null);return null}const detail=await apiGet('detail',{strategy_id:first.id});renderRecommendation(detail);return detail}
async function refreshCurrent(){if(!currentStrategy?.id)return loadLatestStrategy();const detail=await apiGet('detail',{strategy_id:currentStrategy.id});renderRecommendation(detail);return detail}
async function refreshDashboard(){const [strategy,opportunities,learnings,settings]=await Promise.allSettled([loadLatestStrategy(),apiGet('opportunities'),apiGet('learnings'),apiGet('settings')]);renderOpportunities(opportunities.status==='fulfilled'?opportunities.value.items||[]:[]);renderLearnings(learnings.status==='fulfilled'?learnings.value:{evidence_level:'insufficient'});if(settings.status==='fulfilled')settingsCache=settings.value;if(strategy.status==='rejected')notice('Não foi possível carregar a recomendação agora.','error')}
async function populateAccounts(){const select=currentRoot?.querySelector?.('[data-strategy-account]');if(!select)return;try{await loadAccounts();select.innerHTML='<option value="">Selecione</option>'+accounts.map(account=>`<option value="${esc(account.id)}">${esc(channelByPhone(account.phone_e164))} · ${esc(account.display_name||'WhatsApp')}</option>`).join('');if(accounts[0]?.id)select.value=accounts[0].id}catch(error){select.innerHTML='<option value="">Não foi possível carregar</option>';notice(`Erro ao carregar canais: ${String(error?.message||error)}`,'error')}}
async function generateStrategy(){const accountId=String(currentRoot?.querySelector?.('[data-strategy-account]')?.value||'');if(!accountId){notice('Escolha o canal antes de gerar a estratégia.','error');return}setBusy(true,'Analisando Cestas, Kits e clientes…');try{const result=await apiPost('generate',{whatsapp_account_id:accountId,prefer_carousel:true}),id=result?.strategy?.id;if(id){const detail=await apiGet('detail',{strategy_id:id});renderRecommendation(detail)}await loadOpportunities();notice('Estratégia criada. Revise antes de aprovar.','success')}catch(error){notice(`Não foi possível gerar: ${String(error?.message||error)}`,'error')}finally{setBusy(false)}}
async function transitionCurrent(action,label){if(!currentStrategy?.id||busy)return;setBusy(true,label);try{await apiPost(action,{strategy_id:currentStrategy.id,expected_revision:Number(currentStrategy.revision||1)});await refreshCurrent();notice('Estratégia atualizada.','success')}catch(error){notice(`Não foi possível atualizar: ${String(error?.message||error)}`,'error')}finally{setBusy(false)}}
async function regenerateCurrent(){if(!currentStrategy?.id||busy)return;setBusy(true,'Gerando uma alternativa…');try{const result=await apiPost('regenerate',{regenerated_from:currentStrategy.id,prefer_carousel:true}),id=result?.strategy?.id;if(id){const detail=await apiGet('detail',{strategy_id:id});renderRecommendation(detail)}await loadOpportunities();notice('Nova alternativa criada.','success')}catch(error){notice(`Não foi possível gerar alternativa: ${String(error?.message||error)}`,'error')}finally{setBusy(false)}}
async function submitTemplateCurrent(){if(!currentStrategy?.id||busy)return;setBusy(true,'Verificando template aprovado…');try{const data=await apiPost('submit_template',{strategy_id:currentStrategy.id,expected_revision:Number(currentStrategy.revision||1)});await refreshCurrent();notice(data.reused?'Template aprovado reutilizado.':'Template enviado para análise da Meta.','success')}catch(error){notice(`Não foi possível preparar o template: ${String(error?.message||error)}`,'error')}finally{setBusy(false)}}
async function materializeCampaign(){if(!currentStrategy?.id||busy)return;setBusy(true,'Revalidando oferta e preparando campanha…');try{const data=await bridgePost('materialize_campaign',{strategy_id:currentStrategy.id,expected_revision:Number(currentStrategy.revision||1)});await refreshCurrent();notice(`Campanha preparada para revisão${data?.eligible_count!=null?` · ${Number(data.eligible_count)} clientes elegíveis`:''}.`,'success')}catch(error){const code=String(error?.message||error);notice(code==='strategy_material_change'?'A oferta mudou desde a aprovação. Gere uma nova estratégia antes de continuar.':`Não foi possível preparar a campanha: ${code}`,'error')}finally{setBusy(false)}}
function selectedSchedule(){const raw=String(currentRoot?.querySelector?.('[data-strategy-schedule]')?.value||'').trim();if(!raw)return null;const date=new Date(raw);return Number.isNaN(date.getTime())?null:date.toISOString()}
async function approveThen(mode){if(!currentStrategy?.id||busy)return;const when=mode==='schedule'?selectedSchedule():null;if(mode==='schedule'&&!when){notice('Escolha a data e hora do agendamento.','error');return}setBusy(true,mode==='schedule'?'Registrando aprovação e agendamento…':'Registrando aprovação e envio…');try{const approved=await bridgePost('approve_send',{strategy_id:currentStrategy.id,expected_revision:Number(currentStrategy.revision||1)});const revision=Number(approved?.revision||currentStrategy.revision||1);const body={strategy_id:currentStrategy.id,expected_revision:revision,...(mode==='schedule'?{scheduled_for:when}:{})};const result=await bridgePost(mode==='schedule'?'schedule_send':'start_send',body);await refreshCurrent();notice(mode==='schedule'?`Envio aprovado e agendado para ${fmtDate(result.scheduled_for)}.`:'Envio aprovado e liberado para o motor de campanhas.','success')}catch(error){await refreshCurrent().catch(()=>null);const code=String(error?.message||error);if(code==='campaigns_disabled')notice('A aprovação do envio foi registrada, mas os envios automáticos continuam desativados. Nenhuma mensagem foi disparada.','error');else if(code==='strategy_material_change')notice('A oferta mudou desde a aprovação. O envio foi bloqueado e precisa de nova revisão.','error');else notice(`Não foi possível concluir o Portão C: ${code}`,'error')}finally{setBusy(false)}}
async function sendApproved(mode){if(!currentStrategy?.id||busy)return;const when=mode==='schedule'?selectedSchedule():null;if(mode==='schedule'&&!when){notice('Escolha a data e hora do agendamento.','error');return}setBusy(true,mode==='schedule'?'Agendando campanha…':'Liberando campanha…');try{const body={strategy_id:currentStrategy.id,expected_revision:Number(currentStrategy.revision||1),...(mode==='schedule'?{scheduled_for:when}:{})};const result=await bridgePost(mode==='schedule'?'schedule_send':'start_send',body);await refreshCurrent();notice(mode==='schedule'?`Campanha agendada para ${fmtDate(result.scheduled_for)}.`:'Campanha liberada para o motor de envios.','success')}catch(error){const code=String(error?.message||error);notice(code==='campaigns_disabled'?'Os envios automáticos estão desativados. Nenhuma mensagem foi disparada.':`Não foi possível liberar a campanha: ${code}`,'error')}finally{setBusy(false)}}
async function loadOpportunities(){try{const data=await apiGet('opportunities');renderOpportunities(data.items||[])}catch{renderOpportunities([])}}
function bindStrategyActions(scope=currentRoot){
  scope?.querySelector?.('[data-strategy-action="request_internal_approval"]')?.addEventListener('click',()=>transitionCurrent('request_internal_approval','Preparando para sua aprovação…'));
  scope?.querySelector?.('[data-strategy-action="approve_internal"]')?.addEventListener('click',()=>transitionCurrent('approve_internal','Registrando sua aprovação…'));
  scope?.querySelector?.('[data-strategy-action="discard"]')?.addEventListener('click',()=>transitionCurrent('discard','Descartando estratégia…'));
  scope?.querySelector?.('[data-strategy-action="regenerate"]')?.addEventListener('click',regenerateCurrent);
  scope?.querySelector?.('[data-strategy-action="submit_template"]')?.addEventListener('click',submitTemplateCurrent);
  scope?.querySelector?.('[data-strategy-action="refresh_template_status"]')?.addEventListener('click',()=>transitionCurrent('refresh_template_status','Atualizando análise da Meta…'));
  scope?.querySelector?.('[data-strategy-action="materialize_campaign"]')?.addEventListener('click',materializeCampaign);
  scope?.querySelector?.('[data-strategy-action="approve_start"]')?.addEventListener('click',()=>approveThen('start'));
  scope?.querySelector?.('[data-strategy-action="approve_schedule"]')?.addEventListener('click',()=>approveThen('schedule'));
  scope?.querySelector?.('[data-strategy-action="start_send"]')?.addEventListener('click',()=>sendApproved('start'));
  scope?.querySelector?.('[data-strategy-action="schedule_send"]')?.addEventListener('click',()=>sendApproved('schedule'));
}
function monthWindow(){const now=new Date(),start=new Date(now.getFullYear(),now.getMonth(),1),end=new Date(now.getFullYear(),now.getMonth()+1,0),iso=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;return {start:iso(start),end:iso(end)}}
async function showCalendar(){const panel=currentRoot?.querySelector?.('[data-strategy-calendar]');if(!panel)return;panel.hidden=false;currentRoot.querySelector('[data-strategy-settings]').hidden=true;panel.innerHTML='<p>Carregando calendário…</p>';try{const range=monthWindow(),data=await apiGet('calendar',range),rows=Array.isArray(data.strategies)?data.strategies:[],rules=Array.isArray(data.seasonality)?data.seasonality:[];panel.innerHTML=`<div class="strategy-panel-head"><div><span>Planejamento</span><h3>Calendário</h3></div><button type="button" data-strategy-close-panel>Fechar</button></div><div class="strategy-calendar-grid"><div><h4>Estratégias do período</h4>${rows.length?rows.map(item=>`<article><strong>${esc(item.objective||'Estratégia')}</strong><span>${esc(item.period_start)} a ${esc(item.period_end)}</span><small>${esc(STATUS_LABELS[item.status]||item.status)}</small></article>`).join(''):'<p>Nenhuma estratégia planejada neste período.</p>'}</div><div><h4>Sazonalidades</h4>${rules.length?rules.map(item=>`<article><strong>${esc(item.name)}</strong><span>${esc(item.rule_key)}</span><small>${item.operational_closed?'Operação fechada':`Peso ${Number(item.score_effect||0)}`}</small></article>`).join(''):'<p>Nenhuma sazonalidade ativa.</p>'}</div></div>`;panel.querySelector('[data-strategy-close-panel]')?.addEventListener('click',()=>{panel.hidden=true})}catch(error){panel.innerHTML=`<p>Não foi possível carregar o calendário: ${esc(error?.message||error)}</p>`}}
function settingsMarkup(data){const weights=objectLike(data?.weights?.weights)?data.weights.weights:{};return `<div class="strategy-panel-head"><div><span>Regras do motor</span><h3>Configurações</h3></div><button type="button" data-strategy-close-panel>Fechar</button></div><form class="strategy-settings-form" data-strategy-weight-form><h4>Pesos da estratégia</h4><p>A soma precisa ser 100. Alterações criam uma nova versão e preservam o histórico.</p><div class="strategy-weight-grid">${Object.entries(WEIGHT_LABELS).map(([key,label])=>`<label><span>${esc(label)}</span><input type="number" min="0" max="100" step="1" name="${key}" value="${Number(weights[key]??0)}"></label>`).join('')}</div><label><span>Observação da versão</span><input name="version_note" maxlength="300"></label><button type="submit" data-strategy-action="save_weights">Salvar nova versão de pesos</button></form><form class="strategy-settings-form" data-strategy-seasonality-form><h4>Nova regra de sazonalidade</h4><div class="strategy-settings-grid"><label><span>Chave</span><input name="rule_key" required placeholder="inicio_mes"></label><label><span>Nome</span><input name="name" required placeholder="Início do mês"></label><label><span>Meses (1-12)</span><input name="month_numbers" placeholder="1,2,3"></label><label><span>Dia inicial</span><input type="number" min="1" max="31" name="day_of_month_start"></label><label><span>Dia final</span><input type="number" min="1" max="31" name="day_of_month_end"></label><label><span>Efeito no score</span><input type="number" min="-100" max="100" name="score_effect" value="0"></label></div><label class="strategy-check"><input type="checkbox" name="operational_closed"> <span>Marcar período como operação fechada</span></label><button type="submit" data-strategy-action="save_seasonality">Salvar nova versão da regra</button></form>`}
function weightPayload(form){const weights={};for(const key of Object.keys(WEIGHT_LABELS))weights[key]=Number(form.elements[key]?.value||0);return {weights,version_note:String(form.elements.version_note?.value||'').trim()}}
function seasonalityPayload(form){const months=String(form.elements.month_numbers?.value||'').split(/[\s,;]+/).map(Number).filter(n=>Number.isInteger(n)&&n>=1&&n<=12);return {rule_key:String(form.elements.rule_key?.value||'').trim(),name:String(form.elements.name?.value||'').trim(),month_numbers:months,day_of_month_start:form.elements.day_of_month_start?.value?Number(form.elements.day_of_month_start.value):null,day_of_month_end:form.elements.day_of_month_end?.value?Number(form.elements.day_of_month_end.value):null,priority:0,score_effect:Number(form.elements.score_effect?.value||0),operational_closed:Boolean(form.elements.operational_closed?.checked),metadata:{source:'admin_strategy_settings'}}}
async function showSettings(){const panel=currentRoot?.querySelector?.('[data-strategy-settings]');if(!panel)return;panel.hidden=false;currentRoot.querySelector('[data-strategy-calendar]').hidden=true;try{settingsCache=settingsCache||await apiGet('settings');panel.innerHTML=settingsMarkup(settingsCache);panel.querySelector('[data-strategy-close-panel]')?.addEventListener('click',()=>{panel.hidden=true});panel.querySelector('[data-strategy-weight-form]')?.addEventListener('submit',async event=>{event.preventDefault();if(busy)return;setBusy(true,'Salvando pesos…');try{settingsCache=await apiPost('save_weights',weightPayload(event.currentTarget));notice('Nova versão dos pesos salva.','success');await showSettings()}catch(error){notice(`Erro ao salvar pesos: ${String(error?.message||error)}`,'error')}finally{setBusy(false)}});panel.querySelector('[data-strategy-seasonality-form]')?.addEventListener('submit',async event=>{event.preventDefault();if(busy)return;setBusy(true,'Salvando sazonalidade…');try{await apiPost('save_seasonality',seasonalityPayload(event.currentTarget));settingsCache=await apiGet('settings');notice('Nova versão da sazonalidade salva.','success');await showSettings()}catch(error){notice(`Erro ao salvar sazonalidade: ${String(error?.message||error)}`,'error')}finally{setBusy(false)}})}catch(error){panel.innerHTML=`<p>Não foi possível carregar configurações: ${esc(error?.message||error)}</p>`}}
function bindMainActions(root){root.querySelector('[data-strategy-action="generate"]')?.addEventListener('click',generateStrategy);root.querySelector('[data-strategy-action="calendar"]')?.addEventListener('click',showCalendar);root.querySelector('[data-strategy-action="settings"]')?.addEventListener('click',showSettings)}
async function mountStrategyView(root=document.querySelector('#content')){if(!root)return;currentRoot=root;ensureCss();root.innerHTML=shellHtml();bindNav(root);bindMainActions(root);bindStrategyActions(root);await populateAccounts();notice('Carregando recomendações…');try{await refreshDashboard();notice('Estratégia atualizada.','success')}catch(error){notice(`Não foi possível carregar Estratégia: ${String(error?.message||error)}`,'error')}window.DAMarketingPolish?.apply?.()}

window.DAMarketingStrategyCenter={mountStrategyView};
export {mountStrategyView};