import {CONFIG} from '../admin-v3/config.js';
import {validatePhotoFiles,buildFiveCharacteristicName,normalizeManualCatalogFields,buildWhatsAppUrl,buildShareText,buildRunCardModel} from './app-core.mjs';

const $=id=>document.getElementById(id);
const ANALYZE_FUNCTION='ame-mais-analyze-v1';
const LOGO_URL='./assets/logo-ame-store.jpg';
const IMAGE_KINDS=[['hero','Foto 1 · Principal'],['lifestyle','Foto 2 · Em uso'],['detail','Foto 3 · Detalhe']];
const PROCESS_STAGES=[
 ['preparing_photo','Preparando fotos','Otimizando as fotos para envio.',4],['saving_original','Salvando originais','Guardando até 3 referências no Supabase.',9],['analyzing_product','Analisando produto','Cruzando todas as fotos, inclusive possível EAN.',16],['creating_name','Criando nome','Montando somente as 5 características definidas.',22],['creating_catalog_description','Criando descrição de cadastro','Montando a descrição para pesquisa interna.',28],['creating_storefront_description','Criando descrição comercial','Escrevendo a descrição da vitrine.',34],['choosing_scene_profile','Escolhendo perfil visual','Definindo as 3 cenas para este tipo de produto.',39],['generating_hero','Gerando foto 1','Criando a primeira foto ultrarrealista.',46],['validating_hero','Validando foto 1','Comparando com as referências.',51],['saving_hero','Salvando foto 1','Salvando no Supabase.',56],['generating_lifestyle','Gerando foto 2','Criando a segunda cena.',62],['validating_lifestyle','Validando foto 2','Conferindo identidade e cores.',67],['saving_lifestyle','Salvando foto 2','Salvando no Supabase.',72],['generating_detail','Gerando foto 3','Criando o detalhe/close-up.',78],['validating_detail','Validando foto 3','Conferindo fidelidade.',84],['saving_detail','Salvando foto 3','Salvando no Supabase.',90],['building_card','Montando card','Montando o card final.',96],['completed','Concluído','Criação completa e salva.',100]
];
const STAGE_INDEX=Object.fromEntries(PROCESS_STAGES.map((s,i)=>[s[0],i]));
const state={files:[],sourceUrls:[],analysis:null,images:{},sessionId:null,busy:false,statusTimer:null,activeKind:'hero',model:null,catalog:{ean:'',ncm:'',preco_custo:null,preco_venda:null}};
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=s=>String(s||'produto').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,70)||'produto';
const moneyText=v=>v===null||v===undefined||v===''?'':Number(v).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
const toast=(message,type='')=>{const el=document.createElement('div');el.className=`toast ${type}`.trim();el.textContent=message;$('toastRegion').append(el);setTimeout(()=>el.remove(),3800)};
function friendly(code){return({image_required:'Adicione pelo menos uma foto.',too_many_images:'Use no máximo 3 fotos.',image_type_not_allowed:'Formato da foto não suportado.',image_size_invalid:'Uma foto está muito grande ou inválida.',processing_failed:'A IA não conseguiu concluir esta etapa.',image_fidelity_rejected:'A imagem foi bloqueada porque não ficou fiel ao produto.',rate_limited:'Muitas solicitações em pouco tempo. Aguarde e tente novamente.',run_not_found:'Criação não encontrada.',run_not_ready:'A criação ainda está sendo preparada.',invalid_session_id:'Identificador inválido.',origin_not_allowed:'Este endereço não está autorizado.',server_config:'Configuração do servidor indisponível.',invalid_kind:'Tipo de imagem inválido.'}[code]||code||'Não foi possível concluir.')}
async function apiForm(form){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),145000);try{const r=await fetch(`${CONFIG.supabaseUrl}/functions/v1/${ANALYZE_FUNCTION}`,{method:'POST',headers:{apikey:CONFIG.supabasePublishableKey},body:form,cache:'no-store',signal:controller.signal});const d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw Object.assign(new Error(d.detail||friendly(d.error)),{code:d.error||'request_failed',payload:d,status:r.status});return d}catch(e){if(e?.name==='AbortError')throw new Error('A etapa demorou mais que o esperado. Tente novamente.');throw e}finally{clearTimeout(timer)}}
function renderTimeline(){$('processingTimeline').innerHTML=PROCESS_STAGES.map(([key,label],i)=>`<div class="process-step" data-step="${key}"><span class="process-dot">${i+1}</span><span>${escapeHtml(label)}</span></div>`).join('')}
function setStage(key,overrideText=''){const idx=STAGE_INDEX[key]??0,[,label,detail,pct]=PROCESS_STAGES[idx];$('progressCard').classList.remove('hidden');$('progressTitle').textContent=label;$('progressText').textContent=overrideText||detail;$('progressBar').style.width=`${pct}%`;$('progressPercent').textContent=`${pct}%`;document.querySelectorAll('.process-step').forEach((el,i)=>{el.classList.toggle('done',i<idx);el.classList.toggle('current',i===idx);const dot=el.querySelector('.process-dot');if(dot)dot.textContent=i<idx?'✓':String(i+1)})}
function showProcessError(message){$('progressCard').classList.remove('hidden');$('progressTitle').textContent='Erro no processamento';$('progressText').textContent=message;$('progressPercent').textContent='!'}
function setBusy(on){state.busy=on;$('analyzeButton').disabled=on||state.files.length===0;document.body.classList.toggle('is-busy',on)}
async function statusOnce(){if(!state.sessionId)return;const f=new FormData();f.append('action','status');f.append('session_id',state.sessionId);try{const d=await apiForm(f);if(d.run?.step)setStage(d.run.step);if(d.run?.status==='error'&&d.run?.error_message)showProcessError(d.run.error_message)}catch(e){if(e.status!==404&&e.code!=='run_not_found')console.debug('ame-mais status',e.message)}}
function startStatusPoll(){stopStatusPoll();state.statusTimer=setInterval(statusOnce,1200)}function stopStatusPoll(){if(state.statusTimer){clearInterval(state.statusTimer);state.statusTimer=null}}
async function compressPhoto(file){const bitmap=await createImageBitmap(file),maxSide=2200,scale=Math.min(1,maxSide/Math.max(bitmap.width,bitmap.height)),w=Math.max(1,Math.round(bitmap.width*scale)),h=Math.max(1,Math.round(bitmap.height*scale)),c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d',{alpha:false});ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.drawImage(bitmap,0,0,w,h);bitmap.close();const blob=await new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('Falha ao preparar a foto.')),'image/jpeg',.9));return new File([blob],`produto-${Date.now()}.jpg`,{type:'image/jpeg'})}
function renderInputPhotos(urls=null){const remote=Array.isArray(urls)?urls:[];if(remote.length){$('inputPhotoGrid').innerHTML=remote.slice(0,3).map((url,i)=>`<div class="input-photo-item"><img src="${escapeHtml(url)}" alt="Referência ${i+1}"><span class="input-photo-number">${i+1}</span></div>`).join('');return}if(!state.files.length){$('inputPhotoGrid').innerHTML='<div class="empty-photo"><div class="camera-icon">◉</div><strong>Nenhuma foto</strong><span>Adicione até 3 fotos do mesmo produto</span></div>';return}$('inputPhotoGrid').innerHTML=state.files.map((file,i)=>`<div class="input-photo-item"><img src="${URL.createObjectURL(file)}" alt="Foto ${i+1}"><span class="input-photo-number">${i+1}</span><button class="input-photo-remove" data-remove-photo="${i}" type="button" aria-label="Remover">×</button></div>`).join('')}
async function addFiles(fileList){const incoming=Array.from(fileList||[]);if(!incoming.length)return;if(state.files.length+incoming.length>3)return toast('Use no máximo 3 fotos do mesmo produto.','error');const valid=validatePhotoFiles([...state.files,...incoming]);if(!valid.ok)return toast(valid.error,'error');for(const file of incoming){try{state.files.push(await compressPhoto(file))}catch{state.files.push(file)}}state.sourceUrls=[];renderInputPhotos();setBusy(false);$('mainMessage').textContent=''}
function currentAnalysis(){const a={...(state.analysis||{}),tipo_produto:$('fieldType').value.trim(),devocao_tema:$('fieldDevotion').value.trim(),material_modelo:$('fieldMaterial').value.trim(),cor_acabamento:$('fieldColor').value.trim(),diferencial_tamanho:$('fieldDetail').value.trim(),descricao_cadastro:$('catalogDescription').value.trim(),descricao_vitrine:$('storefrontDescription').value.trim()};a.nome_cadastro=buildFiveCharacteristicName(a);return a}
function syncName(){const a=currentAnalysis();$('productName').value=a.nome_cadastro;if(state.analysis)state.analysis={...state.analysis,...a};renderStorefrontCard()}
function normalizeImage(item,kind){if(!item)return{kind,status:'pending'};return{kind,title:item.title||'',url:item.url||item.image_url||'',status:item.status||(item.url||item.image_url?'completed':'pending'),validation:item.validation||{},model:item.model||'',quality:item.quality||'',size:item.size||''}}
function setCatalog(run={},detected=''){state.catalog={ean:String(run.ean||detected||'').trim(),ncm:String(run.ncm||'').trim(),preco_custo:run.preco_custo??null,preco_venda:run.preco_venda??null};$('resultEan').value=state.catalog.ean;$('resultNcm').value=state.catalog.ncm;$('resultCost').value=moneyText(state.catalog.preco_custo);$('resultPrice').value=moneyText(state.catalog.preco_venda)}
function renderAnalysis(a,model,run={}){state.analysis=a||{};state.model=model||state.model;$('fieldType').value=a?.tipo_produto||'';$('fieldDevotion').value=a?.devocao_tema||'';$('fieldMaterial').value=a?.material_modelo||'';$('fieldColor').value=a?.cor_acabamento||'';$('fieldDetail').value=a?.diferencial_tamanho||'';$('productName').value=buildFiveCharacteristicName(a);$('catalogDescription').value=a?.descricao_cadastro||'';$('storefrontDescription').value=a?.descricao_vitrine||'';setCatalog(run,a?.ean_detectado||'');const pct=Math.round(Number(a?.confianca_geral||0)*100);$('confidenceBadge').textContent=`${pct}% · ${String(model||'').includes('terra')?'revisão avançada':'análise rápida'}`;$('searchTerms').innerHTML=(a?.termos_busca||[]).map(x=>`<span class="term">${escapeHtml(x)}</span>`).join('');$('reviewWarning').classList.toggle('hidden',!a?.precisa_revisao);$('reviewWarning').textContent=a?.precisa_revisao?`Revisar: ${a.motivo_revisao||'a IA sinalizou baixa confiança.'}`:'';const conflicts=a?.conflitos||[];$('conflictBox').classList.toggle('hidden',!conflicts.length);$('conflictBox').innerHTML=conflicts.length?`<strong>Conflitos / incertezas</strong><ul>${conflicts.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul>`:'';$('resultArea').classList.remove('hidden');renderImageStatus();renderStorefrontCard()}
function renderImageStatus(){$('imageGrid').innerHTML=IMAGE_KINDS.map(([kind,title])=>{const img=normalizeImage(state.images[kind],kind),pct=img.validation?.fidelity_score!=null?Math.round(Number(img.validation.fidelity_score)*100):null,preview=img.url?`<img src="${escapeHtml(img.url)}" alt="${escapeHtml(title)}">`:`<span>${img.status==='rejected'?'Reprovada':'Aguardando'}</span>`,actions=img.url?`<button class="download-button" data-download-url="${escapeHtml(img.url)}" data-download-kind="${kind}" type="button">Baixar</button><button class="retry-button" data-retry-kind="${kind}" type="button">Refazer</button>`:`<button class="retry-button" data-retry-kind="${kind}" type="button">${img.status==='rejected'?'Repetir':'Gerar'}</button>`;return`<article class="image-card"><div class="image-card-row"><div class="image-card-preview">${preview}</div><div class="image-card-info"><strong>${escapeHtml(title)}</strong><span>${escapeHtml(img.status||'pending')}${pct!==null?` · fidelidade ${pct}%`:''}</span></div><div class="image-actions">${actions}</div></div></article>`}).join('')}
function cardRun(){return{id:state.sessionId,analysis:currentAnalysis(),images:state.images,ean:state.catalog.ean,ncm:state.catalog.ncm,preco_custo:state.catalog.preco_custo,preco_venda:state.catalog.preco_venda,conflicts:state.analysis?.conflitos||[],observations:state.analysis?.observacoes||[]}}
function renderStorefrontCard(){if(!state.analysis)return;const card=buildRunCardModel(cardRun(),LOGO_URL);let active=card.gallery.find(x=>x.kind===state.activeKind&&x.url)||card.gallery.find(x=>x.url)||card.gallery[0];if(active?.kind)state.activeKind=active.kind;$('storefrontCardName').textContent=card.name||'Produto';$('storefrontCardDescription').textContent=card.storefrontDescription||'Descrição comercial da vitrine.';$('storefrontCatalogDescription').textContent=card.catalogDescription||'';$('runReference').textContent=card.runId?`Criação: ${card.runId}`:'';const attrs=Object.values(card.attributes||{}).filter(Boolean);$('storefrontAttributes').innerHTML=attrs.map(x=>`<span class="attribute-chip">${escapeHtml(x)}</span>`).join('');const meta=[];if(card.ean)meta.push(`EAN ${card.ean}`);if(card.ncm)meta.push(`NCM ${card.ncm}`);if(card.precoCusto!=null)meta.push(`Custo R$ ${moneyText(card.precoCusto)}`);if(card.precoVenda!=null)meta.push(`Venda R$ ${moneyText(card.precoVenda)}`);$('storefrontCatalogMeta').innerHTML=meta.map(x=>`<span class="catalog-meta-chip">${escapeHtml(x)}</span>`).join('');$('storefrontSearchTerms').innerHTML=card.searchTerms.length?`<strong>Busca:</strong>${card.searchTerms.map(x=>`<span class="detail-chip">${escapeHtml(x)}</span>`).join('')}`:'';$('storefrontConflicts').innerHTML=card.conflicts.length?`<strong>Revisar:</strong>${card.conflicts.map(x=>`<span class="detail-chip">${escapeHtml(x)}</span>`).join('')}`:'';if(active?.url){$('storefrontMainImage').src=active.url;$('storefrontMainImage').classList.remove('hidden');$('mainImagePlaceholder').classList.add('hidden');$('downloadActive').disabled=false;$('downloadActive').dataset.url=active.url;$('downloadActive').dataset.kind=active.kind}else{$('storefrontMainImage').classList.add('hidden');$('mainImagePlaceholder').classList.remove('hidden');$('downloadActive').disabled=true;delete $('downloadActive').dataset.url}$('storefrontThumbs').innerHTML=card.gallery.map(x=>`<button type="button" class="storefront-thumb ${x.kind===state.activeKind?'active':''}" data-thumb-kind="${x.kind}">${x.url?`<img src="${escapeHtml(x.url)}" alt="${escapeHtml(x.title)}">`:`<span class="thumb-empty">${escapeHtml(x.title)}<br>${escapeHtml(x.status)}</span>`}</button>`).join('')}
async function generateImage(kind){const form=new FormData();form.append('action','generate_image');form.append('kind',kind);form.append('session_id',state.sessionId);form.append('analysis_json',JSON.stringify(currentAnalysis()));return apiForm(form)}
async function saveCatalogFields(showToast=true){if(!state.sessionId)return;const fields=normalizeManualCatalogFields({ean:$('resultEan').value,ncm:$('resultNcm').value,preco_custo:$('resultCost').value,preco_venda:$('resultPrice').value});const form=new FormData();form.append('action','save_metadata');form.append('session_id',state.sessionId);form.append('ean',fields.ean);form.append('ncm',fields.ncm);form.append('preco_custo',fields.preco_custo??'');form.append('preco_venda',fields.preco_venda??'');form.append('analysis_json',JSON.stringify(currentAnalysis()));const d=await apiForm(form);state.catalog={ean:d.ean||'',ncm:d.ncm||'',preco_custo:d.preco_custo??null,preco_venda:d.preco_venda??null};renderStorefrontCard();if(showToast)toast('Dados do cadastro salvos.','ok');await loadHistory()}
async function analyze(){if(!state.files.length||state.busy)return;const valid=validatePhotoFiles(state.files);if(!valid.ok)return toast(valid.error,'error');setBusy(true);state.sessionId=crypto.randomUUID();state.images={};state.analysis=null;state.activeKind='hero';$('resultArea').classList.add('hidden');renderTimeline();setStage('preparing_photo');startStatusPoll();try{const initial=normalizeManualCatalogFields({ean:$('fieldEan').value,ncm:$('fieldNcm').value,preco_custo:$('fieldCost').value,preco_venda:$('fieldPrice').value});const form=new FormData();form.append('action','analyze');form.append('session_id',state.sessionId);state.files.forEach((file,i)=>form.append('images',file,`produto-${i+1}.jpg`));form.append('ean',initial.ean);form.append('ncm',initial.ncm);form.append('preco_custo',initial.preco_custo??'');form.append('preco_venda',initial.preco_venda??'');const d=await apiForm(form);state.sourceUrls=d.source_urls||[];renderAnalysis(d.analysis,d.model,{ean:d.ean||initial.ean,ncm:initial.ncm,preco_custo:initial.preco_custo,preco_venda:initial.preco_venda});for(const [kind] of IMAGE_KINDS){setStage(`generating_${kind}`);try{const image=await generateImage(kind);state.images[kind]=normalizeImage(image,kind)}catch(e){state.images[kind]={kind,status:e.code==='image_fidelity_rejected'?'rejected':'error',error:e.message,validation:e.payload?.validation||{}};toast(`${IMAGE_KINDS.find(x=>x[0]===kind)?.[1]}: ${e.message}`,'error')}renderImageStatus();renderStorefrontCard()}const ok=IMAGE_KINDS.every(([k])=>state.images[k]?.url);if(ok){await saveCatalogFields(false);setStage('completed');toast('Produto completo e salvo no Supabase.','ok');history.replaceState({},'',`${location.pathname}?run=${state.sessionId}`);await loadHistory()}else toast('Cadastro salvo. Uma ou mais fotos precisam ser refeitas.','error')}catch(e){showProcessError(e.message||'Falha ao analisar.');toast(e.message||'Falha ao analisar.','error')}finally{stopStatusPoll();setBusy(false)}}
async function downloadImage(url,kind){if(!url)return;try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('download');const b=await r.blob(),objectUrl=URL.createObjectURL(b),a=document.createElement('a');a.href=objectUrl;a.download=`${slug(currentAnalysis().nome_cadastro)}-${kind}.webp`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(objectUrl),1500)}catch{window.open(url,'_blank','noopener')}}
async function shareWhatsApp(){const analysis=currentAnalysis(),text=buildShareText(analysis),urls=IMAGE_KINDS.map(([k])=>state.images[k]?.url).filter(Boolean);if(navigator.share&&urls.length){try{const files=[];for(const [i,url]of urls.entries()){const r=await fetch(url);if(!r.ok)throw new Error('download');const b=await r.blob();files.push(new File([b],`ame-mais-${i+1}.webp`,{type:b.type||'image/webp'}))}if(!navigator.canShare||navigator.canShare({files})){await navigator.share({title:analysis.nome_cadastro,text,files});return}}catch(e){if(e?.name==='AbortError')return}}window.open(buildWhatsAppUrl([text,urls.length?`Imagens:\n${urls.join('\n')}`:''].filter(Boolean).join('\n\n')),'_blank','noopener')}
function reset(){stopStatusPoll();state.files=[];state.sourceUrls=[];state.analysis=null;state.images={};state.sessionId=null;state.activeKind='hero';state.catalog={ean:'',ncm:'',preco_custo:null,preco_venda:null};renderInputPhotos();$('analyzeButton').disabled=true;$('resultArea').classList.add('hidden');$('progressCard').classList.add('hidden');$('mainMessage').textContent='';['fieldEan','fieldNcm','fieldCost','fieldPrice'].forEach(id=>$(id).value='');history.replaceState({},'',location.pathname);window.scrollTo({top:0,behavior:'smooth'})}
async function loadSavedRun(runId){if(!/^[0-9a-f-]{36}$/i.test(runId||''))return;state.sessionId=runId;setBusy(true);renderTimeline();setStage('building_card','Abrindo criação salva…');try{const form=new FormData();form.append('action','get_run');form.append('session_id',runId);const d=await apiForm(form);state.analysis=d.run?.analysis||{};state.model=d.run?.model_analysis||'';state.images={};for(const row of d.image_rows||[])state.images[row.kind]=normalizeImage(row,row.kind);state.sourceUrls=d.run?.source_urls||[];state.files=[];renderInputPhotos(state.sourceUrls);renderAnalysis(state.analysis,state.model,d.run||{});$('progressCard').classList.add('hidden');history.replaceState({},'',`${location.pathname}?run=${runId}`);toast('Criação carregada.','ok')}catch(e){showProcessError(e.message);toast(e.message,'error')}finally{setBusy(false)}}
async function loadHistory(){const form=new FormData();form.append('action','history');try{const d=await apiForm(form),runs=d.runs||[];$('historyList').innerHTML=runs.length?runs.map(run=>{const a=run.analysis||{},name=buildFiveCharacteristicName(a)||a.nome_cadastro||'Criação',hero=run.images?.hero?.url||run.card_json?.gallery?.find?.(x=>x.kind==='hero')?.url||'',date=run.created_at?new Date(run.created_at).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'';return`<article class="history-item"><div class="history-thumb">${hero?`<img src="${escapeHtml(hero)}" alt="${escapeHtml(name)}">`:''}</div><div class="history-info"><strong>${escapeHtml(name)}</strong><span>${escapeHtml(date)}${run.ean?` · EAN ${escapeHtml(run.ean)}`:''}</span></div><button class="history-open" type="button" data-open-run="${escapeHtml(run.id)}">Abrir</button></article>`}).join(''):'<span class="history-empty">Nenhuma criação salva ainda.</span>'}catch(e){$('historyList').innerHTML='<span class="history-empty">Não foi possível carregar o histórico.</span>';console.debug(e)}}

$('cameraInput').addEventListener('change',e=>{addFiles(e.target.files);e.target.value=''});$('galleryInput').addEventListener('change',e=>{addFiles(e.target.files);e.target.value=''});$('inputPhotoGrid').addEventListener('click',e=>{const b=e.target.closest('[data-remove-photo]');if(!b)return;state.files.splice(Number(b.dataset.removePhoto),1);renderInputPhotos();setBusy(false)});$('analyzeButton').addEventListener('click',analyze);
$('copyName').addEventListener('click',async()=>{await navigator.clipboard.writeText($('productName').value);toast('Nome copiado.','ok')});$('copyStorefront').addEventListener('click',async()=>{await navigator.clipboard.writeText($('storefrontDescription').value);toast('Descrição copiada.','ok')});$('shareWhatsApp').addEventListener('click',shareWhatsApp);$('newProduct').addEventListener('click',reset);$('saveCatalogFields').addEventListener('click',()=>saveCatalogFields(true));$('copyRunLink').addEventListener('click',async()=>{if(!state.sessionId)return toast('Crie ou abra um produto primeiro.','error');const url=`${location.origin}${location.pathname}?run=${state.sessionId}`;await navigator.clipboard.writeText(url);toast('Link da criação copiado.','ok')});$('downloadActive').addEventListener('click',()=>downloadImage($('downloadActive').dataset.url,$('downloadActive').dataset.kind||state.activeKind));
['fieldType','fieldDevotion','fieldMaterial','fieldColor','fieldDetail'].forEach(id=>$(id).addEventListener('input',syncName));['catalogDescription','storefrontDescription','resultEan','resultNcm','resultCost','resultPrice'].forEach(id=>$(id).addEventListener('input',()=>{if(id.startsWith('result')){const f=normalizeManualCatalogFields({ean:$('resultEan').value,ncm:$('resultNcm').value,preco_custo:$('resultCost').value,preco_venda:$('resultPrice').value});state.catalog=f}renderStorefrontCard()}));$('storefrontThumbs').addEventListener('click',e=>{const b=e.target.closest('[data-thumb-kind]');if(!b)return;state.activeKind=b.dataset.thumbKind;renderStorefrontCard()});$('historyList').addEventListener('click',e=>{const b=e.target.closest('[data-open-run]');if(b)loadSavedRun(b.dataset.openRun)});
$('imageGrid').addEventListener('click',async e=>{const retry=e.target.closest('[data-retry-kind]'),download=e.target.closest('[data-download-url]');if(download){await downloadImage(download.dataset.downloadUrl,download.dataset.downloadKind);return}if(!retry||state.busy||!state.sessionId)return;const kind=retry.dataset.retryKind;setBusy(true);startStatusPoll();try{setStage(`generating_${kind}`);const d=await generateImage(kind);state.images[kind]=normalizeImage(d,kind);renderImageStatus();renderStorefrontCard();toast('Imagem refeita e salva.','ok');await loadHistory()}catch(err){state.images[kind]={kind,status:err.code==='image_fidelity_rejected'?'rejected':'error',error:err.message,validation:err.payload?.validation||{}};renderImageStatus();renderStorefrontCard();toast(err.message,'error')}finally{stopStatusPoll();setBusy(false)}});

renderTimeline();renderInputPhotos();loadHistory();const runId=new URLSearchParams(location.search).get('run');if(runId)loadSavedRun(runId);
