(()=>{'use strict';
const API='https://ssbesxgaijknwsjbsbcz.supabase.co/functions/v1/admin-products-live-v1';
const ADMIN_TOKEN_KEY='da_finance_access_token_v1';
const qs=new URLSearchParams(location.search),orderId=String(qs.get('order_id')||'').trim();
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});const qty=v=>Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:3});
let data=null,busyItem=null,completing=false;
function adminToken(){return String(sessionStorage.getItem(ADMIN_TOKEN_KEY)||'').trim()}
function separatorKey(){return String(data?.assignment?.separator_key||'').trim()||null}
function validUuid(v){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v)}
function showNotice(message,tone=''){const n=$('#notice');if(!n)return;n.hidden=!message;n.className='notice'+(tone?' '+tone:'');n.textContent=message||''}
async function api(action,params={},method='GET'){
  const token=adminToken();if(!token){const e=new Error('admin_session_required');e.status=401;throw e}
  const url=new URL(API);url.searchParams.set('action',action);if(method==='GET')for(const [k,v] of Object.entries(params))if(v!==null&&v!==undefined&&v!=='')url.searchParams.set(k,String(v));
  const options={method,headers:{Authorization:`Bearer ${token}`}};if(method!=='GET'){options.headers['Content-Type']='application/json';options.body=JSON.stringify(params)}
  const response=await fetch(url,options),body=await response.json().catch(()=>({}));if(!response.ok||body?.ok===false){const e=new Error(body?.error||`admin_${response.status}`);e.status=response.status;e.data=body;throw e}return body
}
function stateLabel(state){return state==='separated'?'Separado':state==='missing'?'Em falta':'Pendente'}
function stateClass(state){return state==='separated'?'separated':state==='missing'?'missing':''}
function groupItems(items){const groups=[],map=new Map(),loose=[];for(const x of items||[]){const basket=String(x.basket_name||'').trim();if(!basket){loose.push(x);continue}if(!map.has(basket)){const g={name:basket,items:[]};map.set(basket,g);groups.push(g)}map.get(basket).items.push(x)}if(loose.length)groups.push({name:'Produtos avulsos',items:loose});return groups}
function itemCard(x){const state=String(x.state||'pending'),klass=stateClass(state),disabled=busyItem===x.order_item_id||completing?'disabled':'';return `<article class="item ${klass}"><div>${x.image_url?`<img src="${esc(x.image_url)}" alt="${esc(x.name)}">`:'<div class="placeholder"></div>'}</div><div class="item-name">${esc(x.name||'Produto')}</div><div class="item-meta">Quantidade: <strong>${esc(qty(x.quantity))}</strong>${x.basket_name?` · ${esc(x.basket_name)}`:''}</div><div class="item-price">${esc(money(x.line_total))}</div><div class="state-label">${esc(stateLabel(state))}</div><div class="item-actions"><button class="state-btn separated ${state==='separated'?'active':''}" type="button" data-item-state="separated" data-order-item-id="${esc(x.order_item_id)}" ${disabled}>SEPARADO</button><button class="state-btn missing ${state==='missing'?'active':''}" type="button" data-item-state="missing" data-order-item-id="${esc(x.order_item_id)}" ${disabled}>EM FALTA</button></div></article>`}
function renderItems(){const host=$('#items'),groups=groupItems(data?.items||[]);if(!groups.length){host.innerHTML='<div class="empty">Nenhum produto disponível para separação.</div>';return}let html='';for(const group of groups){html+=`<h2 style="grid-column:1/-1;margin:8px 0 0;font-size:15px">${esc(group.name)}</h2>`+group.items.map(itemCard).join('')}host.innerHTML=html;host.querySelectorAll('[data-item-state]').forEach(button=>button.addEventListener('click',()=>setItemState(button.dataset.orderItemId,button.dataset.itemState)))}
function financialPreview(){const items=Array.isArray(data?.items)?data.items:[],missingAmount=items.filter(x=>x.state==='missing').reduce((sum,x)=>sum+Number(x.line_total||0),0),original=Number(data?.completion?.original_total??data?.original_total??data?.total??0),finalTotal=data?.completion?Number(data.completion.final_total??data.total??0):Math.max(0,Number(data?.total||0)-missingAmount);return {missingAmount,original,finalTotal}}
function renderSummary(){const counts=data?.counts||{},pending=Number(counts.pending||0),separated=Number(counts.separated||0),missing=Number(counts.missing||0),total=Number(counts.total||0),fin=financialPreview();$('#summary').innerHTML=`<div class="summary-box"><small>Total de itens</small><strong>${total}</strong></div><div class="summary-box"><small>Pendentes</small><strong>${pending}</strong></div><div class="summary-box"><small>Separados</small><strong>${separated}</strong></div><div class="summary-box"><small>Em falta</small><strong>${missing}</strong></div>`;const card=$('#completeCard'),completeReady=Number(data.counts?.pending||0)===0&&total>0&&!data?.completion?.completed_at;card.hidden=!completeReady;const separatedCount=separated,missingCount=missing;$('#completeSummary').innerHTML=`<div><small>Separados / Em falta</small><strong>${separatedCount} / ${missingCount}</strong></div><div><small>Valor a abater</small><strong>${money(fin.missingAmount)}</strong></div><div><small>Total após concluir</small><strong>${money(fin.finalTotal)}</strong></div>`;const btn=$('#completeSeparation');btn.disabled=completing||!completeReady;btn.textContent=completing?'CONCLUINDO…':'CONCLUIR SEPARAÇÃO'}
function render(){if(!data)return;$('#orderNumber').textContent=String(data.order_number||'Pedido');$('#customer').textContent=[data.customer_name,data.assignment?.separator_label?`Separando: ${data.assignment.separator_label}`:''].filter(Boolean).join(' · ');$('#orderStatus').textContent=data.status==='out_for_delivery'?'Em entrega':data.completion?.completed_at?'Separação concluída':'Em separação';renderSummary();renderItems();if(data.completion?.completed_at)showNotice(`Separação concluída. Total final: ${money(data.completion.final_total)}.`)}
async function loadSeparation(){showNotice('');if(!validUuid(orderId)){showNotice('Pedido inválido. Volte ao Admin e abra a separação novamente.','error');return}if(!adminToken()){showNotice('Sessão do Admin não encontrada. Volte ao Admin e abra a separação novamente.','error');return}try{const result=await api('order_separation_get',{id:orderId});data=result.separation;render()}catch(error){if(error.status===401||String(error.message)==='admin_session_required')showNotice('Sua sessão do Admin expirou. Volte ao Admin e abra novamente.','error');else showNotice('Não foi possível carregar a separação agora.','error')}}
async function setItemState(orderItemId,state){if(!data||busyItem||completing)return;busyItem=orderItemId;renderItems();try{const result=await api('order_separation_item_set',{order_id:orderId,order_item_id:orderItemId,state,expected_order_updated_at:data.order_updated_at,separator_key:separatorKey()},'POST');if(result?.item?.order_updated_at)data.order_updated_at=result.item.order_updated_at;await loadSeparation()}catch(error){if(error.status===409||error.data?.error==='stale_order_version'||error.data?.conflict==='order_version_conflict'){showNotice('O pedido foi alterado em outro aparelho. Atualizei a separação com o estado mais recente.');await loadSeparation()}else showNotice('Não consegui salvar este item. Tente novamente.','error')}finally{busyItem=null;if(data)render()}}
async function completeSeparation(){if(!data||completing)return;const pending=Number(data.counts?.pending||0);if(pending!==0)return;const items=Array.isArray(data.items)?data.items:[],separatedCount=Number(data.counts?.separated||0),missingCount=Number(data.counts?.missing||0),fin=financialPreview(),summary=`Separados: ${separatedCount}\nEm falta: ${missingCount}\nValor a abater: ${money(fin.missingAmount)}\nTotal final: ${money(fin.finalTotal)}\n\nConcluir a separação e liberar para entrega?`;if(!confirm(summary))return;completing=true;renderSummary();showNotice('Concluindo separação e validando estoque/Bling…');try{const result=await api('order_separation_complete',{order_id:orderId,expected_order_updated_at:data.order_updated_at,separator_key:separatorKey()},'POST');showNotice(`Separação concluída. Pedido liberado para entrega. Total: ${money(result.final_total??fin.finalTotal)}.`);await loadSeparation()}catch(error){if(error.status===409||error.data?.error==='stale_order_version'||error.data?.conflict==='order_version_conflict'){showNotice('O pedido mudou em outro aparelho. Recarreguei os dados antes de concluir.','error');await loadSeparation()}else if(error.data?.recovery_scheduled)showNotice('A separação foi registrada, mas há uma validação de Bling/fiscal pendente. O pedido ficou protegido para retomada sem repetir desconto ou estoque.','error');else showNotice('Não foi possível concluir a separação agora. Confira o aviso no Admin.','error')}finally{completing=false;if(data)renderSummary()}}
$('#completeSeparation').addEventListener('click',completeSeparation);document.addEventListener('visibilitychange',()=>{if(!document.hidden)loadSeparation()});loadSeparation();
})();
