(function(){
'use strict';
const C=window.DA_ADMIN_V3_CONFIG||{},AUTH_KEY='da_admin_v3_auth';
let root=null,state={snapshot:null,user:null,tab:'overview',selectedCommand:null,selectedCampaign:null,selectedAsset:null};
const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const fmt=v=>{if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('pt-BR')};
const j=v=>{try{return JSON.stringify(v??{},null,2)}catch{return '{}'}};
function auth(){try{return JSON.parse(localStorage.getItem(AUTH_KEY)||'null')}catch{return null}}
async function refresh(a){const r=await fetch(`${C.supabaseUrl}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:C.supabasePublishableKey,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:a?.refresh_token})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw new Error('Sessão expirada.');localStorage.setItem(AUTH_KEY,JSON.stringify(d));return d}
async function api(action,payload={},retry=true){let a=auth();if(!a?.access_token)throw new Error('Faça login.');const r=await fetch(`${C.supabaseUrl}/functions/v1/${C.marketingEdgeFunction||'admin-marketing-v1'}`,{method:'POST',headers:{apikey:C.supabasePublishableKey,Authorization:`Bearer ${a.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const d=await r.json().catch(()=>({}));if(r.status===401&&retry){await refresh(a);return api(action,payload,false)}if(!r.ok||d.ok===false)throw new Error(d.detail||d.error||`Erro ${r.status}`);return d}
function toast(m,k=''){const box=document.getElementById('toastRegion');if(!box)return;const x=document.createElement('div');x.className=`toast ${k}`.trim();x.textContent=m;box.appendChild(x);setTimeout(()=>x.remove(),4500)}
function parseJson(text,fallback={}){const t=String(text||'').trim();if(!t)return fallback;try{return JSON.parse(t)}catch{throw new Error('JSON inválido. Revise as configurações avançadas.')}}
const channelLabels={whatsapp_status:'Status WhatsApp',instagram_story:'Stories Instagram',facebook_story:'Stories Facebook',instagram_carousel:'Carrossel Instagram',pinterest_pin:'Pinterest',google_business_post:'Google Perfil da Empresa'};
const channelHelp={whatsapp_status:'Prepara oficialmente; publicação final exige confirmação no WhatsApp.',instagram_story:'Adapter oficial Meta; transporte continua OFF.',facebook_story:'Adapter oficial Meta; transporte continua OFF.',instagram_carousel:'Carrossel via API oficial quando homologado.',pinterest_pin:'Pin via Pinterest API quando homologado.',google_business_post:'Local Post via Google Business Profile API quando homologado.'};
const channels=Object.keys(channelLabels);
function shell(){return `<section class="marketing-center">
<div class="marketing-alert"><strong>Marketing protegido: publicação externa está desligada.</strong>O Admin pode criar, editar, versionar e organizar conteúdo. Nenhum canal, IA paga ou publicação é ativado por esta tela nesta versão.</div>
<div id="mktMetrics" class="marketing-metrics"></div>
<div class="marketing-tabs"><button class="marketing-tab active" data-mkt-tab="overview" type="button">Visão geral</button><button class="marketing-tab" data-mkt-tab="create" type="button">Criar conteúdo</button><button class="marketing-tab" data-mkt-tab="commands" type="button">Modelos e comandos</button><button class="marketing-tab" data-mkt-tab="campaigns" type="button">Campanhas</button><button class="marketing-tab" data-mkt-tab="queue" type="button">Fila</button><button class="marketing-tab" data-mkt-tab="channels" type="button">Canais</button></div>
<section class="marketing-pane active" data-mkt-pane="overview"><div class="marketing-grid"><section class="panel"><div class="panel-head"><div><div class="eyebrow">Segurança</div><h2>Runtime</h2></div><button id="mktReload" class="button secondary small" type="button">Atualizar</button></div><div id="mktRuntime" class="marketing-runtime"></div></section><section class="panel"><div class="panel-head"><div><div class="eyebrow">Próximos conteúdos</div><h2>Fila resumida</h2></div></div><div id="mktQueueSummary" class="marketing-list"></div></section></div><section class="panel"><div class="panel-head"><div><div class="eyebrow">Atalhos</div><h2>Operação rápida</h2></div></div><div class="marketing-actions"><button class="button primary" data-go-tab="create" type="button">+ Criar conteúdo</button><button class="button secondary" data-go-tab="commands" type="button">Comandos salvos</button><button class="button secondary" data-go-tab="campaigns" type="button">Campanhas</button></div></section><section class="marketing-danger"><strong>Parada de emergência</strong><p>Força o Marketing global e todas as campanhas para OFF, canary 0 e kill switch ligado. Não publica nada.</p><button id="mktKill" class="button danger" type="button">Aplicar kill switch</button></section></section>
<section class="marketing-pane" data-mkt-pane="create"><div class="marketing-grid"><section class="panel"><div class="panel-head"><div><div class="eyebrow">Compositor</div><h2>Novo conteúdo editável</h2></div><span class="marketing-pill off">rascunho</span></div><form id="mktAssetForm" class="marketing-form"><label>Título<input id="mktAssetTitle" required placeholder="Ex.: Ofertas de limpeza de sexta-feira"></label><div class="marketing-row"><label>Formato<select id="mktMediaKind"><option value="image">Imagem</option><option value="video">Vídeo</option><option value="carousel">Carrossel</option></select></label><label>Campanha<select id="mktAssetCampaign"><option value="">Sem campanha</option></select></label></div><label>Como produzir</label><div class="marketing-mode-picker"><label><input type="radio" name="mktMode" value="no_ai" checked> Sem IA</label><label><input type="radio" name="mktMode" value="ai"> Com IA</label><label><input type="radio" name="mktMode" value="hybrid"> Híbrido</label><label><input type="radio" name="mktMode" value="manual"> Manual</label></div><label>Comando salvo<select id="mktAssetCommand"><option value="">Nenhum</option></select></label><label>Instruções/edição<textarea id="mktAssetBrief" placeholder="Ex.: fundo cinza claro, produto centralizado, preço grande, logo discreto..."></textarea></label><label>Configuração avançada editável (JSON)<textarea id="mktAssetEdit">{"background":"#f1f1f1","safe_area":true,"brand":"dona_antonia"}</textarea></label><fieldset><legend>Preparar saídas para</legend><div class="marketing-channel-grid">${channels.map((x,i)=>`<label class="marketing-channel"><input type="checkbox" name="mktChannel" value="${x}" ${i<2?'checked':''}><span><strong>${channelLabels[x]}</strong><small>${channelHelp[x]}</small></span></label>`).join('')}</div></fieldset><button class="button primary" type="submit">Salvar rascunho e preparar canais</button><small>Nesta fase “preparar canais” cria apenas jobs draft idempotentes. Não agenda nem publica.</small></form></section><section class="panel"><div class="panel-head"><div><div class="eyebrow">Preview lógico</div><h2>Como será produzido</h2></div></div><div id="mktAssetPreview" class="marketing-preview">Escolha formato, modo e comando. O render visual entra no próximo bloco do módulo.</div><pre id="mktAssetResult" class="marketing-json">Nenhum rascunho criado.</pre></section></div><section class="panel"><div class="panel-head"><div><div class="eyebrow">Rascunhos</div><h2>Conteúdos recentes</h2></div></div><div id="mktAssets" class="marketing-list"></div></section></section>
<section class="marketing-pane" data-mkt-pane="commands"><div class="marketing-grid"><section class="panel"><div class="panel-head"><div><div class="eyebrow">Reutilização</div><h2>Salvar comando</h2></div><span class="marketing-pill">versionado</span></div><form id="mktCommandForm" class="marketing-form"><div class="marketing-row"><label>Chave<input id="mktCommandKey" required placeholder="oferta_estudio_produto"></label><label>Nome<input id="mktCommandName" required placeholder="Oferta estúdio produto"></label></div><div class="marketing-row"><label>Tipo<select id="mktCommandKind"><option value="image">Imagem</option><option value="video">Vídeo</option><option value="carousel">Carrossel</option><option value="caption">Legenda</option></select></label><label>Modo<select id="mktCommandMode"><option value="no_ai">Sem IA</option><option value="ai">IA</option><option value="hybrid">Híbrido</option><option value="manual">Manual</option></select></label></div><label>Provedor preferido<select id="mktProvider"><option value="auto">Automático</option><option value="deterministic_renderer">Renderer sem IA</option><option value="openai">OpenAI</option><option value="google">Google</option><option value="other">Outro homologado</option></select></label><label>Comando<textarea id="mktCommandText" required placeholder="Descreva exatamente o resultado desejado. Variáveis poderão ser reutilizadas."></textarea></label><label>Configurações (JSON)<textarea id="mktCommandSettings">{"editable":true}</textarea></label><button class="button primary" type="submit">Salvar nova versão</button><small>Editar um comando existente e salvar cria uma nova versão; a anterior continua auditável.</small></form></section><section class="panel"><div class="panel-head"><div><div class="eyebrow">Biblioteca</div><h2>Comandos salvos</h2></div></div><div id="mktCommands" class="marketing-list"></div></section></div></section>
<section class="marketing-pane" data-mkt-pane="campaigns"><div class="marketing-grid"><section class="panel"><div class="panel-head"><div><div class="eyebrow">Planejamento</div><h2 id="mktCampaignHeading">Nova campanha</h2></div><span class="marketing-pill off">OFF</span></div><form id="mktCampaignForm" class="marketing-form"><input id="mktCampaignId" type="hidden"><label>Nome<input id="mktCampaignName" required placeholder="Ex.: Ofertas da semana"></label><label>Objetivo<textarea id="mktCampaignObjective" placeholder="Vender cestas, girar limpeza, destacar ofertas..."></textarea></label><label>Produtos/regra de seleção (JSON)<textarea id="mktProductSelection">{"source":"catalog","only_in_stock":true,"avoid_recent_days":3}</textarea></label><label>Agenda desejada (JSON)<textarea id="mktScheduleRule">{"timezone":"America/Cuiaba","times":["08:00","12:00","18:00"]}</textarea></label><label>Política de IA (JSON)<textarea id="mktAiPolicy">{"mode":"optional","image":"optional","video":"optional","prefer_no_ai":true}</textarea></label><button class="button primary" type="submit">Salvar campanha em rascunho</button><button id="mktCampaignCancelEdit" class="button secondary hidden" type="button">Cancelar edição</button></form></section><section class="panel"><div class="panel-head"><div><div class="eyebrow">Campanhas</div><h2>Rascunhos e histórico</h2></div></div><div id="mktCampaigns" class="marketing-list"></div></section></div></section>
<section class="marketing-pane" data-mkt-pane="queue"><section class="panel"><div class="panel-head"><div><div class="eyebrow">Publicação</div><h2>Jobs preparados</h2></div><span class="marketing-pill off">sem dispatcher</span></div><div id="mktJobs" class="marketing-list"></div></section></section>
<section class="marketing-pane" data-mkt-pane="channels"><div class="marketing-grid"><section class="panel"><div class="panel-head"><div><div class="eyebrow">Canais oficiais</div><h2>Capacidades</h2></div></div><div id="mktChannels" class="marketing-list"></div></section><section class="panel"><div class="panel-head"><div><div class="eyebrow">Contas</div><h2>Conexões</h2></div></div><div id="mktAccounts" class="marketing-list"></div><small class="muted">Tokens não são armazenados nesta UI. Futuras credenciais serão referências seguras no Vault.</small></section></div></section>
</section>`}
function setTab(tab){state.tab=tab;root.querySelectorAll('[data-mkt-tab]').forEach(x=>x.classList.toggle('active',x.dataset.mktTab===tab));root.querySelectorAll('[data-mkt-pane]').forEach(x=>x.classList.toggle('active',x.dataset.mktPane===tab))}
function badgeMode(x){const c=x==='ai'||x==='hybrid'?'ai':x==='no_ai'?'no-ai':'off';return `<span class="marketing-pill ${c}">${esc(x||'—')}</span>`}
function render(){const s=state.snapshot||{},r=s.readiness||{},cfg=r.runtime||{},counts=r.counts||{};root.querySelector('#mktMetrics').innerHTML=`<article class="marketing-metric"><small>Campanhas</small><strong>${esc(counts.campaigns||0)}</strong></article><article class="marketing-metric"><small>Conteúdos</small><strong>${esc(counts.assets||0)}</strong></article><article class="marketing-metric"><small>Comandos</small><strong>${esc(counts.commands||0)}</strong></article><article class="marketing-metric"><small>Fila</small><strong>${esc(counts.publication_jobs||0)}</strong></article>`;
root.querySelector('#mktRuntime').innerHTML=[['Marketing',cfg.enabled?'ON':'OFF'],['Modo',cfg.execution_mode||'off'],['Kill switch',cfg.kill_switch?'LIGADO':'desligado'],['Publicação',cfg.publishing_enabled?'habilitada':'OFF'],['Imagem IA',cfg.ai_image_enabled?'habilitada':'OFF'],['Vídeo IA',cfg.ai_video_enabled?'habilitado':'OFF'],['Renderer sem IA',cfg.deterministic_render_enabled?'habilitado':'OFF'],['Canary',`${cfg.canary_percent||0}%`]].map(x=>`<div class="marketing-runtime-line"><span>${esc(x[0])}</span><strong>${esc(x[1])}</strong></div>`).join('');
const jobs=s.jobs||[];root.querySelector('#mktQueueSummary').innerHTML=jobs.length?jobs.slice(0,6).map(jobItem).join(''):'<div class="marketing-empty">Nenhum job preparado.</div>';root.querySelector('#mktJobs').innerHTML=jobs.length?jobs.map(jobItem).join(''):'<div class="marketing-empty">A fila está vazia.</div>';
const cmds=s.commands||[];root.querySelector('#mktCommands').innerHTML=cmds.length?cmds.map(c=>`<div class="marketing-item"><div class="marketing-item-head"><div><strong>${esc(c.name)}</strong><small>${esc(c.command_key)} · v${esc(c.version)} · ${esc(c.media_kind)}</small></div>${badgeMode(c.generation_mode)}</div><div class="marketing-actions"><button class="linkish" data-edit-command="${esc(c.id)}" type="button">Usar como base para nova versão</button></div></div>`).join(''):'<div class="marketing-empty">Nenhum comando salvo.</div>';
const camps=s.campaigns||[];root.querySelector('#mktCampaigns').innerHTML=camps.length?camps.map(c=>`<div class="marketing-item"><div class="marketing-item-head"><div><strong>${esc(c.name)}</strong><small>${esc(c.objective||'Sem objetivo')} · ${esc(c.status)} · ${esc(c.execution_mode)}</small></div><span class="marketing-pill off">${c.kill_switch?'kill ON':'kill OFF'}</span></div><div class="marketing-actions"><button class="linkish" data-edit-campaign="${esc(c.id)}" type="button">Editar rascunho</button></div></div>`).join(''):'<div class="marketing-empty">Nenhuma campanha.</div>';
const assets=s.assets||[];root.querySelector('#mktAssets').innerHTML=assets.length?assets.map(a=>`<div class="marketing-item"><div class="marketing-item-head"><div><strong>${esc(a.title)}</strong><small>${esc(a.media_kind)} · ${esc(a.status)} · atualizado ${fmt(a.updated_at)}</small></div>${badgeMode(a.generation_mode)}</div><div class="marketing-actions">${a.status==='draft'?`<button class="linkish" data-edit-asset="${esc(a.id)}" type="button">Editar configurações</button>`:''}</div></div>`).join(''):'<div class="marketing-empty">Nenhum conteúdo criado.</div>';
const channelState=r.channels||{};root.querySelector('#mktChannels').innerHTML=channels.map(ch=>{const x=channelState[ch]||{};return `<div class="marketing-item"><div class="marketing-item-head"><div><strong>${channelLabels[ch]}</strong><small>${channelHelp[ch]}</small></div><span class="marketing-pill off">${x.publish_gate?'gate ON':'gate OFF'}</span></div><small>Caminho: ${esc(x.publication_path||'planejado')} · confirmação manual: ${x.manual_confirmation_required?'sim':'não quando homologado'}</small></div>`}).join('');
const acc=s.accounts||[];root.querySelector('#mktAccounts').innerHTML=acc.length?acc.map(a=>`<div class="marketing-item"><div class="marketing-item-head"><div><strong>${esc(a.display_name)}</strong><small>${esc(channelLabels[a.channel]||a.channel)} · ${esc(a.provider)}</small></div><span class="marketing-pill off">${esc(a.status)}</span></div></div>`).join(''):'<div class="marketing-empty">Nenhuma conta conectada nesta fundação.</div>';
fillSelects();bindDynamic();updatePreview()}
function jobItem(x){return `<div class="marketing-item"><div class="marketing-item-head"><div><strong>${esc(channelLabels[x.channel]||x.channel)}</strong><small>${esc(x.content_type)} · ${esc(x.status)}${x.scheduled_for?' · '+fmt(x.scheduled_for):''}</small></div><span class="marketing-pill off">${x.manual_confirmation_required?'manual':'draft'}</span></div></div>`}
function fillSelects(){const s=state.snapshot||{},campaign=root.querySelector('#mktAssetCampaign'),command=root.querySelector('#mktAssetCommand');const cv=campaign.value,qv=command.value;campaign.innerHTML='<option value="">Sem campanha</option>'+((s.campaigns||[]).map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join(''));command.innerHTML='<option value="">Nenhum</option>'+((s.commands||[]).map(x=>`<option value="${esc(x.id)}">${esc(x.name)} · v${esc(x.version)}</option>`).join(''));if([...campaign.options].some(x=>x.value===cv))campaign.value=cv;if([...command.options].some(x=>x.value===qv))command.value=qv}
function bindDynamic(){root.querySelectorAll('[data-edit-command]').forEach(b=>b.onclick=()=>editCommand(b.dataset.editCommand));root.querySelectorAll('[data-edit-campaign]').forEach(b=>b.onclick=()=>editCampaign(b.dataset.editCampaign));root.querySelectorAll('[data-edit-asset]').forEach(b=>b.onclick=()=>editAsset(b.dataset.editAsset))}
async function load(){const d=await api('overview');state.snapshot=d.snapshot||{};state.user=d.user||null;render()}
function updatePreview(){const kind=root.querySelector('#mktMediaKind')?.value||'image',mode=root.querySelector('input[name="mktMode"]:checked')?.value||'no_ai',cmd=root.querySelector('#mktAssetCommand')?.selectedOptions?.[0]?.textContent||'sem comando';const p=root.querySelector('#mktAssetPreview');if(!p)return;p.classList.toggle('vertical',kind==='video');p.innerHTML=`<div><strong>${esc(kind.toUpperCase())}</strong><br>${mode==='no_ai'?'Renderer determinístico · sem custo de IA':mode==='ai'?'Geração por IA · sujeita a orçamento/gate':mode==='hybrid'?'Template + IA seletiva':'Edição manual'}<br><small>${esc(cmd)}</small></div>`}
async function createAsset(e){e.preventDefault();try{const title=root.querySelector('#mktAssetTitle').value.trim(),media_kind=root.querySelector('#mktMediaKind').value,generation_mode=root.querySelector('input[name="mktMode"]:checked').value,campaign_id=root.querySelector('#mktAssetCampaign').value||null,command_preset_id=root.querySelector('#mktAssetCommand').value||null,brief=root.querySelector('#mktAssetBrief').value.trim(),edit_spec=parseJson(root.querySelector('#mktAssetEdit').value,{});edit_spec.instructions=brief;const d=await api('create_asset',{title,media_kind,generation_mode,campaign_id,command_preset_id,edit_spec,render_spec:{editable:true,requested_from:'marketing_admin'}});const assetId=d.result.id;const selected=[...root.querySelectorAll('input[name="mktChannel"]:checked')].map(x=>x.value);const jobs=[];for(const channel of selected){const content_type=media_kind==='carousel'?'carousel':media_kind;jobs.push((await api('create_publication_draft',{asset_id:assetId,channel,content_type,payload:{title,source:'marketing_admin'},idempotency_key:`admin:${assetId}:${channel}`})).result)}root.querySelector('#mktAssetResult').textContent=j({asset:d.result,jobs,external_side_effect:false});toast('Rascunho salvo. Nenhuma publicação foi feita.','success');await load()}catch(err){root.querySelector('#mktAssetResult').textContent=`Bloqueado: ${err.message}`;toast(err.message,'error')}}
async function saveCommand(e){e.preventDefault();try{const payload={command_key:root.querySelector('#mktCommandKey').value,name:root.querySelector('#mktCommandName').value,media_kind:root.querySelector('#mktCommandKind').value,generation_mode:root.querySelector('#mktCommandMode').value,provider_hint:root.querySelector('#mktProvider').value,command_text:root.querySelector('#mktCommandText').value,settings:parseJson(root.querySelector('#mktCommandSettings').value,{})};const d=await api('create_command',payload);toast(`Comando salvo como versão ${d.result.version}.`,'success');await load()}catch(err){toast(err.message,'error')}}
function editCommand(id){const c=(state.snapshot?.commands||[]).find(x=>x.id===id);if(!c)return;root.querySelector('#mktCommandKey').value=c.command_key;root.querySelector('#mktCommandName').value=c.name;root.querySelector('#mktCommandKind').value=c.media_kind;root.querySelector('#mktCommandMode').value=c.generation_mode;setTab('commands');root.querySelector('#mktCommandText').focus();toast('Dados básicos carregados. Ajuste o comando e salve uma nova versão.')}
async function saveCampaign(e){e.preventDefault();try{const id=root.querySelector('#mktCampaignId').value,payload={name:root.querySelector('#mktCampaignName').value,objective:root.querySelector('#mktCampaignObjective').value,product_selection:parseJson(root.querySelector('#mktProductSelection').value,{}),schedule_rule:parseJson(root.querySelector('#mktScheduleRule').value,{}),ai_policy:parseJson(root.querySelector('#mktAiPolicy').value,{}),content_policy:{editable:true,require_current_price:true,require_stock:true},channel_plan:{channels:channels}};await api(id?'update_campaign':'create_campaign',id?{campaign_id:id,...payload}:payload);toast('Campanha salva em rascunho.','success');cancelCampaignEdit();await load()}catch(err){toast(err.message,'error')}}
function editCampaign(id){const c=(state.snapshot?.campaigns||[]).find(x=>x.id===id);if(!c)return;if(c.status!=='draft'){toast('Somente campanha draft pode ser editada nesta versão.','error');return}root.querySelector('#mktCampaignId').value=c.id;root.querySelector('#mktCampaignName').value=c.name||'';root.querySelector('#mktCampaignObjective').value=c.objective||'';root.querySelector('#mktProductSelection').value=j(c.product_selection||{});root.querySelector('#mktScheduleRule').value=j(c.schedule_rule||{});root.querySelector('#mktAiPolicy').value=j(c.ai_policy||{});root.querySelector('#mktCampaignHeading').textContent='Editar campanha';root.querySelector('#mktCampaignCancelEdit').classList.remove('hidden');setTab('campaigns')}
function cancelCampaignEdit(){root.querySelector('#mktCampaignId').value='';root.querySelector('#mktCampaignHeading').textContent='Nova campanha';root.querySelector('#mktCampaignCancelEdit').classList.add('hidden');root.querySelector('#mktCampaignForm').reset();root.querySelector('#mktProductSelection').value='{"source":"catalog","only_in_stock":true,"avoid_recent_days":3}';root.querySelector('#mktScheduleRule').value='{"timezone":"America/Cuiaba","times":["08:00","12:00","18:00"]}';root.querySelector('#mktAiPolicy').value='{"mode":"optional","image":"optional","video":"optional","prefer_no_ai":true}'}
function editAsset(id){const a=(state.snapshot?.assets||[]).find(x=>x.id===id);if(!a)return;root.querySelector('#mktAssetTitle').value=a.title||'';root.querySelector('#mktMediaKind').value=a.media_kind||'image';const r=root.querySelector(`input[name="mktMode"][value="${CSS.escape(a.generation_mode||'no_ai')}"]`);if(r)r.checked=true;root.querySelector('#mktAssetCommand').value=a.command_preset_id||'';root.querySelector('#mktAssetEdit').value=j(a.edit_spec||{});root.querySelector('#mktAssetResult').textContent=`Editando localmente o rascunho ${a.id}. O salvamento versionado completo do asset entra no próximo bloco.`;setTab('create');updatePreview()}
async function kill(){if(!confirm('Forçar Marketing e campanhas para OFF?'))return;try{await api('kill',{reason:'owner_admin_marketing_kill'});toast('Kill switch aplicado.','success');await load()}catch(err){toast(err.message,'error')}}
function bind(){root.querySelectorAll('[data-mkt-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.mktTab));root.querySelectorAll('[data-go-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.goTab));root.querySelector('#mktReload').onclick=()=>load().catch(e=>toast(e.message,'error'));root.querySelector('#mktKill').onclick=kill;root.querySelector('#mktAssetForm').onsubmit=createAsset;root.querySelector('#mktCommandForm').onsubmit=saveCommand;root.querySelector('#mktCampaignForm').onsubmit=saveCampaign;root.querySelector('#mktCampaignCancelEdit').onclick=cancelCampaignEdit;root.querySelector('#mktMediaKind').onchange=updatePreview;root.querySelector('#mktAssetCommand').onchange=updatePreview;root.querySelectorAll('input[name="mktMode"]').forEach(x=>x.onchange=updatePreview)}
async function mount(el){root=el;root.innerHTML=shell();bind();await load().catch(e=>toast(e.message,'error'))}
window.DAMarketingCenter={mount};
})();
