import { loadCatalog } from '../shared/catalog.js';
import { loadHomeCollections } from '../shared/collections.js';
import { loadOrders } from '../shared/orders.js';
import { buildDiagnosticSummary, diagnosticRecommendations } from './diagnostic-audit.js';

const content=document.getElementById('admin-content');
const status=document.getElementById('admin-status');
const title=document.getElementById('module-title');
const subtitle=document.getElementById('module-subtitle');
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const metric=(value,label)=>`<article class="metric"><strong>${value}</strong><span>${label}</span></article>`;
const state={loading:false,loaded:false,summary:null,generatedAt:''};

function localIntegrationResults(){try{return JSON.parse(localStorage.getItem('da_v2:integration-results')||'[]');}catch{return [];}}
function localPublicationPlan(){try{const rows=JSON.parse(localStorage.getItem('da_v2:publication-plans')||'[]');return rows[0]||null;}catch{return null;}}
function statusLabel(value){return value==='ready'?'Pronto para revisão':value==='attention'?'Exige atenção':'Bloqueado';}

function render(){const summary=state.summary,recommendations=diagnosticRecommendations(summary);title.textContent='Diagnóstico geral';subtitle.textContent='Visão consolidada sem substituir as auditorias especializadas.';content.innerHTML=`<section class="module-hero diagnostic-hero"><div><span class="eyebrow">CONSOLIDAÇÃO · SOMENTE LEITURA</span><h2>Saúde geral da V2</h2><p>Catálogo, estoque, coleções, pedidos, integrações e publicação reunidos em uma única leitura. Nenhuma correção é executada automaticamente.</p></div><div class="diagnostic-score ${summary.status}"><strong>${summary.score}%</strong><span>${statusLabel(summary.status)}</span></div></section><section class="metrics">${metric(summary.passed,'VERIFICAÇÕES APROVADAS')}${metric(summary.total-summary.passed,'BLOQUEIOS')}${metric(summary.productIssues+summary.collectionIssues+summary.orderIssues,'PENDÊNCIAS ESTRUTURAIS')}${metric(summary.integrationOk+'/'+summary.integrationTotal,'INTEGRAÇÕES LIDAS')}</section><section class="panel"><div class="panel-head"><h3>Verificações consolidadas</h3><span class="pill">Atualizado ${escapeHtml(state.generatedAt)}</span></div><div class="diagnostic-checks">${summary.checks.map(check=>`<article class="diagnostic-check ${check.ok?'ok':'error'}"><span>${check.ok?'✓':'!'}</span><div><strong>${escapeHtml(check.label)}</strong><small>${escapeHtml(check.detail)}</small></div></article>`).join('')}</div></section><section class="panel"><div class="panel-head"><h3>Próximas correções recomendadas</h3><span class="pill">Sem automação</span></div>${recommendations.length?`<div class="recommendation-list">${recommendations.map(item=>`<article><strong>${escapeHtml(item.text)}</strong><span>Abra o módulo correspondente para analisar os registros.</span></article>`).join('')}</div>`:'<div class="notice success">Todas as verificações consolidadas foram aprovadas. Ainda é necessária revisão humana antes de qualquer escrita ou publicação.</div>'}<div class="notice">Este diagnóstico não salva produtos, não altera pedidos, não chama Make/Bling e não publica arquivos.</div></section>`;}

async function openModule(){document.querySelectorAll('[data-module]').forEach(button=>button.classList.toggle('active',button.dataset.module==='diagnostics'));if(state.loading)return;state.loading=true;title.textContent='Diagnóstico geral';subtitle.textContent='Reunindo leituras seguras…';content.innerHTML='<div class="panel"><div class="empty">Carregando diagnóstico consolidado…</div></div>';try{const [catalog,collections,orders]=await Promise.all([loadCatalog(),loadHomeCollections(),loadOrders().catch(()=>[])]);state.summary=buildDiagnosticSummary({products:catalog.products,baskets:collections.baskets,kits:collections.kits,orders,integrationResults:localIntegrationResults(),publicationPlan:localPublicationPlan()});state.generatedAt=new Date().toLocaleString('pt-BR');state.loaded=true;status.textContent=`Diagnóstico ${state.summary.score}%`;status.dataset.type=state.summary.status==='ready'?'success':'error';render();}catch(error){status.textContent='Falha no diagnóstico';status.dataset.type='error';content.innerHTML=`<div class="panel"><div class="notice error">${escapeHtml(error.message||error)}</div></div>`;}finally{state.loading=false;}}

document.addEventListener('click',event=>{const button=event.target.closest('[data-module="diagnostics"]');if(!button)return;event.preventDefault();event.stopImmediatePropagation();openModule();},true);
