BEGIN;

CREATE SCHEMA IF NOT EXISTS private;

CREATE TABLE IF NOT EXISTS private.whatsapp_ana_admin_draft_v1 (
  singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
  configuration jsonb NOT NULL CHECK (jsonb_typeof(configuration) = 'object'),
  revision bigint NOT NULL DEFAULT 1 CHECK (revision > 0),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid
);

CREATE TABLE IF NOT EXISTS private.whatsapp_ana_admin_versions_v1 (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version integer NOT NULL UNIQUE CHECK (version > 0),
  configuration jsonb NOT NULL CHECK (jsonb_typeof(configuration) = 'object'),
  actor_id uuid,
  change_note text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS private.whatsapp_ana_admin_runtime_v1 (
  singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
  active_version_id bigint NOT NULL REFERENCES private.whatsapp_ana_admin_versions_v1(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid
);

CREATE TABLE IF NOT EXISTS private.whatsapp_ana_admin_events_v1 (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action text NOT NULL CHECK (action IN ('draft_saved','published','rolled_back','channel_toggled')),
  actor_id uuid,
  version_id bigint,
  draft_revision bigint,
  channel_key text,
  detail jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(detail) = 'object'),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS private.whatsapp_ana_admin_test_runs_v1 (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  draft_revision bigint NOT NULL,
  scenario_keys text[] NOT NULL DEFAULT '{}',
  passed_count integer NOT NULL CHECK (passed_count >= 0),
  failed_count integer NOT NULL CHECK (failed_count >= 0),
  safe_reasons jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(safe_reasons) = 'array'),
  latency_ms integer NOT NULL DEFAULT 0 CHECK (latency_ms >= 0),
  actor_id uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE private.whatsapp_ana_admin_draft_v1 ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.whatsapp_ana_admin_versions_v1 ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.whatsapp_ana_admin_runtime_v1 ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.whatsapp_ana_admin_events_v1 ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.whatsapp_ana_admin_test_runs_v1 ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON private.whatsapp_ana_admin_draft_v1, private.whatsapp_ana_admin_versions_v1,
  private.whatsapp_ana_admin_runtime_v1, private.whatsapp_ana_admin_events_v1,
  private.whatsapp_ana_admin_test_runs_v1 FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION private.whatsapp_ana_admin_immutable_v1()
RETURNS trigger LANGUAGE plpgsql SET search_path = pg_catalog AS $$
BEGIN
  RAISE EXCEPTION 'ana_admin_record_immutable';
END;
$$;
DROP TRIGGER IF EXISTS whatsapp_ana_admin_versions_immutable_v1 ON private.whatsapp_ana_admin_versions_v1;
CREATE TRIGGER whatsapp_ana_admin_versions_immutable_v1 BEFORE UPDATE OR DELETE ON private.whatsapp_ana_admin_versions_v1
FOR EACH ROW EXECUTE FUNCTION private.whatsapp_ana_admin_immutable_v1();
DROP TRIGGER IF EXISTS whatsapp_ana_admin_events_immutable_v1 ON private.whatsapp_ana_admin_events_v1;
CREATE TRIGGER whatsapp_ana_admin_events_immutable_v1 BEFORE UPDATE OR DELETE ON private.whatsapp_ana_admin_events_v1
FOR EACH ROW EXECUTE FUNCTION private.whatsapp_ana_admin_immutable_v1();
DROP TRIGGER IF EXISTS whatsapp_ana_admin_test_runs_immutable_v1 ON private.whatsapp_ana_admin_test_runs_v1;
CREATE TRIGGER whatsapp_ana_admin_test_runs_immutable_v1 BEFORE UPDATE OR DELETE ON private.whatsapp_ana_admin_test_runs_v1
FOR EACH ROW EXECUTE FUNCTION private.whatsapp_ana_admin_immutable_v1();

INSERT INTO private.whatsapp_ana_admin_versions_v1(version, configuration, change_note)
VALUES (1, jsonb_build_object(
  'behavior', jsonb_build_object('tone','cordial','conciseness','short','emoji','sparingly','use_known_first_name_on_first_greeting',true),
  'knowledge', jsonb_build_array(
    jsonb_build_object('key','catalogo','title','Catálogo e pedidos','category','vendas','status','published','content','Para consultar produtos e fazer pedidos, direcione a pessoa ao catálogo/site oficial. O atendimento pode orientar por aqui; a ANA não cria pedidos.'),
    jsonb_build_object('key','atendimento-humano','title','Atendimento humano','category','atendimento','status','published','content','Encaminhe para uma pessoa quando o cliente pedir, quando faltar informação confiável ou houver exceção operacional.'),
    jsonb_build_object('key','dados-dinamicos','title','Dados que precisam de confirmação','category','seguranca','status','published','content','Não invente preço, estoque, total, composição, prazo, endereço, pedido, pagamento ou dado do cliente.')
  ),
  'triggers', jsonb_build_array(),
  'test_cases', jsonb_build_array(
    jsonb_build_object('key','greeting','input','Oi','expected','reply'),
    jsonb_build_object('key','dynamic_price','input','Qual o preço?','expected','handoff'),
    jsonb_build_object('key','operational_issue','input','Meu pedido atrasou','expected','handoff')
  )
), 'Baseline ANA behavior preserved before configurable worker rollout')
ON CONFLICT (version) DO NOTHING;

INSERT INTO private.whatsapp_ana_admin_draft_v1(singleton, configuration, revision)
SELECT true, configuration, 1 FROM private.whatsapp_ana_admin_versions_v1 WHERE version = 1
ON CONFLICT (singleton) DO NOTHING;
INSERT INTO private.whatsapp_ana_admin_runtime_v1(singleton, active_version_id)
SELECT true, id FROM private.whatsapp_ana_admin_versions_v1 WHERE version = 1
ON CONFLICT (singleton) DO NOTHING;

CREATE OR REPLACE FUNCTION public.ops2_ana_admin_load_v1()
RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path = pg_catalog, private AS $$
  SELECT jsonb_build_object(
    'ok', true,
    'draft', (SELECT jsonb_build_object('configuration', d.configuration, 'revision', d.revision, 'updated_at', d.updated_at)
              FROM private.whatsapp_ana_admin_draft_v1 d WHERE d.singleton),
    'active', (SELECT jsonb_build_object('id', v.id, 'version', v.version, 'configuration', v.configuration, 'created_at', v.created_at)
               FROM private.whatsapp_ana_admin_runtime_v1 r JOIN private.whatsapp_ana_admin_versions_v1 v ON v.id = r.active_version_id WHERE r.singleton),
    'versions', (SELECT coalesce(jsonb_agg(jsonb_build_object('id', v.id, 'version', v.version, 'actor_id', v.actor_id, 'change_note', v.change_note, 'created_at', v.created_at) ORDER BY v.version DESC), '[]'::jsonb)
                 FROM (SELECT * FROM private.whatsapp_ana_admin_versions_v1 ORDER BY version DESC LIMIT 20) v),
    'test_runs', (SELECT coalesce(jsonb_agg(jsonb_build_object('id', t.id, 'draft_revision', t.draft_revision, 'scenario_keys', t.scenario_keys, 'passed_count', t.passed_count, 'failed_count', t.failed_count, 'safe_reasons', t.safe_reasons, 'latency_ms', t.latency_ms, 'created_at', t.created_at) ORDER BY t.created_at DESC), '[]'::jsonb)
                  FROM (SELECT * FROM private.whatsapp_ana_admin_test_runs_v1 ORDER BY created_at DESC LIMIT 20) t),
    'events', (SELECT coalesce(jsonb_agg(jsonb_build_object('action', e.action, 'actor_id', e.actor_id, 'version_id', e.version_id, 'draft_revision', e.draft_revision, 'channel_key', e.channel_key, 'detail', e.detail, 'created_at', e.created_at) ORDER BY e.created_at DESC), '[]'::jsonb)
               FROM (SELECT * FROM private.whatsapp_ana_admin_events_v1 ORDER BY created_at DESC LIMIT 30) e)
  );
$$;

CREATE OR REPLACE FUNCTION public.ops2_ana_admin_save_draft_v1(p_configuration jsonb, p_expected_revision bigint, p_note text DEFAULT '', p_actor_id uuid DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, private AS $$
DECLARE current_row private.whatsapp_ana_admin_draft_v1%ROWTYPE;
BEGIN
  IF jsonb_typeof(p_configuration) <> 'object' OR jsonb_typeof(p_configuration->'behavior') <> 'object'
     OR jsonb_typeof(p_configuration->'knowledge') <> 'array' OR jsonb_typeof(p_configuration->'triggers') <> 'array'
     OR jsonb_typeof(p_configuration->'test_cases') <> 'array' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'configuration_shape_invalid');
  END IF;
  SELECT * INTO current_row FROM private.whatsapp_ana_admin_draft_v1 WHERE singleton FOR UPDATE;
  IF NOT FOUND THEN RETURN jsonb_build_object('ok', false, 'error', 'draft_missing'); END IF;
  IF current_row.revision <> p_expected_revision THEN
    RETURN jsonb_build_object('ok', false, 'error', 'revision_conflict', 'revision', current_row.revision);
  END IF;
  UPDATE private.whatsapp_ana_admin_draft_v1 SET configuration = p_configuration, revision = revision + 1,
    updated_at = now(), updated_by = p_actor_id WHERE singleton RETURNING * INTO current_row;
  INSERT INTO private.whatsapp_ana_admin_events_v1(action, actor_id, draft_revision, detail)
    VALUES ('draft_saved', p_actor_id, current_row.revision, jsonb_build_object('note', left(coalesce(p_note,''),240)));
  RETURN jsonb_build_object('ok', true, 'revision', current_row.revision, 'updated_at', current_row.updated_at);
END;
$$;

CREATE OR REPLACE FUNCTION public.ops2_ana_admin_publish_v1(p_test_run_id uuid, p_note text DEFAULT '', p_actor_id uuid DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, private AS $$
DECLARE d private.whatsapp_ana_admin_draft_v1%ROWTYPE; t private.whatsapp_ana_admin_test_runs_v1%ROWTYPE;
  next_version integer; new_id bigint;
BEGIN
  SELECT * INTO d FROM private.whatsapp_ana_admin_draft_v1 WHERE singleton FOR UPDATE;
  SELECT * INTO t FROM private.whatsapp_ana_admin_test_runs_v1 WHERE id = p_test_run_id;
  IF NOT FOUND OR t.draft_revision <> d.revision OR t.failed_count <> 0 OR t.passed_count = 0 THEN
    RETURN jsonb_build_object('ok', false, 'error', 'test_run_missing_stale_or_failed');
  END IF;
  SELECT coalesce(max(version),0)+1 INTO next_version FROM private.whatsapp_ana_admin_versions_v1;
  INSERT INTO private.whatsapp_ana_admin_versions_v1(version, configuration, actor_id, change_note)
    VALUES(next_version, d.configuration, p_actor_id, left(coalesce(p_note,''),240)) RETURNING id INTO new_id;
  INSERT INTO private.whatsapp_ana_admin_runtime_v1(singleton, active_version_id, updated_at, updated_by)
    VALUES(true,new_id,now(),p_actor_id)
    ON CONFLICT(singleton) DO UPDATE SET active_version_id=excluded.active_version_id,updated_at=excluded.updated_at,updated_by=excluded.updated_by;
  INSERT INTO private.whatsapp_ana_admin_events_v1(action,actor_id,version_id,draft_revision,detail)
    VALUES('published',p_actor_id,new_id,d.revision,jsonb_build_object('version',next_version,'test_run_id',p_test_run_id,'note',left(coalesce(p_note,''),240)));
  RETURN jsonb_build_object('ok',true,'version',next_version,'version_id',new_id,'draft_revision',d.revision);
END;
$$;

CREATE OR REPLACE FUNCTION public.ops2_ana_admin_rollback_v1(p_version_id bigint, p_note text DEFAULT '', p_actor_id uuid DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, private AS $$
DECLARE target private.whatsapp_ana_admin_versions_v1%ROWTYPE;
BEGIN
  SELECT * INTO target FROM private.whatsapp_ana_admin_versions_v1 WHERE id=p_version_id;
  IF NOT FOUND THEN RETURN jsonb_build_object('ok',false,'error','version_not_found'); END IF;
  INSERT INTO private.whatsapp_ana_admin_runtime_v1(singleton,active_version_id,updated_at,updated_by)
    VALUES(true,target.id,now(),p_actor_id)
    ON CONFLICT(singleton) DO UPDATE SET active_version_id=excluded.active_version_id,updated_at=excluded.updated_at,updated_by=excluded.updated_by;
  INSERT INTO private.whatsapp_ana_admin_events_v1(action,actor_id,version_id,detail)
    VALUES('rolled_back',p_actor_id,target.id,jsonb_build_object('version',target.version,'note',left(coalesce(p_note,''),240)));
  RETURN jsonb_build_object('ok',true,'version',target.version,'version_id',target.id);
END;
$$;

CREATE OR REPLACE FUNCTION public.ops2_ana_active_config_v1()
RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path = pg_catalog, private AS $$
  SELECT jsonb_build_object('ok',true,'version',v.version,'version_id',v.id,'configuration',v.configuration)
  FROM private.whatsapp_ana_admin_runtime_v1 r JOIN private.whatsapp_ana_admin_versions_v1 v ON v.id=r.active_version_id
  WHERE r.singleton;
$$;

REVOKE ALL ON FUNCTION public.ops2_ana_admin_load_v1() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.ops2_ana_admin_save_draft_v1(jsonb,bigint,text,uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.ops2_ana_admin_publish_v1(uuid,text,uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.ops2_ana_admin_rollback_v1(bigint,text,uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.ops2_ana_active_config_v1() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.ops2_ana_admin_load_v1() TO service_role;
GRANT EXECUTE ON FUNCTION public.ops2_ana_admin_save_draft_v1(jsonb,bigint,text,uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.ops2_ana_admin_publish_v1(uuid,text,uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.ops2_ana_admin_rollback_v1(bigint,text,uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.ops2_ana_active_config_v1() TO service_role;

CREATE OR REPLACE FUNCTION public.ops2_ana_admin_set_channel_v1(p_whatsapp_account_id uuid, p_enabled boolean, p_actor_id uuid)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, private AS $$
DECLARE changed_id uuid; channel_suffix text;
BEGIN
  IF p_enabled IS TRUE AND NOT EXISTS(
    SELECT 1 FROM public.whatsapp_channel_runtime_v1 r
    WHERE r.whatsapp_account_id=p_whatsapp_account_id AND r.capture_enabled IS TRUE
      AND r.send_enabled IS TRUE AND r.outbound_provider='meta' AND r.homologated_at IS NOT NULL
  ) THEN
    RETURN jsonb_build_object('ok',false,'error','channel_not_ready_for_ana');
  END IF;
  UPDATE public.whatsapp_channel_runtime_v1 SET ana_enabled = p_enabled, updated_at = now()
    WHERE whatsapp_account_id = p_whatsapp_account_id RETURNING whatsapp_account_id INTO changed_id;
  IF changed_id IS NULL THEN RETURN jsonb_build_object('ok',false,'error','channel_not_found'); END IF;
  SELECT right(regexp_replace(coalesce(a.phone_e164,''),'\\D','','g'),4) INTO channel_suffix
    FROM public.whatsapp_accounts a WHERE a.id = changed_id;
  INSERT INTO private.whatsapp_ana_admin_events_v1(action,actor_id,channel_key,detail)
    VALUES('channel_toggled',p_actor_id,channel_suffix,jsonb_build_object('ana_enabled',p_enabled));
  RETURN jsonb_build_object('ok',true,'channel_key',channel_suffix,'ana_enabled',p_enabled);
END;
$$;
REVOKE ALL ON FUNCTION public.ops2_ana_admin_set_channel_v1(uuid,boolean,uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.ops2_ana_admin_set_channel_v1(uuid,boolean,uuid) TO service_role;

ALTER TABLE public.attendance_conversation_auto_labels_v1
  DROP CONSTRAINT IF EXISTS attendance_conversation_auto_labels_v1_source_check;
ALTER TABLE public.attendance_conversation_auto_labels_v1
  ADD CONSTRAINT attendance_conversation_auto_labels_v1_source_check
  CHECK (source_kind IN ('delivery_schedule','product_purchase','ana_trigger'));

CREATE OR REPLACE FUNCTION public.ops2_ana_apply_trigger_label_v1(p_conversation_id uuid,p_label_id uuid,p_trigger_key text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE label_source uuid; inserted_count integer:=0;
BEGIN
  IF p_conversation_id IS NULL OR p_label_id IS NULL OR btrim(coalesce(p_trigger_key,''))='' OR char_length(p_trigger_key)>40 THEN
    RETURN jsonb_build_object('ok',false,'error','trigger_label_input_invalid');
  END IF;
  IF NOT EXISTS(SELECT 1 FROM public.conversations WHERE id=p_conversation_id) THEN
    RETURN jsonb_build_object('ok',false,'error','conversation_not_found');
  END IF;
  IF NOT EXISTS(SELECT 1 FROM public.attendance_labels_v1 WHERE id=p_label_id AND is_active=true) THEN
    RETURN jsonb_build_object('ok',false,'error','label_not_active');
  END IF;
  label_source:=md5('ana-trigger:'||p_trigger_key)::uuid;
  INSERT INTO public.attendance_conversation_auto_labels_v1(conversation_id,label_id,source_kind,source_ref)
    VALUES(p_conversation_id,p_label_id,'ana_trigger',label_source) ON CONFLICT DO NOTHING;
  GET DIAGNOSTICS inserted_count=ROW_COUNT;
  INSERT INTO public.attendance_conversation_labels_v1(conversation_id,label_id)
    VALUES(p_conversation_id,p_label_id) ON CONFLICT DO NOTHING;
  RETURN jsonb_build_object('ok',true,'applied',inserted_count>0);
END;
$$;
REVOKE ALL ON FUNCTION public.ops2_ana_apply_trigger_label_v1(uuid,uuid,text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.ops2_ana_apply_trigger_label_v1(uuid,uuid,text) TO service_role;

CREATE OR REPLACE FUNCTION public.ops2_ana_admin_record_test_run_v1(
  p_draft_revision bigint,p_scenario_keys text[],p_passed_count integer,p_failed_count integer,
  p_safe_reasons jsonb,p_latency_ms integer,p_actor_id uuid
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, private AS $$
DECLARE run_id uuid;
BEGIN
  IF p_draft_revision IS NULL OR p_draft_revision<1 OR coalesce(cardinality(p_scenario_keys),0)>20
     OR p_passed_count IS NULL OR p_failed_count IS NULL OR p_passed_count<0 OR p_failed_count<0
     OR p_passed_count+p_failed_count>20 OR coalesce(p_latency_ms,0)<0 THEN
    RETURN jsonb_build_object('ok',false,'error','test_run_input_invalid');
  END IF;
  IF p_safe_reasons IS NULL OR jsonb_typeof(p_safe_reasons)<>'array' THEN
    RETURN jsonb_build_object('ok',false,'error','test_run_privacy_input_invalid');
  END IF;
  IF jsonb_array_length(p_safe_reasons)>20 THEN
    RETURN jsonb_build_object('ok',false,'error','test_run_input_invalid');
  END IF;
  IF EXISTS(SELECT 1 FROM jsonb_array_elements(p_safe_reasons) AS items(value) WHERE jsonb_typeof(items.value)<>'string' OR length(items.value#>>'{}')>80)
     OR EXISTS(SELECT 1 FROM unnest(coalesce(p_scenario_keys,'{}'::text[])) k WHERE k !~ '^[a-z0-9][a-z0-9_-]{0,39}$') THEN
    RETURN jsonb_build_object('ok',false,'error','test_run_privacy_input_invalid');
  END IF;
  INSERT INTO private.whatsapp_ana_admin_test_runs_v1(draft_revision,scenario_keys,passed_count,failed_count,safe_reasons,latency_ms,actor_id)
    VALUES(p_draft_revision,coalesce(p_scenario_keys,'{}'::text[]),p_passed_count,p_failed_count,p_safe_reasons,p_latency_ms,p_actor_id)
    RETURNING id INTO run_id;
  RETURN jsonb_build_object('ok',true,'id',run_id,'draft_revision',p_draft_revision,'passed_count',p_passed_count,'failed_count',p_failed_count);
END;
$$;
REVOKE ALL ON FUNCTION public.ops2_ana_admin_record_test_run_v1(bigint,text[],integer,integer,jsonb,integer,uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.ops2_ana_admin_record_test_run_v1(bigint,text[],integer,integer,jsonb,integer,uuid) TO service_role;

COMMIT;
