create or replace function public.basket_lot_admin_allowed_v1() returns boolean language sql stable security definer set search_path to '' as $$select exists(select 1 from public.admin_users a where a.user_id=auth.uid() and a.is_active=true);$$;

create or replace function public.basket_lot_suggestions_admin_v1(p_status text default 'pending') returns jsonb language plpgsql security definer set search_path to '' as $$
declare v_result jsonb;begin
if not public.basket_lot_admin_allowed_v1() then raise exception 'admin_forbidden';end if;
select jsonb_build_object('ok',true,'settings',(select to_jsonb(x) from public.basket_lot_automation_settings x where id=1),'rules',coalesce((select jsonb_agg(to_jsonb(r) order by r.sort_order,r.label) from public.basket_lot_substitution_rules r),'[]'::jsonb),'suggestions',coalesce((select jsonb_agg(sj order by (sj->>'suggestion_date')::date desc,sj->>'basket_name') from (select jsonb_build_object('id',s.id,'basket_id',s.basket_id,'basket_name',b.name,'basket_image_url',b.image_url,'suggestion_date',s.suggestion_date,'status',s.status,'buildability_status',s.buildability_status,'quantity_planned',s.quantity_planned,'sale_price',s.sale_price,'component_sum',s.component_sum,'hidden_adjustment',s.hidden_adjustment,'price_variation_pct_snapshot',s.price_variation_pct_snapshot,'issues',s.issues,'created_at',s.created_at,'updated_at',s.updated_at,'reviewed_at',s.reviewed_at,'reviewed_by',s.reviewed_by,'approved_lot_id',s.approved_lot_id,'items',coalesce((select jsonb_agg(jsonb_build_object('id',i.id,'template_item_id',i.template_item_id,'original_product_id',i.original_product_id,'suggested_product_id',i.suggested_product_id,'quantity_per_basket',i.quantity_per_basket,'position_order',i.position_order,'original_unit_price',i.original_unit_price,'suggested_unit_price',i.suggested_unit_price,'price_delta_pct',i.price_delta_pct,'is_substituted',i.is_substituted,'substitution_family',i.substitution_family,'substitution_reason',i.substitution_reason,'loose_stock_snapshot',i.loose_stock_snapshot,'stock_ok_snapshot',i.stock_ok_snapshot,'original_product',jsonb_build_object('id',op.id,'name',op.name,'sku',op.sku,'gtin',op.gtin,'packaging',op.packaging,'price',op.price,'image_url',op.image_url),'suggested_product',jsonb_build_object('id',sp.id,'name',sp.name,'sku',sp.sku,'gtin',sp.gtin,'packaging',sp.packaging,'price',sp.price,'image_url',sp.image_url,'loose_stock',coalesce(ls.loose_sellable_stock,0))) order by i.position_order,i.id) from public.basket_lot_suggestion_items i join public.products op on op.id=i.original_product_id join public.products sp on sp.id=i.suggested_product_id left join public.ops2_loose_sellable_stock_v1 ls on ls.product_id=sp.id where i.suggestion_id=s.id),'[]'::jsonb)) sj from public.basket_lot_suggestions s join public.basket_templates b on b.id=s.basket_id where p_status is null or p_status='' or s.status=p_status order by s.suggestion_date desc,s.created_at desc limit 100) q),'[]'::jsonb)) into v_result;return v_result;end;$$;

create or replace function public.basket_lot_suggestion_save_v1(p_suggestion_id uuid,p_quantity integer,p_items jsonb,p_operator text default null) returns jsonb language plpgsql security definer set search_path to '' as $$
declare s public.basket_lot_suggestions%rowtype;it record;ov jsonb;pid uuid;p record;avail numeric;required numeric;component numeric:=0;issues jsonb:='[]'::jsonb;buildable boolean:=true;orig record;delta numeric;is_sub boolean;fam text;req record;
begin if not public.basket_lot_admin_allowed_v1() then raise exception 'admin_forbidden';end if;if coalesce(p_quantity,0)<1 or p_quantity>500 then raise exception 'invalid_lot_quantity';end if;if jsonb_typeof(coalesce(p_items,'[]'::jsonb))<>'array' then raise exception 'invalid_items';end if;select * into s from public.basket_lot_suggestions where id=p_suggestion_id for update;if not found then raise exception 'suggestion_not_found';end if;if s.status<>'pending' then raise exception 'suggestion_not_pending';end if;
for it in select * from public.basket_lot_suggestion_items where suggestion_id=s.id order by position_order,id loop select value into ov from jsonb_array_elements(p_items) x(value) where x.value->>'id'=it.id::text limit 1;begin pid:=coalesce(nullif(ov->>'suggested_product_id','')::uuid,it.suggested_product_id);exception when others then raise exception 'invalid_product';end;select id,name,price,packaging,subcategory,is_active into p from public.products where id=pid;if not found or p.is_active<>true then raise exception 'product_unavailable';end if;select id,name,price,packaging,subcategory into orig from public.products where id=it.original_product_id;select coalesce(loose_sellable_stock,0) into avail from public.ops2_loose_sellable_stock_v1 where product_id=pid;avail:=coalesce(avail,0);required:=it.quantity_per_basket*p_quantity;is_sub:=pid<>it.original_product_id;fam:=public.basket_substitution_family_v1(orig.name,orig.subcategory);delta:=case when coalesce(orig.price,0)>0 then round(((coalesce(p.price,0)-orig.price)/orig.price*100)::numeric,3) else null end;update public.basket_lot_suggestion_items set suggested_product_id=pid,suggested_unit_price=coalesce(p.price,0),price_delta_pct=delta,is_substituted=is_sub,substitution_family=fam,substitution_reason=case when is_sub then 'Alteração manual no Admin.' else null end,loose_stock_snapshot=avail,stock_ok_snapshot=avail>=required,updated_at=now(),metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('manual_edit',true,'edited_by',coalesce(nullif(trim(p_operator),''),'Operação')) where id=it.id;component:=component+coalesce(p.price,0)*it.quantity_per_basket;if avail<required then buildable:=false;issues:=issues||jsonb_build_array(jsonb_build_object('type','insufficient_stock','product_id',pid,'product_name',p.name,'available',avail,'required',required));end if;end loop;
for req in select i.suggested_product_id,sum(i.quantity_per_basket*p_quantity)::numeric required,max(coalesce(ls.loose_sellable_stock,0))::numeric available,max(p.name) product_name from public.basket_lot_suggestion_items i join public.products p on p.id=i.suggested_product_id left join public.ops2_loose_sellable_stock_v1 ls on ls.product_id=i.suggested_product_id where i.suggestion_id=s.id group by i.suggested_product_id having sum(i.quantity_per_basket*p_quantity)>max(coalesce(ls.loose_sellable_stock,0)) loop update public.basket_lot_suggestion_items set stock_ok_snapshot=false,updated_at=now() where suggestion_id=s.id and suggested_product_id=req.suggested_product_id;buildable:=false;issues:=issues||jsonb_build_array(jsonb_build_object('type','cumulative_stock_shortage','product_id',req.suggested_product_id,'product_name',req.product_name,'available',req.available,'required',req.required));end loop;
update public.basket_lot_suggestions set quantity_planned=p_quantity,component_sum=round(component,2),hidden_adjustment=round(s.sale_price-component,2),buildability_status=case when buildable then 'ready' else 'attention' end,issues=issues,updated_at=now(),metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('manual_edit',true,'edited_by',coalesce(nullif(trim(p_operator),''),'Operação')) where id=s.id;return jsonb_build_object('ok',true,'id',s.id,'buildability_status',case when buildable then 'ready' else 'attention' end,'issues',issues);end;$$;

create or replace function public.basket_lot_suggestion_approve_v1(p_suggestion_id uuid,p_operator text default null) returns jsonb language plpgsql security definer set search_path to '' as $$
declare s public.basket_lot_suggestions%rowtype;items jsonb;res jsonb;lot_id uuid;begin if not public.basket_lot_admin_allowed_v1() then raise exception 'admin_forbidden';end if;select * into s from public.basket_lot_suggestions where id=p_suggestion_id for update;if not found then raise exception 'suggestion_not_found';end if;if s.status<>'pending' then raise exception 'suggestion_not_pending';end if;select coalesce(jsonb_agg(jsonb_build_object('product_id',i.suggested_product_id,'template_item_id',i.template_item_id,'quantity_per_basket',i.quantity_per_basket,'position_order',i.position_order,'substitution_reason',i.substitution_reason,'template_product_id',i.original_product_id,'is_substitution',i.is_substituted) order by i.position_order,i.id),'[]'::jsonb) into items from public.basket_lot_suggestion_items i where i.suggestion_id=s.id;res:=public.create_basket_stock_lot_v1(s.basket_id,s.quantity_planned,items,coalesce(nullif(trim(p_operator),''),'Operação'),'Lote criado a partir da sugestão automática '||s.id::text,'admin',false);lot_id:=nullif(res->>'lot_id','')::uuid;update public.basket_lot_suggestions set status='approved',reviewed_at=now(),reviewed_by=coalesce(nullif(trim(p_operator),''),'Operação'),approved_lot_id=lot_id,updated_at=now() where id=s.id;return jsonb_build_object('ok',true,'suggestion_id',s.id,'lot',res);end;$$;
create or replace function public.basket_lot_suggestion_reject_v1(p_suggestion_id uuid,p_operator text default null) returns jsonb language plpgsql security definer set search_path to '' as $$begin if not public.basket_lot_admin_allowed_v1() then raise exception 'admin_forbidden';end if;update public.basket_lot_suggestions set status='rejected',reviewed_at=now(),reviewed_by=coalesce(nullif(trim(p_operator),''),'Operação'),updated_at=now() where id=p_suggestion_id and status='pending';if not found then raise exception 'suggestion_not_pending';end if;return jsonb_build_object('ok',true,'suggestion_id',p_suggestion_id);end;$$;
create or replace function public.basket_lot_suggestion_generate_now_v1() returns jsonb language plpgsql security definer set search_path to '' as $$begin if not public.basket_lot_admin_allowed_v1() then raise exception 'admin_forbidden';end if;return public.generate_basket_lot_suggestions_v1(null,'admin_manual',true);end;$$;
create or replace function public.basket_lot_automation_settings_admin_v1(p_enabled boolean,p_lot_quantity integer,p_price_variation_pct numeric,p_enabled_families text[],p_operator text default null) returns jsonb language plpgsql security definer set search_path to '' as $$begin if not public.basket_lot_admin_allowed_v1() then raise exception 'admin_forbidden';end if;return public.update_basket_lot_automation_settings_v1(p_enabled,p_lot_quantity,p_price_variation_pct,p_enabled_families,p_operator);end;$$;

revoke all on function public.basket_lot_admin_allowed_v1(),public.basket_lot_suggestions_admin_v1(text),public.basket_lot_suggestion_save_v1(uuid,integer,jsonb,text),public.basket_lot_suggestion_approve_v1(uuid,text),public.basket_lot_suggestion_reject_v1(uuid,text),public.basket_lot_suggestion_generate_now_v1(),public.basket_lot_automation_settings_admin_v1(boolean,integer,numeric,text[],text) from public,anon;
grant execute on function public.basket_lot_admin_allowed_v1(),public.basket_lot_suggestions_admin_v1(text),public.basket_lot_suggestion_save_v1(uuid,integer,jsonb,text),public.basket_lot_suggestion_approve_v1(uuid,text),public.basket_lot_suggestion_reject_v1(uuid,text),public.basket_lot_suggestion_generate_now_v1(),public.basket_lot_automation_settings_admin_v1(boolean,integer,numeric,text[],text) to authenticated,service_role;
