import { FIREBASE_BASE, MUG_NODES, text, norm, digits, money, safeKey, fbGet, fbWrite, nowIso } from '../shared/mug-commerce-v1.js?v=20260828-1';

const BUILD='20260828-canecafacil-enhancements-v2';
const ENGAGEMENT_NODE='canecas/engajamento';
const FAQ_NODE='canecas/perguntas_padrao';
const COUPON_NODE='canecas/cupons';
const DEVICE_KEY='canecafacil_device_v1';
const FAVORITES_KEY='canecafacil_favorites_v1';
const RATINGS_KEY='canecafacil_ratings_v1';
const COUPON_SESSION='canecafacil_coupon_v1';
const BASE_PATH='/canecafacil/';
const nativeFetch=window.fetch.bind(window);
const priorOpen=window.open.bind(window);
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const readLocal=(k,f)=>{try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch{return f}};
const writeLocal=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const readSession=(k,f)=>{try{const v=sessionStorage.getItem(k);return v?JSON.parse(v):f}catch{return f}};
const writeSession=(k,v)=>{try{sessionStorage.setItem(k,JSON.stringify(v))}catch{}};
const state={products:new Map(),engagement:{},standardFaq:{},manifest:{},activeCoupon:null,lastOrder:null};
let productFlagsResolve; const productFlagsReady=new Promise(r=>productFlagsResolve=r); let productFlagsDone=false;

function slugify(v){return norm(v).replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,90)||'caneca'}
function productKey(p={}){return text(p.firebaseKey||p.id||p.__key)}
function themeOf(p={}){return text(p.canecafacil_tema||p.tema_caneca||p.subcategoria||p.subsubcategoria||p.categoria||'Canecas')}
function productSlug(p={}){return text(p.canecafacil_slug)||slugify(p.nome||productKey(p))}
function offerActive(p={}){const price=Number(p.preco_oferta||0);if(!(price>0))return false;const expires=text(p.validade_oferta||p.oferta_validade||'');if(!expires)return true;const d=/^\d{2}\/\d{2}\/\d{4}$/.test(expires)?new Date(expires.split('/').reverse().join('-')+'T23:59:59'):new Date(expires);return Number.isNaN(d.getTime())||d.getTime()>=Date.now()}
function basePrice(p={}){return Number(p.preco||p.price||0)}
function salePrice(p={}){return offerActive(p)?Number(p.preco_oferta):basePrice(p)}
function friendlyUrl(p){return `${location.origin}${BASE_PATH}caneca/${encodeURIComponent(productSlug(p))}/`}
function rawImages(p={}){const arr=[p.mockup_1,p.mockup_2,...(Array.isArray(p.imagens_site)?p.imagens_site:[]),...(Array.isArray(p.imagens)?p.imagens:[]),p.url_imagem,p.imagem,p.imagem_url].map(text).filter(v=>/^https?:\/\//i.test(v)||/^data:image\//i.test(v));return [...new Set(arr)].slice(0,2)}
function artUrl(p={}){return text(p.arte_horizontal||p.arte_personalizacao||p.arte_impressao?.url||p.arte_final_url)}
function manifestImages(key,p){const m=state.manifest?.[key]||{};const mockups=(Array.isArray(m.mockups)?m.mockups:[]).map(v=>new URL(v,location.origin).href);return mockups.length?mockups.slice(0,2):rawImages(p)}
function manifestArt(key,p){const m=state.manifest?.[key]||{};return m.art?new URL(m.art,location.origin).href:artUrl(p)}
function metric(key){return state.engagement?.[key]||{}}
function favCount(key){return Math.max(0,Number(metric(key).favoritos||0))}
function ratingCount(key){return Math.max(0,Number(metric(key).avaliacao_qtd||0))}
function ratingAvg(key){const n=ratingCount(key);return n?Number(metric(key).avaliacao_soma||0)/n:0}
function localFav(key){return Boolean(readLocal(FAVORITES_KEY,{})?.[key])}
function localRating(key){return Number(readLocal(RATINGS_KEY,{})?.[key]||0)}
function setMeta(name,content,attr='name'){let el=document.head.querySelector(`meta[${attr}="${name}"]`);if(!el){el=document.createElement('meta');el.setAttribute(attr,name);document.head.appendChild(el)}el.content=content||''}
function setCanonical(url){let el=document.head.querySelector('link[rel="canonical"]');if(!el){el=document.createElement('link');el.rel='canonical';document.head.appendChild(el)}el.href=url}

window.fetch=async function(input,init={}){
  const url=String(input?.url||input||'');
  const method=String(init?.method||input?.method||'GET').toUpperCase();
  if(method==='GET'&&url.includes('/produtos.json')){
    const res=await nativeFetch(input,init); const data=await res.clone().json().catch(()=>null);
    if(data&&typeof data==='object'){
      Object.entries(data).forEach(([k,p])=>{if(!p||typeof p!=='object')return;const explicit=p.canecafacil_personalizavel;if(explicit===false||explicit==='false'){p.personalizacao_publica=false;p.personalizavel=false}p.__key=k;state.products.set(k,p)});
      if(!productFlagsDone){productFlagsDone=true;productFlagsResolve()}
      return new Response(JSON.stringify(data),{status:res.status,statusText:res.statusText,headers:{'Content-Type':'application/json; charset=utf-8'}});
    }
    if(!productFlagsDone){productFlagsDone=true;productFlagsResolve()}
    return res;
  }
  if(method==='GET'&&url.includes('/canecas/modelos_criacao.json')){
    const res=await nativeFetch(input,init); const data=await res.clone().json().catch(()=>null); await Promise.race([productFlagsReady,new Promise(r=>setTimeout(r,2500))]);
    if(data&&typeof data==='object'){
      Object.keys(data).forEach(k=>{const p=state.products.get(k);if(p&&(p.canecafacil_personalizavel===false||p.canecafacil_personalizavel==='false'))delete data[k]});
      return new Response(JSON.stringify(data),{status:res.status,statusText:res.statusText,headers:{'Content-Type':'application/json; charset=utf-8'}});
    }
    return res;
  }
  if(method==='PUT'&&/\/canecas\/pedidos\/[^/]+\.json(?:\?|$)/.test(url)&&typeof init.body==='string'){
    try{
      const order=JSON.parse(init.body); const key=text(order?.itens?.[0]?.firebaseKey||order?.itens?.[0]?.id); const coupon=state.activeCoupon&&state.activeCoupon.productKey===key?state.activeCoupon:null;
      const token=crypto.randomUUID?.().replace(/-/g,'')||`${Date.now().toString(36)}${Math.random().toString(36).slice(2)}`;
      order.cadastro_token=token; order.cadastro_status='pendente'; order.cadastro_url=`${location.origin}${BASE_PATH}cadastro.html?pedido=${encodeURIComponent(order.id)}&token=${encodeURIComponent(token)}`;
      if(coupon){const subtotal=Number(order.subtotal||0);const discount=coupon.type==='fixed'?Math.min(subtotal,coupon.value):subtotal*Math.min(100,coupon.value)/100;order.cupom={codigo:coupon.code,tipo:coupon.type,valor:coupon.value,desconto:Number(discount.toFixed(2))};order.desconto=Number(discount.toFixed(2));order.subtotal_original=subtotal;order.total=Math.max(0,Number((subtotal-discount+Number(order.frete?.valor||0)).toFixed(2)));order.itens=(order.itens||[]).map(it=>({...it,subtotal_original:Number(it.subtotal||0),desconto_rateado:Number(discount.toFixed(2)),subtotal_com_desconto:Math.max(0,Number((Number(it.subtotal||0)-discount).toFixed(2)))}))}
      state.lastOrder=order; window.__CF_LAST_ORDER__=order; init={...init,body:JSON.stringify(order)};
    }catch(e){console.debug('[CanecaFácil] enriquecimento de pedido:',e)}
  }
  return nativeFetch(input,init);
};

window.open=function(url,target,features){
  let next=String(url||'');
  if(/^https:\/\/wa\.me\//i.test(next)&&state.lastOrder){
    try{const u=new URL(next);let msg=decodeURIComponent(u.searchParams.get('text')||'');const o=state.lastOrder;if(o.cupom){msg=msg.replace(/Total estimado:[^\n]*/i,`Total antes do cupom: ${money(Number(o.subtotal_original||0)+Number(o.frete?.valor||0))}`);msg+=`\nCupom: ${o.cupom.codigo} · desconto ${money(o.cupom.desconto)}\nTotal com desconto: ${money(o.total)}`;}msg+=`\nCadastro para finalizar: ${o.cadastro_url}`;u.searchParams.set('text',msg);next=u.toString()}catch{}
  }
  return priorOpen(next,target,features);
};

async function loadExtras(){
  const [eng,faq,manifest]=await Promise.all([
    fbGet(ENGAGEMENT_NODE).catch(()=>({})),fbGet(FAQ_NODE).catch(()=>({})),nativeFetch('./image-manifest.json',{cache:'no-store'}).then(r=>r.ok?r.json():{}).catch(()=>({}))
  ]);state.engagement=eng||{};state.standardFaq=faq||{};state.manifest=manifest||{};applyAll();
}

function atomicIncrement(path,delta){return nativeFetch(`${FIREBASE_BASE}/${path}.json`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({'.sv':{increment:delta}})}).then(r=>{if(!r.ok)throw new Error(`Firebase ${r.status}`);return r.json().catch(()=>null)})}
async function toggleFavorite(key){const favs=readLocal(FAVORITES_KEY,{}),on=!Boolean(favs[key]);favs[key]=on;writeLocal(FAVORITES_KEY,favs);state.engagement[key]||={};state.engagement[key].favoritos=Math.max(0,favCount(key)+(on?1:-1));refreshEngagement(key);try{await atomicIncrement(`${ENGAGEMENT_NODE}/${safeKey(key)}/favoritos`,on?1:-1);await fbWrite(`${ENGAGEMENT_NODE}/${safeKey(key)}/atualizado_em`,nowIso(),'PUT')}catch{} }
async function rate(key,value){value=Math.max(1,Math.min(5,Number(value)));const ratings=readLocal(RATINGS_KEY,{}),prev=Number(ratings[key]||0);ratings[key]=value;writeLocal(RATINGS_KEY,ratings);state.engagement[key]||={};state.engagement[key].avaliacao_soma=Number(metric(key).avaliacao_soma||0)+(value-prev);if(!prev)state.engagement[key].avaliacao_qtd=ratingCount(key)+1;refreshEngagement(key);try{await Promise.all([atomicIncrement(`${ENGAGEMENT_NODE}/${safeKey(key)}/avaliacao_soma`,value-prev),prev?Promise.resolve():atomicIncrement(`${ENGAGEMENT_NODE}/${safeKey(key)}/avaliacao_qtd`,1),fbWrite(`${ENGAGEMENT_NODE}/${safeKey(key)}/ultima_avaliacao_em`,nowIso(),'PUT')])}catch{} }
async function shareProduct(key,channel='share'){const p=state.products.get(key);if(!p)return;const url=friendlyUrl(p),title=p.nome||'CanecaFácil',img=manifestImages(key,p)[0]||rawImages(p)[0]||'';try{if(channel==='pinterest'){const pin=`https://www.pinterest.com/pin/create/button/?url=${encodeURIComponent(url)}&media=${encodeURIComponent(img)}&description=${encodeURIComponent(`${title} — caneca de porcelana personalizada CanecaFácil`)}`;priorOpen(pin,'_blank','noopener');await atomicIncrement(`${ENGAGEMENT_NODE}/${safeKey(key)}/pinterest`,1).catch(()=>{});return}if(navigator.share)await navigator.share({title,text:'Veja esta caneca no CanecaFácil',url});else{await navigator.clipboard.writeText(url);toastMini('Link copiado.')}await atomicIncrement(`${ENGAGEMENT_NODE}/${safeKey(key)}/compartilhamentos`,1).catch(()=>{})}catch(e){if(e?.name!=='AbortError')console.debug(e)}}
function toastMini(msg){const t=document.querySelector('#toast');if(!t)return;t.textContent=msg;t.hidden=false;setTimeout(()=>t.hidden=true,2200)}
function refreshEngagement(key){$$(`[data-cf-fav="${CSS.escape(key)}"]`).forEach(b=>{b.classList.toggle('on',localFav(key));b.innerHTML=`<span aria-hidden="true">${localFav(key)?'♥':'♡'}</span><b>${favCount(key)}</b>`});$$(`[data-cf-rating-summary="${CSS.escape(key)}"]`).forEach(n=>n.textContent=ratingCount(key)?`★ ${ratingAvg(key).toFixed(1)} (${ratingCount(key)})`:'☆ Seja o primeiro a avaliar');$$(`[data-cf-star][data-key="${CSS.escape(key)}"]`).forEach(b=>b.classList.toggle('on',Number(b.dataset.cfStar)<=localRating(key)))}

function enhanceCard(card){if(card.dataset.cfEnhanced)return;const key=text(card.dataset.product),p=state.products.get(key);if(!p)return;card.dataset.cfEnhanced='1';const media=card.querySelector('.product-media'),imgs=manifestImages(key,p).slice(0,2);if(media&&imgs.length){const tag=media.querySelector('.product-tag')?.outerHTML||'';media.innerHTML=`<div class="cf-card-slider" data-index="0" aria-roledescription="carousel" aria-label="Imagens de ${esc(p.nome||'caneca')}"><div class="cf-card-track">${imgs.map((src,i)=>`<img class="cf-card-slide ${i===0?'active':''}" loading="lazy" decoding="async" draggable="false" src="${esc(src)}" alt="${esc(p.nome||'Caneca')} — vista ${i+1}" data-pin-nopin>`).join('')}</div>${imgs.length>1?`<button class="cf-arrow prev" type="button" aria-label="Imagem anterior">‹</button><button class="cf-arrow next" type="button" aria-label="Próxima imagem">›</button><div class="cf-dots" aria-hidden="true">${imgs.map((_,i)=>`<i class="${i===0?'active':''}"></i>`).join('')}</div><span class="sr-only" aria-live="polite">Imagem 1 de ${imgs.length}</span>`:''}</div>${tag}`;bindSlider(media.querySelector('.cf-card-slider'))}
  const info=card.querySelector('.product-info');if(info&&!info.querySelector('.cf-card-engagement')){const div=document.createElement('div');div.className='cf-card-engagement';div.innerHTML=`<button type="button" class="cf-fav" data-cf-fav="${esc(key)}" aria-label="Favoritar"></button><span data-cf-rating-summary="${esc(key)}"></span>`;info.appendChild(div);div.querySelector('.cf-fav').onclick=e=>{e.stopPropagation();toggleFavorite(key)};refreshEngagement(key)}
}
function bindSlider(slider){if(!slider||slider.dataset.bound)return;slider.dataset.bound='1';const slides=$$('.cf-card-slide',slider),dots=$$('.cf-dots i',slider),live=$('.sr-only',slider);let idx=0,startX=0;const go=n=>{idx=(n+slides.length)%slides.length;slider.dataset.index=idx;slides.forEach((s,i)=>s.classList.toggle('active',i===idx));dots.forEach((d,i)=>d.classList.toggle('active',i===idx));if(live)live.textContent=`Imagem ${idx+1} de ${slides.length}`};$('.prev',slider)?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();go(idx-1)});$('.next',slider)?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();go(idx+1)});slider.addEventListener('touchstart',e=>{startX=e.changedTouches[0]?.clientX||0},{passive:true});slider.addEventListener('touchend',e=>{const dx=(e.changedTouches[0]?.clientX||0)-startX;if(Math.abs(dx)>36)go(idx+(dx<0?1:-1))},{passive:true})}

function faqFor(p){const selected=p.canecafacil_perguntas_padrao&&typeof p.canecafacil_perguntas_padrao==='object'?p.canecafacil_perguntas_padrao:{};const standard=Object.entries(selected).filter(([,cfg])=>cfg===true||cfg?.ativo===true).map(([id,cfg])=>{const base=state.standardFaq[id]||{};return{q:text(base.pergunta||cfg?.pergunta),a:text(cfg?.resposta||base.resposta)}}).filter(x=>x.q&&x.a);const custom=(Array.isArray(p.canecafacil_faq_custom)?p.canecafacil_faq_custom:[]).filter(x=>x&&x.ativo!==false&&text(x.pergunta)&&text(x.resposta)).map(x=>({q:text(x.pergunta),a:text(x.resposta)}));return [...standard,...custom]}
function injectFaq(p){if(document.querySelector('#cfFaq'))return;const list=faqFor(p);if(!list.length)return;const section=document.createElement('section');section.id='cfFaq';section.className='section cf-faq';section.innerHTML=`<div class="section-head"><div><h2>Perguntas frequentes</h2><p>Informações deste modelo.</p></div></div><div class="cf-faq-list">${list.map((x,i)=>`<details ${i===0?'open':''}><summary>${esc(x.q)}</summary><p>${esc(x.a)}</p></details>`).join('')}</div>`;document.querySelector('.product-page')?.after(section)}

function enhanceProductPage(){const match=location.hash.match(/^#\/produto\/([^/?#]+)/);if(!match)return;const key=decodeURIComponent(match[1]),p=state.products.get(key);if(!p)return;const page=document.querySelector('.product-page');if(!page||page.dataset.cfEnhanced===key)return;page.dataset.cfEnhanced=key;
  const gallery=page.querySelector('.gallery'),mockups=manifestImages(key,p).slice(0,2),art=manifestArt(key,p);if(gallery){gallery.className='cf-product-gallery';gallery.innerHTML=`<div class="cf-main-view" data-index="0" aria-roledescription="carousel" aria-label="Fotos do produto"><div class="cf-main-track">${mockups.map((src,i)=>`<img class="cf-main-slide ${i===0?'active':''}" src="${esc(src)}" loading="eager" decoding="async" draggable="false" data-pin-nopin alt="${esc(p.nome||'Caneca')} — mockup ${i+1}">`).join('')||'<div class="hero-placeholder">☕</div>'}</div>${mockups.length>1?`<button class="cf-arrow prev" type="button" aria-label="Imagem anterior">‹</button><button class="cf-arrow next" type="button" aria-label="Próxima imagem">›</button><div class="cf-counter">1 / ${mockups.length}</div>`:''}</div>${mockups.length>1?`<div class="cf-thumbs">${mockups.map((src,i)=>`<button type="button" class="${i===0?'active':''}" data-thumb="${i}"><img src="${esc(src)}" draggable="false" data-pin-nopin alt="Miniatura ${i+1}"></button>`).join('')}</div>`:''}${art?`<div class="cf-art-panel"><div><strong>Arte horizontal da estampa</strong><span>Visualização em proporção real da personalização.</span></div><div class="cf-art-protected"><img src="${esc(art)}" loading="lazy" decoding="async" draggable="false" data-pin-nopin alt="Arte horizontal de ${esc(p.nome||'caneca')}"><i aria-hidden="true"></i></div></div>`:''}`;bindProductSlider(gallery)}
  const note=page.querySelector('.personal-note');if(note){note.innerHTML=`<strong>${esc(p.canecafacil_personalizacao_titulo||'Quer colocar seu toque?')}</strong><br>${esc(p.canecafacil_personalizacao_texto||'Gere somente a arte horizontal. Você poderá pedir até 3 ajustes antes de encomendar.')}`}
  injectEngagementPanel(p,key);injectCoupon(p,key);injectFaq(p);updateSeo(p,key);
}
function bindProductSlider(gallery){const root=gallery.querySelector('.cf-main-view');if(!root)return;const slides=$$('.cf-main-slide',root),thumbs=$$('[data-thumb]',gallery),counter=$('.cf-counter',root);let idx=0;const go=n=>{idx=(n+slides.length)%slides.length;slides.forEach((s,i)=>s.classList.toggle('active',i===idx));thumbs.forEach((b,i)=>b.classList.toggle('active',i===idx));if(counter)counter.textContent=`${idx+1} / ${slides.length}`};$('.prev',root)?.addEventListener('click',()=>go(idx-1));$('.next',root)?.addEventListener('click',()=>go(idx+1));thumbs.forEach(b=>b.onclick=()=>go(Number(b.dataset.thumb)));root.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')go(idx-1);if(e.key==='ArrowRight')go(idx+1)})}
function injectEngagementPanel(p,key){const panel=document.querySelector('.product-panel');if(!panel||panel.querySelector('.cf-engagement'))return;const price=panel.querySelector('.price-big');const div=document.createElement('div');div.className='cf-engagement';div.innerHTML=`<div class="cf-stars" aria-label="Avalie esta arte">${[1,2,3,4,5].map(v=>`<button type="button" data-cf-star="${v}" data-key="${esc(key)}" aria-label="${v} estrela${v>1?'s':''}">★</button>`).join('')}<span data-cf-rating-summary="${esc(key)}"></span></div><div class="cf-social-actions"><button class="cf-fav" type="button" data-cf-fav="${esc(key)}" aria-label="Favoritar"></button><button type="button" data-cf-share="${esc(key)}">Compartilhar</button><button type="button" class="pinterest" data-cf-pin="${esc(key)}">Pinterest</button></div>`;price?.after(div);$$('[data-cf-star]',div).forEach(b=>b.onclick=()=>rate(key,b.dataset.cfStar));$('[data-cf-fav]',div).onclick=()=>toggleFavorite(key);$('[data-cf-share]',div).onclick=()=>shareProduct(key);$('[data-cf-pin]',div).onclick=()=>shareProduct(key,'pinterest');refreshEngagement(key)}
function couponBoxHtml(){return `<div class="cf-coupon"><strong>Tem cupom?</strong><div><input id="cfCouponInput" autocomplete="off" maxlength="24" placeholder="Digite o código"><button type="button" id="cfCouponApply">Aplicar</button></div><p id="cfCouponStatus"></p></div>`}
function injectCoupon(p,key){const panel=document.querySelector('.product-panel');if(!panel||panel.querySelector('.cf-coupon'))return;const divider=[...panel.querySelectorAll('.divider')].pop();const wrap=document.createElement('div');wrap.innerHTML=couponBoxHtml();divider?.before(wrap.firstElementChild);const saved=readSession(COUPON_SESSION,null);if(saved?.productKey===key){state.activeCoupon=saved;$('#cfCouponInput').value=saved.code;showCouponStatus(p,saved)}$('#cfCouponApply')?.addEventListener('click',()=>applyCoupon(p,key))}
async function applyCoupon(p,key){const code=text($('#cfCouponInput')?.value).toUpperCase().replace(/[^A-Z0-9_-]/g,'');const status=$('#cfCouponStatus');if(!code){state.activeCoupon=null;writeSession(COUPON_SESSION,null);status.textContent='';return}status.textContent='Validando cupom…';try{const c=await fbGet(`${COUPON_NODE}/${safeKey(code)}`);if(!c||c.ativo===false)throw new Error('Cupom inválido ou inativo.');const expires=text(c.validade||c.expira_em);if(expires&&new Date(expires).getTime()<Date.now())throw new Error('Este cupom expirou.');const min=Number(c.valor_minimo||0),subtotal=salePrice(p)*Number($('#qtyValue')?.textContent||1);if(subtotal<min)throw new Error(`Valor mínimo ${money(min)}.`);const coupon={code,type:text(c.tipo||'percent')==='fixed'?'fixed':'percent',value:Number(c.valor||c.percentual||0),productKey:key};if(!(coupon.value>0))throw new Error('Cupom sem desconto configurado.');state.activeCoupon=coupon;writeSession(COUPON_SESSION,coupon);showCouponStatus(p,coupon)}catch(e){state.activeCoupon=null;writeSession(COUPON_SESSION,null);status.textContent=e.message||String(e);status.className='bad'}}
function showCouponStatus(p,c){const subtotal=salePrice(p)*Number($('#qtyValue')?.textContent||1),discount=c.type==='fixed'?Math.min(subtotal,c.value):subtotal*Math.min(100,c.value)/100;const status=$('#cfCouponStatus');if(status){status.className='good';status.textContent=`Cupom ${c.code} aplicado: -${money(discount)} no produto.`}}

function updateSeo(p,key){const title=text(p.seo_titulo)||`${p.nome||'Caneca de porcelana personalizada'} | CanecaFácil`;const desc=text(p.seo_descricao)||`${p.nome||'Caneca'} em porcelana. Personalize com foto, nome ou frase e encomende pelo WhatsApp com entrega para todo o Brasil.`;const url=friendlyUrl(p),img=manifestImages(key,p)[0]||rawImages(p)[0]||'';document.title=title;setMeta('description',desc);setCanonical(url);setMeta('og:title',title,'property');setMeta('og:description',desc,'property');setMeta('og:type','product','property');setMeta('og:url',url,'property');if(img)setMeta('og:image',img,'property');setMeta('twitter:card','summary_large_image');const old=document.querySelector('#cfProductSchema');old?.remove();const schema={ '@context':'https://schema.org','@type':'Product',name:p.nome||'Caneca',description:desc,image:manifestImages(key,p),sku:text(p.codigo||key),brand:{'@type':'Brand',name:'Dona Antônia'},offers:{'@type':'Offer',priceCurrency:'BRL',price:salePrice(p).toFixed(2),availability:'https://schema.org/InStock',url}};if(ratingCount(key)){schema.aggregateRating={'@type':'AggregateRating',ratingValue:ratingAvg(key).toFixed(2),reviewCount:ratingCount(key),bestRating:'5',worstRating:'1'}}const s=document.createElement('script');s.type='application/ld+json';s.id='cfProductSchema';s.textContent=JSON.stringify(schema);document.head.appendChild(s)}

function renderThemes(){const app=$('#app');if(!app||app.dataset.cfCustomRoute==='themes')return;const groups=new Map();state.products.forEach((p,key)=>{if(p.canecafacil_ativo===false)return;const t=themeOf(p);if(!groups.has(t))groups.set(t,{name:t,count:0,img:manifestImages(key,p)[0]||rawImages(p)[0]||''});groups.get(t).count++});const items=[...groups.values()].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));app.dataset.cfCustomRoute='themes';app.innerHTML=`<section class="route-title"><div class="eyebrow">Explore</div><h1>Temas</h1><p>Encontre uma caneca pelo assunto, ocasião ou estilo.</p></section><section class="section cf-theme-grid">${items.map(x=>`<button type="button" data-cf-theme="${esc(x.name)}"><span>${x.img?`<img src="${esc(x.img)}" loading="lazy" decoding="async" draggable="false" data-pin-nopin alt="Canecas ${esc(x.name)}">`:''}</span><strong>${esc(x.name)}</strong><small>${x.count} modelo(s)</small></button>`).join('')}</section>`;$$('[data-cf-theme]',app).forEach(b=>b.onclick=()=>location.hash=`#/temas/${encodeURIComponent(b.dataset.cfTheme)}`)}
function cfProductCard(p,key){const imgs=manifestImages(key,p);return `<article class="product-card" data-product="${esc(key)}"><div class="product-media" data-cf-open="${esc(key)}"><img loading="lazy" decoding="async" draggable="false" data-pin-nopin src="${esc(imgs[0]||'')}" alt="${esc(p.nome||'Caneca')}"><span class="product-tag ${p.canecafacil_personalizavel===true?'personal':''}">${p.canecafacil_personalizavel===true?'Personalize':'Caneca'}</span></div><div class="product-info"><p class="product-name">${esc(p.nome||'Caneca')}</p><div class="product-meta">${offerActive(p)?`<span class="product-price"><s>${money(basePrice(p))}</s> ${money(salePrice(p))}</span>`:`<span class="product-price">${money(salePrice(p))}</span>`}<span class="product-category">${esc(themeOf(p))}</span></div></div></article>`}
function renderCustomListing(mode,arg=''){const app=$('#app');if(!app)return;const products=[...state.products.entries()].filter(([,p])=>p.canecafacil_ativo!==false);let list=products,title='';if(mode==='offers'){list=list.filter(([,p])=>offerActive(p));title='Ofertas'}else{const target=decodeURIComponent(arg||'');list=list.filter(([,p])=>norm(themeOf(p))===norm(target));title=target||'Tema'}app.dataset.cfCustomRoute=`${mode}:${arg}`;app.innerHTML=`<section class="route-title"><div class="eyebrow">CanecaFácil</div><h1>${esc(title)}</h1><p>${mode==='offers'?'Canecas com preço especial por tempo limitado.':'Modelos selecionados deste tema.'}</p></section><section class="section" style="padding-top:18px">${list.length?`<div class="product-grid">${list.map(([k,p])=>cfProductCard(p,k)).join('')}</div>`:'<div class="empty-state">Nenhuma caneca disponível aqui no momento.</div>'}</section>`;$$('[data-cf-open]',app).forEach(el=>el.onclick=()=>location.hash=`#/produto/${encodeURIComponent(el.dataset.cfOpen)}`);setTimeout(()=>$$('.product-card',app).forEach(enhanceCard),0)}
function applyRouteOverrides(){const hash=location.hash||'#/';const app=$('#app');if(!app)return;if(hash==='#/temas'||hash==='#/temas/')return renderThemes();const tm=hash.match(/^#\/temas\/(.+)$/);if(tm)return renderCustomListing('theme',tm[1]);if(hash==='#/ofertas'||hash==='#/ofertas/')return renderCustomListing('offers');if(app.dataset.cfCustomRoute)delete app.dataset.cfCustomRoute}

function applyAll(){applyRouteOverrides();$$('.product-card').forEach(enhanceCard);enhanceProductPage()}
const observer=new MutationObserver(()=>queueMicrotask(applyAll));observer.observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('hashchange',()=>setTimeout(applyAll,0));

document.addEventListener('contextmenu',e=>{if(!e.target.closest('input,textarea,select'))e.preventDefault()});document.addEventListener('dragstart',e=>{if(e.target.closest('img,.product-media,.cf-product-gallery'))e.preventDefault()});document.addEventListener('copy',e=>{if(!e.target.closest('input,textarea'))e.preventDefault()});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&['s','u'].includes(e.key.toLowerCase())&&!e.target.closest('input,textarea'))e.preventDefault()});

document.documentElement.dataset.canecaFacilEnhancements=BUILD;
loadExtras();
