(()=>{
const $=id=>document.getElementById(id),cfg=window.DA_ADMIN_CONFIG||{},BASE=cfg.supabaseUrl,KEY=cfg.supabasePublishableKey,FN='creative-storyboard-projects';
let modules=[],seq=0;
const TYPES={opening:'Abertura / prompt',content:'Vídeo / prompt',transition_countdown:'Transição · contagem 5→1',transition_time:'Transição · passagem do tempo',closing_cta:'Encerramento / CTA'};
async function api(body){const r=await fetch(BASE+'/functions/v1/'+FN,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw Error(d.detail||d.error||'Falha na automação');return d}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function make(type='content'){return{id:++seq,type,duration:10,orientation:'',phrase:'',elapsed:'30 minutos',useProducts:false,prompt:''}}
function note(m){if(m.type==='transition_countdown')return'Prompt de transição visual 5 → 4 → 3 → 2 → 1.';if(m.type==='transition_time')return'Prompt para representar passagem rápida do tempo.';if(m.type==='closing_cta')return'Prompt de encerramento com logo, WhatsApp 98449-1018, www.donaantonia.com.br e Entrega grátis em Cuiabá e VG.';return m.useProducts?'Usará '+(window.VideoProductSelection?.getCount?.()||0)+' produto(s) selecionado(s) na outra aba.':'Este módulo será criado sem produtos.'}
function html(m,i){return '<article class="timeline-module" data-id="'+m.id+'" data-type="'+m.type+'"><div class="timeline-head"><div class="timeline-head-left"><span class="timeline-index">'+(i+1)+'</span><div><strong>'+esc(TYPES[m.type])+'</strong><div class="module-status">'+(m.prompt?'Prompt pronto':'Ainda não gerado')+'</div></div></div><div class="timeline-actions"><button data-act="up" '+(i===0?'disabled':'')+'>↑</button><button data-act="down" '+(i===modules.length-1?'disabled':'')+'>↓</button><button data-act="remove">Remover</button></div></div><div class="timeline-fields"><label class="field"><span>Tipo</span><select class="type-select" data-field="type">'+Object.entries(TYPES).map(([v,l])=>'<option value="'+v+'" '+(m.type===v?'selected':'')+'>'+l+'</option>').join('')+'</select></label><label class="field"><span>Duração</span><select class="duration-select" data-field="duration">'+[4,6,8,10].map(x=>'<option value="'+x+'" '+(m.duration===x?'selected':'')+'>'+x+' segundos</option>').join('')+'</select></label><label class="field wide"><span>Orientação</span><textarea data-field="orientation" maxlength="900" placeholder="Explique o que deve acontecer nesta etapa…">'+esc(m.orientation)+'</textarea></label><label class="field wide phrase-field"><span>Frase na tela <em>opcional</em></span><input data-field="phrase" maxlength="140" value="'+esc(m.phrase)+'" placeholder="Ex.: Aqui tem tudo para sua casa"></label><label class="field elapsed-field"><span>Tempo que deve parecer ter passado</span><input data-field="elapsed" maxlength="80" value="'+esc(m.elapsed)+'" placeholder="Ex.: 30 minutos"></label></div><label class="checkbox-row products-field"><input type="checkbox" data-field="useProducts" '+(m.useProducts?'checked':'')+'> Usar produtos selecionados no Gerador de prompt</label><div class="module-note">'+note(m)+'</div><div class="actions"><button class="primary" data-act="generate">'+(m.prompt?'Gerar nova variação':'Gerar prompt')+'</button>'+(m.prompt?'<button data-act="copy">Copiar prompt</button>':'')+'</div><div class="'+(m.prompt?'':'hidden')+'"><pre class="prompt">'+esc(m.prompt)+'</pre></div></article>'}
function render(){$('timelineTotal').textContent=modules.length+' etapa'+(modules.length===1?'':'s');$('timelineModules').innerHTML=modules.map(html).join('')}
function context(i){const p=modules[i-1],n=modules[i+1];return{position:i+1,total:modules.length,previous:p?{type:p.type,duration:p.duration,orientation:p.orientation,phrase:p.phrase}:null,next:n?{type:n.type,duration:n.duration,orientation:n.orientation,phrase:n.phrase}:null}}
async function generate(m,i,card){try{const products=m.useProducts?(window.VideoProductSelection?.getProducts?.()||[]):[];if(m.useProducts&&!products.length)throw Error('Selecione primeiro os produtos na aba Gerador de prompt.');card.querySelector('[data-act="generate"]').disabled=true;card.querySelector('.module-status').textContent='Gerando prompt com IA…';const d=await api({action:'video_timeline_prompt',module_type:m.type,duration:m.duration,orientation:m.orientation,phrase:m.phrase,elapsed_time:m.elapsed,theme:$('timelineTheme').value.trim()||window.VideoProductSelection?.getTheme?.()||'',products,context:context(i),variation:Date.now()%100000});m.prompt=d.prompt||'';render()}catch(e){card.querySelector('.module-status').textContent='Erro: '+e.message;card.querySelector('[data-act="generate"]').disabled=false}}
document.querySelectorAll('.video-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.video-tab').forEach(x=>x.classList.toggle('active',x===b));$('generatorTab').classList.toggle('hidden',b.dataset.tab!=='generator');$('timelineTab').classList.toggle('hidden',b.dataset.tab!=='timeline')});
$('createTimeline').onclick=()=>{const n=Math.max(1,Math.min(20,Math.round(Number($('timelineCount').value)||1)));modules=Array.from({length:n},(_,i)=>make(i===0?'opening':'content'));render()};
$('addTimelineModule').onclick=()=>{modules.push(make(modules.length?'content':'opening'));render()};
$('timelineModules').addEventListener('input',e=>{const card=e.target.closest('.timeline-module');if(!card)return;const m=modules.find(x=>x.id===Number(card.dataset.id)),f=e.target.dataset.field;if(!m||!f)return;m[f]=f==='duration'?Number(e.target.value):f==='useProducts'?e.target.checked:e.target.value;if(f==='type'){m.prompt='';render()}else if(f==='useProducts')card.querySelector('.module-note').textContent=note(m)});
$('timelineModules').addEventListener('click',async e=>{const btn=e.target.closest('button[data-act]');if(!btn)return;const card=btn.closest('.timeline-module'),i=modules.findIndex(x=>x.id===Number(card.dataset.id));if(i<0)return;const m=modules[i],a=btn.dataset.act;if(a==='remove'){modules.splice(i,1);render();return}if(a==='up'&&i>0){[modules[i-1],modules[i]]=[modules[i],modules[i-1]];render();return}if(a==='down'&&i<modules.length-1){[modules[i+1],modules[i]]=[modules[i],modules[i+1]];render();return}if(a==='copy'){await navigator.clipboard.writeText(m.prompt);btn.textContent='Copiado ✓';setTimeout(()=>btn.textContent='Copiar prompt',1200);return}if(a==='generate')await generate(m,i,card)});
modules=[make('opening')];render();
})();