(() => {
'use strict';
const BUILD='20260826-ceneca10-v4-todas-canecas';
const FB='https://cedar-chemist-310801-default-rtdb.firebaseio.com';
const N={products:'produtos',models:'canecas/modelos_criacao',commands:'canecas/comandos_criacao',pub:'canecas/personalizadas_publicas',priv:'canecas/personalizadas',cfg:'canecas/config_publica'};
const WKEY='da_admin_v2_mug_make_webhook',QKEY='da_ceneca10_quality',WA='5565998150975';
const CATS=['Caneca de Porcelana','Canecas de Porcelana','Canecas'];
const PH={art:'__MUG_ART__',m1:'__MUG_MOCKUP_1__',m2:'__MUG_MOCKUP_2__',m3:'__MUG_MOCKUP_3__'};
const S={models:[],created:[],commands:[],selected:null,file:null,busy:false,hook:'',quality:'high',id:'',waOpen:false,waOk:false};
const $=id=>document.getElementById(id),txt=v=>String(v??'').trim(),norm=v=>txt(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),url=v=>/^https?:\/\//i.test(txt(v));
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const uniq=a=>[...new Set(a.flat(Infinity).map(txt).filter(url))];
function toast(m,d=3200){const e=$('toast');e.textContent=m;e.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>e.hidden=true,d)}
function stamp(p={}){const n=Number(p.last_update||p.timestamp||0);if(Number.isFinite(n)&&n>0)return n;return Date.parse(p.updated_at||p.atualizado_em||p.criado_em||'')||0}
function active(p={}){return txt(p.situacao).toUpperCase()!=='I'&&p.ativo!==false}
function mug(p={}){return norm(p.categoria).includes('caneca')||norm(p.tipo_produto).includes('caneca')||norm(p.origem_cadastro).includes('caneca')}
function phrase(p={},f=''){return txt(p.personalizacao_cliente?.frase||p.configuracao_arte?.frase_cliente||p.frase||p.modelo_frase||f||p.texto_identificado_arte)}
function hiName(p={},f=''){return txt(p.personalizacao_cliente?.nome_destaque||p.configuracao_arte?.nome_destaque||p.nome_destaque||f)}
function imgs(p={}){return uniq([p.mockup_1,p.mockup_2,p.mockup_3,p.url_imagem,p.imagem_url,p.imagem,p.imagens_site||[],p.imagens||[]]).slice(0,3)}
function art(p={}){return txt(p.arte_horizontal||p.arte_personalizacao||p.arte_impressao?.url||p.mockup_1||p.url_imagem||p.imagem)}
function cmdIds(p={}){const a=p.modelo_comandos_ids||p.configuracao_arte?.comandos_salvos_ids||p.configuracao_arte?.comandos_ids||[];return Array.isArray(a)?[...new Set(a.map(txt).filter(Boolean))]:[]}
function fromProduct(key,p={}){const im=imgs(p),a=art(p);if(!im.length&&!a)return null;return{id:txt(p.id||key),product_key:txt(p.firebaseKey||p.id||key),nome:txt(p.nome||'Caneca criada'),images:im,imagem:im[0]||a,art:a,frase:phrase(p),nome_destaque:hiName(p),comandos_ids:cmdIds(p),instrucao_manual:'',instrucao_efetiva:'',ativo:active(p),source:'criada',product:p,sortAt:stamp(p)}}
async function get(path,query=''){const r=await fetch(`${FB}/${path}.json${query}`,{cache:'no-store'});if(!r.ok)throw new Error(`Firebase ${r.status}`);return r.json()}
async function allCreated(){const rs=await Promise.allSettled(CATS.map(async c=>{const q=new URLSearchParams({orderBy:JSON.stringify('categoria'),equalTo:JSON.stringify(c)});return get(N.products,`?${q}`)}));const map=new Map();for(const r of rs)if(r.status==='fulfilled')for(const[k,p]of Object.entries(r.value||{})){if(!p||typeof p!=='object'||!mug(p))continue;const m=fromProduct(k,p);if(m)map.set(m.product_key,m)}return[...map.values()].sort((a,b)=>b.sortAt-a.sortAt||a.nome.localeCompare(b.nome,'pt-BR'))}
async function loadCommands(){try{const d=await get(N.commands);return Object.entries(d||{}).map(([k,v])=>({id:txt(v?.id||k),texto:txt(v?.texto)})).filter(x=>x.id&&x.texto)}catch{return[]}}
async function allSaved(createdMap){let d={};try{d=await get(N.models,`?_=${Date.now()}`)}catch{return[]}return Object.entries(d||{}).filter(([,v])=>v&&typeof v==='object').map(([k,v])=>{const pk=txt(v.product_key||v.firebaseKey||v.id||k),c=createdMap.get(pk),p=c?.product||{},im=uniq([v.mockup_1,v.mockup_2,v.mockup_3,v.imagem,c?.images||[]]).slice(0,3),a=txt(v.arte_horizontal||c?.art||v.imagem||im[0]);return{id:txt(v.id||pk),product_key:pk,nome:txt(v.nome||c?.nome||p.nome||'Modelo de caneca'),images:im,imagem:im[0]||a,art:a,frase:txt(v.frase||c?.frase||phrase(p)),nome_destaque:txt(v.nome_destaque||c?.nome_destaque||hiName(p)),comandos_ids:Array.isArray(v.comandos_ids)?v.comandos_ids.map(txt).filter(Boolean):(c?.comandos_ids||[]),instrucao_manual:txt(v.instrucao_manual),instrucao_efetiva:txt(v.instrucao_efetiva),ativo:c?c.ativo:active(p),source:'modelo_salvo',product:p,sortAt:Math.max(Date.parse(v.atualizado_em||'')||0,c?.sortAt||0)}}).filter(m=>m.product_key&&(m.images.length||m.art))}
async function loadModels(){const c=await allCreated(),cm=new Map(c.map(x=>[x.product_key,x])),sv=await allSaved(cm),mm=new Map(c.map(x=>[x.product_key,x]));for(const m of sv){const e=mm.get(m.product_key);mm.set(m.product_key,e?{...e,...m,images:m.images.length?m.images:e.images,art:m.art||e.art}:m)}S.created=c;S.models=[...mm.values()].sort((a,b)=>b.sortAt-a.sortAt||a.nome.localeCompare(b.nome,'pt-BR'));S.commands=await loadCommands();if(!S.selected&&S.models.length)S.selected=S.models[0]}
function card(m,i,small=false){const sel=S.selected?.product_key===m.product_key;return`<button type="button" class="model-card ${small?'compact-model':''} ${sel?'is-selected':''}" data-model="${esc(m.product_key)}"><div class="model-image"><img loading="lazy" decoding="async" src="${esc(m.images[0]||m.imagem||m.art||'../site/img/logoantonia5.png')}" alt="${esc(m.nome||`Modelo ${i+1}`)}"><span class="model-status ${m.ativo?'active':'inactive'}">${m.ativo?'Ativa':'Inativa'}</span></div><div class="model-foot"><strong>${esc(m.nome)}</strong><small>${m.source==='modelo_salvo'?'Modelo salvo':'Caneca criada'}${m.frase?' · tem frase':''}</small></div></button>`}
function render(){modelsTrack.innerHTML=S.models.length?S.models.map((m,i)=>card(m,i)).join(''):'<div class="empty-models">Nenhuma caneca encontrada.</div>';createdTrack.innerHTML=S.created.length?S.created.map((m,i)=>card(m,i,true)).join(''):'<div class="empty-models">Nenhuma criação encontrada.</div>';const m=S.selected;if(!m){selectedModelInfo.hidden=true;return}selectedModelInfo.hidden=false;selectedModelName.textContent=m.nome;selectedModelPhrase.textContent=m.frase||'Este modelo não possui frase salva.';useModelPhraseButton.hidden=!m.frase;selectedModelStatus.textContent=`${m.ativo?'Ativa':'Inativa'} · ${m.source==='modelo_salvo'?'modelo salvo':'caneca criada'} · pode ser reutilizada como modelo`}
function choose(pk){const m=S.models.find(x=>x.product_key===pk)||S.created.find(x=>x.product_key===pk);if(!m)return;S.selected=m;invalidate();render()}
function recipe(m){const b=S.commands.filter(c=>(m.comandos_ids||[]).includes(c.id)).map((c,i)=>`COMANDO DE ESTILO ${i+1}:\n${c.texto}`);if(m.instrucao_manual)b.push(`INSTRUÇÃO VISUAL DO MODELO:\n${m.instrucao_manual}`);else if(!b.length&&m.instrucao_efetiva)b.push(`INSTRUÇÃO VISUAL DO MODELO:\n${m.instrucao_efetiva}`);return b.join('\n\n')}
function artPrompt(r,n,f){return`A referência está dividida em duas partes: à esquerda está o MODELO VISUAL escolhido e à direita está a FOTO DO CLIENTE.\n\nCrie uma NOVA ARTE HORIZONTAL PARA SUBLIMAÇÃO DE CANECA, aproximadamente 24 × 9,5 cm, pronta para 2400 × 960 px.\n\nREGRAS OBRIGATÓRIAS:\n- preserve linguagem visual, clima, cores e acabamento do modelo;\n- use a foto do cliente como conteúdo principal;\n- NÃO copie nomes nem frases do modelo original;\n- organize em DOIS POLOS: FOTO + NOME EM DESTAQUE de um lado e FRASE do outro lado da caneca;\n- o NOME deve ficar próximo da foto, destacado, harmonioso e sem cobrir rosto ou detalhes importantes;\n- a FRASE deve continuar NO LADO OPOSTO da caneca, separada da foto e do nome;\n- não gerar caneca, mãos, mesa, embalagem ou mockup; entregar somente a arte plana.\n\n${r?`REGRAS DE ESTILO DO MODELO:\n${r}\n\n`:''}NOME EM DESTAQUE — ESCREVER EXATAMENTE ASSIM:\n${n}\n\nFRASE — ESCREVER EXATAMENTE ASSIM:\n${f}\n- preserve palavras, acentos e pontuação.\n\nENTREGA: uma única arte horizontal harmoniosa e pronta para sublimação.`}
function mockPrompt(s){const p=s===1?'primeira metade/lado esquerdo':s===2?'segunda metade/lado direito':'centro da arte';return`Use a arte como arte-mestre imutável. Mostre o ${p} em uma caneca branca de porcelana 350ml, fotografia quadrada 1:1 ultra realista, fundo claro, caneca inteira. Não redesenhe nem reescreva. Preserve exatamente nome e frase, aplicando somente a curvatura natural.`}
function fileData(f){return new Promise((ok,no)=>{const r=new FileReader;r.onload=()=>ok(String(r.result||''));r.onerror=no;r.readAsDataURL(f)})}
function image(src){return new Promise((ok,no)=>{const i=new Image;i.onload=()=>ok(i);i.onerror=no;i.src=src})}
async function normalizePhoto(f){const i=await image(await fileData(f)),s=Math.min(1,1500/i.naturalWidth,1500/i.naturalHeight),w=Math.max(1,Math.round(i.naturalWidth*s)),h=Math.max(1,Math.round(i.naturalHeight*s)),c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d',{alpha:false});x.fillStyle='#fff';x.fillRect(0,0,w,h);x.drawImage(i,0,0,w,h);return c.toDataURL('image/webp',.94)}
async function asData(u){if(!url(u))return'';const r=await fetch(u,{cache:'no-store'});if(!r.ok)return'';return fileData(await r.blob())}
async function composite(a,b){if(!a)return b;const[i,j]=await Promise.all([image(a),image(b)]),c=document.createElement('canvas');c.width=1800;c.height=1000;const x=c.getContext('2d',{alpha:false});x.fillStyle='#fff';x.fillRect(0,0,1800,1000);const draw=(im,xx)=>{const s=Math.min(900/im.naturalWidth,1000/im.naturalHeight),w=im.naturalWidth*s,h=im.naturalHeight*s;x.drawImage(im,xx+(900-w)/2,(1000-h)/2,w,h)};draw(i,0);draw(j,900);x.fillStyle='#ddd';x.fillRect(897,0,6,1000);return c.toDataURL('image/webp',.94)}
async function crop(src){const i=await image(src),tr=2.5,sr=i.naturalWidth/i.naturalHeight;let sx=0,sy=0,sw=i.naturalWidth,sh=i.naturalHeight;if(sr>tr){sw=i.naturalHeight*tr;sx=(i.naturalWidth-sw)/2}else{sh=i.naturalWidth/tr;sy=(i.naturalHeight-sh)/2}const c=document.createElement('canvas');c.width=2400;c.height=960;const x=c.getContext('2d',{alpha:false});x.fillStyle='#fff';x.fillRect(0,0,2400,960);x.drawImage(i,sx,sy,sw,sh,0,0,2400,960);return c.toDataURL('image/webp',.96)}
async function side(master,mode){const i=await image(master),w=1344,sx=mode===1?0:mode===2?2400-w:Math.round((2400-w)/2),c=document.createElement('canvas');c.width=w;c.height=960;const x=c.getContext('2d',{alpha:false});x.fillStyle='#fff';x.fillRect(0,0,w,960);x.drawImage(i,sx,0,w,960,0,0,w,960);return c.toDataURL('image/webp',.96)}
async function make(payload,t=180000){if(!S.hook)throw new Error('Automação ainda não configurada.');const c=new AbortController(),tm=setTimeout(()=>c.abort(),t);try{const r=await fetch(S.hook,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({payload:JSON.stringify(payload)}),signal:c.signal}),raw=await r.text();let d={};try{d=raw?JSON.parse(raw):{}}catch{throw new Error(`Automação respondeu conteúdo inválido (${r.status}).`)}if(!r.ok||d.ok===false)throw new Error(d.error||d.message||`Automação respondeu HTTP ${r.status}.`);return d}finally{clearTimeout(tm)}}
function rid(){return`cp-${Date.now()}-${Math.random().toString(36).slice(2,10)}`}
function resultUrl(id){const u=new URL('./resultado.html',location.href);u.search='';u.searchParams.set('id',id);return u.href}
function waStart(id,d){return`https://wa.me/${WA}?text=${encodeURIComponent(['Olá! Quero criar uma caneca personalizada na Dona Antônia.',`Código da criação: ${id}`,`Meu nome: ${d.customerName}`,`Nome para destacar na caneca: ${d.highlightName}`,`Modelo: ${d.model.nome}`,`Frase: ${d.phrase}`,'','Estou enviando esta mensagem para liberar minha criação no site.'].join('\n'))}`}
function waEnd(id,u,d){return`https://wa.me/${WA}?text=${encodeURIComponent(['Olá! Minha caneca personalizada ficou pronta.',`Código: ${id}`,`Meu nome: ${d.customerName}`,`Nome destacado: ${d.highlightName}`,`Frase: ${d.phrase}`,`Link com as 4 imagens: ${u}`].join('\n'))}`}
function form(){return{model:S.selected,customerName:txt(customerNameInput.value),highlightName:txt(highlightNameInput.value),phrase:txt(phraseInput.value)}}
function validate(){const d=form();if(!d.model)throw new Error('Escolha um modelo.');if(!S.file)throw new Error('Envie sua foto.');if(!d.customerName)throw new Error('Informe seu nome.');if(!d.highlightName)throw new Error('Informe o nome que deve aparecer em destaque na caneca.');if(!d.phrase)throw new Error('Escreva a frase da caneca.');return d}
function gate(){const ok=S.waOpen&&S.waOk;whatsappGateCard.classList.toggle('is-unlocked',ok);whatsappConfirmBox.hidden=!S.waOpen;whatsappUnlockButton.textContent=S.waOpen?'Abrir o WhatsApp novamente':'Abrir WhatsApp e enviar mensagem';generateButton.disabled=S.busy||!ok;generateHelp.textContent=ok?'Contato confirmado. Agora você pode gerar sua caneca.':'Envie primeiro a mensagem pelo WhatsApp para liberar.';if(S.waOpen&&!S.waOk)whatsappGateStatus.textContent='Depois de enviar no WhatsApp, volte e marque a confirmação.';else if(ok)whatsappGateStatus.textContent=`Liberado para gerar · código ${S.id}`}
function invalidate(){if(S.busy)return;S.id='';S.waOpen=false;S.waOk=false;whatsappSentConfirm.checked=false;gate()}
async function lead(id,d){fetch(`${FB}/${N.priv}/${encodeURIComponent(id)}.json`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,cliente_nome:d.customerName,nome_destaque:d.highlightName,modelo_key:d.model.product_key,modelo_nome:d.model.nome,frase:d.phrase,status:'contato_whatsapp_iniciado',whatsapp_contato_iniciado:true,origem:BUILD,criado_em:new Date().toISOString()})}).catch(()=>{})}
function openWa(){let d;try{d=validate()}catch(e){toast(e.message);return}if(!S.id)S.id=rid();S.waOpen=true;S.waOk=false;whatsappSentConfirm.checked=false;gate();window.open(waStart(S.id,d),'_blank','noopener');lead(S.id,d)}
function productTemplate(id,d){const now=new Date().toISOString(),name=`Caneca de Porcelana Personalizada ${d.highlightName} - 350ml`;return{id,firebaseKey:id,codigo:`CANP-${id.slice(-8).toUpperCase()}`,nome:name,categoria:'Caneca de Porcelana',subcategoria:'Personalizadas',tema:'Personalizada',ncm:'69111090',preco_custo:10,preco:24.9,estoque:0,situacao:'I',ativo:false,modelo_caneca:true,material:'Porcelana',capacidade:'350ml',unidade:'UN',descricao:`${name}. Caneca de porcelana branca 350ml personalizada com foto, nome em destaque e frase.`,tags:['caneca personalizada','caneca com foto','caneca com nome','presente personalizado'],url_imagem:PH.m1,imagem:PH.m1,imagem_url:PH.m1,imagens:[PH.m1,PH.m2,PH.m3],imagens_site:[PH.m1,PH.m2,PH.m3],mockup_1:PH.m1,mockup_2:PH.m2,mockup_3:PH.m3,arte_personalizacao:PH.art,arte_horizontal:PH.art,arte_impressao:{url:PH.art,ratio:'2400:960',width:2400,height:960,dimensao_real:'24 × 9,5 cm',formato:'webp'},midias_admin:[PH.m1,PH.m2,PH.m3,PH.art],origem_cadastro:'ceneca10_cliente_teste',tipo_produto:'caneca_personalizada',geracao_status:'concluido',geracao_versao:BUILD,personalizacao_cliente:{nome:d.customerName,nome_destaque:d.highlightName,frase:d.phrase,frase_modelo_origem:d.model.frase||'',modelo_key:d.model.product_key,modelo_nome:d.model.nome,resultado_url:d.publicUrl,whatsapp_contato_iniciado:true,whatsapp_confirmado_pelo_cliente:true,codigo_contato:id},configuracao_arte:{modo:'cliente_modelo_foto_nome_frase',modelo_key:d.model.product_key,nome_destaque:d.highlightName,frase_cliente:d.phrase,layout_texto:'foto_e_nome_em_um_lado_frase_no_lado_oposto',width:2400,height:960},criado_em:now,updated_at:now,last_update:Date.now()}}
function materialize(p,u){const rep=v=>v===PH.art?u.art:v===PH.m1?u.m1:v===PH.m2?u.m2:v===PH.m3?u.m3:v;p.imagens=p.imagens.map(rep);p.imagens_site=p.imagens_site.map(rep);p.midias_admin=p.midias_admin.map(rep);p.url_imagem=p.imagem=p.imagem_url=p.mockup_1=u.m1;p.mockup_2=u.m2;p.mockup_3=u.m3;p.arte_personalizacao=p.arte_horizontal=u.art;p.arte_impressao.url=u.art;return p}
async function saveAll(id,d,u,r,makeSaved){const product=productTemplate(id,d);if(!makeSaved){const x=await fetch(`${FB}/${N.products}/${encodeURIComponent(id)}.json`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(materialize(product,u))});if(!x.ok)throw new Error('Não foi possível salvar a caneca no Produção.')}else await fetch(`${FB}/${N.products}/${encodeURIComponent(id)}.json`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({modelo_caneca:true,modelo_atualizado_em:new Date().toISOString()})}).catch(()=>{});const now=new Date().toISOString(),pub={id,nome_publico:`Caneca personalizada ${d.highlightName}`,nome_destaque:d.highlightName,modelo_nome:d.model.nome,modelo_key:d.model.product_key,frase:d.phrase,arte_horizontal:u.art,mockup_1:u.m1,mockup_2:u.m2,mockup_3:u.m3,produto_key:id,criado_em:now,expira_em:new Date(Date.now()+604800000).toISOString()},priv={...pub,cliente_nome:d.customerName,status:'criacao_gerada_aguardando_envio_link',resultado_url:d.publicUrl,whatsapp_contato_iniciado:true,whatsapp_confirmado_pelo_cliente:true,codigo_contato:id,origem:BUILD},model={id,product_key:id,nome:product.nome,imagem:u.m1,mockup_1:u.m1,mockup_2:u.m2,mockup_3:u.m3,arte_horizontal:u.art,frase:d.phrase,nome_destaque:d.highlightName,comandos_ids:Array.isArray(d.model.comandos_ids)?d.model.comandos_ids:[],instrucao_efetiva:r,atualizado_em:now,origem:BUILD};const rs=await Promise.all([fetch(`${FB}/${N.pub}/${encodeURIComponent(id)}.json`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(pub)}),fetch(`${FB}/${N.priv}/${encodeURIComponent(id)}.json`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(priv)}),fetch(`${FB}/${N.models}/${encodeURIComponent(id)}.json`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(model)})]);if(!rs[0].ok||!rs[1].ok)throw new Error('A caneca foi criada, mas o link público não pôde ser salvo.')}
function progress(n,t,d){progressCard.hidden=false;progressPercent.textContent=`${n}%`;progressBar.style.width=`${n}%`;progressTitle.textContent=t;if(d)progressDetail.textContent=d}
async function generate(){if(S.busy)return;if(!S.waOpen||!S.waOk||!S.id)return toast('Envie primeiro a mensagem pelo WhatsApp e confirme o envio.');let d;try{d=validate()}catch(e){invalidate();return toast(`${e.message} Será necessário liberar novamente pelo WhatsApp.`)}if(!S.hook)return toast('Esta página de teste ainda não está ligada à automação.');S.busy=true;gate();doneCard.hidden=true;bottomAction.hidden=true;const id=S.id,pubUrl=resultUrl(id);d={...d,publicUrl:pubUrl};try{progress(8,'Preparando sua foto…','Organizando as referências do modelo escolhido.');const user=await normalizePhoto(S.file);let modelData='';try{modelData=await asData(d.model.art||d.model.images[0])}catch{}const comp=await composite(modelData,user),r=recipe(d.model);progress(22,'Criando a arte personalizada…','Foto + nome em destaque de um lado e frase do outro.');const ar=await make({action:'generate_mug_art',request_id:id,image_base64:comp,instruction:r,prompt_art:artPrompt(r,d.highlightName,d.phrase),customer_highlight_name:d.highlightName,customer_phrase:d.phrase,layout_instruction:'nome destacado próximo da imagem; frase no lado oposto da caneca',quality:S.quality}),src=txt(ar.art_source_url||ar.result_url);if(!src)throw new Error('A automação não devolveu a arte criada.');progress(46,'Ajustando a arte…','Preparando a imagem final.');const master=await crop(src),[l,rr,c]=await Promise.all([side(master,1),side(master,2),side(master,3)]),template=JSON.stringify(productTemplate(id,d));progress(58,'Criando as prévias…','Gerando as três vistas sem alterar os textos.');const fr=await make({action:'finalize_mug_product',request_id:id,image_base64:master,mockup_left_base64:l,mockup_right_base64:rr,mockup_center_base64:c,instruction:r,product_name:`Caneca de Porcelana Personalizada ${d.highlightName} - 350ml`,prompt_mockup_1:mockPrompt(1),prompt_mockup_2:mockPrompt(2),prompt_mockup_3:mockPrompt(3),quality:'high',firebase_url:FB,products_node:N.products,firebase_template_json:template}),u={art:txt(fr.art_url||fr.arte_url||fr.art_source_url)||src,m1:txt(fr.mockup_1_url),m2:txt(fr.mockup_2_url),m3:txt(fr.mockup_3_url)};if(!u.m1||!u.m2||!u.m3)throw new Error('A automação não devolveu os três mockups.');progress(82,'Salvando sua criação…','Cadastrando como inativa e também como modelo.');await saveAll(id,d,u,r,fr.product_saved===true);progress(100,'Tudo pronto!','Seu link com as quatro imagens foi criado.');donePreview.src=u.m1;viewResultButton.href=pubUrl;sendResultWhatsappButton.href=waEnd(id,pubUrl,d);doneMessage.textContent='Sua caneca foi salva como inativa e já pode servir de modelo para novas criações.';doneCard.hidden=false;progressCard.hidden=true;doneCard.scrollIntoView({behavior:'smooth',block:'start'})}catch(e){console.error(e);toast(e?.message||String(e),5200);progressCard.hidden=true;bottomAction.hidden=false}finally{S.busy=false;gate()}}
async function hook(){S.quality=localStorage.getItem(QKEY)||'high';S.hook=txt(localStorage.getItem(WKEY));if(S.hook)return;try{const v=await get(`${N.cfg}/make_webhook`);if(typeof v==='string'&&/^https:\/\//i.test(v))S.hook=v}catch{}}
async function saveCfg(){const h=txt(webhookInput.value);if(!/^https:\/\//i.test(h))return toast('Informe um webhook válido.');localStorage.setItem(WKEY,h);localStorage.setItem(QKEY,qualityInput.value||'high');S.hook=h;S.quality=qualityInput.value||'high';if(publishWebhookInput.checked){const r=await fetch(`${FB}/${N.cfg}/make_webhook.json`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(h)});if(!r.ok)return toast('Configuração local salva, mas não foi possível publicar.')}toast('Automação configurada.');adminSettingsDialog.close()}
function bind(){const pick=e=>{const b=e.target.closest('[data-model]');if(b)choose(txt(b.dataset.model))};modelsTrack.addEventListener('click',pick);createdTrack.addEventListener('click',pick);useModelPhraseButton.addEventListener('click',()=>{if(!S.selected?.frase)return;phraseInput.value=S.selected.frase;phraseCount.textContent=phraseInput.value.length;invalidate();toast('Frase do modelo copiada. Você pode editar antes de continuar.')});customerPhotoInput.addEventListener('change',()=>{const f=customerPhotoInput.files?.[0];if(!f||!f.type.startsWith('image/'))return;S.file=f;customerPhotoPreview.src=URL.createObjectURL(f);customerPhotoPreview.hidden=false;photoEmpty.hidden=true;changePhotoButton.hidden=false;invalidate()});changePhotoButton.addEventListener('click',()=>customerPhotoInput.click());phraseInput.addEventListener('input',()=>{phraseCount.textContent=phraseInput.value.length;invalidate()});customerNameInput.addEventListener('input',invalidate);highlightNameInput.addEventListener('input',invalidate);whatsappUnlockButton.addEventListener('click',openWa);whatsappSentConfirm.addEventListener('change',()=>{S.waOk=S.waOpen&&whatsappSentConfirm.checked;gate()});generateButton.addEventListener('click',generate);createAnotherButton.addEventListener('click',()=>location.reload());if(new URLSearchParams(location.search).get('admin')==='1'){adminSettingsButton.hidden=false;adminSettingsButton.addEventListener('click',()=>{webhookInput.value=S.hook;qualityInput.value=S.quality;adminSettingsDialog.showModal()});saveAdminSettingsButton.addEventListener('click',saveCfg)}}
async function init(){bind();await hook();try{await loadModels();render()}catch(e){console.error(e);modelsTrack.innerHTML=`<div class="empty-models">${esc(e?.message||e)}</div>`;createdTrack.innerHTML='<div class="empty-models">Não foi possível carregar as canecas criadas.</div>'}gate();console.info(`Caneca 10 · ${BUILD}`)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
