import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const PROJECT_HOST="ssbesxgaijknwsjbsbcz.supabase.co";
const BUCKET="product-images";
const MODEL="gpt-image-2.5-sunburst";
const OPENAI_URL="https://api.openai.com/v1/images/edits";
const LEGACY_COMMIT_PREFIX="chore: process product studio image batch";
const GH_OWNER="osvaldosereia";
const GH_REPO="SUCEDOAN12";
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json","Cache-Control":"no-store"}});
const clean=(v:unknown,max=1000)=>String(v??"").replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").trim().slice(0,max);
const obj=(v:unknown):Record<string,any>=>v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,any>:{};
const arr=(v:unknown)=>Array.isArray(v)?v:[];
async function sha256Hex(value:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("")}
function base64ToBytes(b64:string){const raw=atob(b64);const out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
function safeName(value:string){return clean(value,120).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,70)||"produto"}
function allowedSource(raw:string){try{const u=new URL(raw);if(u.protocol!=="https:")return false;return ["raw.githubusercontent.com",PROJECT_HOST,"donaantonia.com.br","www.donaantonia.com.br"].includes(u.hostname)}catch{return false}}
function contentTypeFor(url:string,header:string|null){const h=(header||"").split(";",1)[0].trim().toLowerCase();if(["image/png","image/jpeg","image/webp"].includes(h))return h;const p=url.toLowerCase();if(p.includes(".png"))return "image/png";if(p.includes(".jpg")||p.includes(".jpeg"))return "image/jpeg";return "image/webp"}
async function fetchImage(url:string){if(!allowedSource(url))throw new Error("source_host_not_allowed");const r=await fetch(url,{headers:{"User-Agent":"DonaAntonia-ProductImageWorker/1.0"},signal:AbortSignal.timeout(30000)});if(!r.ok)throw new Error(`source_http_${r.status}`);const declared=Number(r.headers.get("content-length")||0);if(declared>5_000_000)throw new Error("source_too_large");const bytes=new Uint8Array(await r.arrayBuffer());if(bytes.length===0||bytes.length>5_000_000)throw new Error("source_size_invalid");return {bytes,type:contentTypeFor(url,r.headers.get("content-type"))}}
function githubPathFromRaw(raw:string){try{const u=new URL(raw);if(u.hostname!=="raw.githubusercontent.com")return null;const parts=u.pathname.split("/").filter(Boolean);if(parts.length<4||parts[0]!==GH_OWNER||parts[1]!==GH_REPO)return null;return {ref:parts[2],path:parts.slice(3).join("/")}}catch{return null}}
async function recoverOriginal(currentUrl:string){const parsed=githubPathFromRaw(currentUrl);if(!parsed||!parsed.path.includes("-foto-atual-otimizada-")){const f=await fetchImage(currentUrl);return {...f,url:currentUrl,origin:"current_asset"}}try{const api=`https://api.github.com/repos/${GH_OWNER}/${GH_REPO}/commits?path=${encodeURIComponent(parsed.path)}&per_page=8`;const r=await fetch(api,{headers:{Accept:"application/vnd.github+json","User-Agent":"DonaAntonia-ProductImageWorker/1.0"},signal:AbortSignal.timeout(15000)});if(r.ok){const commits=arr(await r.json());const hit=commits.find((c:any)=>clean(c?.commit?.message,300).startsWith(LEGACY_COMMIT_PREFIX)&&c?.parents?.[0]?.sha);if(hit){const parent=clean(hit.parents[0].sha,80);const originalUrl=`https://raw.githubusercontent.com/${GH_OWNER}/${GH_REPO}/${parent}/${parsed.path}`;const f=await fetchImage(originalUrl);return {...f,url:originalUrl,origin:"github_parent_before_legacy_rembg"}}}}catch(_e){}const f=await fetchImage(currentUrl);return {...f,url:currentUrl,origin:"current_asset_fallback"}}
function promptFor(p:any){const context=[clean(p?.name,240),clean(p?.brand,120),clean(p?.packaging,120),clean(p?.gtin,40)].filter(Boolean).join(" | ");return `Edite a FOTO ENVIADA para criar uma foto quadrada profissional de catálogo do MESMO produto. A foto enviada é a verdade visual principal. Contexto de apoio: ${context}. Preserve fielmente formato, proporções, marca, logotipo, rótulo, textos visíveis, cores, material, transparências, tampa, alça e todos os detalhes reais da embalagem. Não redesenhe a embalagem, não corrija nem invente textos, não troque marca, variante, sabor, peso ou conteúdo e não remova partes do produto. Fundo totalmente uniforme cinza muito claro #ECECEC. Mostre somente um produto, inteiro e centralizado, sem cortes, com margens confortáveis em todos os lados. O produto deve ocupar no máximo aproximadamente 78% a 80% da largura ou altura disponível. Sem cenário, mesa, pessoas, preço, selo, decoração ou objetos extras. Iluminação neutra de estúdio e no máximo sombra de contato muito discreta. Prioridade máxima: fidelidade ao item fotografado, não criatividade.`}
async function generate(openaiKey:string,source:{bytes:Uint8Array,type:string},product:any){const form=new FormData();form.append("model",MODEL);form.append("prompt",promptFor(product));form.append("size","816x816");form.append("quality","low");form.append("output_format","webp");form.append("output_compression","65");form.append("background","opaque");const ext=source.type==="image/png"?"png":source.type==="image/jpeg"?"jpg":"webp";form.append("image[]",new Blob([source.bytes],{type:source.type}),`produto.${ext}`);const r=await fetch(OPENAI_URL,{method:"POST",headers:{Authorization:`Bearer ${openaiKey}`},body:form,signal:AbortSignal.timeout(115000)});const requestId=r.headers.get("x-request-id")||null;const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`openai_http_${r.status}_${clean(data?.error?.code||data?.error?.message||"error",120)}`);const b64=clean(data?.data?.[0]?.b64_json,20_000_000);if(!b64)throw new Error("openai_empty_image");const bytes=base64ToBytes(b64);if(bytes.length===0||bytes.length>500000)throw new Error(`openai_output_size_${bytes.length}`);return {bytes,usage:obj(data?.usage),requestId}}
async function processProduct(sb:any,openaiKey:string,product:any,dryRun:boolean,jobId:string|null){const currentUrl=clean(product?.image_original_url||product?.image_url,1800);if(!currentUrl)throw new Error("product_image_missing");const source=await recoverOriginal(currentUrl);const generated=await generate(openaiKey,source,product);const stamp=Date.now();const folder=dryRun?"openai/v1/previews":"openai/v1/final";const path=`${folder}/${product.id}/${stamp}-${safeName(product.name)}.webp`;const upload=await sb.storage.from(BUCKET).upload(path,generated.bytes,{contentType:"image/webp",cacheControl:"31536000",upsert:false});if(upload.error)throw new Error(`storage_${clean(upload.error.message,140)}`);const publicUrl=sb.storage.from(BUCKET).getPublicUrl(path).data.publicUrl;if(!dryRun){const now=new Date().toISOString();const productUpdate={image_original_url:product.image_original_url||source.url,image_ai_url:publicUrl,image_url:publicUrl,image_ai_status:"completed",image_ai_model:MODEL,image_ai_processed_at:now,image_ai_attempts:Number(product.image_ai_attempts||0)+1,image_ai_error:null,updated_at:now};const u=await sb.from("products").update(productUpdate).eq("id",product.id);if(u.error)throw new Error(`product_update_${clean(u.error.message,140)}`);if(jobId){const j=await sb.from("product_image_jobs").update({status:"completed",source_original_url:source.url,source_origin:source.origin,model:MODEL,output_storage_path:path,output_url:publicUrl,openai_usage:generated.usage,error_message:null,processed_at:now,updated_at:now}).eq("id",jobId);if(j.error)throw new Error(`job_update_${clean(j.error.message,140)}`)}}return {product_id:product.id,name:product.name,source_origin:source.origin,source_original_url:source.url,output_url:publicUrl,storage_path:path,output_bytes:generated.bytes.length,model:MODEL,quality:"low",size:"816x816",request_id:generated.requestId,usage:generated.usage,dry_run:dryRun}}

Deno.serve(async(req:Request)=>{if(req.method!=="POST")return json({ok:false,error:"method_not_allowed"},405);const supabaseUrl=Deno.env.get("SUPABASE_URL")||"",serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";if(!supabaseUrl||!serviceKey)return json({ok:false,error:"server_config"},500);const parsed=new URL(supabaseUrl);if(parsed.protocol!=="https:"||parsed.hostname!==PROJECT_HOST)return json({ok:false,error:"unexpected_project"},500);const sb=createClient(supabaseUrl,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}});const supplied=req.headers.get("x-da-product-image-key")||"";if(!supplied)return json({ok:false,error:"unauthorized"},401);const secretRow=await sb.from("system_secrets").select("key_hash,is_active").eq("key_name","product_image_worker_webhook_v1").maybeSingle();if(secretRow.error||!secretRow.data?.is_active||(await sha256Hex(supplied))!==secretRow.data.key_hash)return json({ok:false,error:"unauthorized"},401);let openaiKey=Deno.env.get("OPENAI_API_KEY")||"";if(!openaiKey){try{const k=await sb.rpc("get_conversation_worker_provider_secret_v1");if(typeof k.data==="string")openaiKey=k.data}catch(_e){}}let body:any={};try{body=await req.json()}catch{return json({ok:false,error:"invalid_json"},400)};if(body?.event==="healthcheck")return json({ok:true,event:"healthcheck",provider_configured:Boolean(openaiKey),model:MODEL,bucket:BUCKET});if(!openaiKey)return json({ok:false,error:"openai_key_missing"},500);
if(body?.event==="test_product"){const productId=clean(body?.product_id,80);if(!productId)return json({ok:false,error:"product_id_required"},400);const q=await sb.from("products").select("id,name,brand,packaging,gtin,image_url,image_original_url,image_ai_attempts").eq("id",productId).maybeSingle();if(q.error||!q.data)return json({ok:false,error:"product_not_found"},404);try{return json({ok:true,event:"test_product",result:await processProduct(sb,openaiKey,q.data,true,null)})}catch(e){return json({ok:false,event:"test_product",error:clean(e instanceof Error?e.message:e,240)},500)}}
if(body?.event!=="drain")return json({ok:false,error:"unknown_event"},400);const limit=Math.max(1,Math.min(3,Number(body?.limit||1)));await sb.rpc("enqueue_product_image_jobs_v1",{p_limit:Math.max(12,limit*4)});const claimed=await sb.rpc("claim_product_image_jobs_v1",{p_limit:limit});if(claimed.error)return json({ok:false,error:"claim_failed",detail:clean(claimed.error.message,180)},500);const results:any[]=[];for(const job of arr(claimed.data)){const jobId=clean(job?.id,80),productId=clean(job?.product_id,80);try{const q=await sb.from("products").select("id,name,brand,packaging,gtin,image_url,image_original_url,image_ai_attempts").eq("id",productId).maybeSingle();if(q.error||!q.data)throw new Error("product_not_found");await sb.from("products").update({image_ai_status:"processing",image_ai_error:null}).eq("id",productId);const result=await processProduct(sb,openaiKey,q.data,false,jobId);results.push({ok:true,...result})}catch(e){const message=clean(e instanceof Error?e.message:e,240);const now=new Date().toISOString();if(jobId)await sb.from("product_image_jobs").update({status:"error",error_message:message,updated_at:now}).eq("id",jobId);if(productId){const row=await sb.from("products").select("image_ai_attempts").eq("id",productId).maybeSingle();await sb.from("products").update({image_ai_status:"error",image_ai_error:message,image_ai_attempts:Number(row.data?.image_ai_attempts||0)+1}).eq("id",productId)}results.push({ok:false,product_id:productId,error:message})}}
return json({ok:true,event:"drain",processed:results.length,succeeded:results.filter(x=>x.ok).length,failed:results.filter(x=>!x.ok).length,model:MODEL,results});});