(()=>{
  'use strict';
  const API='https://ssbesxgaijknwsjbsbcz.supabase.co/functions/v1/admin-baskets-v2-v1';
  const PUB='sb_publishable_tFXHtH0HCXZepVtwgKElIg_DxS76Gu8';
  const CSS='/vitrine/admin/cestas-kits-v2.css?v=20261005';
  const OFFICIAL=['Cestas Completas','Cestas Só Alimento','Kits Limpeza e Higiene','Kits Limpeza','Kits Higiene'];
  const state={items:[],categories:[],query:'',category:'',edit:null,productResults:[],componentResults:[],swapIndex:null,swapSuggestions:[],lotDraft:null,busy:false};
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const cents=v=>Math.round(Number(v||0)*100);
  const money=c=>Number(c||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  const moneyCents=c=>money(Number(c||0)/100);
  const qty=v=>{const n=Number(v||0);return Number.isInteger(n)?String(n):n.toFixed(3).replace(/\.?0+$/,'')};
  const token=()=>String(sessionStorage.getItem('da_finance_access_token_v1')||'').trim();
  function toast(message){const el=$('#toast');if(!el){console.info(message);return}el.textContent=String(message||'');el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
  function ensureCss(){if(document.querySelector('link[data-baskets-kits-v2-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href=CSS;l.dataset.basketsKitsV2Css='1';document.head.appendChild(l)}
  async function request(action,{query={},method='GET',body}={}){
    const access=token();if(!access)throw new Error('Sua sessão do Admin expirou');
    const u=new URL(API);u.searchParams.set('action',action);Object.entries(query||{}).forEach(([k,v])=>{if(v!==undefined&&v!==null&&String(v)!=='')u.searchParams.set(k,String(v))});
    const r=await fetch(u,{method,headers:{Authorization:'Bearer '+access,apikey:PUB,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store'});
    const data=await r.json().catch(()=>({}));if(!r.ok||data?.ok===false)throw new Error(data?.error||'Não foi possível concluir a operação');return data?.result??data;
  }
  function content(){return $('#content')}
  function setActiveNav(btn){$$('.admin-sidebar-item.active').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active')}
  function ensureNav(){
    let btn=$('[data-baskets-kits-v2-nav]');if(btn)return btn;
    const old=$('button[data-tab="baskets"]');if(!old)return null;
    btn=document.createElement('button');btn.className=old.className||'admin-sidebar-item';btn.type='button';btn.dataset.basketsKitsV2Nav='1';btn.innerHTML='<span class="nav-item-icon" aria-hidden="true">◆</span><span>Cestas e Kits</span>';
    old.insertAdjacentElement('afterend',btn);
    btn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();setActiveNav(btn);history.replaceState(null,'','#cestas-kits-v2');renderList()});
    return btn;
  }
  function stateLabel(s){return s==='selling'?'Vendendo':s==='paused'?'Pausado':'Sem estoque'}
  function categoryName(item){return item?.category?.name||'Sem categoria'}
  function modeLabel(mode){return mode==='combined_kits'?'Combinação':'Produtos'}
  function filtered(){const q=state.query.trim().toLocaleLowerCase('pt-BR');return state.items.filter(x=>(!state.category||String(x.category?.id)===state.category)&&(!q||String(x.public_name||'').toLocaleLowerCase('pt-BR').includes(q)))}
  function renderFilters(){
    const host=$('#v2BkFilters');if(!host)return;
    host.innerHTML='<input class="v2bk-search" id="v2BkSearch" type="search" placeholder="Buscar cesta ou kit" value="'+esc(state.query)+'">'+
      '<button class="v2bk-chip '+(!state.category?'active':'')+'" data-cat="">Todas</button>'+state.categories.map(c=>'<button class="v2bk-chip '+(state.category===String(c.id)?'active':'')+'" data-cat="'+esc(c.id)+'">'+esc(c.name)+'</button>').join('');
    $('#v2BkSearch').oninput=e=>{state.query=e.target.value;paintCards()};
    $$('[data-cat]',host).forEach(b=>b.onclick=()=>{state.category=b.dataset.cat||'';renderFilters();paintCards()});
  }
  function paintCards(){
    const host=$('#v2BkCards');if(!host)return;const rows=filtered();
    if(!rows.length){host.innerHTML='<div class="v2bk-empty">Nenhuma Cesta/Kit encontrada com este filtro.</div>';return}
    host.innerHTML=rows.map(x=>'<article class="v2bk-card" data-id="'+esc(x.id)+'"><img src="'+esc(x.image_url||'/img/sem-foto.svg')+'" alt=""><div class="v2bk-card-main"><div class="v2bk-card-title"><strong>'+esc(x.public_name)+'</strong><span class="v2bk-status '+esc(x.state)+'">'+esc(stateLabel(x.state))+'</span></div><div class="v2bk-card-meta">'+esc(categoryName(x))+' · '+esc(modeLabel(x.composition_mode))+'</div><div class="v2bk-card-kpis"><span class="v2bk-kpi"><b>'+moneyCents(x.price_cents)+'</b> venda</span><span class="v2bk-kpi"><b>'+esc(x.availability)+'</b> disponíveis</span></div><div class="v2bk-card-actions"><button class="secondary" data-edit="'+esc(x.id)+'">Editar</button>'+(x.composition_mode==='products'?'<button class="secondary" data-lot="'+esc(x.id)+'">Novo lote</button>':'')+'<button class="secondary" data-duplicate="'+esc(x.id)+'">Duplicar</button><button class="text" data-pause="'+esc(x.id)+'" data-value="'+(x.state==='paused'?'false':'true')+'">'+(x.state==='paused'?'Retomar':'Pausar')+'</button></div></div></article>').join('');
    $$('[data-edit]',host).forEach(b=>b.onclick=()=>openEditor(b.dataset.edit));
    $$('[data-lot]',host).forEach(b=>b.onclick=()=>openEditor(b.dataset.lot,true));
    $$('[data-duplicate]',host).forEach(b=>b.onclick=()=>duplicateItem(b.dataset.duplicate));
    $$('[data-pause]',host).forEach(b=>b.onclick=()=>pauseItem(b.dataset.pause,b.dataset.value==='true'));
  }
  async function loadList(){const d=await request('list');state.items=d.items||[];state.categories=(d.categories||[]).filter(c=>c&&typeof c==='object');}
  async function renderList(){
    ensureCss();const host=content();if(!host)return;host.innerHTML='<div class="v2bk-shell"><div class="v2bk-head"><div><h1>Cestas e Kits</h1><p>Crie, edite e monte com poucos passos. A seção antiga Cestas continua disponível durante a homologação.</p></div><button class="primary" id="v2BkNew">+ Nova Cesta/Kit</button></div><div class="v2bk-filters" id="v2BkFilters"><div class="loading">Carregando…</div></div><div class="v2bk-grid" id="v2BkCards"></div></div>';
    try{await loadList();renderFilters();paintCards();$('#v2BkNew').onclick=()=>openEditor(null)}catch(e){host.innerHTML='<div class="v2bk-empty">'+esc(e.message)+'<br><button class="secondary" id="v2BkRetry">Tentar novamente</button></div>';$('#v2BkRetry').onclick=renderList}
  }
  async function duplicateItem(id){if(state.busy)return;state.busy=true;try{const x=await request('item_duplicate',{method:'POST',body:{item_id:id}});toast('Cópia criada como pausada');await loadList();paintCards();if(x?.id)openEditor(x.id)}catch(e){toast(e.message)}finally{state.busy=false}}
  async function pauseItem(id,paused){if(state.busy)return;state.busy=true;try{await request('item_pause',{method:'POST',body:{item_id:id,paused}});toast(paused?'Cesta/Kit pausada':'Cesta/Kit retomada');await loadList();paintCards()}catch(e){toast(e.message)}finally{state.busy=false}}
  function blankEdit(){const first=state.categories[0];return {item:{id:null,public_name:'',category_id:first?.id||'',image_url:'',description_short:'',composition_mode:'products',sale_price_cents:0},product_components:[],kit_components:[],lots:[],availability:0,financial:null,summary:null}}
  function normalizeDetail(d){
    const item=d.item||{};item.sale_price_cents=cents(item.sale_price);item.category_id=String(item.category_id||'');
    d.product_components=(d.product_components||[]).map((x,i)=>({product_id:x.product_id||x.product?.id,quantity:Number(x.quantity||1),position_order:Number(x.position_order??i),product:{...(x.product||{}),cost:x.product?.cost==null?null:Number(x.product.cost),price:x.product?.price==null?null:Number(x.product.price),loose_stock:Number(x.product?.loose_stock||x.loose_stock||0)}}));
    d.kit_components=(d.kit_components||[]).map((x,i)=>({item_id:x.item_id||x.component_item_id,name:x.name||'',quantity:Number(x.quantity||1),availability:Number(x.availability||0),current_cost_cents:x.current_cost_cents==null?null:Number(x.current_cost_cents),retail_products_cents:x.retail_products_cents==null?null:Number(x.retail_products_cents),sale_price_cents:x.sale_price_cents==null?null:Number(x.sale_price_cents),position_order:i}));
    return d;
  }
  async function openEditor(id,focusLots=false){
    const host=content();if(!host)return;host.innerHTML='<div class="loading">Abrindo Cesta/Kit…</div>';state.productResults=[];state.componentResults=[];state.swapIndex=null;state.swapSuggestions=[];state.lotDraft=null;
    try{if(!state.categories.length)await loadList();state.edit=id?normalizeDetail((await request('detail',{query:{id}})).detail):blankEdit();renderEditor();if(focusLots)setTimeout(()=>$('#v2BkLots')?.scrollIntoView({behavior:'smooth',block:'start'}),60)}catch(e){host.innerHTML='<div class="v2bk-empty">'+esc(e.message)+'<br><button class="secondary" id="v2BkBack">Voltar</button></div>';$('#v2BkBack').onclick=renderList}
  }
  function categoryOptions(){return state.categories.map(c=>'<option value="'+esc(c.id)+'" '+(String(state.edit.item.category_id)===String(c.id)?'selected':'')+'>'+esc(c.name)+'</option>').join('')}
  function currentProductFinancial(){
    const rows=state.edit.product_components||[],costKnown=rows.every(x=>x.product?.cost!==null&&x.product?.cost!==undefined&&Number(x.product.cost)>0),retailKnown=rows.every(x=>x.product?.price!==null&&x.product?.price!==undefined&&Number(x.product.price)>0);
    const cost=costKnown?Math.round(rows.reduce((s,x)=>s+Number(x.product.cost)*Number(x.quantity||0),0)*100):null;
    const retail=retailKnown?Math.round(rows.reduce((s,x)=>s+Number(x.product.price)*Number(x.quantity||0),0)*100):null;
    return {cost,retail,componentSales:null};
  }
  function currentCombinedFinancial(){
    const rows=state.edit.kit_components||[],costKnown=rows.every(x=>x.current_cost_cents!==null),retailKnown=rows.every(x=>x.retail_products_cents!==null),salesKnown=rows.every(x=>x.sale_price_cents!==null);
    return {cost:costKnown?Math.round(rows.reduce((s,x)=>s+Number(x.current_cost_cents)*Number(x.quantity||0),0)):null,retail:retailKnown?Math.round(rows.reduce((s,x)=>s+Number(x.retail_products_cents)*Number(x.quantity||0),0)):null,componentSales:salesKnown?Math.round(rows.reduce((s,x)=>s+Number(x.sale_price_cents)*Number(x.quantity||0),0)):null};
  }
  function financialHtml(){
    const mode=state.edit.item.composition_mode,f=mode==='products'?currentProductFinancial():currentCombinedFinancial(),final=Number(state.edit.item.sale_price_cents||0),reference=mode==='products'?f.retail:f.componentSales,adjust=reference===null?null:final-reference,margin=f.cost&&final?((final-f.cost)/f.cost*100):null,missing=mode==='products'&&(state.edit.product_components||[]).some(x=>x.product?.cost===null||x.product?.cost===undefined||Number(x.product.cost)<=0);
    return '<div class="v2bk-panel v2bk-financial-sticky"><h2>Financeiro</h2><div class="v2bk-financial-grid"><div class="v2bk-fin-line"><span>Custo</span><strong>'+(f.cost===null?'—':moneyCents(f.cost))+'</strong></div><div class="v2bk-fin-line"><span>Valor total dos produtos</span><strong>'+(f.retail===null?'—':moneyCents(f.retail))+'</strong></div>'+(mode==='combined_kits'?'<div class="v2bk-fin-line"><span>Soma da venda dos kits</span><strong>'+(f.componentSales===null?'—':moneyCents(f.componentSales))+'</strong></div>':'')+'<div class="v2bk-fin-line final"><span>Valor total venda</span><strong>'+moneyCents(final)+'</strong></div><div class="v2bk-fin-line"><span>Ajuste comercial</span><strong>'+(adjust===null?'—':(adjust>=0?'+ ':'− ')+moneyCents(Math.abs(adjust)))+'</strong></div><div class="v2bk-fin-line"><span>Margem sobre custo</span><strong>'+(margin===null?'—':margin.toFixed(1).replace('.',',')+'%')+'</strong></div></div>'+(missing?'<div class="v2bk-warning"><b>Custo não informado</b><br>Você pode salvar o rascunho, mas o lote não poderá ser marcado como Montado até corrigir o custo.</div>':'')+'</div>';
  }
  function productRow(x,i,scope='model'){
    const p=x.product||{},cost=p.cost===null||p.cost===undefined||Number(p.cost)<=0?null:Number(p.cost),price=p.price==null?null:Number(p.price),isLot=scope==='lot';
    return '<div class="v2bk-product-row '+(cost===null?'missing-cost':'')+'" data-product-row="'+i+'"><img src="'+esc(p.image_url||'/img/sem-foto.svg')+'" alt=""><div class="v2bk-product-main"><strong>'+esc(p.name||'Produto')+'</strong><small>'+esc(p.sku||p.gtin||'Sem código')+(p.packaging?' · '+esc(p.packaging):'')+'</small></div><input type="number" min="0.001" step="0.001" value="'+esc(qty(x.quantity||x.quantity_per_kit||1))+'" data-'+scope+'-qty="'+i+'" aria-label="Quantidade"><div class="v2bk-number '+(cost===null?'warn':'')+'"><small>Custo un.</small><strong>'+(cost===null?'Custo não informado':money(cost))+'</strong></div><div class="v2bk-number"><small>Venda un.</small><strong>'+(price===null?'—':money(price))+'</strong></div><div class="v2bk-number"><small>Estoque</small><strong>'+esc(qty(p.loose_stock||0))+'</strong></div><div class="v2bk-row-actions"><button class="text" data-'+scope+'-swap="'+i+'">Trocar</button><button class="text danger" data-'+scope+'-remove="'+i+'">Remover</button></div>'+(state.swapIndex===scope+':'+i?swapHtml(scope,i):'')+'</div>';
  }
  function swapHtml(scope,index){return '<div class="v2bk-inline-suggestions">'+(state.swapSuggestions.length?state.swapSuggestions.map((p,j)=>'<div class="v2bk-suggestion"><img src="'+esc(p.image_url||'/img/sem-foto.svg')+'" alt=""><div><strong>'+esc(p.name)+'</strong><small>Estoque '+esc(qty(p.loose_stock||0))+' · '+(p.cost==null?'Custo não informado':money(p.cost))+' · '+(p.price==null?'Venda —':money(p.price))+'</small></div><button class="secondary" data-'+scope+'-choose="'+j+'" data-index="'+index+'">Usar</button></div>').join(''):'<div class="sub">Nenhuma sugestão configurada nesta família.</div>')+'</div>'}
  function productsHtml(){
    return '<div class="v2bk-panel"><div class="v2bk-compose-head"><h2>Produtos</h2><span class="sub">Composição padrão para novos lotes</span></div><div class="v2bk-product-search"><input id="v2ProductSearch" type="search" placeholder="Buscar produto por nome, EAN ou código"><button class="secondary" id="v2ProductSearchBtn">Buscar</button></div><div class="v2bk-search-results" id="v2ProductResults">'+productResultsHtml()+'</div><div class="v2bk-rows">'+(state.edit.product_components||[]).map((x,i)=>productRow(x,i,'model')).join('')+'</div></div>';
  }
  function productResultsHtml(){return (state.productResults||[]).map((p,i)=>'<div class="v2bk-search-result"><img src="'+esc(p.image_url||'/img/sem-foto.svg')+'" alt=""><div><strong>'+esc(p.name)+'</strong><small>'+esc(p.gtin||p.sku||'Sem código')+' · estoque '+esc(qty(p.loose_stock||0))+' · '+(p.cost==null?'Custo não informado':money(p.cost))+' · '+(p.price==null?'Venda —':money(p.price))+'</small></div><button class="secondary" data-add-product="'+i+'">Adicionar</button></div>').join('')}
  function componentsHtml(){
    return '<div class="v2bk-panel"><div class="v2bk-compose-head"><h2>Combinar Cestas/Kits</h2><button class="secondary" id="v2FocusComponentSearch">+ Adicionar Cesta/Kit</button></div><div class="v2bk-component-search"><input id="v2ComponentSearch" type="search" placeholder="Buscar Cesta/Kit base"><button class="secondary" id="v2ComponentSearchBtn">Buscar</button></div><div class="v2bk-search-results" id="v2ComponentResults">'+componentResultsHtml()+'</div><div class="v2bk-component-list">'+(state.edit.kit_components||[]).map((x,i)=>'<div class="v2bk-component-card"><div><strong>'+esc(x.name)+'</strong><small>'+esc(x.availability)+' disponíveis</small></div><input type="number" min="1" step="1" value="'+esc(x.quantity)+'" data-component-qty="'+i+'"><div class="v2bk-number"><small>Custo</small><strong>'+(x.current_cost_cents==null?'—':moneyCents(x.current_cost_cents))+'</strong></div><div class="v2bk-number"><small>Total produtos</small><strong>'+(x.retail_products_cents==null?'—':moneyCents(x.retail_products_cents))+'</strong></div><div class="v2bk-number"><small>Venda</small><strong>'+(x.sale_price_cents==null?'—':moneyCents(x.sale_price_cents))+'</strong></div><div class="v2bk-number"><small>Qtd.</small><strong>'+esc(x.quantity)+'</strong></div><div class="v2bk-row-actions"><button class="text danger" data-component-remove="'+i+'">Remover</button></div></div>').join('')+'</div></div>';
  }
  function componentResultsHtml(){return (state.componentResults||[]).map((x,i)=>'<div class="v2bk-search-result"><img src="'+esc(x.image_url||'/img/sem-foto.svg')+'" alt=""><div><strong>'+esc(x.public_name)+'</strong><small>'+esc(x.category?.name||'')+' · '+esc(x.availability)+' disponíveis · venda '+(x.sale_price==null?'—':money(x.sale_price))+'</small></div><button class="secondary" data-add-component="'+i+'">Adicionar</button></div>').join('')}
  function lotsHtml(){
    const lots=state.edit.lots||[],canCreate=Boolean(state.edit.item.id);
    return '<div class="v2bk-panel" id="v2BkLots"><div class="v2bk-compose-head"><h2>Lotes</h2><button class="secondary" id="v2NewLot" '+(canCreate?'':'disabled')+'>+ Novo lote</button></div>'+(state.lotDraft?lotDraftHtml():'')+'<div class="v2bk-lots">'+(lots.length?lots.map(l=>'<div class="v2bk-lot-row"><div><strong>'+esc(l.code||'—')+'</strong><small>'+esc(l.status==='mounted'?'Montado':l.status==='exhausted'?'Esgotado':'Rascunho')+'</small></div><div><strong>'+esc(l.quantity_available||0)+'</strong><small>disponíveis de '+esc(l.quantity_built||0)+'</small></div><div><strong>'+(l.cost_total_snapshot==null?'Custo pendente':money(Number(l.cost_total_snapshot)))+'</strong><small>'+(l.retail_total_snapshot==null?'Produtos pendentes':'Produtos '+money(Number(l.retail_total_snapshot)))+'</small></div><div><strong>'+esc(l.mounted_at?new Date(l.mounted_at).toLocaleDateString('pt-BR'):'—')+'</strong><small>montagem</small></div><div class="v2bk-row-actions">'+(l.status==='draft'?'<button class="primary" data-mount-lot="'+esc(l.id)+'">Montar</button><button class="text danger" data-delete-lot="'+esc(l.id)+'">Excluir</button>':'')+'</div></div>').join(''):'<div class="sub">Nenhum lote criado.</div>')+'</div></div>';
  }
  function lotDraftHtml(){const d=state.lotDraft;return '<div class="v2bk-lot-create"><label><span>Quantidade a montar</span><input id="v2LotQty" type="number" min="1" step="1" value="'+esc(d.quantity)+'"></label><p>O custo e o preço dos produtos serão relidos do cadastro ao marcar como Montado.</p><button class="primary" id="v2SaveLotDraft">Salvar rascunho</button></div><div class="v2bk-rows" style="margin-bottom:12px">'+(d.items||[]).map((x,i)=>productRow(x,i,'lot')).join('')+'</div>'}
  function renderEditor(){
    const host=content(),d=state.edit,i=d.item,mode=i.composition_mode||'products';if(!host)return;
    host.innerHTML='<div class="v2bk-editor"><div class="v2bk-head"><div><button class="text" id="v2Back">← Cestas e Kits</button><h1>'+(i.id?esc(i.public_name):'Nova Cesta/Kit')+'</h1><p>'+(i.id?'Edite somente o necessário e salve.':'Defina dados, composição e preço final em uma tela.')+'</p></div></div><div class="v2bk-editor-grid"><div style="display:grid;gap:12px"><div class="v2bk-panel"><h2>Dados</h2><div class="v2bk-fields"><label><span>Nome no site</span><input id="v2Name" value="'+esc(i.public_name||'')+'" placeholder="Ex.: Cesta Pequena Só Alimentos"></label><label><span>Categoria</span><select id="v2Category">'+categoryOptions()+'</select></label><label><span>Preço final de venda</span><input id="v2SalePrice" inputmode="decimal" value="'+(Number(i.sale_price_cents||0)/100).toFixed(2).replace('.',',')+'"></label><label><span>Foto</span><input id="v2Image" value="'+esc(i.image_url||'')+'" placeholder="URL da imagem"></label><label class="wide"><span>Descrição curta</span><input id="v2Description" value="'+esc(i.description_short||'')+'"></label></div><div class="section-title">Como esta Cesta/Kit será formada?</div><div class="v2bk-mode"><button data-mode="products" class="'+(mode==='products'?'active':'')+'">Produtos</button><button data-mode="combined_kits" class="'+(mode==='combined_kits'?'active':'')+'">Combinar Cestas/Kits</button></div></div>'+(mode==='products'?productsHtml():componentsHtml())+(mode==='products'?lotsHtml():'')+'</div><aside id="v2Financial">'+financialHtml()+'</aside></div><div class="v2bk-savebar"><button class="secondary" id="v2Cancel">Cancelar</button><button class="primary" id="v2Save">Salvar Cesta/Kit</button></div></div>';
    bindEditor();
  }
  function bindEditor(){
    $('#v2Back').onclick=renderList;$('#v2Cancel').onclick=renderList;$('#v2Save').onclick=saveItem;
    $('#v2Name').oninput=e=>state.edit.item.public_name=e.target.value;$('#v2Category').onchange=e=>state.edit.item.category_id=e.target.value;$('#v2Image').oninput=e=>state.edit.item.image_url=e.target.value;$('#v2Description').oninput=e=>state.edit.item.description_short=e.target.value;
    $('#v2SalePrice').oninput=e=>{const n=Number(String(e.target.value).replace(',','.'));state.edit.item.sale_price_cents=Number.isFinite(n)?Math.round(n*100):0;paintFinancial()};
    $$('[data-mode]').forEach(b=>b.onclick=()=>{state.edit.item.composition_mode=b.dataset.mode;state.productResults=[];state.componentResults=[];state.swapIndex=null;renderEditor()});
    if(state.edit.item.composition_mode==='products')bindProducts();else bindComponents();
  }
  function bindProducts(){
    const search=()=>searchProducts($('#v2ProductSearch')?.value||'');$('#v2ProductSearchBtn')?.addEventListener('click',search);$('#v2ProductSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();search()}});
    $$('[data-add-product]').forEach(b=>b.onclick=()=>addProduct(Number(b.dataset.addProduct)));
    $$('[data-model-qty]').forEach(inp=>inp.onchange=()=>{const i=Number(inp.dataset.modelQty),n=Number(inp.value);if(n>0)state.edit.product_components[i].quantity=n;renderEditor()});
    $$('[data-model-remove]').forEach(b=>b.onclick=()=>{state.edit.product_components.splice(Number(b.dataset.modelRemove),1);renderEditor()});
    $$('[data-model-swap]').forEach(b=>b.onclick=()=>openSwap('model',Number(b.dataset.modelSwap)));
    $$('[data-model-choose]').forEach(b=>b.onclick=()=>chooseSwap('model',Number(b.dataset.index),Number(b.dataset.modelChoose)));
    $('#v2NewLot')?.addEventListener('click',()=>{state.lotDraft={lot_id:null,quantity:1,items:(state.edit.product_components||[]).map(x=>({product_id:x.product_id,quantity:Number(x.quantity||1),product:{...x.product}}))};renderEditor();setTimeout(()=>$('#v2LotQty')?.focus(),30)});
    if(state.lotDraft){$('#v2LotQty').oninput=e=>state.lotDraft.quantity=Math.max(1,Math.floor(Number(e.target.value)||1));$('#v2SaveLotDraft').onclick=saveLotDraft;$$('[data-lot-qty]').forEach(inp=>inp.onchange=()=>{const i=Number(inp.dataset.lotQty),n=Number(inp.value);if(n>0)state.lotDraft.items[i].quantity=n;renderEditor()});$$('[data-lot-remove]').forEach(b=>b.onclick=()=>{state.lotDraft.items.splice(Number(b.dataset.lotRemove),1);renderEditor()});$$('[data-lot-swap]').forEach(b=>b.onclick=()=>openSwap('lot',Number(b.dataset.lotSwap)));$$('[data-lot-choose]').forEach(b=>b.onclick=()=>chooseSwap('lot',Number(b.dataset.index),Number(b.dataset.lotChoose)))}
    $$('[data-mount-lot]').forEach(b=>b.onclick=()=>mountLot(b.dataset.mountLot));$$('[data-delete-lot]').forEach(b=>b.onclick=()=>deleteLot(b.dataset.deleteLot));
  }
  function bindComponents(){
    const search=()=>searchComponents($('#v2ComponentSearch')?.value||'');$('#v2ComponentSearchBtn')?.addEventListener('click',search);$('#v2FocusComponentSearch')?.addEventListener('click',()=>$('#v2ComponentSearch')?.focus());$('#v2ComponentSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();search()}});
    $$('[data-add-component]').forEach(b=>b.onclick=()=>addComponent(Number(b.dataset.addComponent)));$$('[data-component-qty]').forEach(inp=>inp.onchange=()=>{const i=Number(inp.dataset.componentQty),n=Math.max(1,Math.floor(Number(inp.value)||1));state.edit.kit_components[i].quantity=n;renderEditor()});$$('[data-component-remove]').forEach(b=>b.onclick=()=>{state.edit.kit_components.splice(Number(b.dataset.componentRemove),1);renderEditor()});
  }
  function paintFinancial(){const h=$('#v2Financial');if(h)h.innerHTML=financialHtml()}
  async function searchProducts(q){q=String(q||'').trim();if(q.length<2){state.productResults=[];renderEditor();return}try{const d=await request('product_search',{query:{q,limit:15}});state.productResults=d.products||[];renderEditor();setTimeout(()=>{$('#v2ProductSearch')?.focus();},20)}catch(e){toast(e.message)}}
  function addProduct(i){const p=state.productResults[i];if(!p)return;const ex=state.edit.product_components.find(x=>String(x.product_id)===String(p.id));if(ex)ex.quantity=Number(ex.quantity||0)+1;else state.edit.product_components.push({product_id:p.id,quantity:1,position_order:state.edit.product_components.length,product:{...p}});state.productResults=[];renderEditor()}
  async function openSwap(scope,index){const rows=scope==='lot'?state.lotDraft?.items:state.edit.product_components,p=rows?.[index]?.product;if(!p)return;try{const d=await request('product_suggestions',{query:{product_id:p.id}});state.swapIndex=scope+':'+index;state.swapSuggestions=d.suggestions||[];renderEditor()}catch(e){toast(e.message)}}
  function chooseSwap(scope,index,suggestionIndex){const p=state.swapSuggestions[suggestionIndex];if(!p)return;const rows=scope==='lot'?state.lotDraft.items:state.edit.product_components,old=rows[index];rows[index]={...old,product_id:p.id,product:{...p}};state.swapIndex=null;state.swapSuggestions=[];renderEditor()}
  async function searchComponents(q){try{const d=await request('component_candidates',{query:{q:String(q||'').trim()}});state.componentResults=(d.items||[]).filter(x=>String(x.id)!==String(state.edit.item.id));renderEditor();setTimeout(()=>$('#v2ComponentSearch')?.focus(),20)}catch(e){toast(e.message)}}
  function addComponent(i){const x=state.componentResults[i];if(!x)return;const ex=state.edit.kit_components.find(c=>String(c.item_id)===String(x.id));if(ex)ex.quantity+=1;else state.edit.kit_components.push({item_id:x.id,name:x.public_name,quantity:1,availability:Number(x.availability||0),current_cost_cents:x.current_cost==null?null:cents(x.current_cost),retail_products_cents:x.retail_products_total==null?null:cents(x.retail_products_total),sale_price_cents:x.sale_price==null?null:cents(x.sale_price),position_order:state.edit.kit_components.length});state.componentResults=[];renderEditor()}
  async function saveItem(){if(state.busy)return;const i=state.edit.item,name=String(i.public_name||'').trim(),cat=String(i.category_id||''),sale=Number(i.sale_price_cents||0);if(!name){toast('Informe o nome da Cesta/Kit');$('#v2Name')?.focus();return}if(!cat){toast('Selecione a categoria');return}if(sale<=0){toast('Informe o valor de venda');$('#v2SalePrice')?.focus();return}state.busy=true;const btn=$('#v2Save');if(btn){btn.disabled=true;btn.textContent='Salvando…'}try{const saved=await request('item_save',{method:'POST',body:{id:i.id||undefined,public_name:name,category_id:cat,image_url:i.image_url||'',description_short:i.description_short||'',sale_price_cents:sale,composition_mode:i.composition_mode,sort_order:Number(i.sort_order||0)}});const id=saved.id;if(i.composition_mode==='products')await request('product_components_save',{method:'POST',body:{item_id:id,components:(state.edit.product_components||[]).map((x,n)=>({product_id:x.product_id,quantity:Number(x.quantity||1),position_order:n}))}});else await request('kit_components_save',{method:'POST',body:{item_id:id,components:(state.edit.kit_components||[]).map((x,n)=>({component_item_id:x.item_id,quantity:Math.max(1,Math.floor(Number(x.quantity||1))),position_order:n}))}});toast('Cesta/Kit salva');await openEditor(id)}catch(e){toast(e.message)}finally{state.busy=false;if(btn&&document.contains(btn)){btn.disabled=false;btn.textContent='Salvar Cesta/Kit'}}}
  async function saveLotDraft(){if(state.busy||!state.edit.item.id)return;const d=state.lotDraft;if(!d?.items?.length){toast('Adicione produtos ao lote');return}state.busy=true;try{await request('lot_draft_save',{method:'POST',body:{item_id:state.edit.item.id,lot_id:d.lot_id||undefined,quantity:Math.max(1,Math.floor(Number(d.quantity||1))),items:d.items.map((x,n)=>({product_id:x.product_id,quantity_per_kit:Number(x.quantity||1),position_order:n}))}});toast('Rascunho do lote salvo');await openEditor(state.edit.item.id,true)}catch(e){toast(e.message)}finally{state.busy=false}}
  async function mountLot(id){if(state.busy)return;state.busy=true;try{const r=await request('lot_mount',{method:'POST',body:{lot_id:id}});if(r?.ok===false){if(r.error==='missing_cost_products')toast('Há produto com custo não informado. Corrija o cadastro antes de montar.');else if(r.error==='insufficient_stock')toast('Estoque insuficiente para montar esta quantidade.');else toast(r.error);return}toast('Lote marcado como Montado');await openEditor(state.edit.item.id,true)}catch(e){toast(e.message)}finally{state.busy=false}}
  async function deleteLot(id){if(!confirm('Excluir este rascunho de lote?'))return;try{await request('lot_delete_draft',{method:'POST',body:{lot_id:id}});toast('Rascunho excluído');await openEditor(state.edit.item.id,true)}catch(e){toast(e.message)}}
  function init(){ensureCss();const nav=ensureNav();if(location.hash==='#cestas-kits-v2'&&nav){setActiveNav(nav);renderList()}}
  window.DonaAntoniaBasketsV2={open:()=>{const nav=ensureNav();setActiveNav(nav);renderList()},renderList};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
