-- Storefront short identity codes v2
-- Production project: qxstkwshuvplmmftrctj
-- Applied 2026-09-23.
alter table public.storefront_identity_tokens
  add column if not exists redeemed_at timestamptz,
  add column if not exists short_code text;

create index if not exists storefront_identity_tokens_redeem_idx
  on public.storefront_identity_tokens(token_hash,expires_at,redeemed_at);

create index if not exists storefront_identity_tokens_short_code_idx
  on public.storefront_identity_tokens(short_code)
  where short_code is not null;

create table if not exists public.storefront_identity_resolve_attempts (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  attempted_at timestamptz not null default now(),
  success boolean not null default false
);

create index if not exists storefront_identity_resolve_attempts_ip_time_idx
  on public.storefront_identity_resolve_attempts(ip_hash,attempted_at desc);

alter table public.storefront_identity_resolve_attempts enable row level security;
revoke all on public.storefront_identity_resolve_attempts from anon,authenticated;
grant all on public.storefront_identity_resolve_attempts to service_role;
