import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
import {buildCreativeSignals} from '../marketing/creative-studio/creative-mining.js';
import {validateCreativePlan} from '../marketing/creative-studio/validate-plan.js';
import {proceduralKind} from '../marketing/creative-studio/asset-request.js';
import {compileTimeline} from '../marketing/creative-studio/timeline.js';

const cfg=window.DA_ADMIN_CONFIG;
const sb=createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
let selected=null,currentPlan=null,currentAssets=null,currentUsage=null,currentTimeline=null;

function toast(message){const el=$('toast');el.textContent=message;el.classList.remove('hidden');clearTimeout(el._timer);el._timer=setTimeout(()=>el.classList.add('hidden'),3000)}
function setProgress(message=''){const el=$('progress');el.textContent=message;el.classList.toggle('hidden',!message)}
async function publicAdmin(action,payload={}){const r=await fetch(`${cfg.supabaseUrl}/functions/v1/${cfg.edgeFunction}`,{method:'POST',headers:{apikey:cfg.supabasePublishableKey,'Content-Type':'application/json'},body:JSON.stringify({action,...payload}),cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw new Error(d.detail||d.error||'request_failed');return d}
async function session(){return (await sb.auth.getSession()).data.session||null}
async function secureInvoke(name,payload){const s=await session();if(!s?.access_token)throw new Error('secure_session_required');const r=await fetch(`${cfg.supabaseUrl}/functions/v1/${name}`,{method:'POST',headers:{apikey:cfg.supabasePublishableKey,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify(payload),cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw new Error(d.detail||d.error||`Erro em ${name}`);return d}

async function refreshAuth(){const s=await session();$('authPanel').classList.toggle('hidden',!!s);$('secureState').textContent=s?'Sessão segura ativa':'Sessão segura necessária';$('secureState').classList.toggle('ok',!!s);$('createIdeaButton').disabled=!selected||!s;return s}

function renderProducts(products){$('productResults').innerHTML=(products||[]).map(p=>`<button class="product-card" type="button" data-product='${esc(JSON.stringify(p))}'>${p.image_url?`<img src="${esc(p.image_url)}" alt="">`:'<span></span>'}<span><strong>${esc(p.name)}</strong><small>${esc(p.brand||p.category||'')}</small><small>${money(p.price)}</small></span></button>`).join('')||'<p>Nenhum produto encontrado.</p>'}
async function searchProducts(){setProgress('Buscando produtos…');try{const d=await publicAdmin('products',{q:$('productSearch').value.trim(),status:'active',page:1,limit:30});renderProducts(d.products)}finally{setProgress('')}}
async function chooseProduct(p){const detail=await publicAdmin('product',{id:p.id}).catch(()=>({product:p}));selected=detail.product||p;$('selectedProduct').innerHTML=`${selected.image_url?`<img src="${esc(selected.image_url)}" alt="">`:''}<div><strong>${esc(selected.name)}</strong><div>${money(selected.price)}${selected.is_offer&&selected.offer_price!=null?` · Oferta ${money(selected.offer_price)}`:''}</div><small>${esc([selected.brand,selected.category,selected.subcategory].filter(Boolean).join(' · '))}</small></div>`;$('selectedProduct').classList.remove('hidden');$('productResults').innerHTML='';await refreshAuth()}

async function resolveAssets(plan,jobKey){const items=[];let external=0;for(const request of (plan.asset_requests||[])){const kind=proceduralKind(request);if(kind){items.push({status:'procedural',request,procedural:{kind}});continue}try{const r=await secureInvoke('creative-studio-assets-v1',{action:'resolve',need:request.need,keywords:request.keywords||[],job_key:jobKey,external_acquisitions:external,allow_external:true});if(r.external_acquisition)external=Number(r.external_acquisitions||external+1);items.push({...r,request})}catch(error){items.push({status:'missing',reason:error.message,request})}}const ready=items.filter(x=>['procedural','resolved_local','acquired','resolved'].includes(x.status)).length;return {items,externalAcquisitions:external,summary:{total:items.length,ready,missing:items.filter(x=>x.status==='missing').length,blocked:items.filter(x=>x.status==='blocked').length}}}

function renderIdea(){const p=currentPlan,a=currentAssets;$('conceptTitle').textContent=p.concept;$('durationBadge').textContent=`${p.duration} s`;$('territoryText').textContent=p.territory;$('emotionText').textContent=(p.emotions||[]).join(' · ')||'—';$('hookText').textContent=p.hook;$('payoffText').textContent=p.payoff;$('sceneList').innerHTML=(p.scenes||[]).map((s,i)=>`<div class="scene"><strong>${i+1}. ${esc(s.beat||'Cena')}</strong><div>${esc(s.summary||'')}</div><small>${esc((s.actors||[]).map(x=>`${x.role}: ${x.motion}/${x.behavior}`).join(' · '))}</small></div>`).join('');$('assetList').innerHTML=(a.items||[]).map(x=>`<div class="asset ${esc(['resolved','resolved_local','procedural','acquired'].includes(x.status)?'ready':x.status)}"><strong>${esc(x.request?.need||'Elemento')}</strong><div>${esc(x.status)}</div><small>${esc(x.asset?.provider||x.asset?.source_provider||x.procedural?.kind||x.reason||'biblioteca/procedural')}</small></div>`).join('')||'<p>Nenhum elemento externo necessário.</p>';$('assetSummary').textContent=`${a.summary.ready}/${a.summary.total} prontos`;$('usageSummary').textContent=currentUsage?`${currentUsage.input_tokens||0} entrada · ${currentUsage.output_tokens||0} saída`:'registrado pelo provedor';$('produceButton').disabled=!(a.summary.total===a.summary.ready&&a.summary.missing===0&&a.summary.blocked===0);$('ideaPanel').classList.remove('hidden');$('otherIdeaButton').classList.remove('hidden')}

async function createIdea(){if(!selected)return;const s=await refreshAuth();if(!s){$('authPanel').classList.remove('hidden');toast('Entre na sessão segura para usar o Diretor.');return}currentPlan=null;currentAssets=null;currentTimeline=null;$('ideaPanel').classList.add('hidden');$('createIdeaButton').disabled=true;setProgress('Diretor Criativo analisando territórios e construindo a história…');try{const signals=buildCreativeSignals(selected);const duration=Number($('duration').value||18);const instruction=$('creativeInstruction').value.trim();const d=await secureInvoke('creative-studio-director',{product:{...selected,requested_duration:duration,creative_instruction:instruction},creativeSignals:signals.candidates,recentMemory:[]});const checked=validateCreativePlan(d.plan);if(!checked.ok)throw new Error(`Plano inválido: ${checked.errors.join(', ')}`);currentPlan=checked.plan;currentUsage=d.usage||null;setProgress('Resolvendo elementos: biblioteca → procedural → fonte gratuita…');const jobKey=`studio-${selected.id}-${Date.now()}`;currentAssets=await resolveAssets(currentPlan,jobKey);renderIdea();toast('Ideia pronta.')}catch(error){toast(error.message);$('productionMessage').textContent=error.message}finally{$('createIdeaButton').disabled=false;setProgress('')}}

$('productSearchForm').addEventListener('submit',e=>{e.preventDefault();searchProducts().catch(e=>toast(e.message))});
$('productResults').addEventListener('click',e=>{const b=e.target.closest('[data-product]');if(!b)return;try{chooseProduct(JSON.parse(b.dataset.product)).catch(e=>toast(e.message))}catch{}});
$('createIdeaButton').addEventListener('click',()=>createIdea());$('otherIdeaButton').addEventListener('click',()=>createIdea());$('adjustButton').addEventListener('click',()=>{$('creativeInstruction').focus();scrollTo({top:$('creativeInstruction').offsetTop-120,behavior:'smooth'})});
$('produceButton').addEventListener('click',()=>{try{currentTimeline=compileTimeline(currentPlan);sessionStorage.setItem('creative-studio-render-job',JSON.stringify({product:selected,plan:currentPlan,assets:currentAssets,timeline:currentTimeline,created_at:new Date().toISOString()}));$('productionMessage').textContent='Plano de produção compilado. A próxima etapa do motor vai transformar este job em MP4.';toast('Produção preparada.')}catch(e){toast(e.message)}});
$('authForm').addEventListener('submit',async e=>{e.preventDefault();$('authMessage').textContent='Entrando…';const email=$('authEmail').value.trim(),password=$('authPassword').value;const {error}=await sb.auth.signInWithPassword({email,password});$('authMessage').textContent=error?error.message:'Acesso liberado.';await refreshAuth()});
$('magicLinkButton').addEventListener('click',async()=>{const email=$('authEmail').value.trim();if(!email){$('authMessage').textContent='Digite seu e-mail.';return}const {error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:location.href}});$('authMessage').textContent=error?error.message:'Link de acesso enviado para seu e-mail.'});
sb.auth.onAuthStateChange(()=>refreshAuth());
await refreshAuth();
