const $=x=>document.getElementById(x),cfg=window.DA_ADMIN_CONFIG||{},URL=cfg.supabaseUrl,KEY=cfg.supabasePublishableKey,FN='creative-storyboard-projects';let items=[];
async function api(b){let r=await fetch(URL+'/functions/v1/'+FN,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(b)}),d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'Falha');return d}
function img(url){return new Promise((ok,no)=>{let i=new Image;i.crossOrigin='anonymous';i.onload=()=>ok(i);i.onerror=no;i.src=url})}
function detect(a,w,h){let s=[],step=Math.max(1,Math.floor(Math.min(w,h)/32)),push=(x,y)=>{let k=(y*w+x)*4;s.push([a[k],a[k+1],a[k+2]])};for(let x=0;x<w;x+=step){push(x,0);push(x,h-1)}for(let y=0;y<h;y+=step){push(0,y);push(w-1,y)}s=s.filter(v=>Math.max(...v)-Math.min(...v)<+neu.value);if(!s.length)return[235,235,235];return[0,1,2].map(q=>Math.round(s.map(v=>v[q]).sort((a,b)=>a-b)[Math.floor(s.length/2)]))}
function cut(im){let max=700,sc=Math.min(1,max/Math.max(im.naturalWidth,im.naturalHeight)),w=Math.round(im.naturalWidth*sc),h=Math.round(im.naturalHeight*sc),c=document.createElement('canvas');c.width=w;c.height=h;let x=c.getContext('2d',{willReadFrequently:true});x.drawImage(im,0,0,w,h);let id=x.getImageData(0,0,w,h),a=id.data,key=detect(a,w,h),seen=new Uint8Array(w*h),q=new Int32Array(w*h),head=0,tail=0,T=+tol.value,N=+neu.value;
 let match=i=>{let k=i*4,r=a[k],g=a[k+1],b=a[k+2];return Math.max(r,g,b)-Math.min(r,g,b)<N&&Math.hypot(r-key[0],g-key[1],b-key[2])<T},push=i=>{if(i>=0&&i<w*h&&!seen[i]&&match(i)){seen[i]=1;q[tail++]=i}};
 for(let xx=0;xx<w;xx++){push(xx);push((h-1)*w+xx)}for(let yy=0;yy<h;yy++){push(yy*w);push(yy*w+w-1)}while(head<tail){let i=q[head++],px=i%w,py=i/w|0;if(px)push(i-1);if(px<w-1)push(i+1);if(py)push(i-w);if(py<h-1)push(i+w)}
 let S=+soft.value;for(let i=0;i<w*h;i++)if(seen[i])a[i*4+3]=0;if(S){let alpha=new Uint8ClampedArray(w*h);for(let i=0;i<w*h;i++)alpha[i]=a[i*4+3];for(let pass=0;pass<S;pass++){let n=alpha.slice();for(let y=1;y<h-1;y++)for(let xx=1;xx<w-1;xx++){let i=y*w+xx;if(alpha[i]&&(!alpha[i-1]||!alpha[i+1]||!alpha[i-w]||!alpha[i+w]))n[i]=Math.min(n[i],205)}alpha=n}for(let i=0;i<w*h;i++)a[i*4+3]=alpha[i]}
 x.putImageData(id,0,0);return{c,key}}
async function load(){status.textContent='Carregando…';let d=await api({action:'random_products',limit:20});items=await Promise.all((d.products||[]).slice(0,12).map(async p=>({...p,im:await img(p.image_url)})));render();status.textContent=items.length+' produtos — nada foi salvo'}
function render(){cards.innerHTML='';let keys=[];for(const p of items){let r=cut(p.im);keys.push(r.key);let el=document.createElement('article');el.className='card';el.innerHTML='<h3></h3><div class="compare"><div class="pane" data-label="ORIGINAL"><img></div><div class="pane checker" data-label="RECORTE"></div></div><div class="meta"></div>';el.querySelector('h3').textContent=p.name;el.querySelector('img').src=p.image_url;el.querySelectorAll('.pane')[1].append(r.c);el.querySelector('.meta').textContent='cinza detectado rgb('+r.key.join(', ')+')';cards.append(el)}if(keys.length){let k=[0,1,2].map(q=>Math.round(keys.reduce((s,v)=>s+v[q],0)/keys.length));key.style.background='rgb('+k.join(',')+')';rgb.textContent='rgb('+k.join(', ')+')'}}
load.onclick=load;rerun.onclick=render;[['tol','tolOut',''],['neu','neuOut',''],['soft','softOut',' px']].forEach(([a,b,s])=>$(a).oninput=e=>{$(b).textContent=e.target.value+s});load();