import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
const MODEL='gpt-5.6-luna',URL='https://api.openai.com/v1/responses';
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{'Content-Type':'application/json','Cache-Control':'no-store','Access-Control-Allow-Origin':'*'}});
const marks=(d:number)=>Array.from({length:Math.floor(d/5)+1},(_,i)=>i*5).filter(x=>x<=d);
const packages=(d:number)=>Array.from({length:Math.floor(d/10)},(_,i)=>({package_index:i+1,start_second:i*10,middle_second:i*10+5,end_second:i*10+10}));
function text(data:any){return (data?.output||[]).flatMap((x:any)=>x?.content||[]).filter((x:any)=>x.type==='output_text').map((x:any)=>x.text||'').join('').trim()}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('',{headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,apikey,content-type'}});if(req.method!=='POST')return json({ok:false,error:'method_not_allowed'},405);const key=Deno.env.get('OPENAI_API_KEY')||'';if(!key)return json({ok:false,error:'openai_key_missing'},500);let b:any={};try{b=await req.json()}catch{return json({ok:false,error:'invalid_json'},400)};const products=Array.isArray(b.products)?b.products.filter(Boolean):[];if(!products.length)return json({ok:false,error:'products_required'},400);const duration=Math.max(10,Math.min(60,Number(b.duration_seconds||30)));const ms=marks(duration),pk=packages(duration);
const system=`Você é um diretor criativo sênior especializado em Reels/TikTok, storytelling visual, stop motion artesanal e retenção. Crie primeiro 3 conceitos internamente e devolva somente o melhor. A história precisa funcionar como entretenimento mesmo sem a marca: gancho imediato, curiosidade, emoção ou humor, progressão causal e payoff memorável. Integre os produtos naturalmente no mundo narrativo; eles podem ser detalhe de cenário, descoberta, objeto usado ou parte do desfecho. Evite propaganda convencional, locução de oferta e personagem exibindo produto para câmera como padrão. Visual sempre artesanal NÃO fotorrealista: massinha, papel recortado, origami, feltro, colagem, miniaturas, papelão ou tecido. O CTA deve nascer da história e pode ser apenas assinatura discreta. Preserve rigorosamente embalagem, marca e identidade visual dos produtos fornecidos. Cada keyframe deve descrever uma imagem vertical 9:16 completa e cinematográfica. Cada frame após o primeiro deve ser concebido como evolução visual do anterior, mantendo personagens, roupas, cenário, materiais, paleta e escala. Os prompts Gemini devem tratar as 3 imagens como REFERÊNCIA INICIAL, REFERÊNCIA INTERMEDIÁRIA e REFERÊNCIA FINAL; explicar ação 0-5 e 5-10, câmera, ritmo, física artesanal, áudio/SFX e restrições contra morphing, deformação, troca de personagem/produto e texto inventado. Retorne JSON válido, sem markdown.`;
const user=`Produtos: ${JSON.stringify(products.map((p:any)=>({id:p.id,name:p.name,brand:p.brand,category:p.category,subcategory:p.subcategory,price:p.price,offer_price:p.offer_price,image_url:p.image_url||p.image_ai_url})))}. Duração ${duration}s. Timestamps obrigatórios: ${ms.join(', ')}. Pacotes: ${pk.map(x=>`${x.start_second}/${x.middle_second}/${x.end_second}`).join(' | ')}. Retorne {concept,title,hook,emotion,craft_style,story,product_integration,payoff,cta,continuity_bible:{characters,world,materials,palette,lighting,product_rules},keyframes:[{second_mark,beat,visual_prompt}],gemini_packages:[{package_index,start_second,middle_second,end_second,prompt}]}. Exatamente ${ms.length} keyframes e ${pk.length} pacotes.`;
const r=await fetch(URL,{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:MODEL,store:false,reasoning:{effort:'medium'},input:[{role:'system',content:system},{role:'user',content:user}],text:{format:{type:'json_object'}}}),signal:AbortSignal.timeout(90000)});const data=await r.json().catch(()=>({}));if(!r.ok)return json({ok:false,error:'director_provider_error',detail:data?.error?.message||`HTTP ${r.status}`},502);let out:any;try{out=JSON.parse(text(data))}catch{return json({ok:false,error:'director_invalid_json'},502)};if(!Array.isArray(out.keyframes)||out.keyframes.length!==ms.length||!Array.isArray(out.gemini_packages)||out.gemini_packages.length!==pk.length)return json({ok:false,error:'director_contract_invalid'},502);return json({ok:true,plan:out,usage:data.usage||{},model:MODEL})});