import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...CORS,"Content-Type":"application/json","Cache-Control":"no-store"}});
const clean=(v:unknown,max=4000)=>String(v??"").replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").trim().slice(0,max);
const norm=(v:unknown)=>clean(v,1000).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");
const uuid=(v:unknown)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(clean(v,80))?clean(v,80):"";
const vars=(v:unknown)=>Array.isArray(v)?v.map(x=>clean(x,240)).filter(Boolean).slice(0,30):String(v??"").split(/\n+/).map(x=>clean(x,240)).filter(Boolean).slice(0,30);
const clamp=(v:unknown,min:number,max:number,fallback:number)=>{const n=Number(v);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):fallback};
const MODES=new Set(["text","reply_buttons","cta_url","baskets","offers","products","product_lookup","checkout","silence"]);
const toolCfg=(v:any)=>{if(!v||typeof v!=="object"||Array.isArray(v))return {};try{const s=JSON.stringify(v);return s.length<=12000?JSON.parse(s):{}}catch{return {}}};
const stagesOf=(v:any)=>{const input=Array.isArray(v)?v:[];return input.slice(0,5).map((s:any)=>({question:clean(s?.question,600),variations:vars(s?.variations),answer:clean(s?.answer,2000),response_mode:clean(s?.response_mode,40)||"text",tool_config:toolCfg(s?.tool_config)})).filter((s:any)=>s.question)};
const arr=(v:any)=>Array.isArray(v)?v:[];
function finalText(data:any){return arr(data?.output).flatMap((x:any)=>arr(x?.content)).filter((x:any)=>x?.type==="output_text").map((x:any)=>String(x.text||"")).join("").trim()}
function productTerm(message:string){return clean(message.replace(/\b(voces?|vocês?|tem|temos|vende|vendem|quanto|custa|preco|preço|qual|o|a|um|uma|esse|essa|produto|por favor)\b/gi," "),120)||clean(message,120)}
function deterministic(message:string){const s=norm(message);if(/\b(finalizar|fechar|concluir|checkout|terminar compra|confirmar pedido)\b/.test(s))return {mode:"checkout",reply:"Claro. Vamos finalizar seu pedido.",ui:{type:"checkout"}};if(/\b(oferta|ofertas|promocao|promocoes)\b/.test(s))return {mode:"offers",reply:"Estas são as ofertas disponíveis agora.",ui:{type:"products",offers:true}};if(/\b(cesta|cestas|cesta basica|cestas basicas)\b/.test(s))return {mode:"baskets",reply:"Claro! Veja nossas cestas básicas.",ui:{type:"baskets"}};if(/\b(limpeza|lavanderia|sabao|amaciante|desinfetante)\b/.test(s))return {mode:"products",reply:"Veja os produtos de limpeza e lavanderia.",ui:{type:"products",category:"limpeza_lavanderia"}};if(/\b(higiene|beleza|shampoo|sabonete|desodorante|creme)\b/.test(s))return {mode:"products",reply:"Veja os produtos de higiene e beleza.",ui:{type:"products",category:"higiene_beleza"}};if(/\b(pet|cachorro|gato|vassoura|rodo|balde)\b/.test(s))return {mode:"products",reply:"Veja os produtos de Casa e Pet.",ui:{type:"products",category:"casa_pet"}};if(/\b(mercearia)\b/.test(s))return {mode:"products",reply:"Veja os produtos de mercearia.",ui:{type:"products",category:"mercearia"}};if(/\b(tem|vende|vendem|preco|quanto custa|quanto esta|quanto ta)\b/.test(s))return {mode:"product_lookup",reply:"Vou pesquisar para você.",ui:{type:"product_lookup",query:productTerm(message)}};return null}
function directRule(message:string,rules:any[]){const q=norm(message);let best:any=null,bestScore=0;for(const rule of rules){const st=stagesOf(rule.stages)[0]||{question:rule.question,variations:rule.variations,answer:rule.answer,response_mode:rule.response_mode,tool_config:rule.tool_config};const phrases=[st.question,...vars(st.variations)].map(norm).filter(Boolean);for(const p of phrases){let score=0;if(q===p)score=1;else if(q.includes(p)||p.includes(q))score=.86;else{const a=new Set(q.split(/\s+/).filter(x=>x.length>2)),b=new Set(p.split(/\s+/).filter(x=>x.length>2)),hit=[...a].filter(x=>b.has(x)).length;score=hit/Math.max(1,Math.max(a.size,b.size))}if(score>bestScore){bestScore=score;best={rule,stage:st,score}}}}return best}
function ruleResult(stage:any,source:string,aiUsed=false,ruleQuestion:string|null=null){const mode=clean(stage?.response_mode,40),tool=toolCfg(stage?.tool_config),reply=clean(stage?.answer,1800);let ui:any={type:"none"};if(mode==="reply_buttons")ui={type:"chips",items:arr(tool.buttons).map((x:any)=>clean(x?.label||x?.value||x,80)).filter(Boolean).slice(0,8)};else if(mode==="cta_url")ui={type:"link",label:clean(tool.label||"Abrir",40),url:clean(tool.url,1000)};else if(mode==="baskets")ui={type:"baskets"};else if(mode==="offers")ui={type:"products",offers:true};else if(mode==="products")ui={type:"products",category:clean(tool.category,40)||null};else if(mode==="product_lookup")ui={type:"product_lookup",query:clean(tool.query,120)};else if(mode==="checkout")ui={type:"checkout"};return {source,ai_used:aiUsed,mode,reply,ui,rule_question:ruleQuestion}}
async function aiChoose(message:string,rules:any[],runtime:any){const key=Deno.env.get("OPENAI_API_KEY")||"";if(!key||runtime?.classifier_ai_enabled===false||!rules.length)return null;const candidates=rules.slice(0,Math.max(1,Math.min(10,Number(runtime?.max_candidate_rules||5)))).map((r:any)=>{const s=stagesOf(r.stages)[0]||r;return {id:r.id,question:s.question,variations:vars(s.variations),mode:s.response_mode}});const model=(Deno.env.get("OPENAI_CONVERSATION_MODEL")||"").startsWith("gpt-5.6-")?Deno.env.get("OPENAI_CONVERSATION_MODEL"):"gpt-5.6-luna";try{const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model,store:false,max_output_tokens:100,reasoning:{effort:"low"},instructions:"Classifique a mensagem somente entre as regras candidatas do Chat Comprar. Se nenhuma servir, matched=false. Não invente regras.",input:[{role:"user",content:[{type:"input_text",text:JSON.stringify({message,candidates})}]}],text:{verbosity:"low",format:{type:"json_schema",name:"route",strict:true,schema:{type:"object",additionalProperties:false,properties:{matched:{type:"boolean"},id:{type:"string"}},required:["matched","id"]}}}}),signal:AbortSignal.timeout(20000)});const data=await response.json().catch(()=>({}));if(!response.ok)return null;const parsed=JSON.parse(finalText(data)||"{}");if(!parsed.matched)return null;return rules.find((r:any)=>String(r.id)===String(parsed.id))||null}catch{return null}}
async function simulate(sb:any,message:string){const det=deterministic(message);if(det)return {source:"deterministic",ai_used:false,...det};const [{data:runtime},{data:rules}]=await Promise.all([sb.from("service_simple_runtime_config").select("*").eq("id",1).maybeSingle(),sb.from("service_simple_rules").select("*").eq("status","published").order("priority",{ascending:false}).limit(100)]);const list=arr(rules).filter((r:any)=>MODES.has(clean((stagesOf(r.stages)[0]||r).response_mode,40)));const direct=directRule(message,list);if(direct&&direct.score>=Number(runtime?.similarity_threshold??.3)){const st={...direct.stage,tool_config:{...toolCfg(direct.stage.tool_config),...(direct.stage.response_mode==="product_lookup"?{query:productTerm(message)}:{})}};return ruleResult(st,"rule",false,direct.stage.question)}const aiRule=runtime?.enabled===false?null:await aiChoose(message,list,runtime);if(aiRule){const st0=stagesOf(aiRule.stages)[0]||aiRule,st={...st0,tool_config:{...toolCfg(st0.tool_config),...(st0.response_mode==="product_lookup"?{query:productTerm(message)}:{})}};return ruleResult(st,"ai_rule",true,st0.question)}return {source:"fallback",ai_used:false,mode:"reply_buttons",reply:"Posso te ajudar por aqui. Escolha uma opção:",ui:{type:"chips",items:["Cestas","Ofertas","Produtos"]},rule_question:null}}

Deno.serve(async(req:Request)=>{
  if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});if(req.method!=="POST")return json({ok:false,error:"method_not_allowed"},405);
  const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)return json({ok:false,error:"server_config"},500);
  const token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!token)return json({ok:false,error:"missing_token"},401);
  const sb=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const {data:userData,error:userError}=await sb.auth.getUser(token);if(userError||!userData?.user?.id)return json({ok:false,error:"invalid_user"},401);
  const {data:admin,error:adminError}=await sb.from("admin_users").select("role,is_active,display_name").eq("user_id",userData.user.id).maybeSingle();if(adminError)return json({ok:false,error:"admin_lookup_failed"},500);if(!admin?.is_active)return json({ok:false,error:"admin_not_authorized"},403);
  const isOwner=admin.role==="owner",canEdit=isOwner||["admin","manager","operator"].includes(admin.role);let body:any={};try{body=await req.json()}catch{return json({ok:false,error:"invalid_json"},400)}const action=clean(body?.action||"dashboard",40).toLowerCase();
  if(action==="dashboard"){const [{data:runtime},{count:total},{count:published},{count:drafts}]=await Promise.all([sb.from("service_simple_runtime_config").select("*").eq("id",1).maybeSingle(),sb.from("service_simple_rules").select("id",{count:"exact",head:true}),sb.from("service_simple_rules").select("id",{count:"exact",head:true}).eq("status","published"),sb.from("service_simple_rules").select("id",{count:"exact",head:true}).eq("status","draft")]);return json({ok:true,user:{role:admin.role,display_name:admin.display_name||null},runtime,counts:{total:total||0,published:published||0,drafts:drafts||0}})}
  if(action==="runtime_save"){if(!canEdit)return json({ok:false,error:"editor_required"},403);const patch={enabled:body?.enabled!==false,strict_mode:true,classifier_ai_enabled:body?.classifier_ai_enabled!==false,generative_ai_enabled:body?.generative_ai_enabled!==false,humanize_all_replies:false,max_history_messages:Math.round(clamp(body?.max_history_messages,0,4,2)),max_candidate_rules:Math.round(clamp(body?.max_candidate_rules,1,10,5)),similarity_threshold:clamp(body?.similarity_threshold,0,1,.3),fallback_mode:"silence",updated_at:new Date().toISOString()};const {data,error}=await sb.from("service_simple_runtime_config").update(patch).eq("id",1).select("*").single();if(error)return json({ok:false,error:"runtime_save_failed",detail:error.message},400);return json({ok:true,runtime:data})}
  if(action==="list"){const {data,error}=await sb.from("service_simple_rules").select("*").order("priority",{ascending:false}).order("updated_at",{ascending:false}).limit(300);if(error)return json({ok:false,error:"list_failed",detail:error.message},500);return json({ok:true,items:data||[]})}
  if(action==="save"){if(!canEdit)return json({ok:false,error:"editor_required"},403);const id=uuid(body?.id),stages=stagesOf(body?.stages);if(!stages.length)return json({ok:false,error:"stage_required"},400);for(const s of stages){if(!MODES.has(s.response_mode))return json({ok:false,error:"invalid_response_mode"},400);if(s.response_mode==="text"&&!s.answer)return json({ok:false,error:"answer_required"},400)}const first=stages[0],row={question:first.question,variations:first.variations,answer:first.answer,response_mode:first.response_mode,tool_config:first.tool_config,stages,priority:Math.max(0,Math.min(100,Number(body?.priority??50)||50)),updated_by:userData.user.id,updated_at:new Date().toISOString()};let item:any,error:any;if(id)({data:item,error}=await sb.from("service_simple_rules").update(row).eq("id",id).select("*").single());else ({data:item,error}=await sb.from("service_simple_rules").insert({...row,created_by:userData.user.id}).select("*").single());if(error)return json({ok:false,error:"save_failed",detail:error.message},400);return json({ok:true,item})}
  if(action==="set_status"){if(!isOwner)return json({ok:false,error:"owner_required"},403);const id=uuid(body?.id),status=clean(body?.status,30);if(!id||!["draft","published","archived"].includes(status))return json({ok:false,error:"invalid_status"},400);const {data:item,error}=await sb.from("service_simple_rules").update({status,updated_by:userData.user.id,updated_at:new Date().toISOString()}).eq("id",id).select("*").single();if(error)return json({ok:false,error:"status_update_failed",detail:error.message},400);return json({ok:true,item})}
  if(action==="simulate"){const message=clean(body?.message,800);if(!message)return json({ok:false,error:"message_required"},400);return json({ok:true,result:await simulate(sb,message)})}
  return json({ok:false,error:"unknown_action"},400);
});
