import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.58.0";
const U=Deno.env.get("SUPABASE_URL")||"";
const K=(()=>{try{return JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}").default||Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||""}catch{return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||""}})();
const db=createClient(U,K,{auth:{persistSession:false,autoRefreshToken:false}});
const LEGACY="https://qxstkwshuvplmmftrctj.supabase.co/functions/v1/vitrine-admin-v1";
const O=new Set(["https://donaantonia.com.br","https://www.donaantonia.com.br"]);
const LOCAL=new Set(["health","products","product_facets","product_save","offer_save","expirations","expiration_save","expiry_alerts","product_lifecycle_audit","ean_lookup","balance_confirm","gondolas","gondola","gondola_create","gondola_assign","gondola_shelf_update","gondola_remove"]);
const cors=(r:Request)=>{const o=r.headers.get("origin")||"";return {"Access-Control-Allow-Origin":O.has(o)?o:"https://www.donaantonia.com.br","Vary":"Origin","Access-Control-Allow-Headers":"content-type,authorization","Access-Control-Allow-Methods":"GET,POST,OPTIONS"}};
const js=(r:Request,b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors(r),"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});
const tx=(v:any,n=500)=>String(v??"").replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").trim().slice(0,n);
const dg=(v:any,n=30)=>String(v??"").replace(/\D+/g,"").slice(0,n);
const id=(v:any)=>{const s=tx(v,64);return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(s)?s:""};
const nm=(v:any,a=0,b=999999999)=>{const n=Number(v);return Number.isFinite(n)?Math.max(a,Math.min(b,n)):a};
const dt=(v:any)=>/^\d{4}-\d{2}-\d{2}$/.test(tx(v,10))?tx(v,10):null;
const meta=(v:any)=>v&&typeof v==="object"&&!Array.isArray(v)?v:{};
function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"America/Cuiaba",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
function add(d:string,n:number){const x=new Date(d+"T12:00:00Z");x.setUTCDate(x.getUTCDate()+n);return x.toISOString().slice(0,10)}
function days(a:string,b:string){return Math.round((Date.parse(b+"T12:00:00Z")-Date.parse(a+"T12:00:00Z"))/86400000)}
function offer(p:any){if(!p.is_offer||p.offer_price==null)return null;const m=meta(p.metadata);return {id:p.id,product_id:p.id,title:p.name,sale_price_cents:Math.round(Number(p.offer_price||0)*100),starts_at:m.offer_starts_at||null,ends_at:m.offer_ends_at||null,active:true,metadata:{source:m.offer_source||"manual",discount_percent:m.offer_discount_percent??null,duration_mode:m.offer_duration_mode||"stock_zero"}}}
function mp(p:any){const m=meta(p.metadata);return {id:p.id,sku:p.sku||null,gtin:p.gtin||null,name:p.name||"",description:p.description_short||p.description_long||"",active:p.is_active!==false,sale_price_cents:Math.round(Number(p.price||0)*100),stock_quantity:Number(p.stock||0),image_url:p.image_url||"",expiration_date:p.validity_date||null,auto_expiry_offer_enabled:m.auto_expiry_offer_enabled===true,deactivation_reason:m.deactivation_reason||null,deactivated_at:m.deactivated_at||null,updated_at:p.updated_at,packaging:p.packaging||"",subcategory:p.subcategory||"",detailed_subcategory:p.subsubcategory||"",category:p.sales_category||p.storefront_category||p.category||"",gondola_number:p.gondola&&/^\d+$/.test(String(p.gondola))?Number(p.gondola):null,shelf_label:p.shelf||null,offer:offer(p)}}
async function one(pid:string){const r=await db.from("products").select("*").eq("id",pid).maybeSingle();if(r.error)throw r.error;return r.data}
async function aud(b:any,a:any,p:any,src:string){if(!b||!a)return;const ba=b.is_active!==false,aa=a.is_active!==false,bd=b.validity_date||null,ad=a.validity_date||null;if(ba===aa&&bd===ad)return;let ev="expiration_changed",at="operator",al=tx(p?.operator,80)||"Operador não identificado";if(ba!==aa&&aa)ev="reactivated";else if(ba!==aa&&!aa){if(meta(a.metadata).deactivation_reason==="expired"){ev="auto_expired_deactivation";at="system";al="Sistema · regra de validade"}else ev="manual_deactivated"}await db.from("product_lifecycle_audit").insert({product_id:a.id,event:ev,actor_type:at,actor_label:al,previous_active:ba,new_active:aa,previous_expiration_date:bd,new_expiration_date:ad,details:{source:src}})}
async function rec(){const t=today(),q=await db.from("products").select("id,name,price,stock,is_active,is_offer,offer_price,validity_date,metadata").not("validity_date","is",null).limit(5000);if(q.error)throw q.error;for(const p of q.data||[]){const m=meta(p.metadata),d=days(t,String(p.validity_date));if(d<0&&p.is_active!==false){const r=await db.from("products").update({is_active:false,stock:0,is_offer:false,offer_price:null,metadata:{...m,deactivation_reason:"expired",deactivated_at:new Date().toISOString(),offer_source:null,offer_discount_percent:null},updated_at:new Date().toISOString()}).eq("id",p.id).select("*").single();if(!r.error)await aud(p,r.data,{operator:"Sistema"},"expiry_reconcile");continue}if(p.is_active===false)continue;const auto=m.auto_expiry_offer_enabled===true;if(auto&&d>=0&&d<=90){const pc=d<30?40:d<60?20:10,op=Math.round(Number(p.price||0)*(100-pc))/100;if(p.is_offer!==true||Number(p.offer_price)!==op||m.offer_source!=="expiry_auto"||Number(m.offer_discount_percent)!==pc)await db.from("products").update({is_offer:true,offer_price:op,metadata:{...m,offer_source:"expiry_auto",offer_discount_percent:pc,offer_duration_mode:"validity"},updated_at:new Date().toISOString()}).eq("id",p.id)}else if(m.offer_source==="expiry_auto"&&(p.is_offer||p.offer_price!=null))await db.from("products").update({is_offer:false,offer_price:null,metadata:{...m,offer_source:null,offer_discount_percent:null},updated_at:new Date().toISOString()}).eq("id",p.id)}}
async function products(u:URL){const off=Math.floor(nm(u.searchParams.get("offset"),0,100000)),lim=Math.floor(nm(u.searchParams.get("limit")||60,1,100)),qv=tx(u.searchParams.get("q"),100).replace(/[,%()]/g," "),cat=tx(u.searchParams.get("category"),120),sub=tx(u.searchParams.get("subcategory"),120),act=tx(u.searchParams.get("active"),12);let q=db.from("products").select("*").order("name").range(off,off+lim-1);if(cat)q=q.eq("sales_category",cat);if(sub)q=q.eq("subcategory",sub);if(act==="true")q=q.eq("is_active",true);if(act==="false")q=q.eq("is_active",false);if(qv)q=q.or("name.ilike.%"+qv+"%,gtin.ilike.%"+qv+"%,sku.ilike.%"+qv+"%");const r=await q;if(r.error)throw r.error;return {products:(r.data||[]).map(mp),next_offset:(r.data||[]).length===lim?off+lim:null}}
async function facets(c:string){const r=await db.from("products").select("sales_category,storefront_category,category,subcategory").limit(5000);if(r.error)throw r.error;const cm=new Map(),sm=new Map();for(const p of r.data||[]){const x=tx(p.sales_category||p.storefront_category||p.category,120),s=tx(p.subcategory,120);if(x)cm.set(x,(cm.get(x)||0)+1);if(s&&(!c||x===c))sm.set(s,(sm.get(s)||0)+1)}return {categories:[...cm].map(([value,count])=>({value,label:value,count})).sort((a,b)=>a.label.localeCompare(b.label,"pt-BR")),subcategories:[...sm].map(([value,count])=>({value,label:value,count})).sort((a,b)=>a.label.localeCompare(b.label,"pt-BR"))}}
async function saveProduct(p:any){const pid=id(p?.id),name=tx(p?.name,300);if(!name)return {error:"name_required",status:400};const b=pid?await one(pid):null,m=meta(b?.metadata),exp=Object.prototype.hasOwnProperty.call(p||{},"expiration_date")?dt(p.expiration_date):b?.validity_date||null;if(p?.expiration_date&&!exp)return {error:"invalid_expiration_date",status:400};let active=Object.prototype.hasOwnProperty.call(p||{},"active")?p.active!==false:(b?.is_active!==false),stock=Number(p?.stock_quantity??b?.stock??0),io=b?.is_offer===true,op=b?.offer_price??null,nmeta={...m,auto_expiry_offer_enabled:p?.auto_expiry_offer_enabled===true};if(exp&&days(today(),exp)<0){active=false;stock=0;io=false;op=null;nmeta={...nmeta,deactivation_reason:"expired",deactivated_at:new Date().toISOString(),offer_source:null}}else if(active&&m.deactivation_reason==="expired")nmeta={...nmeta,deactivation_reason:null,deactivated_at:null};const patch:any={name,sku:tx(p?.sku,120)||null,gtin:dg(p?.gtin)||null,price:Number(p?.sale_price_cents||0)/100,stock,is_active:active,validity_date:exp,sales_category:tx(p?.category,120)||null,storefront_category:tx(p?.category,120)||null,category:tx(p?.category,120)||null,subcategory:tx(p?.subcategory,120)||null,packaging:tx(p?.packaging,120)||null,image_url:tx(p?.image_url,1200)||null,description_short:tx(p?.description,1000)||null,is_offer:io,offer_price:op,metadata:nmeta,updated_at:new Date().toISOString()};let r:any;if(pid)r=await db.from("products").update(patch).eq("id",pid).select("*").single();else r=await db.from("products").insert({...patch,source_system:"admin_registration",sync_status:"local"}).select("*").single();if(r.error)throw r.error;if(b)await aud(b,r.data,p,"product_save");await rec();const fr=await one(r.data.id);return {product_id:r.data.id,product:mp(fr)}}
async function saveOffer(p:any){const pid=id(p?.product_id);if(!pid)return {error:"invalid_product",status:400};const x=await one(pid);if(!x)return {error:"product_not_found",status:404};const m=meta(x.metadata),active=p?.active===true,price=Number(x.price||0),sale=Number(p?.sale_price_cents||0)/100,disc=Number(p?.discount_percent||0),dur=tx(p?.duration,20)||"stock_zero";let end:any=null;if(["5","10","15"].includes(dur))end=new Date(Date.now()+Number(dur)*86400000).toISOString();const op=sale>0?sale:(disc>0&&disc<100?Math.round(price*(100-disc))/100:null),nmeta={...m,auto_expiry_offer_enabled:false,offer_source:active?"manual":null,offer_discount_percent:active?disc:null,offer_duration_mode:dur,offer_starts_at:active?new Date().toISOString():null,offer_ends_at:active?end:null};const r=await db.from("products").update({is_offer:active,offer_price:active?op:null,metadata:nmeta,updated_at:new Date().toISOString()}).eq("id",pid).select("*").single();if(r.error)throw r.error;return {product_id:pid,product:mp(r.data),offer:offer(r.data)}}
async function exps(){await rec();const t=today(),h=add(t,90),r=await db.from("products").select("*").eq("is_active",true).not("validity_date","is",null).lte("validity_date",h).order("validity_date").limit(5000);if(r.error)throw r.error;const rows=(r.data||[]).map((p:any)=>{const d=days(t,String(p.validity_date));return {...mp(p),days_left:d,suggested_discount_percent:d<30?40:d<60?20:10}}),all=await db.from("products").select("id,is_active,validity_date,metadata").limit(5000);if(all.error)throw all.error;const ac=(all.data||[]).filter((p:any)=>p.is_active!==false),ex=(all.data||[]).filter((p:any)=>p.is_active===false&&meta(p.metadata).deactivation_reason==="expired"),e=await db.from("products").select("*").eq("is_active",false).limit(5000);if(e.error)throw e.error;return {active_only:true,products:rows,summary:{expired_deactivated:ex.length,under_30:rows.filter((x:any)=>x.days_left<30).length,days_30_59:rows.filter((x:any)=>x.days_left>=30&&x.days_left<60).length,days_60_90:rows.filter((x:any)=>x.days_left>=60&&x.days_left<=90).length,without_expiration:ac.filter((p:any)=>!p.validity_date).length,auto_enabled:ac.filter((p:any)=>meta(p.metadata).auto_expiry_offer_enabled===true).length,total_products:ac.length},expired_deactivated:(e.data||[]).filter((p:any)=>meta(p.metadata).deactivation_reason==="expired").slice(0,30).map(mp)}}
async function expSave(p:any){const pid=id(p?.product_id);if(!pid)return {error:"invalid_product",status:400};const b=await one(pid);if(!b)return {error:"product_not_found",status:404};const exp=p?.expiration_date?dt(p.expiration_date):null;if(p?.expiration_date&&!exp)return {error:"invalid_expiration_date",status:400};let m={...meta(b.metadata),auto_expiry_offer_enabled:p?.auto_expiry_offer_enabled===true},patch:any={validity_date:exp,metadata:m,updated_at:new Date().toISOString()};if(exp&&days(today(),exp)<0)patch={...patch,is_active:false,stock:0,is_offer:false,offer_price:null,metadata:{...m,deactivation_reason:"expired",deactivated_at:new Date().toISOString(),offer_source:null}};else if(meta(b.metadata).deactivation_reason==="expired")patch.metadata={...m,deactivation_reason:null,deactivated_at:null};const r=await db.from("products").update(patch).eq("id",pid).select("*").single();if(r.error)throw r.error;await aud(b,r.data,p,"expiration_save");await rec();return {product:mp(await one(pid))}}
async function auditList(l:number){const r=await db.from("product_lifecycle_audit").select("*").order("created_at",{ascending:false}).limit(l);if(r.error)throw r.error;const ids=[...new Set((r.data||[]).map((x:any)=>x.product_id))],m=new Map();if(ids.length){const p=await db.from("products").select("id,name,sku,gtin").in("id",ids);for(const x of p.data||[])m.set(x.id,x)}return (r.data||[]).map((x:any)=>({...x,product:m.get(x.product_id)||null}))}
async function ean(v:any){const d=dg(v);if(!d)return {error:"invalid_ean",status:400};const r=await db.from("products").select("*").eq("gtin",d).limit(1).maybeSingle();if(r.error)throw r.error;if(!r.data)return {error:"product_not_found",status:404};return {product:mp(r.data)}}
async function bal(p:any){const pid=id(p?.product_id),q=Number(p?.quantity);if(!pid)return {error:"invalid_product",status:400};if(!Number.isFinite(q)||q<0)return {error:"invalid_quantity",status:400};const r=await db.from("products").update({stock:q,last_counted_at:new Date().toISOString(),physically_verified:true,updated_at:new Date().toISOString()}).eq("id",pid).select("*").single();if(r.error)throw r.error;return {product:mp(r.data)}}
async function glist(){const g=await db.from("vitrine_gondolas").select("*").eq("active",true).order("number"),p=await db.from("products").select("gondola").not("gondola","is",null).limit(5000);if(g.error)throw g.error;if(p.error)throw p.error;const c=new Map();for(const x of p.data||[])c.set(String(x.gondola),(c.get(String(x.gondola))||0)+1);return {gondolas:(g.data||[]).map((x:any)=>({...x,product_count:c.get(String(x.number))||0}))}}
async function gone(v:any){const gid=id(v);if(!gid)return {error:"invalid_gondola",status:400};const g=await db.from("vitrine_gondolas").select("*").eq("id",gid).eq("active",true).maybeSingle();if(g.error)throw g.error;if(!g.data)return {error:"gondola_not_found",status:404};const p=await db.from("products").select("*").eq("gondola",String(g.data.number)).order("name").limit(5000);if(p.error)throw p.error;return {gondola:g.data,products:(p.data||[]).map(mp)}}
async function gcreate(p:any){const n=Math.floor(Number(p?.number));if(!Number.isInteger(n)||n<1||n>9999)return {error:"invalid_gondola",status:400};let g=await db.from("vitrine_gondolas").select("*").eq("number",n).maybeSingle();if(g.error)throw g.error;if(g.data){if(!g.data.active)g=await db.from("vitrine_gondolas").update({active:true,updated_at:new Date().toISOString()}).eq("id",g.data.id).select("*").single();return {gondola:g.data,reused:true}}g=await db.from("vitrine_gondolas").insert({number:n}).select("*").single();if(g.error)throw g.error;return {gondola:g.data,reused:false}}
async function gassign(p:any){const gid=id(p?.gondola_id);if(!gid)return {error:"invalid_gondola",status:400};const g=await db.from("vitrine_gondolas").select("*").eq("id",gid).eq("active",true).maybeSingle();if(g.error)throw g.error;if(!g.data)return {error:"gondola_not_found",status:404};const e:any=await ean(p?.ean);if(e.error)return e;const b=await one(e.product.id),prev=b?.gondola&&/^\d+$/.test(String(b.gondola))?Number(b.gondola):null,r=await db.from("products").update({gondola:String(g.data.number),updated_at:new Date().toISOString()}).eq("id",e.product.id).select("*").single();if(r.error)throw r.error;return {product:mp(r.data),previous_gondola_number:prev}}
async function gshelf(p:any){const gid=id(p?.gondola_id),pid=id(p?.product_id);if(!gid||!pid)return {error:"invalid_request",status:400};const g=await db.from("vitrine_gondolas").select("*").eq("id",gid).maybeSingle();if(g.error)throw g.error;if(!g.data)return {error:"gondola_not_found",status:404};const s=tx(p?.shelf_label,24)||null,r=await db.from("products").update({shelf:s,updated_at:new Date().toISOString()}).eq("id",pid).eq("gondola",String(g.data.number)).select("id").maybeSingle();if(r.error)throw r.error;if(!r.data)return {error:"product_not_in_gondola",status:404};return {product_id:pid,shelf_label:s}}
async function grem(p:any){const gid=id(p?.gondola_id),pid=id(p?.product_id);if(!gid||!pid)return {error:"invalid_request",status:400};const g=await db.from("vitrine_gondolas").select("*").eq("id",gid).maybeSingle();if(g.error)throw g.error;if(!g.data)return {error:"gondola_not_found",status:404};const r=await db.from("products").update({gondola:null,shelf:null,updated_at:new Date().toISOString()}).eq("id",pid).eq("gondola",String(g.data.number));if(r.error)throw r.error;return {product_id:pid,removed:true}}
async function proxy(r:Request,u:URL,a:string){const t=new URL(LEGACY);t.searchParams.set("action",a);for(const [k,v] of u.searchParams)if(k!=="action")t.searchParams.set(k,v);const i:any={method:r.method,headers:{"Content-Type":r.headers.get("content-type")||"application/json"}};if(r.method!=="GET"&&r.method!=="HEAD")i.body=await r.clone().text();const x=await fetch(t,i),b=await x.text();return new Response(b,{status:x.status,headers:{...cors(r),"Content-Type":x.headers.get("content-type")||"application/json; charset=utf-8","Cache-Control":"no-store","X-Dona-Antonia-Backend":"legacy-proxy"}})}
Deno.serve(async(r:Request)=>{if(r.method==="OPTIONS")return new Response(null,{status:204,headers:cors(r)});const u=new URL(r.url),a=tx(u.searchParams.get("action")||(r.method==="GET"?"health":""),80);if(!LOCAL.has(a))return proxy(r,u,a);try{if(a==="health")return js(r,{ok:true,service:"admin-products-live-v1",mode:"canonical-admin-gateway",version:8,legacy_proxy:true});if(r.method==="GET"&&a==="products")return js(r,{ok:true,...await products(u)});if(r.method==="GET"&&a==="product_facets")return js(r,{ok:true,...await facets(tx(u.searchParams.get("category"),120))});if(r.method==="GET"&&a==="expirations")return js(r,{ok:true,...await exps()});if(r.method==="GET"&&a==="expiry_alerts"){const x=await exps();return js(r,{ok:true,summary:x.summary,products:x.products.slice(0,12),expired_deactivated:x.expired_deactivated})}if(r.method==="GET"&&a==="product_lifecycle_audit")return js(r,{ok:true,audit:await auditList(Math.floor(nm(u.searchParams.get("limit")||40,1,100)))});if(r.method==="GET"&&a==="ean_lookup"){const x:any=await ean(u.searchParams.get("ean"));return x.error?js(r,{ok:false,error:x.error},x.status):js(r,{ok:true,...x})}if(r.method==="GET"&&a==="gondolas")return js(r,{ok:true,...await glist()});if(r.method==="GET"&&a==="gondola"){const x:any=await gone(u.searchParams.get("id"));return x.error?js(r,{ok:false,error:x.error},x.status):js(r,{ok:true,...x})}let p:any={};try{p=await r.json()}catch{}let x:any;if(a==="product_save")x=await saveProduct(p);else if(a==="offer_save")x=await saveOffer(p);else if(a==="expiration_save")x=await expSave(p);else if(a==="balance_confirm")x=await bal(p);else if(a==="gondola_create")x=await gcreate(p);else if(a==="gondola_assign")x=await gassign(p);else if(a==="gondola_shelf_update")x=await gshelf(p);else if(a==="gondola_remove")x=await grem(p);else return js(r,{ok:false,error:"method_not_allowed"},405);return x?.error?js(r,{ok:false,error:x.error},x.status||400):js(r,{ok:true,...x})}catch(e){console.error("canonical_admin_error",a,String(e?.message||e));return js(r,{ok:false,error:"service_error",detail:String(e?.message||e)},500)}});
