#!/usr/bin/env python3
"""Dona Antônia — production product image studio.

Processes at most 9 current optimized product images per run.

Safety/idempotency guarantees:
- only discovers WebP assets named ``*foto-atual-otimizada*.webp`` under
  ``site/img/produtos_3``;
- keeps a persistent SHA-256 ledger in ``state.json``;
- if the current file hash equals the ledger's processed/output hash, the image
  is skipped and is never processed again;
- if the file is later replaced with a genuinely different source image, its
  hash changes and the new source becomes eligible once;
- no generative AI is used: RGB product pixels come from the real source image;
- the file is written back to the SAME repository path, so existing catalog URLs
  keep working;
- Git history remains the rollback/backup of the previous source image.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from PIL import Image
from rembg import new_session

BATCH_SIZE = 9
BACKGROUND = "#ECECEC"
PIPELINE_VERSION = "studio-v1-rembg-u2net-ececec-400-main-component"
DISCOVERY_ROOT = Path("site/img/produtos_3")
DEFAULT_STATE = Path("automation/product-image-studio/state.json")
DEFAULT_REPORT = Path("artifacts/product-image-studio-production/result.json")


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for block in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def load_helpers(repo_root: Path):
    helper_path = repo_root / "automation/product-image-studio/run_batch.py"
    spec = importlib.util.spec_from_file_location("product_image_studio_helpers", helper_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"unable to load helper module: {helper_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def load_state(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {
            "schema_version": 1,
            "pipeline_version": PIPELINE_VERSION,
            "background": BACKGROUND,
            "items": {},
        }
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("state file must contain a JSON object")
    data.setdefault("schema_version", 1)
    data.setdefault("pipeline_version", PIPELINE_VERSION)
    data.setdefault("background", BACKGROUND)
    data.setdefault("items", {})
    if not isinstance(data["items"], dict):
        raise ValueError("state.items must be a JSON object")
    return data


def discover_candidates(repo_root: Path, state: dict[str, Any]) -> tuple[list[dict[str, Any]], dict[str, int]]:
    root = repo_root / DISCOVERY_ROOT
    if not root.is_dir():
        raise FileNotFoundError(f"discovery root not found: {root}")

    items = state.get("items") or {}
    candidates: list[dict[str, Any]] = []
    scanned = 0
    skipped_processed = 0

    # Stable path order makes the backlog deterministic and auditable.
    for path in sorted(root.rglob("*foto-atual-otimizada*.webp")):
        if not path.is_file():
            continue
        scanned += 1
        rel = path.relative_to(repo_root).as_posix()
        current_hash = sha256_file(path)
        previous = items.get(rel) or {}

        # Core no-repeat guarantee: a file whose bytes equal the last produced
        # studio output is already done and cannot enter a new batch.
        if previous.get("output_sha256") == current_hash:
            skipped_processed += 1
            continue

        candidates.append({
            "path": path,
            "relative_path": rel,
            "source_sha256": current_hash,
            "source_bytes": path.stat().st_size,
        })

    return candidates[:BATCH_SIZE], {
        "scanned": scanned,
        "eligible_total": len(candidates),
        "selected": min(len(candidates), BATCH_SIZE),
        "skipped_already_processed": skipped_processed,
    }


def safe_write_webp(path: Path, payload: bytes) -> None:
    # Validate the generated bytes before replacing a live catalog asset.
    from io import BytesIO

    with Image.open(BytesIO(payload)) as probe:
        probe.load()
        if probe.format != "WEBP":
            raise RuntimeError(f"output is not WebP for {path}")
        if probe.size != (400, 400):
            raise RuntimeError(f"unexpected output size {probe.size} for {path}")

    tmp = path.with_suffix(path.suffix + ".studio-tmp")
    tmp.write_bytes(payload)
    os.replace(tmp, path)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", default=".")
    parser.add_argument("--state", default=str(DEFAULT_STATE))
    parser.add_argument("--report", default=str(DEFAULT_REPORT))
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    state_path = (repo_root / args.state).resolve()
    report_path = (repo_root / args.report).resolve()
    state_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.parent.mkdir(parents=True, exist_ok=True)

    helpers = load_helpers(repo_root)
    state = load_state(state_path)
    selected, discovery = discover_candidates(repo_root, state)

    report: dict[str, Any] = {
        "mode": "production_writeback_same_path",
        "created_at": utc_now(),
        "pipeline_version": PIPELINE_VERSION,
        "background": BACKGROUND,
        "batch_limit": BATCH_SIZE,
        "generative_ai_used": False,
        "openai_used": False,
        "openai_cost_usd": 0.0,
        "discovery": discovery,
        "processed": [],
        "errors": [],
    }

    if not selected:
        state["last_run_at"] = utc_now()
        state["last_run_selected"] = 0
        state["pipeline_version"] = PIPELINE_VERSION
        state["background"] = BACKGROUND
        state_path.write_text(json.dumps(state, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        report["status"] = "nothing_to_do"
        report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(json.dumps(report, ensure_ascii=False, indent=2))
        return 0

    session = new_session("u2net")
    items = state.setdefault("items", {})

    for candidate in selected:
        source: Path = candidate["path"]
        rel = candidate["relative_path"]
        source_hash = candidate["source_sha256"]
        try:
            isolated, segmentation = helpers.isolate_real_product(source, session)
            cell = helpers.make_studio_cell(isolated, BACKGROUND)
            encoded, webp_quality = helpers.encode_webp_under_target(cell)
            safe_write_webp(source, encoded)
            output_hash = sha256_file(source)

            # The ledger stores the hash of the bytes now living at the live
            # path. The next scheduled run sees the same hash and skips it.
            entry = {
                "status": "done",
                "pipeline_version": PIPELINE_VERSION,
                "background": BACKGROUND,
                "source_sha256_before": source_hash,
                "output_sha256": output_hash,
                "processed_at": utc_now(),
                "output_bytes": len(encoded),
                "webp_quality": webp_quality,
                "width": 400,
                "height": 400,
            }
            items[rel] = entry
            report["processed"].append({
                "path": rel,
                "source_sha256_before": source_hash,
                "output_sha256": output_hash,
                "source_bytes": candidate["source_bytes"],
                "output_bytes": len(encoded),
                "webp_quality": webp_quality,
                "segmentation": segmentation,
            })
        except Exception as exc:
            # Never mark a failed image as processed. A later run may retry it.
            report["errors"].append({"path": rel, "error": str(exc)})
            print(f"ERROR processing {rel}: {exc}", file=sys.stderr)

    state["schema_version"] = 1
    state["pipeline_version"] = PIPELINE_VERSION
    state["background"] = BACKGROUND
    state["last_run_at"] = utc_now()
    state["last_run_selected"] = len(selected)
    state["last_run_processed"] = len(report["processed"])
    state["last_run_errors"] = len(report["errors"])
    state_path.write_text(json.dumps(state, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    report["status"] = "completed" if not report["errors"] else "completed_with_errors"
    report["processed_count"] = len(report["processed"])
    report["error_count"] = len(report["errors"])
    report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({
        "status": report["status"],
        "scanned": discovery["scanned"],
        "eligible_total": discovery["eligible_total"],
        "skipped_already_processed": discovery["skipped_already_processed"],
        "processed_count": report["processed_count"],
        "error_count": report["error_count"],
        "openai_cost_usd": 0.0,
    }, ensure_ascii=False, indent=2))

    # Individual failures do not poison the whole queue, but if every selected
    # item failed, fail the Action so the problem is visible.
    if selected and not report["processed"] and report["errors"]:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
