import { loadCatalog, classify } from './catalog.js';
import { loadCart, clearCart, ensureBasket, basketTotal, extrasTotal, grandTotal, totalUnits, changeBasketQty, changeExtraQty, whatsappUrl } from './cart.js';

if ('scrollRestoration' in history) history.scrollRestoration = 'manual';
const params=new URLSearchParams(location.search), section=String(params.get('secao')||'categorias').toLowerCase(), basketParam=String(params.get('cesta')||'').trim();
const PAGE_SIZE=12, money=value=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}), $=id=>document.getElementById(id), n=value=>Number(value||0);
const sections=[{key:'cestas',label:'Cestas Básicas'},{key:'ofertas',label:'Ofertas'},{key:'mercearia',label:'Mercearia'},{key:'limpeza',label:'Lavanderia e Limpeza'},{key:'higiene',label:'Higiene e Beleza'},{key:'utilidades',label:'Utilidades e Pets'}];
const labels=Object.fromEntries(sections.map(x=>[x.key,x.label]));
const state={products:[],baskets:[],productByCode:new Map(),cart:loadCart(),basket:null,search:'',visibleCount:PAGE_SIZE,listKey:''};
const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const clean=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
function matches(item){const q=clean(state.search);return !q||clean([item.name,item.label,item.key,item.code,item.categoryText].filter(Boolean).join(' ')).includes(q)}
function basketByParam(v){const k=String(v).toLowerCase();return state.baskets.find(x=>[x.id,x.code].some(y=>String(y).toLowerCase()===k))}
function basketChanged(){return (state.cart.basket?.items||[]).some(x=>n(x.qty)!==n(x.baseQty))}
function summary(){const units=totalUnits(state.cart);$('summaryItems').innerHTML=!units?'<div class="checkout-empty">Seu pedido ainda está vazio.</div>':`${state.cart.basket?`<section class="checkout-group"><h3>${esc(state.cart.basket.name)} — ${basketChanged()?'ALTERADA':'PADRÃO'}</h3>${state.cart.basket.items.filter(x=>n(x.qty)>0).map(x=>`<div class="checkout-line"><span>${x.qty}x ${esc(x.name)}</span></div>`).join('')}</section>`:''}${Object.values(state.cart.extras||{}).filter(x=>n(x.qty)>0).length?`<section class="checkout-group"><h3>Produtos avulsos</h3>${Object.values(state.cart.extras).filter(x=>n(x.qty)>0).map(x=>`<div class="checkout-line"><span>${x.qty}x ${esc(x.name)}</span></div>`).join('')}</section>`:''}`;$('grandTotal').textContent=$('bottomTotal').textContent=money(grandTotal(state.cart));$('sendWhatsapp').disabled=!units;$('sendWhatsapp').textContent=basketParam?'Confirmar minha cesta':'Adicionar à compra';}
function categories(){$('basketMode').hidden=true;$('offersMode').hidden=false;$('categoryTabs').innerHTML='<strong class="section-name">O que você procura?</strong>';$('offersList').className='category-menu';$('offersList').innerHTML=sections.filter(matches).map(x=>`<a class="menu-button" href="?secao=${x.key}"><span class="menu-label">${esc(x.label)}</span><span class="menu-arrow">›</span></a>`).join('');summary()}
function baskets(){$('basketMode').hidden=true;$('offersMode').hidden=false;$('categoryTabs').innerHTML='<strong class="section-name">Escolha sua cesta</strong>';$('offersList').className='offer-grid basket-grid';$('offersList').innerHTML=state.baskets.filter(matches).map(x=>`<a class="catalog-card" href="?cesta=${encodeURIComponent(x.id)}"><div class="catalog-image-wrap"><img class="catalog-image" src="${esc(x.image)}" alt="${esc(x.name)}" loading="lazy" decoding="async"></div><div class="catalog-body"><div class="catalog-name">${esc(x.name)}</div><div class="catalog-price">${money(x.price)}</div></div></a>`).join('');summary()}
function basketDetail(basket){state.basket=basket;ensureBasket(state.cart,basket,state.productByCode);$('basketMode').hidden=false;$('offersMode').hidden=true;$('basketImage').src=basket.image;$('basketImage').alt=basket.name;$('basketTitle').textContent=basket.name;$('basketPrice').textContent=money(basketTotal(state.cart));$('basketItems').innerHTML=state.cart.basket.items.filter(matches).map(item=>{const i=state.cart.basket.items.indexOf(item),p=state.productByCode.get(String(item.code).toLowerCase());return `<div class="basket-item"><img class="basket-item-image" src="${esc(p?.image||'/img/logoantonia5.png')}" alt="" loading="lazy" decoding="async" width="72" height="72"><div class="basket-item-info"><span class="basket-item-name">${esc(item.name)}</span><small>${item.qty===item.baseQty?'Quantidade original':'Quantidade alterada'}</small></div><div class="qty"><button data-basket-delta="-1" data-index="${i}">−</button><span>${item.qty}</span><button data-basket-delta="1" data-index="${i}">+</button></div></div>`}).join('');summary()}
function products(key){$('basketMode').hidden=true;$('offersMode').hidden=false;$('categoryTabs').innerHTML=`<strong class="section-name">${esc(labels[key]||'Produtos')}</strong>`;const list=state.products.filter(p=>key==='ofertas'?p.offer:classify(p)===key).filter(matches).slice(0,state.visibleCount);$('offersList').className='product-list';$('offersList').innerHTML=list.map(p=>{const q=state.cart.extras?.[p.code]?.qty||0;return `<article class="offer-card"><div class="offer-image-wrap"><img class="offer-image" src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy" decoding="async" width="80" height="80"></div><div class="offer-body"><div class="offer-name">${esc(p.name)}</div><div class="offer-price">${money(p.price)}</div><div class="offer-actions">${q?`<div class="qty"><button data-extra-delta="-1" data-code="${esc(p.code)}">−</button><span>${q}</span><button data-extra-delta="1" data-code="${esc(p.code)}">+</button></div>`:`<button class="offer-add" data-add="${esc(p.code)}">Adicionar</button>`}</div></div></article>`}).join('');summary()}
function render(){if(basketParam&&state.basket)basketDetail(state.basket);else if(section==='categorias')categories();else if(section==='cestas')baskets();else products(labels[section]?section:'ofertas')}
function bind(){$('sendWhatsapp').addEventListener('click',()=>location.href=whatsappUrl(state.cart,money,!basketParam));$('searchInput').addEventListener('input',e=>{state.search=e.target.value;render()});document.addEventListener('click',e=>{const b=e.target.closest('[data-basket-delta]');if(b){changeBasketQty(state.cart,+b.dataset.index,+b.dataset.basketDelta);return render()}const a=e.target.closest('[data-add]');if(a){const p=state.productByCode.get(String(a.dataset.add).toLowerCase());if(p)changeExtraQty(state.cart,p,1);return render()}const x=e.target.closest('[data-extra-delta]');if(x){const p=state.productByCode.get(String(x.dataset.code).toLowerCase());if(p)changeExtraQty(state.cart,p,+x.dataset.extraDelta);return render()}})}
async function init(){const data=await loadCatalog();Object.assign(state,data);if(basketParam)state.basket=basketByParam(basketParam);bind();render()}
init();
