from pathlib import Path
import re


def replace_once(text, old, new, label):
    if old not in text:
        raise SystemExit(f'missing anchor: {label}')
    return text.replace(old,new,1)

# 1) One commercial entity: basket_templates. Internal kit templates are composition only.
commerce_path=Path('supabase/sql/20261004_basket_canonical_commerce_v1.sql')
commerce=commerce_path.read_text()
union_re=re.compile(r'''  from public\.basket_templates bt\n  left join public\.basket_categories c on c\.id=bt\.category_id\n  union all\n  select\n    'kit'::text,[\s\S]*?  where k\.basket_id is null\n''')
m=union_re.search(commerce)
if not m:
    raise SystemExit('missing commercial kit union anchor')
commerce=commerce[:m.start()]+"  from public.basket_templates bt\n  left join public.basket_categories c on c.id=bt.category_id\n"+commerce[m.end():]
commerce=replace_once(commerce,
"  join public.basket_lot_public_availability_v1 a\n    on (m.source_kind='basket' and a.basket_id=m.commercial_id)\n    or (m.source_kind='kit' and a.kit_template_id=m.commercial_id and a.basket_id is null)\n",
"  join public.basket_lot_public_availability_v1 a\n    on a.basket_id=m.commercial_id\n",
'commercial candidates basket join')
commerce_path.write_text(commerce)
Path('supabase/migrations/20261004223000_basket_canonical_commerce_v1.sql').write_text(commerce)

# 2) Atomic commercial creator: model + internal primary composition.
create_sql="""-- Dona Antônia · criação unificada de Cesta/Kit comercial v1\ncreate or replace function public.create_basket_commercial_model_v1(\n  p_name text,\n  p_category_id uuid,\n  p_base_price numeric,\n  p_operator text default 'Operação'\n) returns jsonb\nlanguage plpgsql\nsecurity definer\nset search_path=public\nas $$\ndeclare\n  v_name text:=trim(coalesce(p_name,''));\n  v_basket_id uuid;\n  v_kit_template_id uuid;\n  v_prefix text;\n  v_i integer;\n  v_sort integer;\nbegin\n  if v_name='' then raise exception 'basket_name_required'; end if;\n  if p_category_id is null or not exists(\n    select 1 from public.basket_categories where id=p_category_id and is_active=true\n  ) then raise exception 'basket_category_required'; end if;\n  if p_base_price is null or p_base_price<0 then raise exception 'basket_price_invalid'; end if;\n\n  select coalesce(max(sort_order),0)+10 into v_sort from public.basket_templates;\n  insert into public.basket_templates(\n    name,base_price,is_active,is_whatsapp_active,is_featured,uses_hygiene_kit,split_kits_enabled,category_id,sort_order,internal_notes\n  ) values (\n    v_name,round(p_base_price::numeric,2),true,true,false,false,true,p_category_id,v_sort,\n    'Criado no fluxo unificado Cestas/Kits por '||coalesce(nullif(trim(p_operator),''),'Operação')\n  ) returning id into v_basket_id;\n\n  for v_i in 0..675 loop\n    v_prefix:=chr(65+(v_i/26))+chr(65+(v_i%26));\n    exit when not exists(select 1 from public.basket_kit_templates where code_prefix=v_prefix);\n    v_prefix:=null;\n  end loop;\n  if v_prefix is null then raise exception 'basket_prefix_exhausted'; end if;\n\n  insert into public.basket_kit_templates(\n    kind,basket_id,name,code_prefix,is_active,sort_order,metadata\n  ) values (\n    'food',v_basket_id,v_name,v_prefix,true,0,\n    jsonb_build_object('commercial_unified',true,'created_by',coalesce(nullif(trim(p_operator),''),'Operação'))\n  ) returning id into v_kit_template_id;\n\n  return jsonb_build_object(\n    'basket_id',v_basket_id,\n    'kit_template_id',v_kit_template_id,\n    'code_prefix',v_prefix,\n    'name',v_name,\n    'category_id',p_category_id,\n    'base_price',round(p_base_price::numeric,2)\n  );\nend\n$$;\n\nrevoke all on function public.create_basket_commercial_model_v1(text,uuid,numeric,text) from public,anon,authenticated;\ngrant execute on function public.create_basket_commercial_model_v1(text,uuid,numeric,text) to service_role;\n"""
Path('supabase/sql/20261004_basket_commercial_create_v1.sql').write_text(create_sql)
Path('supabase/migrations/20261004231500_basket_commercial_create_v1.sql').write_text(create_sql)

# 3) Admin backend action.
backend_path=Path('supabase/functions/admin-products-live-v1/index.ts')
backend=backend_path.read_text()
backend=replace_once(backend,'"basket_commercial_admin","basket_kits_admin"','"basket_commercial_create","basket_commercial_admin","basket_kits_admin"','LOCAL create action')
backend=replace_once(backend,'"basket_save","basket_category_save"','"basket_save","basket_commercial_create","basket_category_save"','WRITE create action')
create_fn='''async function basketCommercialCreate(p:any,auth:any){\n  if(auth?.role==="viewer")return {error:"forbidden",status:403};\n  const name=tx(p?.name,220),categoryId=id(p?.category_id),priceCents=Number(p?.base_price_cents);\n  if(!name)return {error:"name_required",status:400};\n  if(!categoryId)return {error:"category_required",status:400};\n  if(!Number.isFinite(priceCents)||priceCents<0)return {error:"price_invalid",status:400};\n  const operator=tx(p?.operator,80)||"Operação";\n  const q=await db.rpc("create_basket_commercial_model_v1",{\n    p_name:name,p_category_id:categoryId,p_base_price:Math.round(priceCents)/100,p_operator:operator\n  });\n  if(q.error){\n    const m=String(q.error.message||"");\n    const code=m.includes("basket_category_required")?"category_required":m.includes("basket_price_invalid")?"price_invalid":m.includes("basket_name_required")?"name_required":"basket_commercial_create_failed";\n    return {error:code,status:400};\n  }\n  const model=q.data||{};\n  await opsEvent("basket.commercial_created","Cesta/Kit criada.","basket",model.basket_id||null,{...model},operator,"human","dona_antonia");\n  return {model};\n}\n'''
backend=replace_once(backend,'async function basketCommercialAdmin(){',create_fn+'async function basketCommercialAdmin(){','insert create helper')
route='if(r.method==="POST"&&a==="basket_commercial_create"){const x:any=await basketCommercialCreate(p,auth);return x.error?js(r,{ok:false,...x},x.status||400):js(r,{ok:true,...x})}'
backend=replace_once(backend,'if(r.method==="POST"&&a==="basket_lot_sale_toggle")',route+'if(r.method==="POST"&&a==="basket_lot_sale_toggle")','insert create route')
backend_path.write_text(backend)

# 4) Fast create flow in the unified Admin page.
admin_path=Path('vitrine/admin/index.html')
admin=admin_path.read_text()
old_head='''content.innerHTML='<div class="page-head"><div><h1>Cestas/Kits</h1><p>Crie, edite e venda rapidamente. O site acompanha estoque e lotes automaticamente.</p></div><div class="basket-auto-actions"><button class="secondary" id="basketProductSuggestions" type="button">Sugestões de produtos</button><button class="secondary" id="refreshBaskets" type="button">Atualizar</button></div></div><div id="basketCommercialFilters"></div><div id="basketAdminBody"><div class="loading">Carregando Cestas/Kits…</div></div>';\n    $('#refreshBaskets').onclick=renderBaskets;$('#basketProductSuggestions').onclick=openBasketSubstitutionCatalog;'''
new_head='''content.innerHTML='<div class="page-head"><div><h1>Cestas/Kits</h1><p>Crie, edite e venda rapidamente. O site acompanha estoque e lotes automaticamente.</p></div><div class="basket-auto-actions"><button class="primary" id="basketCommercialCreate" type="button" disabled>Nova Cesta/Kit</button><button class="secondary" id="basketProductSuggestions" type="button">Sugestões de produtos</button><button class="secondary" id="refreshBaskets" type="button">Atualizar</button></div></div><div id="basketCommercialFilters"></div><div id="basketAdminBody"><div class="loading">Carregando Cestas/Kits…</div></div>';\n    $('#refreshBaskets').onclick=renderBaskets;$('#basketProductSuggestions').onclick=openBasketSubstitutionCatalog;$('#basketCommercialCreate').onclick=openBasketCommercialCreate;'''
admin=replace_once(admin,old_head,new_head,'unified page header')
admin=replace_once(admin,
"state.basketCommercialModels=data.models||[];state.basketCategories=data.categories||[];state.basketCommercialFilter='';\n      paintBasketCommercialFilters();paintBasketCommercialModels();",
"state.basketCommercialModels=data.models||[];state.basketCategories=data.categories||[];state.basketCommercialFilter='';\n      if($('#basketCommercialCreate'))$('#basketCommercialCreate').disabled=!(state.basketCategories||[]).length;\n      paintBasketCommercialFilters();paintBasketCommercialModels();",
'enable create button')
create_ui='''  function openBasketCommercialCreate(){\n    const cats=(state.basketCategories||[]).filter(c=>c.is_active!==false);\n    if(!cats.length){toast('As categorias de Cestas/Kits ainda não carregaram.');return}\n    $('#editorTitle').textContent='Nova Cesta/Kit';\n    $('#editorBody').innerHTML='<div class="form-grid">'+\n      '<label class="span-2"><span>Nome</span><input id="basketCommercialCreateName" maxlength="180" placeholder="Ex.: Kit Limpeza Essencial"></label>'+\n      '<label><span>Categoria</span><select id="basketCommercialCreateCategory"><option value="">Selecione</option>'+cats.map(c=>'<option value="'+esc(c.id)+'">'+esc(c.name)+'</option>').join('')+'</select></label>'+\n      '<label><span>Preço de venda</span><input id="basketCommercialCreatePrice" type="number" min="0" step="0.01" inputmode="decimal" placeholder="0,00"></label>'+\n      '<div class="span-2 rule-notice"><strong>Fluxo rápido</strong><div>Depois de criar, a composição do primeiro lote abre automaticamente.</div></div></div>';\n    $('#editorActions').innerHTML='<button class="secondary" id="basketCommercialCreateCancel" type="button">Cancelar</button><button class="primary" id="basketCommercialCreateSave" type="button">Criar e montar primeiro lote</button>';\n    $('#basketCommercialCreateCancel').onclick=()=>$('#editor').close();\n    $('#basketCommercialCreateSave').onclick=createBasketCommercial;\n    if(!$('#editor').open)$('#editor').showModal();\n    setTimeout(()=>$('#basketCommercialCreateName')?.focus(),0);\n  }\n  async function createBasketCommercial(){\n    const operator=requireOperator();if(!operator)return;\n    const name=String($('#basketCommercialCreateName')?.value||'').trim(),category_id=String($('#basketCommercialCreateCategory')?.value||'');\n    const price=Number(String($('#basketCommercialCreatePrice')?.value||'').replace(',','.'));\n    if(!name){toast('Informe o nome da Cesta/Kit.');return}\n    if(!category_id){toast('Escolha a categoria.');return}\n    if(!Number.isFinite(price)||price<0){toast('Informe um preço válido.');return}\n    const btn=$('#basketCommercialCreateSave');btn.disabled=true;btn.textContent='Criando…';\n    try{\n      const data=await api('basket_commercial_create',{method:'POST',body:{name,category_id,base_price_cents:Math.round(price*100),operator}});\n      const model=data?.model||{};$('#editor').close();toast('Cesta/Kit criada. Agora monte o primeiro lote.');\n      await renderBaskets();\n      if(model.kit_template_id){await openBasketKitAdmin(model.kit_template_id);startBasketKitLotDraft(null)}\n    }catch(e){toast(errorMessage(e?.message||'Não consegui criar a Cesta/Kit.'));btn.disabled=false;btn.textContent='Criar e montar primeiro lote'}\n  }\n'''
admin=replace_once(admin,'  function paintBasketCommercialFilters(){',create_ui+'  function paintBasketCommercialFilters(){','insert fast create UI')
admin_path.write_text(admin)

# 5) Public site: five Cesta/Kit categories filter only baskets, while product categories remain unchanged.
def patch_public(text):
    text=replace_once(text,"home: {baskets:[],categories:STATIC_CATEGORIES},","home: {baskets:[],categories:STATIC_CATEGORIES,basket_categories:[]},",'public home state')
    text=replace_once(text,"category: null,\n      nextOffset:","category: null,\n      basketCategory: '',\n      nextOffset:",'public basket category state')
    text=text.replace("section('Cestas básicas','Escolha uma cesta para conferir.'","section('Cestas e Kits','Escolha uma opção para conferir.'",1)
    start=text.find('    function renderHome(){')
    end=text.find('    function paintOffersPage(){',start)
    if start<0 or end<0:
        raise SystemExit('missing public renderHome block')
    new='''    function basketCategoryControls(categories,active){\n      const list=Array.isArray(categories)?categories:[];if(!list.length)return '';\n      return '<div class="category-list basket-category-list" style="margin-bottom:12px"><button class="category" type="button" data-basket-category="" aria-pressed="'+(!active?'true':'false')+'">Todas<span>›</span></button>'+list.map(c=>'<button class="category" type="button" data-basket-category="'+esc(c.slug)+'" aria-pressed="'+(active===String(c.slug)?'true':'false')+'">'+esc(c.name)+'<span>›</span></button>').join('')+'</div>';\n    }\n    function renderHome(){\n      state.view='home';state.category=null;state.query='';renderNav();$('#globalSearchInput').value='';\n      const baskets=state.home?.baskets||[],categories=state.home?.categories?.length?state.home.categories:STATIC_CATEGORIES;\n      const basketCategories=state.home?.basket_categories||[],active=String(state.basketCategory||'');\n      const visibleBaskets=active?baskets.filter(b=>String(b.category_slug||'')===active):baskets;\n      content.innerHTML=section('Cestas e Kits','Escolha a categoria e monte seu pedido.',basketCategoryControls(basketCategories,active)+'<div class="grid" id="basketGrid">'+(visibleBaskets.length?visibleBaskets.map((b,i)=>basketCard(b,i)).join(''):'<div class="empty">Nenhuma Cesta/Kit disponível nesta categoria agora.</div>')+'</div>')+section('Ofertas','Preços promocionais ativos agora.','<div id="homeOffersMount">'+(state.offersLoaded?'':offersSkeleton())+'</div>')+section('Categorias','Para achar rápido o que você precisa.','<div class="category-list">'+categories.map(c=>'<button class="category" type="button" data-category="'+esc(c.key)+'">'+esc(c.label)+'<span>›</span></button>').join('')+'</div>');\n      content.querySelectorAll('[data-basket]').forEach(btn=>btn.onclick=()=>openBasket(btn.dataset.basket));\n      content.querySelectorAll('[data-basket-category]').forEach(btn=>btn.onclick=()=>{state.basketCategory=String(btn.dataset.basketCategory||'');renderHome()});\n      content.querySelectorAll('[data-category]').forEach(btn=>btn.onclick=()=>renderCategory(btn.dataset.category,btn.textContent.replace('›','').trim()));\n      BasketCarousel.mount(document.querySelector('#basketGrid'));if(state.offersLoaded)paintHomeOffers();else observeOffers();\n    }\n'''
    return text[:start]+new+text[end:]

root_path=Path('index.html');root=patch_public(root_path.read_text());root_path.write_text(root);Path('vitrine/index.html').write_text(root)
