#!/usr/bin/env python3
import json
from pathlib import Path

FALLBACK="iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=="
OPT=lambda d=False:{"type":"array","items":{"type":"object","properties":{"id":{"type":"string"},"title":{"type":"string"},**({"description":{"type":"string"}} if d else {})}}}
MEDIA={"type":"array","items":{"type":"object","properties":{"id":{"type":"string"},"title":{"type":"string"},"description":{"type":"string"},"image":{"type":"string"},"alt-text":{"type":"string"}}}}

def personalize(n):
 return {"id":f"PERSONALIZAR_{n}","title":"Confira sua cesta","data":{
 "basket_name":{"type":"string","__example__":"Cesta Econômica"},"basket_price":{"type":"string","__example__":"R$ 199,90"},"basket_note":{"type":"string","__example__":"Os componentes da cesta não exibem preço individual."},"items_summary":{"type":"string","__example__":"2 × Arroz\n2 × Feijão\n1 × Café"},
 "actions":{**OPT(),"__example__":[{"id":"continue","title":"Está boa assim"},{"id":"edit","title":"Quero alterar um item"}]},
 "items":{**OPT(True),"__example__":[{"id":"00000000-0000-0000-0000-000000000001","title":"Arroz 5 kg","description":"Atual: 2"}]},
 "error_text":{"type":"string","__example__":""},"basket_image_base64":{"type":"string","__example__":FALLBACK},"has_basket_image":{"type":"boolean","__example__":True}},
 "layout":{"type":"SingleColumnLayout","children":[
 {"type":"Image","src":"${data.basket_image_base64}","scale-type":"contain","aspect-ratio":1,"alt-text":"${data.basket_name}"},
 {"type":"TextHeading","text":"${data.basket_name}"},{"type":"TextSubheading","text":"${data.basket_price}"},
 {"type":"TextBody","text":"Veja os produtos e quantidades da cesta:"},{"type":"TextBody","text":"${data.items_summary}"},
 {"type":"TextCaption","text":"${data.basket_note}"},{"type":"TextBody","text":"${data.error_text}"},
 {"type":"Form","name":f"customize_form_{n}","children":[
 {"type":"RadioButtonsGroup","label":"O que deseja fazer?","name":"customize_action","data-source":"${data.actions}","required":True},
 {"type":"Dropdown","label":"Produto que deseja alterar","name":"product_id","data-source":"${data.items}","required":False},
 {"type":"Footer","label":"Continuar","on-click-action":{"name":"data_exchange","payload":{"trigger":"basket_customize_v3","customize_action":"${form.customize_action}","product_id":"${form.product_id}"}}}]}]}}

def adjust(n):
 return {"id":f"AJUSTAR_ITEM_{n}","title":"Alterar quantidade","data":{
 "product_name":{"type":"string","__example__":"Arroz 5 kg"},"current_quantity":{"type":"string","__example__":"2"},
 "allowed_quantities":{**OPT(),"__example__":[{"id":"0","title":"Retirar da cesta"},{"id":"1","title":"1"},{"id":"2","title":"2 · atual"}]},
 "policy_note":{"type":"string","__example__":"Escolha a nova quantidade."}},
 "layout":{"type":"SingleColumnLayout","children":[{"type":"TextHeading","text":"${data.product_name}"},{"type":"TextBody","text":"Quantidade atual: ${data.current_quantity}"},{"type":"TextCaption","text":"${data.policy_note}"},
 {"type":"Form","name":f"adjust_form_{n}","children":[{"type":"Dropdown","label":"Nova quantidade","name":"quantity","data-source":"${data.allowed_quantities}","required":True},{"type":"Footer","label":"Salvar alteração","on-click-action":{"name":"data_exchange","payload":{"trigger":"basket_item_apply","quantity":"${form.quantity}"}}}]}]}}

def extras(n):
 return {"id":f"SECOES_{n}","title":"Adicionar produtos","data":{
 "message":{"type":"string","__example__":"Quer acrescentar mais alguma coisa?"},
 "extras_actions":{**OPT(),"__example__":[{"id":"finish","title":"Finalizar meu pedido"},{"id":"browse","title":"Escolher por categorias"},{"id":"direct_search","title":"Buscar um produto"}]},
 "sections":{**OPT(),"__example__":[{"id":"mercearia","title":"Mercearia"},{"id":"limpeza","title":"Limpeza e lavanderia"},{"id":"higiene","title":"Higiene e beleza"}]},
 "cart_total":{"type":"string","__example__":"Pedido em montagem"}},
 "layout":{"type":"SingleColumnLayout","children":[{"type":"TextHeading","text":"Quer adicionar algo?"},{"type":"TextBody","text":"${data.message}"},{"type":"TextCaption","text":f"Adicionais {n} de 3 · você pode finalizar sem adicionar nada."},
 {"type":"Form","name":f"extras_form_{n}","children":[
 {"type":"RadioButtonsGroup","label":"Escolha uma opção","name":"extras_action","data-source":"${data.extras_actions}","required":True},
 {"type":"CheckboxGroup","label":"Categorias de interesse (até 3)","name":"section_keys","data-source":"${data.sections}","required":False},
 {"type":"TextInput","label":"Buscar produto pelo nome","name":"direct_query","required":False},
 {"type":"Footer","label":"Continuar","on-click-action":{"name":"data_exchange","payload":{"trigger":"extras_continue_v2","extras_action":"${form.extras_action}","section_keys":"${form.section_keys}","direct_query":"${form.direct_query}","round":str(n)}}}]},{"type":"TextCaption","text":"${data.cart_total}"}]}}

def terms(n):
 return {"id":f"TERMOS_{n}","title":"O que procura?","data":{"section_title":{"type":"string","__example__":"O que você procura?"},"terms":{**OPT(True),"__example__":[{"id":"higiene::sabonete","title":"Sabonetes","description":"Higiene e beleza"}]}},
 "layout":{"type":"SingleColumnLayout","children":[{"type":"TextHeading","text":"${data.section_title}"},{"type":"TextBody","text":"Escolha o tipo de produto. Vamos carregar somente opções relacionadas."},{"type":"Form","name":f"term_form_{n}","children":[{"type":"Dropdown","label":"Tipo de produto","name":"term_id","data-source":"${data.terms}","required":True},{"type":"Footer","label":"Mostrar produtos","on-click-action":{"name":"data_exchange","payload":{"trigger":"term_selected_v2","term_id":"${form.term_id}","round":str(n)}}}]}]}}

def products(n):
 return {"id":f"PRODUTOS_{n}","title":"Escolha um produto","data":{"query_title":{"type":"string","__example__":"Sabonetes"},"result_note":{"type":"string","__example__":"8 opções disponíveis"},"products":{**OPT(True),"__example__":[{"id":"00000000-0000-0000-0000-000000000001","title":"Sabonete Dove · R$ 4,99","description":"Dove · 90 g"}]}},
 "layout":{"type":"SingleColumnLayout","children":[{"type":"TextHeading","text":"${data.query_title}"},{"type":"TextBody","text":"${data.result_note}"},{"type":"Form","name":f"products_form_{n}","children":[{"type":"RadioButtonsGroup","label":"Escolha um produto","name":"product_id","data-source":"${data.products}","required":True},{"type":"Footer","label":"Ver produto","on-click-action":{"name":"data_exchange","payload":{"trigger":"product_selected","product_id":"${form.product_id}","round":str(n)}}}]}]}}

def product(n):
 return {"id":f"PRODUTO_{n}","title":"Produto","data":{"product_name":{"type":"string","__example__":"Sabonete Dove 90 g"},"product_price":{"type":"string","__example__":"R$ 4,99"},"product_description":{"type":"string","__example__":"Disponível para entrega"},"product_image_base64":{"type":"string","__example__":FALLBACK},"has_product_image":{"type":"boolean","__example__":True},"product_id":{"type":"string","__example__":"00000000-0000-0000-0000-000000000001"},"quantities":{**OPT(),"__example__":[{"id":"1","title":"1"},{"id":"2","title":"2"}]}},
 "layout":{"type":"SingleColumnLayout","children":[{"type":"Image","src":"${data.product_image_base64}","scale-type":"contain","aspect-ratio":1,"alt-text":"${data.product_name}"},{"type":"TextHeading","text":"${data.product_name}"},{"type":"TextSubheading","text":"${data.product_price}"},{"type":"TextBody","text":"${data.product_description}"},{"type":"Form","name":f"product_form_{n}","children":[{"type":"Dropdown","label":"Quantidade","name":"quantity","data-source":"${data.quantities}","required":True},{"type":"Footer","label":"Adicionar ao pedido","on-click-action":{"name":"data_exchange","payload":{"trigger":"add_product","product_id":"${data.product_id}","quantity":"${form.quantity}","round":str(n)}}}]}]}}

routing={"CESTAS":["PERSONALIZAR_1"],"PERSONALIZAR_1":["AJUSTAR_ITEM_1","SECOES_1"],"AJUSTAR_ITEM_1":["PERSONALIZAR_2"],"PERSONALIZAR_2":["AJUSTAR_ITEM_2","SECOES_1"],"AJUSTAR_ITEM_2":["PERSONALIZAR_3"],"PERSONALIZAR_3":["AJUSTAR_ITEM_3","SECOES_1"],"AJUSTAR_ITEM_3":["SECOES_1"],"SECOES_1":["TERMOS_1","PRODUTOS_1","UPSELL"],"TERMOS_1":["PRODUTOS_1"],"PRODUTOS_1":["PRODUTO_1"],"PRODUTO_1":["SECOES_2"],"SECOES_2":["TERMOS_2","PRODUTOS_2","UPSELL"],"TERMOS_2":["PRODUTOS_2"],"PRODUTOS_2":["PRODUTO_2"],"PRODUTO_2":["SECOES_3"],"SECOES_3":["TERMOS_3","PRODUTOS_3","UPSELL"],"TERMOS_3":["PRODUTOS_3"],"PRODUTOS_3":["PRODUTO_3"],"PRODUTO_3":["UPSELL"],"UPSELL":["REVISAO"],"REVISAO":["CLIENTE"],"CLIENTE":["FINALIZAR"],"FINALIZAR":[]}

screens=[{"id":"CESTAS","title":"Escolha sua cesta","data":{"intro":{"type":"string","__example__":"Escolha uma das 9 cestas."},"baskets":{**MEDIA,"__example__":[{"id":"basket-1","title":"Econômica · R$ 92,00","description":"Toque para ver os itens","image":FALLBACK,"alt-text":"Cesta Econômica"}]}},"layout":{"type":"SingleColumnLayout","children":[{"type":"TextHeading","text":"Cestas Básicas Dona Antônia"},{"type":"TextBody","text":"${data.intro}"},{"type":"Form","name":"basket_form","children":[{"type":"RadioButtonsGroup","label":"Escolha sua cesta","name":"basket_id","data-source":"${data.baskets}","required":True},{"type":"Footer","label":"Ver esta cesta","on-click-action":{"name":"data_exchange","payload":{"trigger":"basket_selected","basket_id":"${form.basket_id}"}}}]}]}}]
for n in range(1,4): screens += [personalize(n),adjust(n)]
for n in range(1,4): screens += [extras(n),terms(n),products(n),product(n)]
screens += [
{"id":"UPSELL","title":"Sugestões para seu pedido","data":{"upsell_note":{"type":"string","__example__":"Sugestões opcionais. Você pode seguir sem adicionar nada."},"products":{**OPT(True),"__example__":[{"id":"00000000-0000-0000-0000-000000000001","title":"Produto · R$ 9,90","description":"Sugestão opcional"}]}},"layout":{"type":"SingleColumnLayout","children":[{"type":"TextHeading","text":"Talvez você também queira"},{"type":"TextBody","text":"${data.upsell_note}"},{"type":"Form","name":"upsell_form","children":[{"type":"Dropdown","label":"Adicionar uma sugestão (opcional)","name":"product_id","data-source":"${data.products}","required":False},{"type":"Footer","label":"Revisar pedido","on-click-action":{"name":"data_exchange","payload":{"trigger":"upsell_continue","product_id":"${form.product_id}"}}}]}]}},
{"id":"REVISAO","title":"Revise seu pedido","data":{"summary":{"type":"string","__example__":"Cesta Econômica\n+ 2 produtos adicionais"},"total":{"type":"string","__example__":"R$ 130,00"},"pricing_note":{"type":"string","__example__":"A cesta possui preço comercial próprio."}},"layout":{"type":"SingleColumnLayout","children":[{"type":"TextHeading","text":"Confira antes de finalizar"},{"type":"TextBody","text":"${data.summary}"},{"type":"TextSubheading","text":"${data.total}"},{"type":"TextCaption","text":"${data.pricing_note}"},{"type":"Footer","label":"Continuar para entrega","on-click-action":{"name":"data_exchange","payload":{"trigger":"review_confirm"}}}]}},
{"id":"CLIENTE","title":"Entrega e pagamento","data":{"customer_name":{"type":"string","__example__":"Maria"},"address_summary":{"type":"string","__example__":"Rua Exemplo, 123, Centro, Cuiabá"},"customer_registered":{"type":"boolean","__example__":True},"name_value":{"type":"string","__example__":"Maria"},"street_value":{"type":"string","__example__":"Rua Exemplo"},"number_value":{"type":"string","__example__":"123"},"complement_value":{"type":"string","__example__":""},"neighborhood_value":{"type":"string","__example__":"Centro"},"city_value":{"type":"string","__example__":"Cuiabá"},"locator_value":{"type":"string","__example__":""},"error_text":{"type":"string","__example__":""},"payment_options":{**OPT(),"__example__":[{"id":"pix","title":"PIX na entrega"},{"id":"dinheiro","title":"Dinheiro na entrega"},{"id":"cartao_entrega","title":"Cartão na entrega"}]}},"layout":{"type":"SingleColumnLayout","children":[{"type":"TextHeading","text":"Dados para entrega"},{"type":"TextBody","text":"Se já conhecemos você, os dados aparecem preenchidos. Confira e altere só se precisar."},{"type":"TextCaption","text":"${data.address_summary}"},{"type":"TextBody","text":"${data.error_text}"},{"type":"Form","name":"checkout_form","children":[{"type":"TextInput","label":"Nome","name":"name","init-value":"${data.name_value}","required":True},{"type":"TextInput","label":"Rua / avenida","name":"street","init-value":"${data.street_value}","required":True},{"type":"TextInput","label":"Número","name":"number","init-value":"${data.number_value}","required":True},{"type":"TextInput","label":"Complemento","name":"complement","init-value":"${data.complement_value}","required":False},{"type":"TextInput","label":"Bairro","name":"neighborhood","init-value":"${data.neighborhood_value}","required":True},{"type":"Dropdown","label":"Cidade","name":"city","data-source":[{"id":"Cuiabá","title":"Cuiabá"},{"id":"Várzea Grande","title":"Várzea Grande"}],"init-value":"${data.city_value}","required":True},{"type":"TextInput","label":"Referência / localização escrita","name":"locator","init-value":"${data.locator_value}","required":False},{"type":"Dropdown","label":"Pagamento na entrega","name":"payment_method","data-source":"${data.payment_options}","required":True},{"type":"TextInput","label":"Observação (opcional)","name":"notes","required":False},{"type":"Footer","label":"Confirmar pedido","on-click-action":{"name":"data_exchange","payload":{"trigger":"checkout_confirm","name":"${form.name}","street":"${form.street}","number":"${form.number}","complement":"${form.complement}","neighborhood":"${form.neighborhood}","city":"${form.city}","locator":"${form.locator}","payment_method":"${form.payment_method}","notes":"${form.notes}"}}}]}]}},
{"id":"FINALIZAR","title":"Pedido confirmado","terminal":True,"data":{"confirmation":{"type":"string","__example__":"Pedido confirmado com sucesso."},"final_summary":{"type":"string","__example__":"Cesta Econômica + adicionais"},"final_total":{"type":"string","__example__":"R$ 130,00"},"next_step":{"type":"string","__example__":"Ao voltar para a conversa, envie sua localização."},"write_enabled":{"type":"boolean","__example__":True}},"layout":{"type":"SingleColumnLayout","children":[{"type":"TextHeading","text":"${data.confirmation}"},{"type":"TextBody","text":"${data.final_summary}"},{"type":"TextSubheading","text":"${data.final_total}"},{"type":"TextBody","text":"${data.next_step}"},{"type":"Footer","label":"Concluir","on-click-action":{"name":"complete","payload":{"status":"completed"}}}]}}
]
flow={"version":"7.3","data_api_version":"3.0","routing_model":routing,"screens":screens}
out=Path(__file__).resolve().parents[1]/"whatsapp"/"flows"/"flow-cestas-comercial-v6.json"
out.parent.mkdir(parents=True,exist_ok=True)
out.write_text(json.dumps(flow,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
print(out)
