import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
path = ROOT / 'whatsapp' / 'flows' / 'flow-cestas-comercial-v28.json'
flow = json.loads(path.read_text(encoding='utf-8'))

# Meta Flow JSON v7.3 NavigationList start objects use `src`, not `image`.
# Normalize both data schemas/examples generated by the V28 builder. Runtime
# hydration performs the same normalization for product rows returned by Data Exchange.

def walk(value):
    if isinstance(value, list):
        for item in value:
            walk(item)
        return
    if not isinstance(value, dict):
        return

    start = value.get('start')
    if isinstance(start, dict):
        if 'image' in start and 'src' not in start:
            start['src'] = start.pop('image')
        props = start.get('properties')
        if isinstance(props, dict) and 'image' in props and 'src' not in props:
            props['src'] = props.pop('image')

    # The schema's `start` definition can itself be a properties object.
    props = value.get('properties')
    if isinstance(props, dict):
        start_schema = props.get('start')
        if isinstance(start_schema, dict):
            start_props = start_schema.get('properties')
            if isinstance(start_props, dict) and 'image' in start_props and 'src' not in start_props:
                start_props['src'] = start_props.pop('image')

    for child in value.values():
        walk(child)

walk(flow)

# Hard gates: no legacy NavigationList start.image survives and every product
# example that has a start image uses `src` + `alt-text`.
raw = json.dumps(flow, ensure_ascii=False)
assert '"start": {"image"' not in raw
assert '"image": {"type": "string"}' not in raw or 'product_image_base64' in raw
for screen in flow['screens']:
    if screen['id'].startswith('PRODUTOS_'):
        product_items = screen.get('data', {}).get('product_items', {})
        example = product_items.get('__example__', [])
        for item in example:
            start = item.get('start')
            if start:
                assert 'src' in start and 'alt-text' in start
                assert 'image' not in start

path.write_text(json.dumps(flow, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
print('V28 NavigationList start schema normalized to src')
