from pathlib import Path
import re

html_path=Path('vitrine/admin/atendimento/index.html')
css_path=Path('vitrine/admin/atendimento/attendance.css')
js_path=Path('vitrine/admin/atendimento/attendance.js')

html=html_path.read_text()
old_nav='''    <nav class="mobile-channel-tabs" aria-label="Canais">\n      <button type="button" data-mobile-channel="0975" class="active">0975</button>\n      <button type="button" data-mobile-channel="1018">1018</button>\n    </nav>\n\n'''
html=html.replace(old_nav,'')
start=html.index('      <aside class="queue-column active-mobile"')
end=html.index('      <section class="conversation-pane"',start)
new_queue='''      <aside class="queue-column" aria-label="Conversas do WhatsApp">\n        <div class="channel-switcher" role="tablist" aria-label="Número do WhatsApp">\n          <button type="button" data-channel-switch="0975" class="active" role="tab" aria-selected="true">0975</button>\n          <button type="button" data-channel-switch="1018" role="tab" aria-selected="false">1018</button>\n        </div>\n        <header class="queue-head">\n          <div><strong>Conversas</strong><small id="activeChannelStatus">Conectando 0975…</small></div>\n          <span class="attention-count" id="activeChannelCount">0</span>\n        </header>\n        <div class="queue-list" id="queueList"></div>\n      </aside>\n\n'''
html=html[:start]+new_queue+html[end:]
html=html.replace('Escolha uma conversa em uma das duas filas.','Escolha uma conversa na lista ao lado.')
html_path.write_text(html)

css=css_path.read_text()
css=css.replace('.queue-head{height:58px;', '.channel-switcher{display:grid;grid-template-columns:1fr 1fr;gap:8px;padding:10px;border-bottom:1px solid #eef0f2;background:#fff}.channel-switcher button{border:1px solid #d0d5dd;background:#f8fafc;color:#344054;border-radius:10px;padding:10px 8px;font-size:13px;font-weight:700;cursor:pointer}.channel-switcher button.active{background:#2563eb;border-color:#2563eb;color:#fff}.queue-head{height:50px;')
css=css.replace('.mobile-channel-tabs{display:none}\n@media (min-width:1180px){.attendance-grid{grid-template-columns:minmax(185px,.72fr) minmax(185px,.72fr) minmax(440px,1.55fr) minmax(300px,1.1fr)}.context-pane{position:relative;transform:none!important}}', '@media (min-width:1180px){.attendance-grid{grid-template-columns:minmax(220px,.72fr) minmax(520px,1.8fr) minmax(300px,1.08fr)}.context-pane{position:relative;transform:none!important}}')
css=css.replace('@media (min-width:760px) and (max-width:1179px){.attendance-grid{grid-template-columns:minmax(180px,.72fr) minmax(180px,.72fr) minmax(410px,1.55fr)}', '@media (min-width:760px) and (max-width:1179px){.attendance-grid{grid-template-columns:minmax(220px,.72fr) minmax(410px,1.55fr)}')
css=css.replace('@media (max-width:759px){.attendance-topbar{height:auto;align-items:stretch;flex-direction:column}.global-search{width:100%}.mobile-channel-tabs{display:flex;background:#fff;border-bottom:1px solid #e5e7eb;padding:6px;gap:4px}.mobile-channel-tabs button{flex:1;border:0;background:#f2f4f7;border-radius:7px;padding:7px}.mobile-channel-tabs button.active{background:#2563eb;color:#fff}.attendance-grid{display:block;position:relative}.queue-column{display:none;height:calc(100vh - 132px)}.queue-column.active-mobile{display:flex}.conversation-pane{display:none;height:calc(100vh - 132px)}', '@media (max-width:759px){.attendance-topbar{height:auto;align-items:stretch;flex-direction:column}.global-search{width:100%}.attendance-grid{display:block;position:relative}.queue-column{display:flex;height:calc(100vh - 108px)}.conversation-pane{display:none;height:calc(100vh - 108px)}')
css_path.write_text(css)

js=js_path.read_text()
js=js.replace("const state={accounts:{},filters:{'0975':'all','1018':'all'},search:'',selected:null,conversation:null,context:null,contextTab:'customer',conversationOpen:false,loadingOlder:false,refreshing:false};", "const state={accounts:{},activeChannel:'0975',search:'',selected:null,conversation:null,context:null,contextTab:'customer',conversationOpen:false,loadingOlder:false,refreshing:false};")
js=js.replace("time.textContent=fmtQueueStamp(item.last_activity_at||item.last_message_at);time.title=fmtDateTime(item.last_activity_at||item.last_message_at);", "time.textContent=fmtQueueStamp(item.canonical_last_message_at||item.last_message_at);time.title=fmtDateTime(item.canonical_last_message_at||item.last_message_at);")
old_accounts='''async function loadAccounts(){\n  const data=await api('accounts');state.accounts={};\n  for(const account of data.items||[]){const ch=channelByPhone(account.phone_e164);if(ch)state.accounts[ch]=account}\n  for(const ch of ['0975','1018'])$(`#status${ch}`).textContent=state.accounts[ch]?'Conectado':'Canal não localizado';\n  $('#connectionStatus').textContent=Object.keys(state.accounts).length===2?'2 canais conectados · envio manual pelo PapoAI':'Verifique os canais';\n}\nasync function loadQueue(channel){\n  const account=state.accounts[channel],box=$(`#queue${channel}`);if(!box)return;box.replaceChildren();if(!account)return;\n  try{const data=await api('queue',{account_id:account.id,limit:QUEUE_PAGE_SIZE,filter:state.filters[channel],search:state.search});const items=data.items||[];for(const item of items)box.append(queueCard(item,channel));$(`#count${channel}`).textContent=String(items.filter(i=>i.unread_count>0||i.human_required||i.status==='needs_human').length);if(!items.length){const empty=document.createElement('div');empty.className='context-empty';empty.textContent='Nenhuma conversa.';box.append(empty)}}catch{const empty=document.createElement('div');empty.className='context-empty';empty.textContent='Não foi possível carregar esta fila.';box.append(empty)}\n}\nasync function loadQueues(){await Promise.all([loadQueue('0975'),loadQueue('1018')]);syncConversationVisibility()}\n'''
new_accounts='''async function loadAccounts(){\n  const data=await api('accounts');state.accounts={};\n  for(const account of data.items||[]){const ch=channelByPhone(account.phone_e164);if(ch)state.accounts[ch]=account}\n  $('#connectionStatus').textContent=Object.keys(state.accounts).length===2?'2 canais conectados · envio manual pelo PapoAI':'Verifique os canais';\n  syncChannelSwitcher();\n}\nfunction syncChannelSwitcher(){\n  $$('[data-channel-switch]').forEach(button=>{const active=button.dataset.channelSwitch===state.activeChannel;button.classList.toggle('active',active);button.setAttribute('aria-selected',String(active));button.disabled=!state.accounts[button.dataset.channelSwitch]});\n  const status=$('#activeChannelStatus');if(status)status.textContent=state.accounts[state.activeChannel]?`Canal ${state.activeChannel} conectado`:`Canal ${state.activeChannel} não localizado`;\n}\nasync function loadQueue(){\n  const channel=state.activeChannel,account=state.accounts[channel],box=$('#queueList');if(!box)return;box.replaceChildren();if(!account){syncChannelSwitcher();return}\n  try{const data=await api('queue',{account_id:account.id,limit:QUEUE_PAGE_SIZE,search:state.search});const items=data.items||[];for(const item of items)box.append(queueCard(item,channel));$('#activeChannelCount').textContent=String(items.filter(i=>i.unread_count>0).length);if(!items.length){const empty=document.createElement('div');empty.className='context-empty';empty.textContent='Nenhuma conversa.';box.append(empty)}}catch{const empty=document.createElement('div');empty.className='context-empty';empty.textContent='Não foi possível carregar esta fila.';box.append(empty)}\n  syncChannelSwitcher();syncConversationVisibility();\n}\nfunction resetConversationView(){\n  state.selected=null;state.conversation=null;state.context=null;state.conversationOpen=false;syncConversationVisibility();closeComposerPanels();\n  const messages=$('#messages');messages.replaceChildren();messages.hidden=true;const empty=$('#conversationEmpty');empty.hidden=false;empty.textContent='Escolha uma conversa na lista ao lado.';\n  const head=$('#conversationHead');head.querySelector('strong').textContent='Selecione uma conversa';head.querySelector('small').textContent=`Canal ${state.activeChannel}`;$('#openContextBtn').disabled=true;\n  $('#serviceWindow').className='service-window neutral';$('#serviceWindow').textContent='Nenhuma conversa selecionada';\n  for(const id of ['catalogBtn','quickRepliesBtn','quoteBtn','saleBtn','followUpBtn','optOutBtn'])$(`#${id}`).disabled=true;\n  renderContext();syncFallbackButtons();\n}\nasync function switchChannel(channel){\n  if(!['0975','1018'].includes(channel)||!state.accounts[channel])return;\n  if(state.activeChannel===channel){syncChannelSwitcher();return}\n  state.activeChannel=channel;resetConversationView();syncChannelSwitcher();await loadQueue();\n}\n'''
if old_accounts not in js: raise SystemExit('queue block not found')
js=js.replace(old_accounts,new_accounts)
js=js.replace("await loadQueues();const inbound", "await loadQueue();const inbound")
js=js.replace("async function backgroundRefresh(){if(document.hidden)return;await loadQueues();await refreshSelectedConversation()}", "async function backgroundRefresh(){if(document.hidden)return;await loadQueue();await refreshSelectedConversation()}")
js=js.replace("showNote(`Retorno marcado para ${fmtDate(iso)} às ${fmtTime(iso)}`,'success');await loadQueues()", "showNote(`Retorno marcado para ${fmtDate(iso)} às ${fmtTime(iso)}`,'success');await loadQueue()")
js=js.replace("showNote('Lembrete de retorno removido');await loadQueues()", "showNote('Lembrete de retorno removido');await loadQueue()")
js=js.replace("state.search=e.target.value.trim();loadQueues()", "state.search=e.target.value.trim();loadQueue()")
js=re.sub(r"\n  \$\$\('\.queue-filters button'\).*?\n  \$\$\('\.context-tabs", "\n  $$('[data-channel-switch]').forEach(b=>b.addEventListener('click',()=>switchChannel(b.dataset.channelSwitch).catch(()=>{})));\n  $$('.context-tabs", js, count=1, flags=re.S)
js=re.sub(r"\n  \$\$\('\[data-mobile-channel\]'\).*?syncConversationVisibility\(\)\}\)\);", "", js, count=1, flags=re.S)
js=js.replace("async function boot(){bind();renderQuickReplies();syncFallbackButtons();try{await loadAccounts();await loadQueues();startRefresh()}", "async function boot(){bind();renderQuickReplies();syncFallbackButtons();try{await loadAccounts();await loadQueue();startRefresh()}")
js_path.write_text(js)

print('patched attendance v2 single queue')
