BEGIN;

CREATE SCHEMA IF NOT EXISTS private;

CREATE TABLE IF NOT EXISTS private.whatsapp_ana_admin_draft_v1 (
  singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
  configuration jsonb NOT NULL CHECK (jsonb_typeof(configuration) = 'object'),
  revision bigint NOT NULL DEFAULT 1 CHECK (revision > 0),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid
);

CREATE TABLE IF NOT EXISTS private.whatsapp_ana_admin_versions_v1 (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version integer NOT NULL UNIQUE CHECK (version > 0),
  configuration jsonb NOT NULL CHECK (jsonb_typeof(configuration) = 'object'),
  actor_id uuid,
  change_note text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS private.whatsapp_ana_admin_runtime_v1 (
  singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
  active_version_id bigint NOT NULL REFERENCES private.whatsapp_ana_admin_versions_v1(id),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid
);

CREATE TABLE IF NOT EXISTS private.whatsapp_ana_admin_events_v1 (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action text NOT NULL CHECK (action IN ('draft_saved','published','rolled_back','channel_toggled')),
  actor_id uuid,
  version_id bigint,
  draft_revision bigint,
  channel_key text,
  detail jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(detail) = 'object'),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS private.whatsapp_ana_admin_test_runs_v1 (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  draft_revision bigint NOT NULL,
  scenario_keys text[] NOT NULL DEFAULT '{}',
  passed_count integer NOT NULL CHECK (passed_count >= 0),
  failed_count integer NOT NULL CHECK (failed_count >= 0),
  safe_reasons jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(safe_reasons) = 'array'),
  latency_ms integer NOT NULL DEFAULT 0 CHECK (latency_ms >= 0),
  actor_id uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE private.whatsapp_ana_admin_draft_v1 ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.whatsapp_ana_admin_versions_v1 ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.whatsapp_ana_admin_runtime_v1 ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.whatsapp_ana_admin_events_v1 ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.whatsapp_ana_admin_test_runs_v1 ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON private.whatsapp_ana_admin_draft_v1, private.whatsapp_ana_admin_versions_v1,
  private.whatsapp_ana_admin_runtime_v1, private.whatsapp_ana_admin_events_v1,
  private.whatsapp_ana_admin_test_runs_v1 FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION private.whatsapp_ana_admin_immutable_v1()
RETURNS trigger LANGUAGE plpgsql SET search_path = pg_catalog AS $$
BEGIN
  RAISE EXCEPTION 'ana_admin_record_immutable';
END;
$$;
DROP TRIGGER IF EXISTS whatsapp_ana_admin_versions_immutable_v1 ON private.whatsapp_ana_admin_versions_v1;
CREATE TRIGGER whatsapp_ana_admin_versions_immutable_v1 BEFORE UPDATE OR DELETE ON private.whatsapp_ana_admin_versions_v1
FOR EACH ROW EXECUTE FUNCTION private.whatsapp_ana_admin_immutable_v1();
DROP TRIGGER IF EXISTS whatsapp_ana_admin_events_immutable_v1 ON private.whatsapp_ana_admin_events_v1;
CREATE TRIGGER whatsapp_ana_admin_events_immutable_v1 BEFORE UPDATE OR DELETE ON private.whatsapp_ana_admin_events_v1
FOR EACH ROW EXECUTE FUNCTION private.whatsapp_ana_admin_immutable_v1();
DROP TRIGGER IF EXISTS whatsapp_ana_admin_test_runs_immutable_v1 ON private.whatsapp_ana_admin_test_runs_v1;
CREATE TRIGGER whatsapp_ana_admin_test_runs_immutable_v1 BEFORE UPDATE OR DELETE ON private.whatsapp_ana_admin_test_runs_v1
FOR EACH ROW EXECUTE FUNCTION private.whatsapp_ana_admin_immutable_v1();

INSERT INTO private.whatsapp_ana_admin_versions_v1(version, configuration, change_note)
VALUES (1, jsonb_build_object(
  'behavior', jsonb_build_object('tone','cordial','conciseness','short','emoji','sparingly','use_known_first_name_on_first_greeting',true),
  'knowledge', jsonb_build_array(
    jsonb_build_object('key','catalogo','title','Catálogo e pedidos','category','vendas','content','Para consultar produtos e fazer pedidos, direcione a pessoa ao catálogo/site oficial. O atendimento pode orientar por aqui; a ANA não cria pedidos.'),
    jsonb_build_object('key','atendimento-humano','title','Atendimento humano','category','atendimento','content','Encaminhe para uma pessoa quando o cliente pedir, quando faltar informação confiável ou houver exceção operacional.'),
    jsonb_build_object('key','dados-dinamicos','title','Dados que precisam de confirmação','category','seguranca','content','Não invente preço, estoque, total, composição, prazo, endereço, pedido, pagamento ou dado do cliente. Sem contexto confirmado, encaminhe para humano ou catálogo.')
  ),
  'triggers', jsonb_build_array(),
  'test_cases', jsonb_build_array(
    jsonb_build_object('key','greeting','input','Oi','expected','reply'),
    jsonb_build_object('key','dynamic_price','input','Qual o preço?','expected','handoff'),
    jsonb_build_object('key','operational_issue','input','Meu pedido atrasou','expected','handoff')
  )
), 'Baseline ANA behavior preserved before configurable worker rollout')
ON CONFLICT (version) DO NOTHING;

INSERT INTO private.whatsapp_ana_admin_draft_v1(singleton, configuration, revision)
SELECT true, configuration, 1 FROM private.whatsapp_ana_admin_versions_v1 WHERE version = 1
ON CONFLICT (singleton) DO NOTHING;
INSERT INTO private.whatsapp_ana_admin_runtime_v1(singleton, active_version_id)
SELECT true, id FROM private.whatsapp_ana_admin_versions_v1 WHERE version = 1
ON CONFLICT (singleton) DO NOTHING;

CREATE OR REPLACE FUNCTION public.ops2_ana_admin_load_v1()
RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path = pg_catalog, private AS $$
  SELECT jsonb_build_object(
    'ok', true,
    'draft', (SELECT jsonb_build_object('configuration', d.configuration, 'revision', d.revision, 'updated_at', d.updated_at)
              FROM private.whatsapp_ana_admin_draft_v1 d WHERE d.singleton),
    'active', (SELECT jsonb_build_object('id', v.id, 'version', v.version, 'configuration', v.configuration, 'created_at', v.created_at)
               FROM private.whatsapp_ana_admin_runtime_v1 r JOIN private.whatsapp_ana_admin_versions_v1 v ON v.id = r.active_version_id WHERE r.singleton),
    'versions', (SELECT coalesce(jsonb_agg(jsonb_build_object('id', v.id, 'version', v.version, 'actor_id', v.actor_id, 'change_note', v.change_note, 'created_at', v.created_at) ORDER BY v.version DESC), '[]'::jsonb)
                 FROM (SELECT * FROM private.whatsapp_ana_admin_versions_v1 ORDER BY version DESC LIMIT 20) v),
    'test_runs', (SELECT coalesce(jsonb_agg(jsonb_build_object('id', t.id, 'draft_revision', t.draft_revision, 'scenario_keys', t.scenario_keys, 'passed_count', t.passed_count, 'failed_count', t.failed_count, 'safe_reasons', t.safe_reasons, 'latency_ms', t.latency_ms, 'created_at', t.created_at) ORDER BY t.created_at DESC), '[]'::jsonb)
                  FROM (SELECT * FROM private.whatsapp_ana_admin_test_runs_v1 ORDER BY created_at DESC LIMIT 20) t),
    'events', (SELECT coalesce(jsonb_agg(jsonb_build_object('action', e.action, 'actor_id', e.actor_id, 'version_id', e.version_id, 'draft_revision', e.draft_revision, 'channel_key', e.channel_key, 'detail', e.detail, 'created_at', e.created_at) ORDER BY e.created_at DESC), '[]'::jsonb)
               FROM (SELECT * FROM private.whatsapp_ana_admin_events_v1 ORDER BY created_at DESC LIMIT 30) e)
  );
$$;

CREATE OR REPLACE FUNCTION public.ops2_ana_admin_save_draft_v1(p_configuration jsonb, p_expected_revision bigint, p_note text DEFAULT '', p_actor_id uuid DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, private AS $$
DECLARE current_row private.whatsapp_ana_admin_draft_v1%ROWTYPE;
BEGIN
  IF jsonb_typeof(p_configuration) <> 'object' OR jsonb_typeof(p_configuration->'behavior') <> 'object'
     OR jsonb_typeof(p_configuration->'knowledge') <> 'array' OR jsonb_typeof(p_configuration->'triggers') <> 'array'
     OR jsonb_typeof(p_configuration->'test_cases') <> 'array' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'configuration_shape_invalid');
  END IF;
  SELECT * INTO current_row FROM private.whatsapp_ana_admin_draft_v1 WHERE singleton FOR UPDATE;
  IF NOT FOUND THEN RETURN jsonb_build_object('ok', false, 'error', 'draft_missing'); END IF;
  IF current_row.revision <> p_expected_revision THEN
    RETURN jsonb_build_object('ok', false, 'error', 'revision_conflict', 'revision', current_row.revision);
  END IF;
  UPDATE private.whatsapp_ana_admin_draft_v1 SET configuration = p_configuration, revision = revision + 1,
    updated_at = now(), updated_by = p_actor_id WHERE singleton RETURNING * INTO current_row;
  INSERT INTO private.whatsapp_ana_admin_events_v1(action, actor_id, draft_revision, detail)
    VALUES ('draft_saved', p_actor_id, current_row.revision, jsonb_build_object('note', left(coalesce(p_note,''),240)));
  RETURN jsonb_build_object('ok', true, 'revision', current_row.revision, 'updated_at', current_row.updated_at);
END;
$$;

CREATE OR REPLACE FUNCTION public.ops2_ana_admin_publish_v1(p_test_run_id uuid, p_note text DEFAULT '', p_actor_id uuid DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, private AS $$
DECLARE d private.whatsapp_ana_admin_draft_v1%ROWTYPE; t private.whatsapp_ana_admin_test_runs_v1%ROWTYPE;
  next_version integer; new_id bigint;
BEGIN
  SELECT * INTO d FROM private.whatsapp_ana_admin_draft_v1 WHERE singleton FOR UPDATE;
  SELECT * INTO t FROM private.whatsapp_ana_admin_test_runs_v1 WHERE id = p_test_run_id;
  IF NOT FOUND OR t.draft_revision <> d.revision OR t.failed_count <> 0 OR t.passed_count = 0 THEN
    RETURN jsonb_build_object('ok', false, 'error', 'test_run_missing_stale_or_failed');
  END IF;
  SELECT coalesce(max(version),0)+1 INTO next_version FROM private.whatsapp_ana_admin_versions_v1;
  INSERT INTO private.whatsapp_ana_admin_versions_v1(version, configuration, actor_id, change_note)
    VALUES(next_version, d.configuration, p_actor_id, left(coalesce(p_note,''),240)) RETURNING id INTO new_id;
  INSERT INTO private.whatsapp_ana_admin_runtime_v1(singleton, active_version_id, updated_at, updated_by)
    VALUES(true,new_id,now(),p_actor_id)
    ON CONFLICT(singleton) DO UPDATE SET active_version_id=excluded.active_version_id,updated_at=excluded.updated_at,updated_by=excluded.updated_by;
  INSERT INTO private.whatsapp_ana_admin_events_v1(action,actor_id,version_id,draft_revision,detail)
    VALUES('published',p_actor_id,new_id,d.revision,jsonb_build_object('version',next_version,'test_run_id',p_test_run_id,'note',left(coalesce(p_note,''),240)));
  RETURN jsonb_build_object('ok',true,'version',next_version,'version_id',new_id,'draft_revision',d.revision);
END;
$$;

CREATE OR REPLACE FUNCTION public.ops2_ana_admin_rollback_v1(p_version_id bigint, p_note text DEFAULT '', p_actor_id uuid DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, private AS $$
DECLARE target private.whatsapp_ana_admin_versions_v1%ROWTYPE;
BEGIN
  SELECT * INTO target FROM private.whatsapp_ana_admin_versions_v1 WHERE id=p_version_id;
  IF NOT FOUND THEN RETURN jsonb_build_object('ok',false,'error','version_not_found'); END IF;
  INSERT INTO private.whatsapp_ana_admin_runtime_v1(singleton,active_version_id,updated_at,updated_by)
    VALUES(true,target.id,now(),p_actor_id)
    ON CONFLICT(singleton) DO UPDATE SET active_version_id=excluded.active_version_id,updated_at=excluded.updated_at,updated_by=excluded.updated_by;
  INSERT INTO private.whatsapp_ana_admin_events_v1(action,actor_id,version_id,detail)
    VALUES('rolled_back',p_actor_id,target.id,jsonb_build_object('version',target.version,'note',left(coalesce(p_note,''),240)));
  RETURN jsonb_build_object('ok',true,'version',target.version,'version_id',target.id);
END;
$$;

CREATE OR REPLACE FUNCTION public.ops2_ana_active_config_v1()
RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path = pg_catalog, private AS $$
  SELECT jsonb_build_object('ok',true,'version',v.version,'version_id',v.id,'configuration',v.configuration)
  FROM private.whatsapp_ana_admin_runtime_v1 r JOIN private.whatsapp_ana_admin_versions_v1 v ON v.id=r.active_version_id
  WHERE r.singleton;
$$;

REVOKE ALL ON FUNCTION public.ops2_ana_admin_load_v1() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.ops2_ana_admin_save_draft_v1(jsonb,bigint,text,uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.ops2_ana_admin_publish_v1(uuid,text,uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.ops2_ana_admin_rollback_v1(bigint,text,uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.ops2_ana_active_config_v1() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.ops2_ana_admin_load_v1() TO service_role;
GRANT EXECUTE ON FUNCTION public.ops2_ana_admin_save_draft_v1(jsonb,bigint,text,uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.ops2_ana_admin_publish_v1(uuid,text,uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.ops2_ana_admin_rollback_v1(bigint,text,uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.ops2_ana_active_config_v1() TO service_role;

COMMIT;
