begin;

-- Dona Antônia Agent Core — Rodada 4/6.
-- Inventário explícito dos routers e primeira consolidação segura de observabilidade.
-- Não altera rollout, Flow, Bling, decisão comercial nem resposta ao cliente.

create table if not exists public.agent_core_router_inventory (
  id bigint generated by default as identity primary key,
  table_name text not null,
  trigger_name text not null,
  function_name text not null,
  phase text not null check (phase in ('before','after')),
  classification text not null check (classification in ('hard_safety','transport','deterministic_policy','compatibility','legacy')),
  retirement_state text not null default 'keep' check (retirement_state in ('keep','consolidated','candidate','blocked','retired')),
  precedence integer not null default 100,
  notes text,
  last_verified_at timestamptz not null default now(),
  unique(table_name,trigger_name)
);

alter table public.agent_core_router_inventory enable row level security;
revoke all on table public.agent_core_router_inventory from public,anon,authenticated;
grant select,insert,update,delete on table public.agent_core_router_inventory to service_role;
grant usage,select on sequence public.agent_core_router_inventory_id_seq to service_role;

insert into public.agent_core_router_inventory(table_name,trigger_name,function_name,phase,classification,retirement_state,precedence,notes)
values
 ('ai_jobs','a0_whatsapp_release_gate_v1','guard_whatsapp_ai_job_release_v1','before','hard_safety','keep',0,'Release gate; deve permanecer fora do modelo.'),
 ('ai_jobs','a1_whatsapp_simple_product_query_v1','route_whatsapp_simple_product_query_v1','before','legacy','candidate',10,'Interpreta texto por regex e responde busca; migrar intenção para Agent Core, mantendo busca determinística como tool.'),
 ('ai_jobs','aa_whatsapp_sales_greeting_fastpath','whatsapp_sales_greeting_ai_job_fastpath_v1','before','legacy','candidate',20,'Fast-path de saudação; candidato a Agent Core após replay/paridade.'),
 ('ai_jobs','aaa_whatsapp_basket_payment_checkout_v1','route_whatsapp_basket_payment_checkout_v1','before','legacy','blocked',30,'Mistura interpretação textual com estado/confirmacao determinísticos; separar antes de aposentar.'),
 ('ai_jobs','ab_whatsapp_checkout_flow_v1','whatsapp_checkout_flow_router_v1','before','legacy','blocked',40,'Mistura interpretação de finalização com confirmação/handoff; separar antes de aposentar.'),
 ('ai_jobs','ai_job_event_dispatch_v2','ai_job_dispatch_trigger_v2','after','transport','keep',200,'Despacha worker atual enquanto Agent Core não está live.'),
 ('ai_jobs','ai_job_human_fallback_v1','ai_job_human_fallback_trigger_v1','after','hard_safety','keep',210,'Handoff humano por erro/held; precedência absoluta.'),
 ('ai_jobs','trg_000_whatsapp_basket_choice_flow_v1','route_whatsapp_basket_choice_flow_v1','before','compatibility','keep',50,'Lane seletiva de Flow; permanece dormente/protegida pelos gates atuais.'),
 ('ai_jobs','trg_001_whatsapp_basket_fallback_v1','route_whatsapp_basket_fallback_v1','before','legacy','blocked',60,'Fallback de cesta; contém interpretação e side effects, migrar após paridade.'),
 ('ai_jobs','trg_00_route_whatsapp_basket_swap_v1','route_whatsapp_basket_swap_ai_job_v1','before','legacy','candidate',70,'Interpretação textual de troca; sessão/substituição determinística deve virar tool.'),
 ('ai_jobs','trg_00_whatsapp_flow_entry_v1','route_whatsapp_flow_entry_v1','before','compatibility','keep',80,'Entrada de Flow protegida por gates; não ativar nesta rodada.'),
 ('ai_jobs','trg_01_whatsapp_basket_personalization_choice_v1','route_whatsapp_basket_personalization_choice_v1','before','legacy','candidate',90,'Interpretação de escolha de personalização; efeitos determinísticos devem ser tools.'),
 ('ai_jobs','trg_agent_core_shadow_postprocess_v1','agent_core_shadow_postprocess_trigger_v1','after','compatibility','keep',220,'Pós-processamento consolidado: observer primeiro e dispatch shadow depois, ambos non-blocking.'),
 ('ai_jobs','trg_route_whatsapp_basic_sales_ai_job_v1','route_whatsapp_basic_sales_ai_job_v1','before','legacy','blocked',100,'Grande router comercial legado; decompor por tools/estado antes de retirar.'),
 ('ai_jobs','trg_whatsapp_sales_multi_search_cta_v1','whatsapp_sales_multi_search_cta_v1','after','legacy','candidate',230,'Augmentação pós-worker de múltiplas buscas; migrar apresentação para Agent Core.'),
 ('outbound_jobs','guard_whatsapp_ai_outbound_rate_v1','guard_whatsapp_ai_outbound_rate_v1','before','hard_safety','keep',0,'Rate guard de outbound.'),
 ('outbound_jobs','outbound_jobs_whatsapp_event_dispatch','notify_whatsapp_outbound_insert','after','transport','keep',100,'Transporte event-driven WhatsApp.'),
 ('outbound_jobs','trg_checkout_address_first_outbound_v1','whatsapp_checkout_address_first_outbound_v1','before','deterministic_policy','keep',20,'Guardrail de endereço antes do checkout.'),
 ('outbound_jobs','trg_enrich_whatsapp_product_selection_outbound_v1','enrich_whatsapp_product_selection_outbound_v1','before','deterministic_policy','keep',30,'Enriquecimento determinístico de seleção de produto.'),
 ('outbound_jobs','zz_whatsapp_checkout_locator_followup_v1','whatsapp_checkout_locator_followup_outbound_v1','after','deterministic_policy','keep',110,'Follow-up determinístico de localizador/checkout.')
on conflict(table_name,trigger_name) do update set
 function_name=excluded.function_name,
 phase=excluded.phase,
 classification=excluded.classification,
 retirement_state=excluded.retirement_state,
 precedence=excluded.precedence,
 notes=excluded.notes,
 last_verified_at=now();

create or replace function public.agent_core_shadow_postprocess_trigger_v1()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
begin
  if new.status<>'done' or (tg_op='UPDATE' and old.status is not distinct from new.status) then
    return new;
  end if;

  if new.conversation_id is not null and new.message_id is not null then
    begin
      perform public.observe_whatsapp_agent_core_turn_v1(new.conversation_id,new.message_id);
    exception when others then
      insert into public.whatsapp_ops_events(event_type,severity,conversation_id,ai_job_id,details)
      values('agent_core_shadow_observe_failed','warning',new.conversation_id,new.id,jsonb_build_object('non_blocking',true,'router_consolidation','round4_v1'));
    end;
  end if;

  begin
    perform public.dispatch_whatsapp_agent_core_shadow_v1(new.id);
  exception when others then
    insert into public.whatsapp_ops_events(event_type,severity,conversation_id,ai_job_id,details)
    values('agent_core_shadow_trigger_error','warning',new.conversation_id,new.id,jsonb_build_object('non_blocking',true,'router_consolidation','round4_v1'));
  end;

  return new;
end;
$$;

revoke all on function public.agent_core_shadow_postprocess_trigger_v1() from public,anon,authenticated;

drop trigger if exists trg_agent_core_shadow_dispatch_ai_job_v1 on public.ai_jobs;
drop trigger if exists trg_agent_core_shadow_observe_ai_job_v1 on public.ai_jobs;
drop trigger if exists trg_agent_core_shadow_postprocess_v1 on public.ai_jobs;
create trigger trg_agent_core_shadow_postprocess_v1
after insert or update of status on public.ai_jobs
for each row when (new.status='done')
execute function public.agent_core_shadow_postprocess_trigger_v1();

drop trigger if exists trg_conversations_updated_at on public.conversations;

create or replace function public.get_agent_core_round4_readiness_v1()
returns jsonb
language sql
security definer
set search_path=''
as $$
with ai as (
  select count(*)::int as trigger_count
  from pg_trigger t
  join pg_class c on c.oid=t.tgrelid
  join pg_namespace n on n.oid=c.relnamespace
  where not t.tgisinternal and n.nspname='public' and c.relname='ai_jobs'
), inv as (
  select count(*)::int as total,
         count(*) filter(where classification='hard_safety')::int as hard_safety,
         count(*) filter(where classification='transport')::int as transport,
         count(*) filter(where classification='deterministic_policy')::int as deterministic_policy,
         count(*) filter(where classification='compatibility')::int as compatibility,
         count(*) filter(where classification='legacy')::int as legacy,
         count(*) filter(where retirement_state='candidate')::int as candidates,
         count(*) filter(where retirement_state='blocked')::int as blocked
  from public.agent_core_router_inventory
), cfg as (
  select whatsapp_live_canary_percent,experience_orchestrator_enabled,whatsapp_flow_data_exchange_enabled,
         whatsapp_flow_send_enabled,bling_order_sync_enabled,whatsapp_flow_commercial_write_enabled
  from public.automation_config where id=1
)
select jsonb_build_object(
  'round',4,
  'router_inventory_total',inv.total,
  'ai_jobs_trigger_count',ai.trigger_count,
  'classification',jsonb_build_object('hard_safety',inv.hard_safety,'transport',inv.transport,'deterministic_policy',inv.deterministic_policy,'compatibility',inv.compatibility,'legacy',inv.legacy),
  'retirement',jsonb_build_object('candidates',inv.candidates,'blocked',inv.blocked),
  'shadow_postprocess_consolidated',exists(select 1 from pg_trigger t join pg_class c on c.oid=t.tgrelid where not t.tgisinternal and c.relname='ai_jobs' and t.tgname='trg_agent_core_shadow_postprocess_v1'),
  'duplicate_conversation_updated_at_removed',not exists(select 1 from pg_trigger t join pg_class c on c.oid=t.tgrelid where not t.tgisinternal and c.relname='conversations' and t.tgname='trg_conversations_updated_at'),
  'rollout',to_jsonb(cfg)
)
from ai,inv,cfg;
$$;
revoke all on function public.get_agent_core_round4_readiness_v1() from public,anon,authenticated;
grant execute on function public.get_agent_core_round4_readiness_v1() to service_role;

commit;
