-- Fiscal recovery controller. No broad unreviewed tax rewrites or duplicate NF-e.
create table if not exists public.fiscal_nfe_recovery_control_v1 (
  id boolean primary key default true check (id),
  enabled boolean not null default true,
  auto_fix_with_verified_evidence boolean not null default true,
  auto_retry_after_verified_fix boolean not null default true,
  max_attempts integer not null default 3 check (max_attempts between 1 and 5),
  updated_at timestamptz not null default now()
);
insert into public.fiscal_nfe_recovery_control_v1(id) values(true) on conflict(id) do nothing;
create table if not exists public.fiscal_nfe_recovery_events_v1 (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  dispatch_job_id uuid null references public.dispatch_fiscal_jobs(id) on delete set null,
  event_key text not null unique,
  stage text not null,
  error_code text,
  error_detail text,
  diagnostics jsonb not null default '{}'::jsonb,
  external_write boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists fiscal_nfe_recovery_events_order_idx on public.fiscal_nfe_recovery_events_v1(order_id,created_at desc);
alter table public.fiscal_nfe_recovery_control_v1 enable row level security;
alter table public.fiscal_nfe_recovery_events_v1 enable row level security;
revoke all on public.fiscal_nfe_recovery_control_v1 from anon,authenticated;
revoke all on public.fiscal_nfe_recovery_events_v1 from anon,authenticated;

-- Reuse the already configured Bling Hub credential, which stays in PostgreSQL.
create or replace function public.dispatch_fiscal_nfe_autorecovery_v1()
returns bigint language plpgsql security definer set search_path = '' as $$
declare v_req bigint;
begin
  if not exists(
    select 1 from public.fiscal_nfe_recovery_control_v1 where id=true and enabled=true
  ) then return null; end if;
  if not exists(
    select 1 from public.bling_hub_runtime_v2
    where id=1 and mode='live' and hub_enabled=true and orders_enabled=true
  ) then return null; end if;
  select net.http_post(
    url := 'https://ssbesxgaijknwsjbsbcz.supabase.co/functions/v1/admin-service-intelligence-v1',
    headers := jsonb_build_object('Content-Type','application/json','x-dona-antonia-bling-hub-key',public.get_bling_hub_key_v2()),
    body := jsonb_build_object('action','vitrine_bling_hub_internal','subaction','fiscal_nfe_autorecovery_v1','limit',2),
    timeout_milliseconds := 55000
  ) into v_req;
  return v_req;
end $$;

-- One controlled tick every five minutes; existing Bling synchronization cron is untouched.
select cron.schedule('fiscal-nfe-autorecovery-v1','*/5 * * * *',
  'select public.dispatch_fiscal_nfe_autorecovery_v1();');
