create table if not exists public.agent_core_legacy_router_observations (
  id bigint generated by default as identity primary key,
  ai_job_id uuid not null unique references public.ai_jobs(id) on delete cascade,
  conversation_id uuid not null,
  message_id uuid,
  action text not null,
  router_family text not null,
  match_source text not null check (match_source in ('interactive','text','unknown')),
  interactive_id text,
  observed_at timestamptz not null default now()
);

alter table public.agent_core_legacy_router_observations enable row level security;
revoke all on table public.agent_core_legacy_router_observations from public, anon, authenticated;
grant select, insert, update, delete on table public.agent_core_legacy_router_observations to service_role;

create or replace function public.agent_core_router_family_for_action_v1(p_action text)
returns text
language sql
immutable
set search_path=''
as $$
  select case coalesce(p_action,'')
    when 'basket_add_more' then 'basket_payment_checkout'
    when 'basket_payment_selection' then 'basket_payment_checkout'
    when 'address_flow_reopened' then 'basket_payment_checkout'
    when 'address_flow_cancelled' then 'basket_payment_checkout'
    when 'legacy_address_escape_to_payment' then 'basket_payment_checkout'
    when 'legacy_address_escape_to_extras' then 'basket_payment_checkout'
    when 'basket_customer_data_processed' then 'basket_payment_checkout'
    when 'change_basket_delivery_address_flow' then 'basket_payment_checkout'
    when 'basket_payment_clarification' then 'basket_payment_checkout'
    when 'basket_final_confirmation' then 'basket_payment_checkout'
    when 'basket_payment_missing' then 'basket_payment_checkout'
    when 'basket_order_confirmed' then 'basket_payment_checkout'
    when 'basket_final_confirmation_repeat' then 'basket_payment_checkout'
    when 'basket_ready_for_human' then 'checkout_flow'
    when 'confirm_order' then 'checkout_flow'
    when 'request_customer_base_data' then 'checkout_flow'
    when 'checkout_summary_then_locator' then 'checkout_flow'
    when 'basket_customer_base_data' then 'checkout_flow'
    when 'basket_summary_then_locator' then 'checkout_flow'
    when 'order_checkout_text_flow' then 'checkout_flow'
    when 'basket_list_fallback' then 'basket_fallback'
    when 'basket_catalog_link' then 'basic_sales'
    when 'show_baskets' then 'basic_sales'
    when 'basket_selected_followup' then 'basic_sales'
    when 'basket_storefront_link' then 'basic_sales'
    else 'other_legacy'
  end
$$;

create or replace function public.observe_agent_core_legacy_router_v1()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
declare
  v_action text;
  v_iid text;
  v_source text;
begin
  if new.job_type <> 'conversation' or new.status <> 'done' then
    return new;
  end if;
  if coalesce((new.result->>'deterministic')::boolean,false) is not true then
    return new;
  end if;
  v_action := nullif(new.result->>'action','');
  if v_action is null then
    return new;
  end if;
  select nullif(left(coalesce(m.ai_interpretation->>'id',''),120),'')
    into v_iid
  from public.messages m
  where m.id=new.message_id;
  v_source := case when v_iid is not null then 'interactive'
                   when new.message_id is not null then 'text'
                   else 'unknown' end;
  insert into public.agent_core_legacy_router_observations(
    ai_job_id,conversation_id,message_id,action,router_family,match_source,interactive_id,observed_at
  ) values (
    new.id,new.conversation_id,new.message_id,v_action,
    public.agent_core_router_family_for_action_v1(v_action),v_source,v_iid,now()
  )
  on conflict(ai_job_id) do update set
    action=excluded.action,
    router_family=excluded.router_family,
    match_source=excluded.match_source,
    interactive_id=excluded.interactive_id,
    observed_at=excluded.observed_at;
  return new;
end
$$;

revoke all on function public.observe_agent_core_legacy_router_v1() from public, anon, authenticated;
revoke all on function public.agent_core_router_family_for_action_v1(text) from public, anon, authenticated;
grant execute on function public.observe_agent_core_legacy_router_v1() to service_role;
grant execute on function public.agent_core_router_family_for_action_v1(text) to service_role;

drop trigger if exists trg_agent_core_legacy_router_observe_v1 on public.ai_jobs;
create trigger trg_agent_core_legacy_router_observe_v1
after insert or update of status,result on public.ai_jobs
for each row execute function public.observe_agent_core_legacy_router_v1();

insert into public.agent_core_legacy_router_observations(
  ai_job_id,conversation_id,message_id,action,router_family,match_source,interactive_id,observed_at
)
select j.id,j.conversation_id,j.message_id,j.result->>'action',
       public.agent_core_router_family_for_action_v1(j.result->>'action'),
       case when nullif(left(coalesce(m.ai_interpretation->>'id',''),120),'') is not null then 'interactive'
            when j.message_id is not null then 'text' else 'unknown' end,
       nullif(left(coalesce(m.ai_interpretation->>'id',''),120),''),
       coalesce(j.updated_at,now())
from public.ai_jobs j
left join public.messages m on m.id=j.message_id
where j.job_type='conversation'
  and j.status='done'
  and coalesce((j.result->>'deterministic')::boolean,false) is true
  and nullif(j.result->>'action','') is not null
  and j.updated_at>=now()-interval '30 days'
on conflict(ai_job_id) do nothing;

create or replace function public.get_agent_core_round4_router_observability_v1()
returns jsonb
language sql
stable
security definer
set search_path=''
as $$
  select jsonb_build_object(
    'version',1,
    'observation_count',count(*),
    'interactive_count',count(*) filter (where match_source='interactive'),
    'text_count',count(*) filter (where match_source='text'),
    'families',coalesce((
      select jsonb_agg(x order by x->>'router_family')
      from (
        select jsonb_build_object(
          'router_family',router_family,
          'count',count(*),
          'interactive',count(*) filter (where match_source='interactive'),
          'text',count(*) filter (where match_source='text')
        ) x
        from public.agent_core_legacy_router_observations
        group by router_family
      ) s
    ),'[]'::jsonb),
    'privacy',jsonb_build_object('message_body_stored',false,'pii_payload_stored',false)
  )
  from public.agent_core_legacy_router_observations
$$;

revoke all on function public.get_agent_core_round4_router_observability_v1() from public, anon, authenticated;
grant execute on function public.get_agent_core_round4_router_observability_v1() to service_role;

update public.agent_core_router_inventory
set notes=case function_name
  when 'route_whatsapp_basket_payment_checkout_v1' then 'Router legado instrumentado sem conteúdo da mensagem; separar interpretação textual dos efeitos determinísticos antes de aposentar.'
  when 'whatsapp_checkout_flow_router_v1' then 'Router legado instrumentado sem conteúdo da mensagem; confirmação/localizador permanecem determinísticos e exigem gate.'
  when 'route_whatsapp_basket_fallback_v1' then 'Fallback legado instrumentado; manter até haver cobertura suficiente do Agent Core.'
  when 'route_whatsapp_basic_sales_ai_job_v1' then 'Router comercial legado instrumentado; decomposição deve preservar tools e guards determinísticos.'
  else notes end,
  last_verified_at=now()
where function_name in ('route_whatsapp_basket_payment_checkout_v1','whatsapp_checkout_flow_router_v1','route_whatsapp_basket_fallback_v1','route_whatsapp_basic_sales_ai_job_v1');