/* Módulo de entrada de NF-e — carregado depois do painel principal. */
(()=>{
  const bridge=window.__DA_NFE_BRIDGE__;if(!bridge){console.error('Ponte da NF-e não encontrada.');return}
  const {state,norm,getKey,productByKey,esc,textNorm,toNum,nowIso,markProductDirty,mark,setStatus,syncProductsToFirebase,saveLocal,renderProducts,renderSummary,openProduct,aiProductCadastro,aiProductImage}=bridge;
  const store={items:[],note:null,message:'Envie ou cole um XML de NF-e para começar.'}; state.nfeImport=store;
  const el=id=>document.getElementById(id), num=v=>Number(String(v??'').replace(',','.'))||0, key=()=>`nfe_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;
  const txt=(p,t)=>String(p?.getElementsByTagName(t)?.[0]?.textContent||'').trim();
  const find=ean=>{const c=norm(ean);return c&&state.produtos.find(p=>[p.gtin,p.ean,...(Array.isArray(p.ean_aliases)?p.ean_aliases:[])].some(v=>norm(v)===c))};
  const item=id=>store.items.find(x=>x.id===id), product=x=>x?.matchedKey&&productByKey(x.matchedKey);

  function ensure(){
    document.querySelectorAll('.tabs').forEach(nav=>{if(nav.querySelector('[data-tab="nfe"]'))return;const b=document.createElement('button');b.className='tab';b.type='button';b.dataset.tab='nfe';b.textContent=nav.classList.contains('drawer-tabs')?'Entrada NF-e':'Entrada de NF-e';(nav.querySelector('[data-tab="leitura"]')||nav.lastElementChild)?.insertAdjacentElement('afterend',b)});
    if(el('tab-nfe'))return;
    const s=document.createElement('section');s.id='tab-nfe';s.className='panel hidden';s.innerHTML=`
      <div class="panel-head"><div class="panel-title"><h2>Entrada de NF-e</h2><p>Leia XML, confira os produtos e faça a entrada no Firebase.</p></div><div class="toolbar"><label class="btn primary">↑ Enviar XML<input id="nfeXmlFile" hidden type="file" accept=".xml,text/xml,application/xml"></label><button class="btn" type="button" data-action="nfe-clear">Limpar nota</button></div></div>
      <div class="nfe-import-box"><div class="nfe-source-grid"><div class="field"><label>Leitor / pistola</label><div class="nfe-scan-line"><input class="input" id="nfeScanInput" placeholder="Escaneie XML em texto, URL do XML ou EAN"><button class="btn blue" data-action="nfe-use-scan">Ler</button></div><small class="tiny">A chave de acesso do DANFE não traz a lista de produtos sozinha. Use o XML da nota, uma URL pública do XML ou o conteúdo XML enviado pelo leitor.</small></div><div class="field"><label>Colar XML da NF-e</label><textarea class="textarea nfe-xml-paste" id="nfeXmlPaste" placeholder="Cole o XML que começa com &lt;?xml ..."></textarea><button class="btn" style="margin-top:8px" data-action="nfe-parse-paste">Ler XML colado</button></div></div><div id="nfeMessage" class="notice gold" style="margin-top:12px"></div></div>
      <div id="nfeSummary"></div><div id="nfeItems" class="nfe-items"></div>`;document.querySelector('main.app')?.appendChild(s);
  }
  function parse(raw){
    const doc=new DOMParser().parseFromString(String(raw||''),'application/xml');if(doc.querySelector('parsererror'))throw Error('O arquivo não é um XML válido.');
    const inf=doc.getElementsByTagName('infNFe')[0]||doc,dets=[...inf.getElementsByTagName('det')];if(!dets.length)throw Error('Não encontrei itens <det> de uma NF-e neste XML.');
    const ide=inf.getElementsByTagName('ide')[0]||doc,emit=inf.getElementsByTagName('emit')[0]||doc;store.note={number:txt(ide,'nNF'),series:txt(ide,'serie'),supplier:txt(emit,'xNome')};
    store.items=dets.map((d,i)=>{const p=d.getElementsByTagName('prod')[0],ean=(txt(p,'cEAN')||txt(p,'cEANTrib')).replace(/\D/g,'');const match=find(ean);return{id:key(),index:i+1,ean,nome:txt(p,'xProd'),ncm:txt(p,'NCM'),unidade:txt(p,'uCom'),quantidade:num(txt(p,'qCom')),custo:num(txt(p,'vUnCom')),multiplicador:1,mode:'stock',matchedKey:match?getKey(match):'',search:'',applied:false}});
    store.message=`${store.items.length} item(ns) lido(s). Confira o multiplicador e o vínculo antes de aplicar.`;render();
  }
  function html(x){
    const p=product(x),units=Math.max(0,x.quantidade*x.multiplicador),safe=v=>esc(String(v??''));
    const choices=state.produtos.filter(q=>!x.search||textNorm([getName(q),q.codigo,q.gtin,q.ean].join(' ')).includes(textNorm(x.search))).slice(0,8);
    const different=p&&norm(p.gtin||p.ean)!==norm(x.ean);
    return `<article class="nfe-item ${p?'matched':'unmatched'} ${x.applied?'applied':''}" data-nfe-id="${safe(x.id)}"><div class="nfe-item-head"><div><span class="chip ${p?'green':'red'}">${p?'Vinculado':'Sem cadastro'}</span><strong>${safe(x.nome||'Produto sem descrição')}</strong><div class="tiny">EAN ${safe(x.ean||'não informado')} · NCM ${safe(x.ncm||'—')} · ${safe(x.quantidade)} ${safe(x.unidade||'un.')} na nota</div></div>${p?`<div class="nfe-match-name"><strong>${safe(getName(p))}</strong><small>Cód. ${safe(p.codigo||getKey(p))} · estoque: ${safe(toNum(p.estoque))}</small></div>`:''}</div>
      <div class="nfe-fields"><div class="field"><label>Quantidade NF</label><input class="input" type="number" min="0" step=".001" data-nfe-field="quantidade" value="${safe(x.quantidade)}"></div><div class="field"><label>Multiplicador p/ un.</label><input class="input" type="number" min=".001" step=".001" data-nfe-field="multiplicador" value="${safe(x.multiplicador)}"></div><div class="field"><label>Entrada estoque</label><div class="nfe-total">${safe(units)} un.</div></div><div class="field"><label>Custo unitário NF</label><input class="input" type="number" min="0" step=".01" data-nfe-field="custo" value="${safe(x.custo)}"></div><div class="field"><label>Nome recebido</label><input class="input" data-nfe-field="nome" value="${safe(x.nome)}"></div><div class="field"><label>EAN recebido</label><input class="input" data-nfe-field="ean" value="${safe(x.ean)}"></div></div>
      ${p?`<div class="nfe-actions"><label class="nfe-mode"><input type="radio" name="mode-${safe(x.id)}" value="stock" data-nfe-mode ${x.mode==='stock'?'checked':''}> Só estoque</label><label class="nfe-mode"><input type="radio" name="mode-${safe(x.id)}" value="full" data-nfe-mode ${x.mode==='full'?'checked':''}> Estoque + dados NF</label>${different?'<span class="tiny">O EAN da nota será salvo como código alternativo.</span>':''}<button class="btn ${x.mode==='stock'?'green':'primary'}" data-action="nfe-apply" data-id="${safe(x.id)}" ${x.applied?'disabled':''}>${x.applied?'Aplicado ✓':x.mode==='stock'?`Adicionar ${safe(units)} ao estoque`:'Atualizar e adicionar'}</button><button class="btn" data-action="nfe-open" data-key="${safe(getKey(p))}">Editar cadastro</button><button class="btn gold" data-action="nfe-ai-cadastro" data-id="${safe(x.id)}">✨ IA cadastro</button><button class="btn gold" data-action="nfe-ai-image" data-id="${safe(x.id)}">🖼 IA imagem</button></div>`:
      `<div class="nfe-manual"><div class="field"><label>Buscar manualmente no Firebase</label><input class="input" data-nfe-search placeholder="Nome, código ou EAN" value="${safe(x.search)}"></div>${choices.length?`<div class="nfe-candidates">${choices.map(q=>`<button class="btn small" data-action="nfe-match" data-id="${safe(x.id)}" data-key="${safe(getKey(q))}">${safe(getName(q))}<small>${safe(q.gtin||q.ean||q.codigo||'sem EAN')}</small></button>`).join('')}</div>`:'<div class="tiny">Nenhum produto encontrado.</div>'}<div class="nfe-actions"><button class="btn green" data-action="nfe-create" data-id="${safe(x.id)}">Criar produto da NF</button><span class="tiny">Crie o rascunho e complete-o pela IA ou no cadastro.</span></div></div>`}</article>`;
  }
  function render(){ensure();const message=el('nfeMessage'),sum=el('nfeSummary'),host=el('nfeItems');if(message){message.textContent=store.message;message.className=`notice ${store.items.some(x=>!product(x))?'gold':'green'}`};if(!sum||!host)return;if(!store.items.length){sum.innerHTML='';host.innerHTML='<div class="empty">Nenhum item de nota carregado.</div>';return}const linked=store.items.filter(product).length,total=store.items.reduce((a,x)=>a+x.quantidade*x.multiplicador,0),e=v=>esc(String(v||'—'));sum.innerHTML=`<div class="nfe-summary"><div class="summary-card"><strong>${e(store.note?.number)}</strong><span>NF-e · série ${e(store.note?.series)}</span></div><div class="summary-card"><strong>${linked}/${store.items.length}</strong><span>Produtos vinculados</span></div><div class="summary-card"><strong>${e(total)}</strong><span>Unidades a entrar</span></div><div class="summary-card"><strong>${e(store.note?.supplier)}</strong><span>Fornecedor</span></div></div>`;host.innerHTML=store.items.map(html).join('')}
  async function apply(x){const p=product(x);if(!p)throw Error('Vincule um produto antes de aplicar.');const add=Math.max(0,num(x.quantidade)*num(x.multiplicador));if(!add)throw Error('Informe uma quantidade maior que zero.');p.estoque=toNum(p.estoque)+add;p.stock_updated_at=nowIso();const fields=['estoque'],ean=String(x.ean||'').replace(/\D/g,'');if(ean&&norm(ean)!==norm(p.gtin||p.ean)){p.ean_aliases=[...new Set([...(Array.isArray(p.ean_aliases)?p.ean_aliases:[]),ean])];fields.push('ean_aliases')}if(x.mode==='full'){p.nome=String(x.nome||p.nome).trim()||p.nome;p.ncm=String(x.ncm||p.ncm).trim();p.preco_custo=num(x.custo);p.embalagem=String(x.unidade||p.embalagem).trim();fields.push('nome','ncm','preco_custo','embalagem')}p.last_update=Date.now();p.updated_at=nowIso();markProductDirty(getKey(p),fields);mark('products');setStatus('Salvando entrada no Firebase...','warn');const out=await syncProductsToFirebase([getKey(p)]);if(out.conflicts?.length)throw Error('O estoque foi alterado em outro dispositivo. Recarregue e tente novamente.');x.applied=true;store.message=`Entrada aplicada: ${getName(p)} recebeu ${add} unidade(s).`;saveLocal();render();renderProducts();renderSummary();setStatus('Entrada de NF-e salva no Firebase','ok')}
  function create(x){const ean=String(x.ean||'').replace(/\D/g,''),base=ean||`NF${Date.now()}`;let k=base,i=2;while(productByKey(k))k=`${base}-${i++}`;const p={firebaseKey:k,id:k,codigo:k,gtin:ean,nome:String(x.nome||'Produto da NF').trim(),ncm:x.ncm||'',preco:0,preco_custo:num(x.custo),estoque:0,situacao:'I',categoria:'A CLASSIFICAR',embalagem:x.unidade||'',descricao:'',tags:[],created_at:nowIso(),updated_at:nowIso(),last_update:Date.now()};state.produtos.push(p);x.matchedKey=k;markProductDirty(k,['__all']);mark('products');store.message=`Rascunho inativo criado para ${p.nome}. Use “Editar cadastro” para IA cadastro/IA imagem e defina preço antes de ativar; depois aplique a entrada.`;render();renderProducts()}
  document.addEventListener('change',async e=>{if(e.target?.id==='nfeXmlFile'&&e.target.files?.[0]){try{parse(await e.target.files[0].text())}catch(err){store.message=err.message;render()}return}const x=item(e.target.closest?.('[data-nfe-id]')?.dataset.nfeId);if(!x)return;if(e.target.matches('[data-nfe-field]')){const f=e.target.dataset.nfeField;x[f]=['quantidade','multiplicador','custo'].includes(f)?num(e.target.value):e.target.value;render()}if(e.target.matches('[data-nfe-mode]')){x.mode=e.target.value;render()}});
  document.addEventListener('input',e=>{const x=item(e.target.closest?.('[data-nfe-id]')?.dataset.nfeId);if(x&&e.target.matches('[data-nfe-search]')){x.search=e.target.value;render()}});
  document.addEventListener('keydown',e=>{if(e.target?.id==='nfeScanInput'&&e.key==='Enter'){e.preventDefault();document.querySelector('[data-action="nfe-use-scan"]')?.click()}});
  document.addEventListener('click',e=>{const b=e.target.closest?.('[data-action]');if(!b)return;const a=b.dataset.action,x=item(b.dataset.id);if(a==='nfe-clear'){store.items=[];store.note=null;store.message='Nota limpa.';render();return}if(a==='nfe-parse-paste'){try{parse(el('nfeXmlPaste')?.value)}catch(err){store.message=err.message;render()}return}if(a==='nfe-use-scan'){const raw=el('nfeScanInput')?.value.trim()||'';if(raw.startsWith('<')){try{parse(raw)}catch(err){store.message=err.message;render()}}else{store.message=raw?`Código lido: ${raw}. Envie o XML para listar produtos; a chave impressa do DANFE não contém os itens.`:'Leia um código ou envie o XML.';render()}return}if(a==='nfe-match'&&x){x.matchedKey=b.dataset.key;x.search='';store.message='Produto vinculado manualmente; o EAN recebido será guardado como alternativo ao aplicar.';render();return}if(a==='nfe-create'&&x){create(x);return}if(a==='nfe-apply'&&x){apply(x).catch(err=>{console.error(err);store.message=`Não foi possível aplicar: ${err.message}`;render();setStatus('Falha na entrada de NF-e','err')});return}if(a==='nfe-open'){openProduct(b.dataset.key);return}if(a==='nfe-ai-cadastro'&&x){aiProductCadastro(x.matchedKey).then(()=>{store.message='Cadastro gerado pela IA. Revise e aplique a entrada.';render()}).catch(err=>alert(err.message));return}if(a==='nfe-ai-image'&&x){aiProductImage(x.matchedKey).then(()=>{store.message='Imagem gerada pela IA e vinculada ao produto.';render()}).catch(err=>alert(err.message));return}});
  function showCurrentTab(){ensure();const panel=el('tab-nfe');if(!panel)return;panel.classList.toggle('hidden',state.activeTab!=='nfe');if(state.activeTab==='nfe')render()}
  document.addEventListener('click',event=>{const tab=event.target.closest?.('.tab');if(tab||event.target.closest?.('[data-action="go-products"]'))requestAnimationFrame(showCurrentTab)});
  if(!el('nfeImportStyles')){const s=document.createElement('style');s.id='nfeImportStyles';s.textContent=`#tab-nfe .nfe-import-box{padding:14px;border:1px solid #d9c783;border-radius:18px;background:linear-gradient(135deg,#fffdf5,#fff)}.nfe-source-grid,.nfe-fields{display:grid;grid-template-columns:1fr 1fr;gap:10px}.nfe-scan-line{display:grid;grid-template-columns:1fr auto;gap:8px}.nfe-xml-paste{min-height:108px}.nfe-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:14px 0}.nfe-summary .summary-card strong{font-size:15px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.nfe-items{display:grid;gap:12px}.nfe-item{border:1px solid var(--line);border-left:5px solid var(--red);border-radius:18px;background:#fff;padding:14px}.nfe-item.matched{border-left-color:var(--green)}.nfe-item.applied{opacity:.72}.nfe-item-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start;margin-bottom:12px}.nfe-item-head strong{display:block;margin-top:6px}.nfe-match-name{padding:8px 10px;border-radius:12px;background:var(--green2);min-width:220px}.nfe-match-name strong,.nfe-match-name small{display:block}.nfe-match-name small{margin-top:3px;color:var(--muted);font-size:11px}.nfe-fields{grid-template-columns:repeat(6,minmax(0,1fr))}.nfe-fields .field label{font-size:10px}.nfe-total{height:42px;display:flex;align-items:center;padding:0 11px;border:1px solid var(--line);border-radius:12px;background:#f8fafc;font-weight:900}.nfe-actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-top:12px}.nfe-mode{font-size:12px;font-weight:800;display:flex;align-items:center;gap:5px}.nfe-manual{padding-top:10px;border-top:1px dashed var(--line);margin-top:12px}.nfe-candidates{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px}.nfe-candidates .btn{display:flex;flex-direction:column;align-items:flex-start;max-width:260px}.nfe-candidates small{font-size:10px;color:var(--muted)}@media(max-width:1000px){.nfe-fields{grid-template-columns:repeat(3,1fr)}.nfe-summary{grid-template-columns:1fr 1fr}}@media(max-width:650px){.nfe-source-grid,.nfe-fields,.nfe-summary{grid-template-columns:1fr}.nfe-scan-line{grid-template-columns:1fr}.nfe-item-head{flex-direction:column}.nfe-match-name{width:100%}}`;document.head.appendChild(s)}showCurrentTab();
})();
