name: Gerar merchant.xml

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:
  gerar-merchant:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Gerar merchant.xml
        run: node scripts/gerar-merchant.js

      - name: Salvar merchant.xml no repositório
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add merchant.xml
          git commit -m "Atualiza merchant.xml" || echo "Sem alterações"
          git push
